CREATE TABLE card_detail_old (
	loan_contract_no char(15) NOT NULL,
	seq_no double precision NOT NULL,
	loan_payment_date timestamp,
	item_type_code char(6),
	ref_loan_doc_no char(15),
	principal_balance decimal(15,2),
	payment_amount decimal(15,2),
	interest_amout decimal(15,2),
	interest_from timestamp,
	interest_payment decimal(15,2),
	interest_arrear decimal(15,2),
	fine_amount decimal(15,2),
	interest_to timestamp,
	fine_payment decimal(15,2),
	fine_arrear decimal(15,2),
	last_interate_date timestamp,
	interest_return decimal(15,2),
	period double precision,
	branch_id char(6),
	entry_id char(16),
	entry_date timestamp,
	client_name char(15),
	int_share_coll decimal(15,2),
	share_coll_amount decimal(15,2),
	balance_receipt decimal(15,2),
	status char(1),
	remark char(255),
	temp_seq double precision,
	external_id char(7),
	membership_no char(15),
	loan_status char(1),
	interest_notpay decimal(15,2),
	client_pc char(3),
	old_interest_arrear decimal(15,2),
	calint_date_move char(1),
	ppm_status char(1),
	pay_principal_arr decimal(15,2),
	calint_method char(6),
	calint_active char(1),
	interest_calulate decimal(15,2),
	interest_arrear_add decimal(15,2),
	interest_arrear_bf decimal(15,2),
	interest_arrear_bal decimal(15,2),
	calcint_date timestamp,
	working_date timestamp,
	mark_status char(1),
	calint_mesage char(100),
	keepint_over decimal(15,2),
	seq_no_temp double precision,
	receive_status char(1),
	keeping_status char(1),
	co_code char(10),
	revers_seq numeric(38),
	finance_date timestamp,
	begin_recalc char(1),
	edit_seq_no integer,
	edit_entry_id char(16),
	edit_entry_date timestamp,
	edit_principal_balance decimal(15,2),
	seq_adjust double precision,
	to_sybase char(1),
	period_payment_amount double precision,
	split_seq integer,
	split_balance decimal(15,2),
	real_balance decimal(15,2),
	accu_interest decimal(15,2),
	calintstep_code char(15),
	fin_status char(1),
	interest_calmonth decimal(15,2),
	interest_arrear_old decimal(15,2),
	intreturn_active char(1),
	old_item_type_code char(2),
	interest_amout_temp decimal(15,2)
) ;
ALTER TABLE card_detail_old ALTER COLUMN loan_contract_no SET NOT NULL;
ALTER TABLE card_detail_old ALTER COLUMN seq_no SET NOT NULL;


