CREATE TABLE cnv_dtuplod2 (
	doc_num varchar(10),
	rec_type varchar(1),
	coptyp_id varchar(6),
	copcus_id varchar(10),
	reserve1 varchar(3),
	data_type varchar(1),
	fun_tion varchar(1),
	cus_stat varchar(1),
	cus_expd varchar(8),
	trn_minamt varchar(11),
	trn_maxamt varchar(11),
	day_limtrn varchar(5),
	day_limamt varchar(11),
	wek_limtrn varchar(5),
	wek_limamt varchar(11),
	mon_limtrn varchar(5),
	mon_limamt varchar(11),
	cus_limtrn varchar(5),
	cus_limamt varchar(11),
	od_princip varchar(11),
	od_int varchar(11),
	due_date varchar(8),
	lst_int_dt varchar(8),
	lst_pay_dt varchar(8),
	min_paytim varchar(5),
	min_payamt varchar(11),
	max_paytim varchar(5),
	max_payamt varchar(11),
	bank_accnt varchar(10),
	reserv3 varchar(95)
) ;


