CREATE TABLE cnv_dt_dwlod (
	doc_num varchar(10),
	rec_type varchar(1),
	card_ownr varchar(3),
	card_num varchar(19),
	term_ownr varchar(3),
	term_num varchar(7),
	term_loca varchar(15),
	term_city varchar(2),
	term_stat varchar(2),
	term_tseq varchar(6),
	tran_date varchar(8),
	tran_time varchar(6),
	tran_code varchar(6),
	from_acno varchar(10),
	to_accno varchar(10),
	cust_id varchar(19),
	tran_amt decimal(11,2),
	disp_amt decimal(11,2),
	tran_fee decimal(9,2),
	resp_by varchar(1),
	resp_cod1 varchar(1),
	resp_cod2 varchar(2),
	rev_code varchar(2),
	appv_code varchar(6),
	mem_no varchar(5),
	bnkacc varchar(3)
) ;


