CREATE TABLE cnv_crdloan (
	req_no varchar(10),
	docdat integer,
	mem_no varchar(5),
	bktype varchar(2),
	bk_num varchar(5),
	bkyear varchar(4),
	crdamt decimal(12,2),
	inst_amt decimal(12,2),
	term_no smallint,
	crdbln decimal(12,2),
	flg_pay varchar(1),
	bk_des varchar(2),
	fl_crd varchar(1),
	docstat varchar(1),
	credid varchar(20),
	crd_dat integer,
	start_dt integer,
	trnseri integer,
	lonseri integer,
	gur_seq smallint,
	bankcod varchar(6),
	accnobk varchar(15),
	conn_no varchar(10),
	psn_nm1 varchar(40),
	psn_nm2 varchar(40),
	usr_id1 smallint,
	usr_id2 smallint,
	flintrat varchar(1),
	gp_rate varchar(2)
) ;


