CREATE TABLE cnv_lonbok (
	bk_num varchar(5),
	bk_year varchar(4),
	bk_type varchar(2),
	bk_date integer,
	mem_no varchar(5),
	memlon varchar(5),
	bk_amt decimal(13,2),
	bk_bal decimal(13,2),
	ins_paid decimal(13,2),
	paid_amt decimal(12,2),
	term_py smallint,
	term_no smallint,
	start_dt integer,
	lst_pay integer,
	bk_des varchar(2),
	clo_date integer,
	fl_close varchar(1),
	fl_other varchar(1),
	flg_pay varchar(1),
	flintrat varchar(1),
	fl_legal varchar(1),
	usr_id1 smallint,
	usr_id2 smallint,
	note_ar varchar(20),
	conn_no varchar(10),
	req_no varchar(10),
	gp_rate varchar(2),
	trnseri integer,
	lonseri smallint,
	fl_stat varchar(1)
) ;


