CREATE TABLE sc_acc_m_expire_edit (
	material_id char(10),
	sequence_no double precision,
	description varchar(100),
	method double precision,
	rate_expire decimal(6,4),
	amount_value decimal(15,2),
	first_used_day timestamp,
	first_expire_year decimal(15,2),
	accu_expire_amount decimal(15,2),
	last_cal_used timestamp,
	cal_id varchar(50),
	cal_id_date timestamp,
	expire_date timestamp,
	status char(1),
	entry_id varchar(15),
	entry_date timestamp,
	description_new varchar(100),
	rate_expire_new decimal(6,4),
	amount_value_new decimal(15,2),
	first_used_day_new timestamp,
	first_expire_year_new decimal(15,2),
	accu_expire_amount_new decimal(15,2),
	last_cal_used_new timestamp,
	cal_id_new varchar(50),
	cal_id_date_new timestamp,
	expire_date_new timestamp,
	status_new char(1),
	type_expire varchar(10),
	edit_id varchar(15),
	edit_date timestamp,
	branch_id varchar(6),
	edit_branch_id varchar(6)
) ;


