CREATE TABLE sc_adm_wfroff_patientform (
	form_no char(15),
	rules_type char(2),
	form_date timestamp,
	officer_no char(6),
	type_person char(2),
	paid_askfor decimal(15,2),
	paid_amount decimal(15,2),
	doc_no char(15),
	docbasis_date timestamp,
	hospital_code char(3),
	patient_type char(3),
	day_in timestamp,
	day_out timestamp,
	footnote char(200),
	paid_status char(1),
	paid_entry_id char(50),
	paid_entry_branch char(2),
	paid_entry_date timestamp,
	entry_id char(50),
	entry_branch char(2),
	entry_date timestamp,
	patient_name char(100),
	relationship char(20),
	pay_by char(1),
	account_no varchar(20),
	remark varchar(500),
	remark_2 varchar(500),
	mem_fam varchar(2),
	principal_patient decimal(15,2),
	pay_type_id char(6),
	bank_code char(6),
	bank_branch_id char(6),
	bank_acc_no char(20),
	per_agent char(100)
) ;


