CREATE TABLE sc_acc_m_account_master (
	account_id varchar(8) NOT NULL,
	account_name varchar(100),
	account_type_id varchar(6),
	account_group_id varchar(6),
	account_control_id varchar(8),
	account_close_id varchar(8),
	account_level double precision,
	balance_begin decimal(15,2),
	nature varchar(6),
	data_desc varchar(250),
	oposite_account_id varchar(8),
	branch_control varchar(6),
	asset_group varchar(3),
	asset_old_group varchar(3),
	rv_desc varchar(100),
	pv_desc varchar(100),
	jv_desc varchar(100),
	balsheet_group varchar(10),
	cash_flow_status char(1) DEFAULT '0',
	account_id_old varchar(8),
	vourcher_group_rec varchar(7),
	vourcher_group_paid varchar(7),
	cancel_status char(1) DEFAULT '0',
	asset_group_2565 varchar(6),
	group_krom varchar(10),
	section_id varchar(8),
	balsheet char(1),
	income char(1),
	fontbold_status char(1),
	data_group double precision,
	percent_group varchar(6),
	data_type varchar(6),
	upperline_status char(1),
	underline_status char(1),
	novisible char(1),
	nousebalancesheet char(1),
	begin_balance_temp decimal(15,2),
	tran_acc_profit char(1),
	od_account char(1),
	group_deprecition smallint,
	group_trans_bank char(10),
	sort_order integer,
	fund_group char(8),
	invest_status char(1) DEFAULT '0'
) ;
ALTER TABLE sc_acc_m_account_master ADD PRIMARY KEY (account_id);
ALTER TABLE sc_acc_m_account_master ALTER COLUMN account_id SET NOT NULL;


