CREATE TABLE sc_crem_master (
	crem_code varchar(15) NOT NULL,
	application_form_no varchar(15),
	membership_no varchar(15),
	crem_type varchar(6) DEFAULT '00',
	member_status char(1) DEFAULT '0',
	prename_code varchar(6) DEFAULT '000',
	memname varchar(50),
	surname varchar(50),
	keep_type varchar(6) DEFAULT '00',
	crem_balance decimal(15,2) DEFAULT 0,
	crem_arrear decimal(15,2) DEFAULT 0,
	pending_amount decimal(15,2) DEFAULT 0,
	fee_new decimal(15,2) DEFAULT 0,
	fee_year decimal(15,2) DEFAULT 0,
	date_of_birth timestamp,
	id_card varchar(15),
	sex char(1) DEFAULT '0',
	salary_id varchar(15),
	position_long varchar(100),
	bank_id varchar(6),
	bank_acc_no varchar(15),
	marriage_status char(1),
	spouse_name varchar(100),
	apply_date timestamp,
	approve_date timestamp,
	officer_id varchar(16),
	address_no varchar(100),
	mooban varchar(100),
	moo varchar(50),
	soi varchar(50),
	road varchar(50),
	tambol varchar(50),
	subdistinct_code varchar(6) DEFAULT '00',
	distinct_code varchar(6) DEFAULT '00',
	province_code varchar(6) DEFAULT '00',
	post_code varchar(10),
	telephone varchar(50),
	card_last_page double precision DEFAULT 0,
	card_last_line double precision DEFAULT 0,
	card_seq double precision DEFAULT 0,
	book_last_page double precision DEFAULT 0,
	book_last_line double precision DEFAULT 0,
	book_seq double precision DEFAULT 0,
	book_no varchar(15),
	resign_code varchar(6) DEFAULT '00',
	resign_date timestamp,
	dead_date timestamp,
	dead_crem_count double precision DEFAULT 0,
	book_carcass varchar(200),
	manager_carcass varchar(100),
	receive_status char(1) DEFAULT '0',
	receive_date timestamp,
	receive_amount decimal(15,2) DEFAULT 0,
	receive_other decimal(15,2) DEFAULT 0,
	expense decimal(15,2) DEFAULT 0,
	carcass_paid double precision DEFAULT 0,
	carcass_count double precision DEFAULT 0,
	remark varchar(200)
) ;
ALTER TABLE sc_crem_master ADD PRIMARY KEY (crem_code);
ALTER TABLE sc_crem_master ALTER COLUMN crem_code SET NOT NULL;


