CREATE TABLE sc_dep_m_creditor_adj (
	deposit_account_no varchar(15) NOT NULL,
	seq_no double precision NOT NULL,
	deposit_type_code varchar(6),
	deposit_opened_date timestamp,
	membership_no varchar(15),
	deposit_account_name varchar(200),
	remark varchar(1000),
	deposit_objective varchar(200),
	address varchar(200),
	passbook_no varchar(15),
	tax_status char(1),
	monthly_deposit_status char(1),
	monthly_deposit_amount decimal(15,2),
	tax_id varchar(15),
	monthly_int_status char(1),
	method_int_month char(1),
	deposit_account_no_other varchar(15),
	sequester_status char(1),
	deposit_standsecurity_amount decimal(15,2),
	withdraw_count double precision,
	withdrawdued timestamp,
	member_status char(1),
	close_status char(1),
	deposit_opened_date_adj timestamp,
	membership_no_adj varchar(15),
	deposit_account_name_adj varchar(200),
	remark_adj varchar(1000),
	deposit_objective_adj varchar(200),
	address_adj varchar(200),
	passbook_no_adj varchar(15),
	tax_status_adj char(1),
	monthly_deposit_status_adj char(1),
	monthly_deposit_amount_adj decimal(15,2),
	tax_id_adj varchar(15),
	monthly_int_status_adj char(1),
	method_int_month_adj char(1),
	deposit_account_no_other_adj varchar(15),
	sequester_status_adj char(1),
	deposit_standsecurity_amount_a decimal(15,2),
	withdraw_count_adj double precision,
	withdrawdued_adj timestamp,
	member_status_adj char(1),
	close_status_adj char(1),
	working_day timestamp,
	entry_date timestamp,
	entry_id varchar(16),
	edit_type char(1),
	signature char(1),
	branch_id varchar(6),
	remark_seques varchar(200),
	remark_seques_adj varchar(200),
	client_name varchar(20),
	account_bank varchar(30),
	account_bank_adj varchar(30),
	conclude_fixed char(1) DEFAULT '0',
	conclude_fixed_adj char(1) DEFAULT '0',
	int_rate decimal(8,6) DEFAULT 0,
	int_rate_adj decimal(8,6) DEFAULT 0,
	int_rate_status char(1) DEFAULT '0',
	int_rate_status_adj char(1) DEFAULT '0',
	loan_holding_amount decimal(15,2) DEFAULT 0,
	withdrawable_amount decimal(15,2) DEFAULT 0,
	loan_holding_amount_adj decimal(15,2) DEFAULT 0,
	withdrawable_amount_adj decimal(15,2) DEFAULT 0,
	printed_seq_no double precision DEFAULT 0,
	printed_seq_no_adj double precision DEFAULT 0,
	last_page double precision DEFAULT 0,
	last_page_adj double precision DEFAULT 0,
	last_line double precision DEFAULT 0,
	last_line_adj double precision DEFAULT 0,
	card_printed_seq_no double precision DEFAULT 0,
	card_printed_seq_no_adj double precision DEFAULT 0,
	card_last_page double precision DEFAULT 0,
	card_last_page_adj double precision DEFAULT 0,
	card_last_line double precision DEFAULT 0,
	card_last_line_adj double precision DEFAULT 0,
	remark_cancleacc_close_adj varchar(100),
	special_tax_rate decimal(10,2) DEFAULT 0,
	special_tax_rate_adj decimal(10,2) DEFAULT 0
) ;
COMMENT ON TABLE sc_dep_m_creditor_adj IS E'!NN!';
ALTER TABLE sc_dep_m_creditor_adj ADD PRIMARY KEY (deposit_account_no,seq_no);


