CREATE TABLE sc_dep_m_creditor_item_6606 (
	deposit_account_no char(15),
	seq_no double precision,
	refer_to_deposit_doc_no char(15),
	operate_date timestamp,
	item_type char(3),
	deposit_balance decimal(15,2),
	total_balance decimal(15,2),
	old_acc_int decimal(15,2),
	interest_rate decimal(15,2),
	refer_seq_no double precision,
	fee_amount decimal(15,2),
	int_amount decimal(15,2),
	tax_amount decimal(15,2),
	cheque_no char(20),
	bank_code char(6),
	bank_branch_id char(6),
	cheque_due timestamp,
	start_int_cheque_date timestamp,
	cheque_clearing_status char(1),
	clearing_date timestamp,
	clearing_user char(15),
	ret_int decimal(15,2),
	dep_ret_to_int decimal(15,2),
	ref_doc_adj char(15),
	deposit_real decimal(15,2),
	total_real decimal(15,2),
	print_status char(1),
	cancle_status char(1),
	officer_id char(16),
	last_access_date timestamp,
	branch_id char(2),
	working_day timestamp,
	fin_status char(1),
	ref_seq_no_adj double precision,
	card_status char(1),
	book_status char(1),
	ref_item_type_adj char(3),
	client_name char(30),
	paidintnostm decimal(15,2),
	accu_int_item decimal(15,2),
	conclude_book double precision,
	auto_print_status char(1),
	auto_print_id char(20),
	auto_print_branch char(2),
	auto_print_date timestamp,
	auto_working_date timestamp,
	calpaidintdate timestamp,
	deposit_account_no_other char(15),
	print_workingdate timestamp,
	ref_int_rate decimal(15,8),
	client_id char(3),
	rollback_int char(1),
	rollback_date timestamp
) ;


