CREATE TABLE sc_dep_m_creditor_6606 (
	deposit_account_no char(15),
	deposit_type_code char(2),
	membership_no char(15),
	deposit_opened_date timestamp,
	deposit_account_name char(200),
	deposit_objective char(200),
	deposit_balance decimal(15,2),
	withdrawable_amount decimal(15,2),
	cheque_pending_amount decimal(15,2),
	loan_holding_amount decimal(15,2),
	deposit_standsecurity_amount decimal(15,2),
	sequester_status char(1),
	withdraw_count double precision,
	accumulate_interest decimal(15,2),
	last_calcint_date timestamp,
	beging_balance decimal(15,2),
	present_account_year double precision,
	special_rule_status char(1),
	monthly_int_status char(1),
	monthly_deposit_status char(1),
	monthly_deposit_amount decimal(15,2),
	tax_status char(1),
	tax_id char(15),
	withdrawdued timestamp,
	accu_int_holding decimal(15,2),
	address char(200),
	remark char(1000),
	moneytype_deposit_status char(1),
	method_int_month char(1),
	deposit_account_no_other char(15),
	account_bank char(30),
	passbook_no char(15),
	printed_seq_no double precision,
	last_page double precision,
	last_line double precision,
	card_printed_seq_no double precision,
	card_last_page double precision,
	card_last_line double precision,
	int_rate_status char(1),
	int_rate decimal(6,4),
	close_status char(1),
	deposit_closing_date timestamp,
	froce_close_date timestamp,
	movement_times double precision,
	movement_check_date timestamp,
	movement_due_date timestamp,
	fee_maintenance decimal(15,2),
	fee_maintenance_arrear decimal(15,2),
	interest_arrear decimal(15,2),
	interest_arrear_date timestamp,
	interest_cut_date timestamp,
	interest_cut decimal(15,2),
	member_status char(1),
	crosscheck_balance decimal(15,2),
	crosscheck_withdraw decimal(15,2),
	crosscheck_day timestamp,
	officer_id char(16),
	month_paid_int decimal(15,2),
	month_date_start timestamp,
	month_date_end timestamp,
	member_type char(1),
	deposit_dued_date timestamp,
	branch_id char(2),
	conclude_fixed char(1),
	transfer_to_bank char(20),
	min_balance_fixed decimal(15,2),
	remark_seques char(200),
	remark_cancleacc_close char(200),
	paidintnostm decimal(15,2),
	paid_nostm_init decimal(15,2),
	membership_no_old char(7),
	mlr_status char(1),
	not_int_comound_status char(1),
	special_tax_rate decimal(15,6),
	depdue timestamp,
	depcount double precision,
	rwmagnatic_status char(1),
	paidint_bycountopen_date timestamp,
	last_access_time_main char(23),
	last_access_time_onsite char(23),
	atm_status char(1),
	last_access_time char(23),
	dep_withdraw_per_day decimal(15,2),
	intmonth_bank char(6),
	deposit_account_old char(15)
) ;


