CREATE TABLE sc_dep_m_constant (
	max_depitem double precision,
	cut_over_date double precision,
	total_pages double precision,
	lines_per_page double precision,
	middle_line double precision,
	seq_no double precision NOT NULL,
	middle_line_amount double precision,
	day_in_year double precision,
	use_check_digit_status char(1),
	first_line double precision,
	use_doc_year_status char(1),
	last_close_day timestamp,
	printer_type varchar(10),
	cheque_status char(1),
	print_slip char(1),
	print_card char(1),
	branch_to_acc char(1),
	card_lines_per_page double precision,
	card_middle_line double precision,
	card_middle_line_amount double precision,
	form_acc_no char(1),
	acc_no_from_branch char(1),
	edit_mask varchar(30),
	show_fee_to_pbk char(1),
	close_day_force timestamp,
	max_withdraw decimal(15,2),
	approve_withdraw_no varchar(15),
	approve_wait_slip char(1),
	approve_pass_slip char(1),
	close_month_to double precision,
	signature_path varchar(50),
	dw_print_card varchar(100),
	dw_print_passbook_fp varchar(100),
	dw_print_passbook_item varchar(100),
	dw_print_slip varchar(100),
	dw_print_interest varchar(100),
	dw_print_withdraw_fee varchar(100),
	edit_print char(1),
	cheque_insertpass char(1),
	fraction_status char(1),
	round_baht varchar(4),
	conclude_fixed char(1),
	conclude_item_fixed char(1),
	print_book char(1),
	max_total_balance_all decimal(15,2),
	max_account_per_type double precision,
	nobook_country_chq char(1),
	adjusermakeonlypresent char(1),
	use_hostname char(1),
	not_int_comound_status char(1),
	fixed_month_method char(1),
	item_to_future char(1),
	use_default_deposit varchar(6),
	use_default_withdraw varchar(6),
	use_default_openaccount varchar(6),
	use_default_closeaccount varchar(6),
	openaccnomember char(1),
	resignnotopen char(1),
	type_book_no char(1),
	use_mag_rw char(1),
	use_int_mlr_paid_month char(1),
	paid_compound_int_if_zero char(1),
	account_length double precision,
	multi_cheque char(1),
	froce_close_acc_with_book char(1),
	int_not_edit_forcloseacc char(1),
	adj_ret_int_paid char(1),
	slip_no_from_branch char(1),
	not_retieve_detail char(1) DEFAULT '0',
	fixed_trans_direct_bank char(1) DEFAULT '0',
	froce_close_endmonth char(1) DEFAULT '0',
	close_arrear_fixed char(1) DEFAULT '0',
	branch_pre varchar(6),
	fixed_div_month_int char(1) DEFAULT '0',
	edit_mask_bank varchar(30),
	used_keep_fee_status char(1) DEFAULT '0',
	multiple_dwt char(1) DEFAULT '0',
	clear_chque_auto char(1) DEFAULT '0',
	default_withdraw varchar(6) DEFAULT '00',
	dep_reason varchar(50),
	use_old_passbook char(1) DEFAULT '0',
	mergecal_int_type_status char(1) DEFAULT '0',
	nouse_table_close_year char(1) DEFAULT '0',
	use_frocecloseacc char(1) DEFAULT '0',
	use_dwteditkey char(1) DEFAULT '0',
	use_withdrawtotalint char(1) DEFAULT '0',
	use_transfer_file varchar(3),
	use_acroce_paid_int_month char(1) DEFAULT '0',
	use_paidintmth_accroseworkday char(1) DEFAULT '0',
	use_calenda_holiday char(1) DEFAULT '0',
	sortprintdwt varchar(10),
	withdraw_nobook char(1) DEFAULT '0',
	use_checkbal_printpbk char(1) DEFAULT '0',
	choose_fixed_depmonth char(1) DEFAULT '0',
	useeditaccountnew_foropen char(1) DEFAULT '0',
	add_stmwpc char(1) DEFAULT '0',
	transfer_dep_nowaring char(1) DEFAULT '0',
	postto_fin_style char(1) DEFAULT '0',
	close_account_waring double precision DEFAULT 0,
	clsmonth_include_lastday char(1) DEFAULT '0',
	loan_coll_effect char(1) DEFAULT '0',
	clearing_chq_auto char(1) DEFAULT '0',
	dw_print_slip_withdraw varchar(100),
	dw_statement varchar(100),
	day_no_move integer
) ;
COMMENT ON TABLE sc_dep_m_constant IS E'!NN!';
ALTER TABLE sc_dep_m_constant ADD PRIMARY KEY (seq_no);


