CREATE TABLE sc_dep_m_fixed_deposit_cond (
	deposit_type_code varchar(6) NOT NULL,
	number_of_month_to_due double precision,
	last_day_that_can_withdraw double precision,
	condition_of_accum_int double precision,
	withdraw_before_due_code char(1),
	referto_deposit_type_code varchar(6),
	withdraw_before_due_int_rate decimal(15,2),
	mindeposit_get_bonus_month decimal(15,2),
	mindeposit_get_bonus_year decimal(15,2),
	min_month_int double precision,
	method_paid_int_pre_dued double precision,
	withdraw_af_min_mth double precision,
	withdraw_af_min_mth_int_rate decimal(6,4),
	int_compound_day double precision,
	method_int_cal double precision,
	deposit_dued_date double precision,
	withdraw_af_min_mth_int_rate2 decimal(6,4),
	withdraw_af_min_type varchar(6),
	withdraw_af_min_type2 varchar(6),
	withdraw_af_min_mth2 double precision,
	min_balance_fixed decimal(15,2),
	min_balance_paid_int decimal(15,2),
	withdraw_patial_status char(1),
	ret_int_rate decimal(10,6),
	method_int_pre_dued char(1) DEFAULT '0',
	min_balanceintmonth char(1) DEFAULT '0',
	withdraw_fixed_due_month char(1) DEFAULT '0',
	withdraw_pre_notaxpaid char(1) DEFAULT '0',
	withdraw_max_only char(1) DEFAULT '0',
	int_of_month_to_due double precision DEFAULT 0,
	paidinttypesaving char(1) DEFAULT '0',
	paidintop_compound_date timestamp,
	paidintstm_compound_date timestamp,
	dep_mth_like_bot double precision DEFAULT 0,
	after_firstdued_calintype varchar(6) DEFAULT '00',
	limit_fixed double precision DEFAULT 0,
	dued_one_time char(1) DEFAULT '0',
	withdraw_af_type varchar(6),
	withdraw_af_type2 varchar(6),
	dep_rate decimal(6,4)
) ;
COMMENT ON TABLE sc_dep_m_fixed_deposit_cond IS E'!NN!';
ALTER TABLE sc_dep_m_fixed_deposit_cond ADD PRIMARY KEY (deposit_type_code);


