CREATE TABLE sc_dep_m_rule (
	deposit_type_code varchar(6) NOT NULL,
	deposit_name varchar(50),
	interest_cal_method_code varchar(6),
	deposit_group_code varchar(6),
	minimum_balance_on_open decimal(15,2),
	minbalancefornextdeposit decimal(15,2),
	minbalanceforwithdraw decimal(15,2),
	interest_tax_rate decimal(15,2),
	minimum_balance_total decimal(15,2),
	use_int_method double precision,
	interrest_rate_expire_date timestamp,
	interest_rate_effective_date timestamp,
	min_balance_monthly_int decimal(15,2),
	keep_status_fee char(1),
	int_month_status char(1),
	int_month_paid_status char(1),
	int_month_compound_day double precision,
	min_balance_keep_fee decimal(15,2),
	min_movement_times double precision,
	min_movement_month double precision,
	keep_fee_percent decimal(15,2),
	keep_fee_method double precision,
	method_ret_paid_int double precision,
	method_int_ret double precision,
	minbalanceforint decimal(15,2),
	ret_int_month_status char(1),
	ret_int_month_rate decimal(6,4),
	keeping_group varchar(6),
	froce_close_acc char(1),
	closing_date timestamp,
	deposit_times double precision,
	mininum_dep_times double precision,
	op_monthly_date timestamp,
	stm_monthly_date timestamp,
	zero_withdraw double precision,
	max_dep_times double precision,
	month_count_day_int double precision,
	used_type_status char(1),
	int_cal_arrear_method varchar(6),
	int_account_id varchar(8),
	period_int_month double precision,
	intrate_present_day char(1),
	prewithdrawdue_havetax char(1),
	int_mlr_paid_month_rate decimal(8,6),
	close_acc_no_int char(1),
	minimum_day_fee decimal(15,2),
	minimum_day numeric(38),
	account_monthlyint_wait varchar(8),
	max_bal_total_per_account decimal(15,2),
	max_account_per_type double precision,
	atm_status char(1),
	paid_int_month_next timestamp,
	use_rate_int_fixed char(1),
	paid_int_close_status char(1),
	paid_int_when_due char(1),
	max_total_balance_all decimal(15,2),
	int_arrear_account_id varchar(8),
	taxint_account_id varchar(8),
	account_id varchar(15),
	lon_coll_status varchar(1),
	keep_max_fee decimal(15,2) DEFAULT 0,
	keep_min_fee decimal(15,2) DEFAULT 0,
	keep_idea_status char(1) DEFAULT '0',
	froce_close_method_retint char(1) DEFAULT '0',
	froce_close_typecode_retint varchar(6) DEFAULT '00',
	froce_close_deppermonth double precision DEFAULT 0,
	froce_close_latetodep double precision DEFAULT 0,
	paid_intmonth_nostm char(1) DEFAULT '0',
	accross_month_as_one char(1) DEFAULT '0',
	min_paidint decimal(15,2) DEFAULT 0,
	prewithdraw_withtax char(1) DEFAULT '0',
	dep_count double precision DEFAULT 0,
	dep_month char(1) DEFAULT '0',
	tax_account_id varchar(8),
	can_not_deposit char(1) DEFAULT '0',
	int_step_rate char(1) DEFAULT '0',
	froce_close_paidintonefordue char(1) DEFAULT '0',
	use_int_mlr_paid_month char(1) DEFAULT '0',
	transfer_fixed_due_for_close char(1) DEFAULT '0',
	mergecal_int_type varchar(6) DEFAULT '00',
	froce_edit_foropenacc char(1) DEFAULT '0',
	interest_of_intrate decimal(10,6) DEFAULT 0,
	reason_withdraw_status char(1) DEFAULT '0',
	fund_for_frend char(1) DEFAULT '0',
	sequence_no double precision DEFAULT 0,
	fund_fee_code varchar(6) DEFAULT '00',
	ret_int_month_type varchar(6) DEFAULT '00',
	use_dw_print double precision DEFAULT 0,
	choose_fixed_depmonth char(1) DEFAULT '0',
	use_fixed_deposit_cond char(1) DEFAULT '0',
	fixed_div_month_int char(1) DEFAULT '0',
	account_id_fee varchar(8),
	method_intmth_cal char(1) DEFAULT '0',
	int_step_active char(1) DEFAULT '0',
	opendate_at_firstdep char(1) DEFAULT '0',
	tax_befor_dued char(1) DEFAULT '0',
	tax_status_bydep char(1) DEFAULT '0',
	intmonth_bydep char(1) DEFAULT '0',
	spp_able char(1) DEFAULT '0',
	not_open_dep char(1) DEFAULT '0',
	only_mem_type varchar(6) DEFAULT '00',
	deposit_group_slip char(1) DEFAULT '0',
	fund_mem char(1) DEFAULT '0',
	cat_id char(1) DEFAULT '0',
	insure_status char(1),
	mobile_status char(1) DEFAULT 'N',
	deposit_flag char(1) DEFAULT 'N',
	withdraw_flag char(1) DEFAULT 'N',
	max_per_month decimal(15,2) DEFAULT 0,
	invest_status char(1) DEFAULT '0',
	paid_loan char(1) DEFAULT '0',
	conclude_int char(1),
	short_name varchar(50),
	deposit_group_report char(2),
	fixed_year_2 char(1),
	use_spec_table_status char(1),
	bot_400 char(1),
	dw_print_card varchar(100),
	dw_print_passbook_fp varchar(100),
	dw_print_passbook_item varchar(100),
	dw_print_slip varchar(100),
	dw_print_interest varchar(100),
	dw_print_withdraw_fee varchar(100),
	dw_print_slip_withdraw varchar(100),
	dw_statement varchar(100)
) ;
COMMENT ON TABLE sc_dep_m_rule IS E'!NN!';
COMMENT ON COLUMN sc_dep_m_rule.account_id IS E'!N?????????N!!MM!';
COMMENT ON COLUMN sc_dep_m_rule.account_monthlyint_wait IS E'!N???????????????????N!!MM!';
COMMENT ON COLUMN sc_dep_m_rule.deposit_name IS E'!N?????????????N!!MM!';
COMMENT ON COLUMN sc_dep_m_rule.deposit_type_code IS E'!N????N!!MM!';
COMMENT ON COLUMN sc_dep_m_rule.int_account_id IS E'!N?????????????????????N!!MM!';
COMMENT ON COLUMN sc_dep_m_rule.int_arrear_account_id IS E'!N?????????????????????N!!MM!';
COMMENT ON COLUMN sc_dep_m_rule.taxint_account_id IS E'!N?????????????????N!!MM!';
ALTER TABLE sc_dep_m_rule ADD PRIMARY KEY (deposit_type_code);


