CREATE TABLE sc_dep_m_close_monthly_okd (
	present_account_year double precision NOT NULL,
	post_month double precision NOT NULL,
	deposit_account_no varchar(15) NOT NULL,
	deposit_type_code varchar(2),
	membership_no varchar(15),
	deposit_opened_date timestamp,
	deposit_account_name varchar(200),
	deposit_objective char(200),
	passbook_no char(15),
	deposit_balance decimal(15,2),
	withdrawable_amount decimal(15,2),
	cheque_pending_amount decimal(15,2),
	loan_holding_amount decimal(15,2),
	deposit_standsecurity_amount decimal(15,2),
	sequester_status char(1),
	monthly_deposit decimal(15,2),
	monthly_withdraw decimal(15,2),
	withdraw_count double precision,
	accumulate_interest decimal(15,2),
	last_calcint_date timestamp,
	beging_balance decimal(15,2),
	int_due decimal(15,2),
	int_due_tax decimal(15,2),
	int_due_date timestamp,
	monthly_int_status char(1),
	monthly_int_amount decimal(15,2),
	method_int_month char(1),
	deposit_account_no_other char(15),
	monthly_tax_amount decimal(15,2),
	monthly_int_arrear decimal(15,2),
	monthly_int_op_date timestamp,
	monthly_int_acc_no char(15),
	special_rule_status char(1),
	monthly_deposit_status char(1),
	monthly_deposit_amount decimal(15,2),
	monthly_deposit_op_date timestamp,
	tax_status char(1),
	close_status char(1),
	deposit_closing_date timestamp,
	printed_seq_no double precision,
	last_line double precision,
	last_page double precision,
	card_printed_seq_no double precision,
	card_last_page double precision,
	card_last_line double precision,
	accu_int_holding decimal(15,2),
	address char(200),
	officer_id char(15),
	fee_maintenance decimal(15,2),
	fee_maintenance_arrear decimal(15,2),
	int_rate_status char(1),
	int_rate decimal(15,2),
	accu_month decimal(15,2),
	cal_int_month timestamp,
	tax_month decimal(15,2),
	begin_month decimal(15,2),
	monthly_close_entry char(15),
	monthly_close_day timestamp,
	monthly_close_branch char(2),
	opn_branch char(2),
	member_staus char(1),
	backday_dep_amt decimal(15,2),
	backday_withdraw_amt decimal(15,2),
	int_paid decimal(15,2),
	int_close decimal(15,2),
	open_account_amt decimal(15,2),
	close_account_amt decimal(15,2),
	member_status char(1),
	int_mlr decimal(15,2),
	min_balance_mlr decimal(15,2)
) ;
ALTER TABLE sc_dep_m_close_monthly_okd ALTER COLUMN present_account_year SET NOT NULL;
ALTER TABLE sc_dep_m_close_monthly_okd ALTER COLUMN post_month SET NOT NULL;
ALTER TABLE sc_dep_m_close_monthly_okd ALTER COLUMN deposit_account_no SET NOT NULL;


