CREATE TABLE sc_dep_m_fixed_item_6606 (
	deposit_account_no char(15),
	ref_seq_no double precision,
	fixed_date timestamp,
	fixed_amount decimal(15,2),
	fixed_dued_date timestamp,
	fixed_dued_month_count double precision,
	fixed_dued_int decimal(15,2),
	fixed_monthly_int decimal(15,2),
	fixed_paid_monthly_int decimal(15,2),
	fixed_next_monthly_dued timestamp,
	interest_rate decimal(8,6),
	cheque_no char(20),
	bank_code char(6),
	bank_branch_id char(6),
	cheque_clearing_status char(1),
	clearing_date timestamp,
	clearing_user char(15),
	start_int_cheque_date timestamp,
	interest_arrear decimal(15,2),
	interest_arrear_date timestamp,
	interest_cut decimal(15,2),
	interest_cut_date timestamp,
	officer_id char(15),
	operate_date timestamp,
	branch_id char(2),
	fixed_paid_int decimal(15,2),
	fixed_paid_date timestamp,
	fixed_paid_due_date timestamp,
	working_day timestamp,
	first_fixed_date timestamp,
	first_dued_date timestamp,
	first_fixed_amount decimal(15,2),
	first_monthly_int decimal(15,2),
	times_dued numeric(38),
	fixed_last_monthly_due timestamp
) ;


