CREATE TABLE sc_dep_t_deposit_slip (
	deposit_slip_no varchar(15) NOT NULL,
	operate_date timestamp,
	deposit_money_type_code varchar(6),
	account_no varchar(15),
	deposit_by_cash_balance decimal(15,2),
	account_coop varchar(15),
	account_coop_date timestamp,
	account_coop_balance decimal(15,2),
	deposit_account_no varchar(15),
	cheque_no varchar(20),
	cheque_due timestamp,
	bank_branch_id varchar(6),
	bank_code varchar(6),
	accu_int_cheque decimal(15,2),
	start_int_cheque_date timestamp,
	cheque_clearing_status char(1),
	clearing_date timestamp,
	clearing_user varchar(50),
	balance_pre_adj decimal(15,2),
	accu_int_pre_adj decimal(15,2),
	accu_int_new decimal(15,2),
	doc_no varchar(15),
	doc_date timestamp,
	doc_type varchar(3),
	deposit_slip_type varchar(3),
	fee_amount decimal(15,2),
	fee_amount_old decimal(15,2),
	old_operate_date timestamp,
	old_item_type varchar(3),
	old_balance decimal(15,2),
	old_withdraw decimal(15,2),
	old_pending decimal(15,2),
	old_acc_int decimal(15,2),
	op_receive_int decimal(15,2),
	op_ret_int decimal(15,2),
	op_tax decimal(15,2),
	op_keep_acc decimal(15,2),
	op_item_type varchar(3),
	op_balance decimal(15,2),
	op_withdraw decimal(15,2),
	op_pending decimal(15,2),
	op_acc_int decimal(15,2),
	officer_id varchar(16),
	entry_date timestamp,
	branch_id varchar(6),
	working_day timestamp,
	op_money_real decimal(15,2),
	fee_real decimal(15,2),
	client_name varchar(30),
	print_slip char(1),
	print_slip_int char(1),
	fin_status char(1),
	vourcher_no varchar(30) DEFAULT '<NEW>',
	cancel_status char(1),
	ret_int_date timestamp,
	transfer_status char(1) DEFAULT '0',
	bank_transfer varchar(15),
	group_pay double precision DEFAULT 0,
	own_other_type varchar(3),
	reason_withdraw varchar(3),
	print_slip_fee char(1) DEFAULT '0',
	mergecal_int_type varchar(6) DEFAULT '00',
	trans_item varchar(3),
	bank_fin varchar(6),
	ref_deposit_slip_no varchar(15),
	slip_multi_paid char(1) DEFAULT '0',
	withdraw_total decimal(15,2) DEFAULT 0,
	cancel_vourcher_no varchar(15),
	month_due double precision DEFAULT 0,
	fixed_count_withdraw char(1) DEFAULT '0',
	cancel_deposit_date timestamp,
	cancel_id varchar(16),
	cancel_pc varchar(3),
	cancel_br varchar(6),
	cancel_time timestamp,
	notcount_withdraw char(1) DEFAULT '0',
	adjust_fin_status char(1) DEFAULT '0',
	adjust_fin_vourcher varchar(15),
	savefixed_status char(1) DEFAULT '0',
	real_paid double precision DEFAULT 0,
	depositor varchar(100),
	bank_accno varchar(10),
	withdraw_count char(1) DEFAULT '0',
	finance_date timestamp,
	finance_cancel timestamp,
	remark_slip varchar(100),
	accumulate_interest decimal(15,2) DEFAULT 0,
	last_calcint_date timestamp,
	split_mode char(1) DEFAULT '0',
	crem_status char(1) DEFAULT '0',
	monthly_int_status char(1) DEFAULT '0'
) ;
COMMENT ON TABLE sc_dep_t_deposit_slip IS E'!NN!';
CREATE INDEX idx_dep_slip_acc_no ON sc_dep_t_deposit_slip (account_no);
CREATE INDEX idx_dep_slip_dmtype ON sc_dep_t_deposit_slip (deposit_money_type_code);
CREATE INDEX idx_dep_slip_opdate ON sc_dep_t_deposit_slip (operate_date);
ALTER TABLE sc_dep_t_deposit_slip ADD PRIMARY KEY (deposit_slip_no);


