CREATE TABLE sc_dep_m_cheque (
	deposit_account_no char(15),
	seq_no double precision,
	operate_date timestamp,
	bank_id char(6),
	bank_branch_id char(6),
	cheque_no varchar(15),
	amount decimal(15,2),
	due_date timestamp,
	ref_doc varchar(15),
	clearing_status char(1),
	clearing_date timestamp,
	clearing_user varchar(30),
	branch_id char(2),
	payslip_status char(1),
	payslip_date timestamp,
	payslip_entry_id varchar(20),
	payslip_entry_date timestamp,
	payslip_entry_br char(2),
	inbank_status char(1),
	entry_id varchar(20),
	payslip_working_day timestamp,
	cancle_status char(1),
	cheque_code char(1),
	clearing_working timestamp,
	working_day timestamp,
	entry_working timestamp,
	cancle_date timestamp,
	cancle_id varchar(20),
	cancle_client varchar(20),
	cancle_br_id char(2)
) ;


