CREATE TABLE sc_fin_m_bank_statement (
	bank_fin varchar(6) NOT NULL,
	seq_no numeric(38) NOT NULL DEFAULT 0,
	operate_date timestamp,
	operate_time varchar(6),
	teller_id varchar(10),
	trans_code varchar(10),
	item_desc varchar(100),
	cheque_no varchar(10),
	item_amount decimal(15,2) DEFAULT 0,
	item_tax decimal(15,2) DEFAULT 0,
	item_balance decimal(15,2) DEFAULT 0,
	bank_br varchar(6),
	file_no numeric(38) DEFAULT 0,
	line_seqno numeric(38) DEFAULT 0,
	item_payable decimal(15,2) DEFAULT 0,
	entry_date timestamp,
	entry_id varchar(16),
	entry_br varchar(6),
	entry_pc varchar(3),
	cancel_status char(1) DEFAULT '0',
	cancel_date timestamp,
	cancel_id varchar(16),
	cancel_br varchar(6),
	cancel_pc varchar(3),
	link_recvpay char(1) DEFAULT '0',
	membership_no varchar(15),
	verify_seq numeric(38) DEFAULT 0,
	bank_error char(1) DEFAULT '0',
	verify_amount decimal(15,2) DEFAULT 0,
	memno_lookup varchar(15),
	vourcher_no varchar(30),
	data_lookup varchar(100),
	vourcher_pot varchar(30),
	verify_date timestamp
) ;
ALTER TABLE sc_fin_m_bank_statement ADD PRIMARY KEY (bank_fin,seq_no);


