CREATE TABLE sc_fin_m_bank_payment (
	bank_fin varchar(6) NOT NULL,
	seq_no numeric(38) NOT NULL DEFAULT 0,
	item_no numeric(38) NOT NULL DEFAULT 0,
	item_amount decimal(15,2) DEFAULT 0,
	item_balance decimal(15,2) DEFAULT 0,
	receipt_date timestamp,
	pay_method varchar(3),
	membership_no varchar(15),
	pay_docno varchar(15),
	fkr_year numeric(38) DEFAULT 0,
	fkr_month numeric(38) DEFAULT 0,
	fkr_saltime numeric(38) DEFAULT 0,
	fkr_agent varchar(15),
	fkr_seqno numeric(38) DEFAULT 0,
	entry_id varchar(16),
	entry_date timestamp,
	entry_br varchar(6),
	entry_pc varchar(3),
	cancel_status char(1) DEFAULT '0',
	cancel_id varchar(16),
	cancel_date timestamp,
	cancel_br varchar(6),
	cancel_pc varchar(3),
	fbk_account_id varchar(8),
	ffe_seq_no numeric(38) DEFAULT 0,
	bank_mode char(1) DEFAULT 'S',
	item_remark varchar(50),
	finance_date timestamp,
	finance_cancel timestamp,
	deposit_slip_no varchar(15),
	memname varchar(250) DEFAULT ''
) ;
ALTER TABLE sc_fin_m_bank_payment ADD PRIMARY KEY (bank_fin,seq_no,item_no);


