CREATE TABLE sc_fin_m_bank (
	bank_fin varchar(6) NOT NULL,
	account_type varchar(6),
	bank_id varchar(6),
	branch_id varchar(6),
	bank_name varchar(100),
	cheque_code varchar(6),
	open_date timestamp,
	balance_begin decimal(15,2),
	balance decimal(15,2),
	account_id varchar(15),
	sort_order integer,
	bank_id_code varchar(20),
	cheque_running integer,
	bank_balance decimal(15,2),
	branch_coop varchar(6),
	cheque_seqno bigint,
	close_status char(1),
	cheque_style char(1) DEFAULT '0',
	cheque_picture varchar(100),
	account_no varchar(10),
	recvpay_able char(1) DEFAULT '0',
	keep_monthly_able char(1) DEFAULT '0',
	pay_bookbank_able char(1) DEFAULT '0',
	install_verify_wait char(1) DEFAULT '0',
	bank_dummy_status char(1) DEFAULT '0',
	dr_account_status char(1) DEFAULT '0',
	spp_able char(1),
	file_intdep char(1),
	paid_loan char(1) DEFAULT '0',
	acc_name_eng varchar(100),
	bill_status char(1) DEFAULT '0',
	mobile_status char(1) DEFAULT '0',
	billpayment_status char(1) DEFAULT '0',
	col_date_last varchar(100),
	account_tr varchar(15),
	by_vourhcer char(1) DEFAULT '0',
	code_for_transbank varchar(10),
	verify_wait_accid varchar(15)
) ;
ALTER TABLE sc_fin_m_bank ADD PRIMARY KEY (bank_fin);
ALTER TABLE sc_fin_m_bank ALTER COLUMN bank_fin SET NOT NULL;


