CREATE TABLE sc_fin_vourcher_head (
	vourcher_no varchar(30) NOT NULL DEFAULT '<NEW>',
	operate_date timestamp,
	vourcher_owner varchar(15),
	vourcher_name varchar(100),
	vourcher_desc varchar(255),
	vourcher_type char(1),
	vourcher_group varchar(7),
	post_journal char(1) DEFAULT '0',
	post_system char(1) DEFAULT '0',
	journal_date timestamp,
	entry_id varchar(16),
	entry_date timestamp,
	entry_branch varchar(6),
	cancel_status char(1) DEFAULT '0',
	cancel_id varchar(16),
	cancel_date timestamp,
	cancel_branch varchar(6),
	cheque_install char(1) DEFAULT 'N',
	cheque_total decimal(15,2),
	cheque_post decimal(15,2),
	ref_system varchar(3),
	ref_docno varchar(15),
	fin_book char(1),
	vourcher_value decimal(15,2),
	money_accept char(1) DEFAULT '0',
	post_open_no double precision,
	adjust_status char(1) DEFAULT '0',
	adjust_vourcher_no varchar(30),
	many2many_status char(1),
	cheque_printable char(1) DEFAULT '0',
	shot_app varchar(3),
	money_return_wait decimal(15,2),
	entry_fin varchar(16),
	blink_status char(1),
	blink_vourcher varchar(15),
	not_journal char(1) DEFAULT '0',
	receipt_print varchar(15),
	counter_split char(1) DEFAULT '0',
	create_loan char(1) DEFAULT '0',
	money_accept_findate timestamp,
	money_accept_time timestamp,
	money_accept_br varchar(6),
	money_accept_pc varchar(3),
	cash_type char(1) DEFAULT '0',
	cheque_paid double precision DEFAULT 0,
	company_id varchar(15),
	adj_tax decimal(15,2) DEFAULT 0,
	borrow_status char(1) DEFAULT '0',
	borrow_vourcher varchar(15),
	borrow_close char(1) DEFAULT '0',
	borrow_refund_amount decimal(15,2) DEFAULT 0.00,
	borrow_return timestamp,
	slip_no varchar(50)
) ;
COMMENT ON TABLE sc_fin_vourcher_head IS E'!NN!';
ALTER TABLE sc_fin_vourcher_head ADD PRIMARY KEY (vourcher_no);


