CREATE TABLE sc_hr_human (
	c_id varchar(15) NOT NULL,
	c_branchid varchar(6) NOT NULL,
	c_prename varchar(6),
	c_name varchar(40),
	c_surname varchar(40),
	c_midname varchar(40),
	c_birthday timestamp,
	c_old decimal(15,2),
	c_sex char(1),
	c_origin varchar(60),
	c_nationality varchar(60),
	c_religion varchar(60),
	c_taxid varchar(15),
	c_accountsaving varchar(15),
	c_citzenid varchar(30),
	c_socialid varchar(30),
	c_social_hospital varchar(100),
	c_malady_personal varchar(255),
	c_lose_medicine varchar(255),
	c_birthmark varchar(255),
	c_gain_name varchar(40),
	c_gain_surname varchar(40),
	c_gain_relation varchar(60),
	c_gain_address varchar(255),
	c_marrystatus varchar(15),
	c_marry_name varchar(40),
	c_marry_surname varchar(40),
	c_marry_office_address varchar(255),
	c_marry_phoe varchar(60),
	c_marry_draw_gain varchar(100),
	c_child_num double precision,
	c_child_boy_num double precision,
	c_child_girl_num double precision,
	c_adress varchar(100),
	c_mu varchar(6),
	c_soi varchar(100),
	c_road varchar(100),
	c_tambon varchar(100),
	c_distict varchar(100),
	c_province_code varchar(6),
	c_post_code varchar(6),
	c_phone varchar(60),
	c_mobile_phone varchar(60),
	c_adress_b varchar(100),
	c_mu_b varchar(6),
	c_soi_b varchar(100),
	c_road_b varchar(100),
	c_tambon_b varchar(100),
	c_distict_b varchar(100),
	c_province_code_b varchar(6),
	c_post_code_b varchar(6),
	c_father_name varchar(120),
	c_father_old decimal(15,2),
	c_father_occupation varchar(200),
	c_father_office_address varchar(255),
	c_father_draw_gain varchar(100),
	c_mother_name varchar(120),
	c_mother_old decimal(15,2),
	c_mother_occupation varchar(200),
	c_mother_office_address varchar(255),
	c_mother_draw_gain varchar(100),
	c_tax_id varchar(20),
	entry_id varchar(15),
	entry_date timestamp,
	c_father_org char(1),
	c_mother_org char(1),
	membership_no varchar(15),
	c_mary_can_draw char(1),
	c_father_can_draw char(1),
	c_mother_can_draw char(1),
	c_father_status char(1),
	c_mother_status char(1),
	c_mother_edu_amount decimal(15,2),
	c_father_edu_amount decimal(15,2),
	c_branchid_rpt varchar(6),
	mother_birthday timestamp,
	father_birthday timestamp
) ;
ALTER TABLE sc_hr_human ADD PRIMARY KEY (c_branchid,c_id);
ALTER TABLE sc_hr_human ALTER COLUMN c_id SET NOT NULL;
ALTER TABLE sc_hr_human ALTER COLUMN c_branchid SET NOT NULL;


