CREATE TABLE sc_hr_rule_sawatdekan (
	c_seq double precision NOT NULL,
	c_suviver_amount decimal(15,2),
	c_food_per_day decimal(15,2),
	c_part_time_normalday decimal(15,2),
	c_part_time_weekday decimal(15,2),
	c_parttime_elseday decimal(15,2),
	c_child_amount decimal(15,2),
	c_child_num double precision,
	c_child_year double precision,
	c_child_num_sick double precision,
	c_tran_doc double precision,
	c_sum_money_per decimal(15,2),
	c_sum_socity_per decimal(15,2),
	c_sum_tax_per decimal(15,2),
	c_seq_runing bigint,
	c_live_amount decimal(15,2),
	c_chlid_1_amount decimal(15,2),
	c_chlid_2_amount decimal(15,2),
	c_edu_amount decimal(15,2),
	c_payaban_amount decimal(15,2),
	c_retrie_year_min decimal(15,2),
	c_sub_tax1 decimal(15,2),
	c_sub_tax12 decimal(15,2),
	c_socity_max decimal(15,2),
	c_book_runing double precision,
	c_hakmoneypakan decimal(15,2),
	c_book_runing_out_in double precision,
	c_book_runing_out_out double precision,
	c_book_runing_in_in double precision,
	c_book_runing_in_out double precision,
	head_bookdocno char(20),
	book_year double precision
) ;
ALTER TABLE sc_hr_rule_sawatdekan ADD PRIMARY KEY (c_seq);


