CREATE TABLE sc_hr_doc_main (
	c_prd_id char(30),
	c_branchid char(2),
	c_prddesc varchar(200),
	c_date_issue timestamp,
	c_date_end timestamp,
	c_max_rent double precision,
	c_place_give varchar(300),
	c_branch_place_give varchar(300),
	c_build_place_give varchar(300),
	c_box_room_give varchar(150),
	c_place_level_give varchar(150),
	c_box_place_give varchar(150),
	c_book_out_id varchar(30),
	c_book_out_date timestamp,
	c_book_out_story varchar(200),
	c_book_out_to_name varchar(120),
	c_book_out_type char(1),
	c_book_in_id varchar(30),
	c_book_in_date timestamp,
	c_book_in_story varchar(200),
	c_book_in_to_name varchar(120),
	c_book_in_type char(1),
	c_book_soamoto_id varchar(30),
	c_book_soamoto_date timestamp,
	c_book_soamoto_story varchar(200),
	c_part_of_postion char(2),
	c_postion char(2),
	c_due_date_destory timestamp,
	c_maatee_destroy varchar(100),
	c_type_destroy varchar(30),
	c_time_to_destroy double precision,
	c_person_takecare varchar(120),
	c_status char(2),
	c_status_rent char(2),
	entry_id varchar(15),
	entry_date timestamp,
	c_doc_out_file varchar(500),
	c_doc_out_desc varchar(4000),
	c_book_out_from varchar(200),
	c_book_out_pos varchar(200),
	c_book_in_from varchar(200),
	c_book_in_pos varchar(200),
	c_doc_in_desc varchar(4000),
	c_remark varchar(500),
	c_doc_in_in varchar(200),
	c_tye char(1),
	c_doc_in_in_date timestamp,
	c_book_out_from_from varchar(300),
	c_book_out_to varchar(300),
	n_type char(3)
) ;


