CREATE TABLE sc_hr_off_member (
	official_no varchar(15) NOT NULL,
	membership_no varchar(15),
	department_id varchar(6),
	official_position varchar(6),
	committee_position varchar(6),
	social_security_id varchar(15),
	tax_id varchar(15),
	hospital_social_id varchar(6),
	ailment_often varchar(100),
	medicine_less varchar(100),
	scar_position varchar(100),
	heal_amount_bf decimal(15,2) DEFAULT 0,
	salary_living decimal(15,2) DEFAULT 0,
	salary_special decimal(15,2) DEFAULT 0,
	tax_amount decimal(15,2) DEFAULT 0,
	alive_status char(1) DEFAULT '0',
	official_status_code char(1) DEFAULT '0',
	resignation_approve_date timestamp,
	deposit_account_no varchar(15),
	official_type varchar(6) DEFAULT '01',
	compensate_amount decimal(15,2) DEFAULT 0,
	employer_provided_amount decimal(15,2) DEFAULT 0,
	type_pay_salary varchar(6) DEFAULT 'TRD',
	bank_acc_no varchar(15),
	working_date timestamp,
	salary_level double precision DEFAULT 0,
	prename_code varchar(6),
	member_name varchar(50),
	member_surname varchar(50),
	sex char(1) DEFAULT '0',
	nationality_code varchar(6) DEFAULT '00',
	date_of_birth timestamp,
	id_card varchar(15),
	salary_amount decimal(15,2) DEFAULT 0,
	eng_name varchar(100),
	paid_other_depno varchar(15),
	salary_exact decimal(15,2) DEFAULT 0,
	assign_date timestamp,
	day_forword_sum numeric(38) DEFAULT 0,
	salary_minus decimal(15,2) DEFAULT 0,
	social_amount decimal(15,2) DEFAULT 0,
	deposit_sasom varchar(15),
	deposit_insure varchar(15),
	sasom_amt decimal(15,2) DEFAULT 0,
	marriage_status char(1) DEFAULT '0',
	bank_code varchar(6),
	student_loan_amount decimal(15,2) DEFAULT 0,
	c_retire_pay decimal(15,2),
	c_retire_date timestamp,
	c_retire_old integer,
	salary_living_status char(1) DEFAULT '0',
	salary_resign decimal(15,2),
	amount_profund_month double precision,
	amount_profund_balance double precision,
	social_not char(1)
) ;
ALTER TABLE sc_hr_off_member ADD PRIMARY KEY (official_no);
ALTER TABLE sc_hr_off_member ALTER COLUMN official_no SET NOT NULL;


