CREATE TABLE sc_hr_constant (
	coop_no varchar(15) NOT NULL,
	account_tax varchar(8),
	account_social_security varchar(8),
	account_salary varchar(8),
	account_salary_living varchar(8),
	account_salary_special varchar(8),
	use_ot char(1) DEFAULT '0',
	use_bonus char(1) DEFAULT '0',
	use_leave char(1) DEFAULT '0',
	use_working_late char(1) DEFAULT '0',
	use_spec_salary char(1) DEFAULT '0',
	use_arrear_salary char(1) DEFAULT '0',
	use_uniform char(1) DEFAULT '0',
	use_souvenir char(1) DEFAULT '0',
	use_vehicle_value char(1) DEFAULT '0',
	use_allowance char(1) DEFAULT '0',
	use_superannuate char(1) DEFAULT '0',
	use_training char(1) DEFAULT '0',
	use_working_note char(1) DEFAULT '0',
	use_parole char(1) DEFAULT '0',
	use_position_adj char(1) DEFAULT '0',
	use_dpm_adj char(1) DEFAULT '0',
	use_his_salary char(1) DEFAULT '0',
	use_aid char(1) DEFAULT '0',
	use_active char(1) DEFAULT '0',
	account_employer_provided varchar(8),
	account_compensate varchar(8),
	ot_tax_rate decimal(8,6) DEFAULT 0,
	round_amount decimal(15,2) DEFAULT 0,
	round_method char(1) DEFAULT '0',
	paid_shar_lon_auto char(1) DEFAULT '0',
	account_lon_shr varchar(8),
	use_salary_exact char(1) DEFAULT '0',
	group_display varchar(30),
	account_ot varchar(8),
	post_shln_not char(1),
	account_sasom varchar(8),
	coop_pay_sasom varchar(8),
	coop_pay_social varchar(8),
	use_income char(1) DEFAULT '0',
	use_parent char(1) DEFAULT '0',
	use_child char(1) DEFAULT '0',
	use_spouse char(1) DEFAULT '0',
	use_work_coll char(1) DEFAULT '0',
	use_committee char(1) DEFAULT '0',
	use_ot_desc char(1) DEFAULT '0',
	account_student_loan varchar(8),
	account_living char(8),
	account_profund char(8)
) ;
ALTER TABLE sc_hr_constant ADD PRIMARY KEY (coop_no);
ALTER TABLE sc_hr_constant ALTER COLUMN coop_no SET NOT NULL;


