CREATE TABLE sc_kep_m_agent_receive (
	receive_year double precision NOT NULL DEFAULT 0,
	receive_month double precision NOT NULL DEFAULT 0,
	salary_time double precision NOT NULL DEFAULT 0,
	agent_no varchar(15) NOT NULL,
	seq_no double precision NOT NULL DEFAULT 0,
	receive_amount decimal(15,2) DEFAULT 0,
	entry_id varchar(16),
	entry_br varchar(6),
	entry_date timestamp,
	entry_pc varchar(3),
	cancel_status char(1) DEFAULT '0',
	vourcher_no varchar(15),
	operate_date timestamp,
	money_type varchar(3),
	bank_fin varchar(6),
	chq_bank_id varchar(6),
	chq_bank_br varchar(6),
	receive_balance decimal(15,2) DEFAULT 0,
	receive_bymem char(1) DEFAULT '0',
	receive_memno varchar(15),
	item_type char(1) DEFAULT 'I',
	link_bank_payment char(1) DEFAULT '0',
	member_group_no varchar(15),
	cancel_date timestamp,
	ppm_status char(1) DEFAULT '0',
	ppm_year double precision,
	ppm_month double precision,
	deposit_account_no varchar(15),
	receipt_number varchar(15),
	return_amount decimal(15,2) DEFAULT 0,
	count_return bigint,
	agent_status char(1) DEFAULT '0',
	loan_contract_no varchar(15),
	book_bank_seq numeric(38),
	item_desc varchar(100),
	cancel_id varchar(16),
	cancel_entry timestamp,
	slip_no varchar(50)
) ;
ALTER TABLE sc_kep_m_agent_receive ADD PRIMARY KEY (receive_year,receive_month,salary_time,agent_no,seq_no);


