CREATE TABLE sc_lon_req_coll_law_owner (
	doc_no varchar(15) NOT NULL,
	seq_no double precision NOT NULL,
	owner_name varchar(150),
	owner_birth_of_date timestamp,
	owner_sex char(1) DEFAULT 'M',
	owner_id_card varchar(15),
	owner_id_tax varchar(15),
	owner_nation varchar(100),
	owner_father_name varchar(400),
	owner_mother_name varchar(400),
	owner_marriage_status char(1) DEFAULT '0',
	owner_spouse_name varchar(400),
	owner_spouse_id_card varchar(15),
	owner_address_no varchar(100),
	owner_moo varchar(100),
	owner_soi varchar(100),
	owner_road varchar(100),
	owner_tumbol varchar(100),
	owner_district_code varchar(6) DEFAULT '00',
	owner_province_code varchar(6) DEFAULT '00',
	owner_postcode varchar(10),
	owner_telephone varchar(100),
	owner_mooban varchar(100),
	loan_requestment_no varchar(15),
	coll_ref varchar(50),
	age double precision,
	parent varchar(50),
	married varchar(10),
	sponse_name varchar(50),
	nationality varchar(10),
	status char(1),
	address varchar(50),
	tambol varchar(50),
	amper varchar(50),
	jungwat varchar(50),
	muu varchar(20),
	seq_coll double precision,
	marriage_status char(1),
	datetime_of_birth timestamp,
	id_card varchar(13),
	tel_no varchar(50),
	road varchar(30),
	soi varchar(30),
	muu_ban varchar(30),
	date_of_birth timestamp,
	is_member char(1)
) ;
ALTER TABLE sc_lon_req_coll_law_owner ADD PRIMARY KEY (doc_no,seq_no);
ALTER TABLE sc_lon_req_coll_law_owner ALTER COLUMN doc_no SET NOT NULL;
ALTER TABLE sc_lon_req_coll_law_owner ALTER COLUMN seq_no SET NOT NULL;


