CREATE TABLE sc_lon_req_coll_law_head (
	doc_no varchar(15) NOT NULL,
	membership_no varchar(15),
	cancel_status char(1) DEFAULT '0',
	appraised_total decimal(15,2) DEFAULT 0,
	mortgage_value decimal(15,2) DEFAULT 0,
	refinance_status char(1) DEFAULT '0',
	coll_type varchar(2) DEFAULT '00',
	coll_ref_type varchar(2) DEFAULT '00',
	order_no integer DEFAULT 0,
	mortgage_date timestamp,
	redemption_type char(1) DEFAULT '0',
	redemption_date timestamp,
	commitee_no varchar(15),
	commitee_name varchar(100),
	cmt_fullname1 varchar(100),
	cmt_fullname2 varchar(100),
	remark varchar(100),
	cmt_fullname3 varchar(100),
	cmt_fullname4 varchar(100),
	redemption_text varchar(100),
	tax_reduce_amount decimal(15,2) DEFAULT 0,
	receive_date timestamp,
	td_control varchar(6),
	cmt_no1 varchar(15),
	cmt_no2 varchar(15),
	remark1 varchar(100),
	remark2 varchar(100),
	mortgage_date1 timestamp,
	mortgage_date2 timestamp,
	sequest_status char(1) DEFAULT '0',
	sequest_date timestamp,
	sequest_remark varchar(200),
	borrow_deep_status char(1),
	borrow_mortgage_status char(1),
	borrow_loan_status char(1),
	file_name varchar(100),
	decrease_status char(1) DEFAULT '0',
	include_status varchar(6) DEFAULT '01',
	loan_doc char(1),
	mortgage_status char(1),
	coop_buy char(1)
) ;
ALTER TABLE sc_lon_req_coll_law_head ADD PRIMARY KEY (doc_no);
ALTER TABLE sc_lon_req_coll_law_head ALTER COLUMN doc_no SET NOT NULL;


