CREATE TABLE sc_lsr_m_contract (
	insurance_no char(15) NOT NULL,
	apply_date timestamp NOT NULL,
	insurance_type char(2),
	membership_no char(15),
	member_group_no char(6),
	prename_code char(3),
	mname char(50),
	surname char(50),
	sex char(1),
	date_of_birth timestamp,
	nationality_code char(2),
	occupation_code char(2),
	marriage_status char(20),
	present_address char(200),
	present_tambol char(50),
	present_district_code char(2),
	present_province_code char(2),
	present_postcode char(10),
	remark char(100),
	insurance_pay decimal(15,2),
	insurance_cost decimal(15,2),
	date_of_death timestamp,
	begin_contract_date timestamp,
	end_contract_date timestamp,
	contact_last_date timestamp,
	member_status double precision,
	entry_date timestamp,
	entry_id char(10),
	pay_status double precision,
	total_pay_times double precision,
	pay_time double precision,
	profiter_status double precision,
	contract_number double precision,
	policy_no char(30),
	contract_status double precision,
	id_card char(15),
	list_seq_no double precision,
	age double precision,
	member_status_code char(2),
	dead_status double precision,
	seq_no double precision,
	insurance_pay_arrear decimal(15,2),
	resign_date timestamp,
	advan_amount decimal(15,2),
	temp_arrear decimal(15,2),
	last_up_amount decimal(15,2),
	last_up_amount_arr decimal(15,2),
	reason_resign char(2),
	member_group_no_old char(6),
	post_status char(2),
	application_no char(20),
	cancel_id char(10),
	paid_dividend char(1),
	return_amount decimal(15,2),
	return_day double precision,
	memresign_status char(1),
	receive_advance_date timestamp,
	paid_advance_date timestamp,
	month double precision,
	year double precision,
	fund_amount decimal(15,2),
	ins_loan_amount decimal(15,2),
	ins_loan_receive_date timestamp,
	ins_loan_pay_date timestamp,
	ins_loanc_receive_date timestamp,
	ins_loanc_pay_date timestamp,
	ins_dep_amt decimal(15,2),
	ins_dep_rdate timestamp,
	ins_dep_pdate timestamp,
	ins_dep_pro_amt decimal(15,2),
	ins_sum_amt decimal(15,2),
	ins_sum_rdate timestamp,
	ins_sum_pdate timestamp,
	ins_sum_pro_amt decimal(15,2),
	ins_sfsum_amt decimal(15,2),
	ins_sfsum_rdate timestamp,
	ins_sfsum_pdate timestamp,
	ins_sfsum_pro_amt decimal(15,2),
	ins_sfplan_amt decimal(15,2),
	ins_sfplan_rdate timestamp,
	ins_sfplan_pdate timestamp,
	ins_sfplan_pro_amt decimal(15,2),
	ins_scplan_amt decimal(15,2),
	ins_scplan_rdate timestamp,
	ins_scplan_pdate timestamp,
	ins_scplan_pro_amt decimal(15,2),
	ins_gsbplan_amt decimal(15,2),
	ins_gsbplan_rdate timestamp,
	ins_gsbplan_pdate timestamp,
	ins_gsbplan_pro_amt decimal(15,2),
	insurance_reimburse decimal(15,2),
	insurance_money_waiting decimal(15,2),
	insurance_accumulate_money decimal(15,2),
	insurance_trial_payment decimal(15,2),
	insurance_money_wait_bal decimal(15,2)
) ;
CREATE UNIQUE INDEX sc_lsr_m_contract_x ON sc_lsr_m_contract (insurance_no);
ALTER TABLE sc_lsr_m_contract ALTER COLUMN insurance_no SET NOT NULL;
ALTER TABLE sc_lsr_m_contract ALTER COLUMN apply_date SET NOT NULL;


