CREATE TABLE sc_lon_m_constant (
	coop_registered_no varchar(15) NOT NULL,
	percent_agv_return decimal(15,2),
	maximum_of_contract double precision,
	max_of_all_loan_amount decimal(15,2),
	max_loan_payment decimal(15,2),
	max_guarantee_contract_allow double precision,
	max_keeping_day double precision,
	day_to_full_month double precision,
	day_in_year double precision,
	interest_round_status double precision,
	use_contract_no_format double precision,
	use_year double precision,
	use_branch double precision,
	count_paid_date double precision,
	clear_loan_type double precision,
	payspec_count_period double precision,
	rule_of_aurth double precision,
	contract_no_format varchar(15),
	max_miss_pay double precision,
	count_last_accesdate double precision,
	count_payment_time double precision,
	clearloan_recieptno_status double precision,
	count_return_day double precision,
	drop_emer double precision,
	drop_normal double precision,
	password varchar(10),
	start_keep_flag double precision,
	start_keep_loan timestamp,
	contract_format varchar(20),
	retire_age double precision,
	share_coll_status char(1),
	tran_statement_old_loan char(1),
	branch_code_comp char(1),
	payment_coll_share char(1),
	fee_keep_status char(1),
	insurance_status char(1),
	voidaverageretifpaylessinst double precision,
	coll_fixed_status char(1),
	method_count_age char(1),
	print_rep_emer_status char(1),
	normshare_mix_norm char(1),
	normshare_mix_loantype varchar(6),
	percent_normshare_mix decimal(15,2),
	fund_status char(1),
	month_retire double precision,
	returnint_at_createloan char(1),
	count_month_date char(1),
	count_spec_date char(1),
	count_clear_date char(1),
	interest_retrun_date char(1),
	int_return_intsertmethod char(1),
	int_calc_lastprocess char(1),
	keeping_othermethod char(1),
	clearpending_type char(1),
	specpay_ableeditcalintdate char(1),
	specpay_ableeditintpay char(1),
	contract_format_tr varchar(20),
	bank_no_default varchar(6),
	calint_by_budget char(1),
	emer_old_atm varchar(6),
	credit_pending_nextmonth char(1),
	credit_pending_spp char(1),
	credit_pending_clr char(1),
	print_vourcher_payment char(1),
	clear_depend_history char(1),
	specpay_methodpayment char(1),
	clear_loan_notall char(1),
	notkep_cm_to_loan varchar(6),
	create_loan_no char(1) DEFAULT '0',
	atm_code varchar(15),
	coop_atm_code varchar(15),
	deposit_coll_percent decimal(15,2) DEFAULT 0,
	specpay_calintdatebefor char(1) DEFAULT '0',
	last_close_day timestamp,
	special_minbalance_dep char(1) DEFAULT '0',
	trans_coll_method char(1) DEFAULT '0',
	specpay_ableeditreceiptdate char(1) DEFAULT '0',
	norm_max_loan decimal(15,2) DEFAULT 0,
	buyshare_calpermit char(1) DEFAULT '0',
	loan_auto_buyshare char(1) DEFAULT '0',
	buyshare_difflevel char(1) DEFAULT '0',
	req_add_del_clear char(1) DEFAULT '0',
	share_pending_loanreq char(1) DEFAULT '0',
	lrqmg_type char(1) DEFAULT '0',
	loan_limit_by_share_stock char(1) DEFAULT '0',
	loan_limit_by_share_amount char(1) DEFAULT '0',
	retire_canloan_status char(1) DEFAULT '0',
	retire_canloan_status_m char(1) DEFAULT '0',
	drop_group_loan_m char(1) DEFAULT '0',
	max_of_all_loan_amount_m char(1) DEFAULT '0',
	voucher_name varchar(35),
	edit_loanreq_no char(1) DEFAULT '0',
	decimal_type_pl varchar(4),
	decimal_type_pm varchar(4),
	check_collre char(1) DEFAULT '0',
	check_sign_collre char(1) DEFAULT '0',
	vourcher_payment_screen char(1) DEFAULT '0',
	fund_account_id varchar(8),
	tran_loan_p_round decimal(6,2) DEFAULT 0,
	tran_loan_p_round_type char(1) DEFAULT '0',
	tran_loan_i_round decimal(6,2) DEFAULT 0,
	tran_loan_i_round_type char(1) DEFAULT '0',
	int_arrar_notpaid char(1) DEFAULT '0',
	wait_clear_notreceive char(1) DEFAULT '0',
	clear_loan_othermem char(1) DEFAULT '0',
	change_period_effend char(1) DEFAULT '0',
	salbal_permit_type char(1) DEFAULT '0',
	salbal_notother char(1) DEFAULT '0',
	payment_steprate char(1) DEFAULT '0',
	contract_period_able char(1) DEFAULT '0',
	coll_active_code char(1) DEFAULT '0',
	maximum_loan_amount_m char(1) DEFAULT '0',
	pay_permit_percent decimal(10,6) DEFAULT 0,
	postto_fin_style char(1) DEFAULT '0',
	payclear_count_period char(1) DEFAULT '0',
	loan_monthly_arrear char(1) DEFAULT '0',
	loan_req_clear_x char(1) DEFAULT '0',
	ref_method_slave char(1) DEFAULT '0',
	doc_approve_status char(1) DEFAULT '0',
	loanreq_buy_share_limit decimal(15,2) DEFAULT 0,
	lonreq_show_salary_meminhr char(1) DEFAULT '0',
	start_keep_main timestamp,
	auto_change_atm_account char(1) DEFAULT '0',
	after_keep_freeday numeric(38) DEFAULT 0,
	day_count_method char(1) DEFAULT '0',
	form_addloan_emer varchar(50),
	form_addloan_spec varchar(50),
	type_pay_money_01 varchar(3),
	type_pay_money_02 varchar(3),
	type_pay_money_03 varchar(3),
	slip_paidloan_more varchar(35),
	update_atm_date timestamp,
	paidloan_multi_way char(1),
	sum_loan_max_amount decimal(15,2),
	sum_loan_max_per_salary decimal(6,4)
) ;
COMMENT ON TABLE sc_lon_m_constant IS E'!N????????????????????????N!!MM!';
COMMENT ON COLUMN sc_lon_m_constant.loan_req_clear_x IS E'!N???????????????????????????????N!!MM!';
ALTER TABLE sc_lon_m_constant ADD PRIMARY KEY (coop_registered_no);


