CREATE TABLE sc_lon_req_coll_law_appraise (
	doc_no varchar(15) NOT NULL,
	seq_no double precision NOT NULL DEFAULT 0,
	land_square decimal(15,2) DEFAULT 0.00,
	land_coop decimal(15,2) DEFAULT 0.00,
	land_rate decimal(10,6) DEFAULT 0.80,
	house_square decimal(15,2) DEFAULT 0.00,
	house_coop decimal(15,2) DEFAULT 0.00,
	house_rate decimal(10,6) DEFAULT 0.60,
	company_square decimal(15,2) DEFAULT 0.00,
	land_company decimal(15,2) DEFAULT 0.00,
	house_company decimal(15,2) DEFAULT 0.00,
	insure_amount decimal(15,2),
	forced_sale decimal(15,2) DEFAULT 0,
	market_price decimal(15,2) DEFAULT 0,
	coop_land_square decimal(15,2) DEFAULT 0,
	coop_house_square decimal(15,2) DEFAULT 0,
	cal_company_land decimal(15,2) DEFAULT 0,
	cal_company_house decimal(15,2) DEFAULT 0,
	company_land_rate decimal(15,2) DEFAULT 0,
	company_house_rate decimal(15,2) DEFAULT 0,
	company_depreciate_rate decimal(15,2) DEFAULT 0,
	cal_company_land_rate decimal(15,2) DEFAULT 0,
	cal_company_house_rate decimal(15,2) DEFAULT 0,
	cal_coop_land decimal(15,2) DEFAULT 0,
	cal_coop_house decimal(15,2) DEFAULT 0,
	coop_land_rate decimal(15,2) DEFAULT 0,
	coop_house_rate decimal(15,2) DEFAULT 0,
	coop_depreciate_rate decimal(15,2) DEFAULT 0,
	cal_coop_land_rate decimal(15,2) DEFAULT 0,
	cal_coop_house_rate decimal(15,2) DEFAULT 0,
	appraised_total decimal(15,2) DEFAULT 0,
	appraised_rate_total decimal(15,2) DEFAULT 0,
	cal_coop_land_rate2 decimal(15,2) DEFAULT 0,
	coop_land_rate2 decimal(15,2) DEFAULT 0,
	coop_land_square2 decimal(15,2) DEFAULT 0,
	land_coop2 decimal(15,2) DEFAULT 0,
	cal_coop_land2 decimal(15,2) DEFAULT 0,
	eva_market_wa decimal(15,2) DEFAULT 0,
	eva_market_meter decimal(15,2) DEFAULT 0,
	eva_market_price decimal(15,2) DEFAULT 0,
	appeaise_name varchar(50),
	appeaise_date timestamp,
	membership_no varchar(7)
) ;
ALTER TABLE sc_lon_req_coll_law_appraise ADD PRIMARY KEY (doc_no,seq_no);
ALTER TABLE sc_lon_req_coll_law_appraise ALTER COLUMN doc_no SET NOT NULL;
ALTER TABLE sc_lon_req_coll_law_appraise ALTER COLUMN seq_no SET NOT NULL;


