CREATE TABLE sc_lon_req_coll_law (
	loan_requestment_no char(15),
	seq_no double precision,
	coll_ref varchar(100),
	lem varchar(50),
	nha varchar(50),
	coll_no varchar(50),
	rawang varchar(50),
	nha_sam_roje varchar(50),
	pantee varchar(50),
	tambol varchar(50),
	amper varchar(50),
	jungwat varchar(50),
	rai varchar(50),
	ghan varchar(50),
	tarangwa varchar(50),
	building varchar(100),
	commiter char(7),
	commit_date timestamp,
	entry_id char(20),
	entry_date timestamp,
	rawang2 varchar(50),
	teedin char(50),
	price_per_unit decimal(15,2),
	survey_date timestamp,
	moo_ban varchar(35),
	lak_kilo char(20),
	front_wide decimal(15,2),
	deep decimal(15,2),
	owner_co char(1),
	owner_other varchar(25),
	floor char(5),
	building_no varchar(35),
	building_name varchar(35),
	address_no varchar(25),
	moo char(5),
	soi varchar(25),
	road varchar(30),
	id_card char(13),
	estimate_date timestamp,
	jungwat_exp varchar(30),
	decrease_status char(1),
	amper_exp varchar(50),
	chanod_no varchar(70),
	coll_seq double precision,
	chanod_no1 varchar(70),
	chanod_no2 varchar(70),
	chanod_total double precision,
	copy_status char(1)
) ;


