CREATE TABLE sc_lon_m_loan_card_temp (
	loan_contract_no varchar(15),
	loan_type char(6),
	membership_no varchar(15),
	principal_balance decimal(15,2),
	total_fine decimal(15,2),
	fine_arrear decimal(15,2),
	total_interest decimal(15,2),
	interest_arrear decimal(15,2),
	old_interest_arrear decimal(15,2),
	interest_arrear_year decimal(15,2),
	last_period double precision,
	last_access_date timestamp,
	last_calcint_date timestamp,
	last_process_date timestamp,
	pending_amount decimal(15,2),
	pending_interest decimal(15,2),
	keeping_status char(1),
	year_total_interest decimal(15,2),
	entry_id char(16),
	entry_date timestamp,
	branch_id char(6),
	start_keep_date timestamp,
	share_coll_amount decimal(15,2),
	period_compomise double precision,
	date_compomise timestamp,
	accu_compomise double precision,
	backlist_count double precision,
	drop_payment_status char(1),
	fixed_payment decimal(15,2),
	intarr_payment decimal(15,2),
	fixed_interest_rate decimal(15,6),
	contact_status char(1),
	old_membership_no char(15),
	loan_code char(1),
	interest_last_year decimal(15,2),
	begin_balance decimal(15,2),
	type_request char(1),
	atm_send_date timestamp,
	atm_balance decimal(15,2),
	close_status char(1),
	now_docno_chgpay char(15),
	loan_level char(1),
	drop_average char(1),
	drp_ang char(1),
	int_temp decimal(10,2),
	year_total_interest_temp decimal(15,2),
	drop_average_temp char(1),
	keeping_memno char(15),
	keeping_recno double precision,
	keeping_seqno double precision,
	keeping_month double precision,
	keeping_year double precision,
	pending_month_arr decimal(15,2),
	last_access_time char(23),
	principal_arr_all decimal(15,2),
	principal_arr_year decimal(15,2),
	create_loan_date timestamp,
	month_arr decimal(15,2),
	month_intarr decimal(15,2),
	fixed_time_month double precision,
	fin_status char(1),
	calint_method char(1),
	fund_coll_status char(1),
	bonus_keeping decimal(15,2),
	divide_keeping decimal(15,2),
	average_keeping decimal(15,2),
	bonus_keeping_type char(1),
	divide_keeping_type char(1),
	average_keeping_type char(1),
	loan_code_copy char(1),
	intarr_approx decimal(15,2),
	report_approx char(1),
	invalid_stm double precision,
	active_chgloan_docno char(15),
	bonus_amount decimal(15,2),
	restructure_status char(1),
	temp_last_calcint_date timestamp,
	temp_last_process_date timestamp,
	to_sybase char(1),
	cnv_calint_add char(1),
	loan_32 char(1),
	drop_looping char(1),
	post_2dep char(1),
	transfer_status char(1),
	transfer_amount decimal(15,2),
	transfer_date timestamp,
	drop_aver char(1),
	keep_with_coll char(1),
	temp_compomise integer,
	accu_interest decimal(15,2),
	temp_drop_status char(1),
	temp_bal decimal(15,2),
	temp_last_period integer,
	active_restruc_docno char(15),
	method_interest char(1),
	interest_loan_type char(2),
	ending_fixed_rate decimal(15,2),
	drop_effactive_status char(1),
	drop_effactive_begin timestamp,
	drop_effactive_end timestamp,
	principal_arr_start timestamp,
	account_status char(2),
	account_status_date timestamp,
	ncb_nosend_status char(1),
	ncb_installment_frequency double precision,
	old_accu_interest decimal(15,2)
) ;


