CREATE TABLE sc_law_tad_nenkadee_head (
	prosec_no varchar(15) NOT NULL,
	kadee_dum varchar(15),
	kadee_dang varchar(15),
	sal_name varchar(50),
	kram_type varchar(35),
	principal decimal(15,2) DEFAULT 0,
	interest decimal(15,2) DEFAULT 0,
	interest_arrear decimal(15,2) DEFAULT 0,
	interest_rate decimal(15,2) DEFAULT 0,
	fong_date timestamp,
	layer_name varchar(50),
	tran_name varchar(50),
	jod_name varchar(100),
	date_doc timestamp,
	num_muy_st timestamp,
	num_muy_nd timestamp,
	result_num_muy_st varchar(50),
	result_num_muy_nd varchar(50),
	operate_other varchar(100),
	nut_song timestamp,
	comp_doc_date timestamp,
	remark_st varchar(1000),
	remark_nd varchar(1000),
	kun_sal_fee decimal(15,2) DEFAULT 0,
	num_muy_fee decimal(15,2) DEFAULT 0,
	layer_fee decimal(15,2) DEFAULT 0,
	ruchar_fee decimal(15,2) DEFAULT 0,
	pipak_sa_date timestamp,
	tum_yum_date timestamp,
	talang_kum_pipaksa_date timestamp,
	talang_kum_pipaksa_returndate timestamp,
	nut_rec_talang timestamp,
	talang_doc_returndate timestamp,
	rec_talang_doc_return timestamp,
	out_pag_kup_kadee timestamp,
	num_muy_out_pag_kup timestamp,
	name_officer_kadee timestamp,
	layer_name_jumley varchar(50),
	talang_fee_date timestamp,
	def_yed_zep timestamp,
	pleace_yed varchar(75),
	owner_yumley varchar(75),
	item_yed varchar(250),
	cost_yed decimal(15,2) DEFAULT 0,
	def_yed_zep_time timestamp,
	payement_last_date timestamp,
	kadee_result varchar(1000),
	datetime_doc timestamp,
	lawyer_bung_kub_kadee varchar(40),
	officer_kadee_date timestamp,
	bung_kub_kadee_jungwat varchar(50)
) ;
ALTER TABLE sc_law_tad_nenkadee_head ADD PRIMARY KEY (prosec_no);
ALTER TABLE sc_law_tad_nenkadee_head ALTER COLUMN prosec_no SET NOT NULL;


