CREATE TABLE sc_mem_m_insure_temp (
	insurance_no varchar(15) NOT NULL,
	insurance_type varchar(5),
	membership_no varchar(15),
	insurance_detail varchar(100),
	insurance_approve decimal(15,2),
	insurance_balance decimal(15,2),
	insurance_period decimal(15,2),
	insurance_period_amount decimal(15,2),
	start_keep_date timestamp,
	last_period double precision,
	insurance_arrear decimal(15,2),
	insurance_arrear_old decimal(15,2),
	insurance_arrear_pending decimal(15,2),
	insurance_status varchar(1),
	entry_id varchar(16),
	entry_pc varchar(6),
	entry_date timestamp,
	entry_br char(6),
	cancel_status char(1),
	cancel_id char(16),
	cancel_pc char(6),
	cancel_date timestamp,
	cancel_br char(6),
	keeping_status char(1),
	pending_amount decimal(15,2),
	insurance_cost decimal(15,2),
	latest_insurance_cost decimal(15,2),
	calc_insurance decimal(15,2),
	ref_contract char(50),
	ref_insurance_no char(15),
	begining_of_contract timestamp,
	company_send_status char(1),
	company_send_amount decimal(15,2),
	company_return decimal(15,2),
	company_add decimal(15,2),
	company_date timestamp,
	company_status char(1),
	cost_last_year decimal(15,2),
	keep_year double precision,
	keep_month double precision,
	drop_payment char(1),
	post_to_fin char(1),
	count_krom integer,
	protec_begin timestamp,
	protec_end timestamp,
	calc_insurance_cost decimal(15,2),
	calc_continue char(1),
	prakan_yperiod decimal(15,2),
	insure_year double precision,
	doc_no char(15),
	seq_no double precision,
	company_code char(15),
	insuer_com_1 decimal(15,2),
	insuer_com_2 decimal(15,2),
	insuer_com_3 decimal(15,2),
	prename_code char(6),
	member_name char(50),
	member_surname char(50),
	sex char(1),
	date_of_birth timestamp,
	remark char(250),
	date_of_death timestamp,
	id_card char(13),
	last_up_amount decimal(15,2),
	advan_amount decimal(15,2),
	receive_advance_date timestamp,
	paid_advance_date timestamp,
	ins_loan_amount decimal(15,2),
	ins_loanc_receive_date timestamp,
	ins_loanc_pay_date timestamp,
	fund_amount decimal(15,2),
	ins_loan_receive_date timestamp,
	ins_loan_pay_date timestamp,
	insurance_reimburse decimal(15,2),
	insurance_trial_payment decimal(15,2),
	insurance_money_waiting decimal(15,2),
	insurance_money_wait_bal decimal(15,2),
	insurance_accumulate_money decimal(15,2),
	ins_dep_pro_amt decimal(15,2),
	ins_dep_amt decimal(15,2),
	ins_dep_rdate timestamp,
	ins_sfplan_pro_amt decimal(15,2),
	ins_sfplan_amt decimal(15,2),
	ins_sfplan_rdate timestamp,
	money_insur_status char(1),
	pay_status char(1),
	advan_amount_temp decimal(15,2),
	insurance_cost_temp decimal(15,2),
	receive_advance_date_temp timestamp,
	protec_begin_temp timestamp,
	protec_end_temp timestamp,
	insurance_mobile char(15),
	reason_resign char(2)
) ;
CREATE UNIQUE INDEX sc_mem_m_insure_x ON sc_mem_m_insure_temp (insurance_no);
ALTER TABLE sc_mem_m_insure_temp ALTER COLUMN insurance_no SET NOT NULL;


