CREATE TABLE sc_mem_kep_return_head (
	membership_no char(7),
	year_receive double precision,
	month_receive double precision,
	status char(1),
	payment_date timestamp,
	reason_return varchar(50),
	total_amount decimal(15,2),
	doc_no char(15),
	return_period double precision,
	entry_date timestamp,
	entry_id char(10),
	client_name char(15),
	return_date timestamp,
	total_keep_amount decimal(15,2),
	method_return char(1),
	posting_status char(1),
	branch_id char(2),
	before_post_status char(1),
	seq_no double precision,
	payment_status char(1),
	payment_id char(10),
	payment_client char(15),
	payment_branch char(2),
	payment_amount decimal(15,2),
	payment_receipt_no char(15),
	cancel_id char(10),
	cancel_client char(15),
	cancel_branch char(2)
) ;


