CREATE TABLE sc_mobile_recv_msg (
	operate_time varchar(23) NOT NULL,
	bank_code varchar(6),
	confirm_status char(1) DEFAULT '0',
	method_uri varchar(30),
	membership_no varchar(20) NOT NULL,
	citizen_no varchar(15),
	from_coop varchar(20),
	from_bay varchar(20),
	to_coop varchar(20),
	to_bay varchar(20),
	trans_amount decimal(15,2) DEFAULT 0,
	trans_fee decimal(15,2) DEFAULT 0,
	note varchar(300),
	return_msg varchar(4000),
	response_code varchar(50) DEFAULT '<>',
	response_text varchar(253),
	finance_date timestamp,
	effect_date timestamp,
	effect_datetime timestamp,
	trans_type varchar(2),
	trans_mode varchar(3),
	member_group_no varchar(15),
	from_account_no varchar(15) DEFAULT '<>',
	from_account_balance decimal(15,2) DEFAULT 0,
	from_avaliable_balance decimal(15,2) DEFAULT 0,
	from_outstanding_balance decimal(15,2) DEFAULT 0,
	to_account_no varchar(15) DEFAULT '<>',
	to_account_balance decimal(15,2) DEFAULT 0,
	to_avaliable_balance decimal(15,2) DEFAULT 0,
	to_outstanding_balance decimal(15,2) DEFAULT 0,
	receipt_no varchar(10),
	vourcher_no varchar(15),
	vourcher_no_fee varchar(15),
	fee_type char(1) DEFAULT '0',
	revers_state char(1) DEFAULT '0',
	cancel_id varchar(16),
	diff_retport_status char(1) DEFAULT '0',
	principal_amount decimal(15,2) DEFAULT 0,
	interest_amount decimal(15,2) DEFAULT 0,
	to_bank_code varchar(6),
	from_bank_code varchar(6),
	to_account_name varchar(200),
	from_account_name varchar(200),
	type_desc_from varchar(100),
	type_desc_to varchar(100),
	diff_cgp char(1) DEFAULT '0',
	coop_fee decimal(15,2) DEFAULT 0
) ;
ALTER TABLE sc_mobile_recv_msg ADD PRIMARY KEY (operate_time,membership_no);
ALTER TABLE sc_mobile_recv_msg ALTER COLUMN operate_time SET NOT NULL;
ALTER TABLE sc_mobile_recv_msg ALTER COLUMN membership_no SET NOT NULL;


