CREATE TABLE sc_mem_m_member_cremation (
	membership_no varchar(15) NOT NULL,
	seq_no double precision NOT NULL DEFAULT 0,
	crem_memno varchar(15) NOT NULL,
	crem_type varchar(6) NOT NULL DEFAULT '00',
	crem_number double precision NOT NULL DEFAULT 0,
	crem_remark varchar(200),
	crem_amount decimal(15,2) DEFAULT 0,
	crem_date timestamp,
	cancel_date timestamp,
	entry_id varchar(16),
	entry_date timestamp,
	client_id varchar(50),
	crem_status char(1) DEFAULT '0',
	crem_detail varchar(6),
	remark_resign varchar(200),
	member_status char(1) DEFAULT '0',
	wait_payment char(1) DEFAULT '0',
	entry_branch varchar(6),
	resign_status varchar(6) DEFAULT '0',
	resign_date timestamp,
	remark_reason varchar(6) DEFAULT '00',
	crem_special char(1) DEFAULT '0',
	return_date timestamp,
	return_from varchar(7),
	crem_arrear decimal(15,2) DEFAULT 0,
	year_arrear double precision DEFAULT 0,
	crem_paid varchar(6),
	bank_acc_no varchar(15),
	bank_name varchar(200),
	remark_date varchar(100),
	requestment_no varchar(15),
	keeping_method char(1),
	fee_arrear decimal(15,2),
	keeping_type varchar(3),
	kep_type_ref varchar(15),
	period_of_month decimal(15,2),
	fee_year_arrear decimal(15,2),
	smk_resign_pay decimal(15,2),
	register_round integer,
	last_period numeric(38),
	keep_method varchar(6),
	deposit_account_no varchar(15),
	deposit_status char(1),
	crem_cover_date timestamp,
	crem_resign_date timestamp,
	crem_amount_last decimal(15,2),
	crem_div decimal(15,2),
	crem_unpaid decimal(15,2) DEFAULT 0.00,
	fee_donat decimal(15,2) DEFAULT 0.00,
	bonus_attendance_pay_status char(1) DEFAULT '0',
	bonus_pay_status char(1) DEFAULT '0',
	monthly_pay_status char(1) DEFAULT '0',
	dividend_pay_status char(1) DEFAULT '0',
	self_pay_status char(1) DEFAULT '0',
	crem_round varchar(6) DEFAULT '0'
) ;
ALTER TABLE sc_mem_m_member_cremation ADD PRIMARY KEY (membership_no,seq_no,crem_type,crem_number,crem_memno);
ALTER TABLE sc_mem_m_member_cremation ALTER COLUMN membership_no SET NOT NULL;
ALTER TABLE sc_mem_m_member_cremation ALTER COLUMN seq_no SET NOT NULL;
ALTER TABLE sc_mem_m_member_cremation ALTER COLUMN crem_memno SET NOT NULL;
ALTER TABLE sc_mem_m_member_cremation ALTER COLUMN crem_type SET NOT NULL;
ALTER TABLE sc_mem_m_member_cremation ALTER COLUMN crem_number SET NOT NULL;


