CREATE TABLE sc_mem_m_share_loan_rep (
	member_group_no char(15),
	membership_no char(7),
	seq_no double precision,
	report_line double precision,
	membername varchar(100),
	share_balance decimal(15,2),
	share_period decimal(15,2),
	share_installment decimal(15,2),
	emer_contract char(15),
	emer_balance decimal(15,2),
	emer_period double precision,
	emer_installment decimal(15,2),
	norm_contract char(15),
	norm_balance decimal(15,2),
	norm_period double precision,
	norm_installment decimal(15,2),
	special_contract char(15),
	special_balance decimal(15,2),
	special_period double precision,
	special_installment decimal(15,2),
	salary_amount decimal(15,2),
	collecteral varchar(100),
	startcontractdate timestamp,
	startdateemer timestamp,
	emer_drop_status char(1),
	lemer_date timestamp,
	lnorm_date timestamp,
	lspec_date timestamp,
	norm_drop_status char(1),
	share_drop_status char(1),
	spec_drop_status char(1),
	share_coll_amount decimal(15,2),
	emer_status_loan char(1),
	mem_type char(2),
	share_coll_status char(1),
	emer_type char(2),
	norm_type char(2),
	spec_type char(2),
	share_coll_contract char(1),
	spec_status char(1),
	member_group_now char(6),
	startdatespec timestamp,
	member_status_code char(1),
	contract_04 char(15),
	balance_04 decimal(15,2),
	period_04 integer,
	installment_04 decimal(15,2),
	startdate_04 timestamp,
	ldate_04 timestamp,
	type_04 char(2),
	drop_status_04 char(1),
	status_loan_04 char(1),
	contract_05 char(15),
	balance_05 decimal(15,2),
	period_05 integer,
	installment_05 decimal(15,2),
	startdate_05 timestamp,
	ldate_05 timestamp,
	type_05 char(2),
	drop_status_05 char(1),
	status_loan_05 char(1),
	contract_06 char(15),
	balance_06 decimal(15,2),
	period_06 integer,
	installment_06 decimal(15,2),
	startdate_06 timestamp,
	ldate_06 timestamp,
	type_06 char(2),
	drop_status_06 char(1),
	status_loan_06 char(1)
) ;


