CREATE TABLE sc_mem_m_membership_regis_bank (
	membership_no varchar(7) NOT NULL,
	application_form_no varchar(15) NOT NULL,
	member_group_no varchar(15) NOT NULL,
	prename_code varchar(3),
	member_name varchar(50),
	member_surname varchar(50),
	member_status_code char(1) NOT NULL,
	sex char(1),
	date_of_birth timestamp,
	nationality_code char(2),
	graduate_code char(2),
	father char(50),
	mother char(50),
	marriage_status char(1) NOT NULL,
	spouse_name char(50),
	present_address char(200),
	present_road char(30),
	present_tambol char(50),
	present_district_code char(2),
	present_province_code char(2),
	present_postcode char(10),
	position_code char(2),
	level_code char(2),
	salary_id char(15),
	salary_rate_code decimal(15,2),
	salary_amount decimal(15,2),
	apply_date timestamp,
	approve_date timestamp,
	approve_id char(16),
	resignation_remark char(100),
	resignation_approve_id char(16),
	resignation_approve_date timestamp,
	remark char(200),
	drop_loanemer_status char(1) NOT NULL,
	drop_loanspec_status char(1) NOT NULL,
	drop_loannormal_status char(1) NOT NULL,
	collactelral_status char(1) NOT NULL,
	total_loan_int decimal(15,2),
	emer_loan_int decimal(15,2),
	norm_loan_int decimal(15,2),
	spec_loan_int decimal(15,2),
	id_card char(15),
	deposit_post_status char(1) NOT NULL,
	mem_type char(2),
	other_loan decimal(15,2),
	password char(10),
	working_date timestamp,
	retire_status char(1),
	debtor_code char(3) NOT NULL,
	share_coll_status char(1) NOT NULL,
	adj_payroll char(1) NOT NULL,
	att_loan_permit char(1) NOT NULL,
	drop_divident char(1) NOT NULL,
	drop_average char(1) NOT NULL,
	group_position char(2),
	eng_name char(50),
	app_type char(1),
	other_code char(3),
	shareloan_code char(3),
	other_saving_member char(3),
	card_type char(1),
	deposit_account_id char(20),
	refund_amt decimal(15,2),
	branch_id char(2),
	phone char(100),
	atm_accno char(10),
	bank_accno char(10),
	atm_bank_code char(6),
	branch_bank_code char(6),
	permanent_address char(50),
	permanent_road char(30),
	permanent_tambol char(50),
	permanent_district_code char(2),
	permanent_province_code char(2),
	permanent_post_code char(10),
	occupation_code char(2),
	blood_code char(2),
	return_rep_status char(1),
	return_member_again char(1),
	drop_chgsharemonth_status char(1),
	chg_buyshare_status char(1),
	drop_chgloanmonth_status char(1),
	dead_status char(1),
	drop_loan_status char(1),
	ending_contractdate timestamp,
	employee_status char(1),
	coop_position char(2),
	bank_acc_no char(15),
	bank_code char(6),
	doc_place_status char(2),
	keep_return_date timestamp,
	retire_date timestamp,
	insurance_no char(15),
	drop_all_loan_status char(1),
	method_recieve_dividend char(3),
	dividend_at_resign char(1),
	bank_transfer char(15),
	present_soi char(50),
	present_moo char(10),
	work_part char(50),
	work_telephone char(30),
	work_phone char(30),
	department char(15),
	present_telephone char(20),
	tax_id char(15),
	atm_no char(20),
	atm_accno_dep char(10),
	atm_branch_code char(6),
	atm_bank_branch char(6),
	keep_bank_status char(1),
	total_loan_int_last_year decimal(15,2),
	bank_code_backup char(6),
	position_amount decimal(15,2),
	other_amount decimal(15,2),
	salary_pure_amount decimal(15,2),
	method_rec_resign char(3),
	acc_no_rising char(15),
	mem_password char(15),
	force_keeping char(1) NOT NULL,
	group_advance char(15),
	id_card_exdat timestamp,
	share_sequester char(1) NOT NULL,
	resign_doc_no char(15),
	active_keepmethod_docno char(15),
	active_chgshare_docno char(15),
	active_chgloan_docno char(15),
	resign_code char(2),
	drop_all_keeping char(1) NOT NULL,
	crem_status char(1) NOT NULL,
	lose_send_share char(1) NOT NULL,
	seize_divident char(1) NOT NULL,
	seize_average char(1) NOT NULL,
	yearly_reason char(50),
	membership_no_ref char(7),
	concern_code_ref char(2)
) ;
ALTER TABLE sc_mem_m_membership_regis_bank ALTER COLUMN membership_no SET NOT NULL;
ALTER TABLE sc_mem_m_membership_regis_bank ALTER COLUMN application_form_no SET NOT NULL;
ALTER TABLE sc_mem_m_membership_regis_bank ALTER COLUMN member_group_no SET NOT NULL;
ALTER TABLE sc_mem_m_membership_regis_bank ALTER COLUMN member_status_code SET NOT NULL;
ALTER TABLE sc_mem_m_membership_regis_bank ALTER COLUMN marriage_status SET NOT NULL;
ALTER TABLE sc_mem_m_membership_regis_bank ALTER COLUMN drop_loanemer_status SET NOT NULL;
ALTER TABLE sc_mem_m_membership_regis_bank ALTER COLUMN drop_loanspec_status SET NOT NULL;
ALTER TABLE sc_mem_m_membership_regis_bank ALTER COLUMN drop_loannormal_status SET NOT NULL;
ALTER TABLE sc_mem_m_membership_regis_bank ALTER COLUMN collactelral_status SET NOT NULL;
ALTER TABLE sc_mem_m_membership_regis_bank ALTER COLUMN deposit_post_status SET NOT NULL;
ALTER TABLE sc_mem_m_membership_regis_bank ALTER COLUMN debtor_code SET NOT NULL;
ALTER TABLE sc_mem_m_membership_regis_bank ALTER COLUMN share_coll_status SET NOT NULL;
ALTER TABLE sc_mem_m_membership_regis_bank ALTER COLUMN adj_payroll SET NOT NULL;
ALTER TABLE sc_mem_m_membership_regis_bank ALTER COLUMN att_loan_permit SET NOT NULL;
ALTER TABLE sc_mem_m_membership_regis_bank ALTER COLUMN drop_divident SET NOT NULL;
ALTER TABLE sc_mem_m_membership_regis_bank ALTER COLUMN drop_average SET NOT NULL;
ALTER TABLE sc_mem_m_membership_regis_bank ALTER COLUMN force_keeping SET NOT NULL;
ALTER TABLE sc_mem_m_membership_regis_bank ALTER COLUMN share_sequester SET NOT NULL;
ALTER TABLE sc_mem_m_membership_regis_bank ALTER COLUMN drop_all_keeping SET NOT NULL;
ALTER TABLE sc_mem_m_membership_regis_bank ALTER COLUMN crem_status SET NOT NULL;
ALTER TABLE sc_mem_m_membership_regis_bank ALTER COLUMN lose_send_share SET NOT NULL;
ALTER TABLE sc_mem_m_membership_regis_bank ALTER COLUMN seize_divident SET NOT NULL;
ALTER TABLE sc_mem_m_membership_regis_bank ALTER COLUMN seize_average SET NOT NULL;


