CREATE TABLE sc_mem_m_insure (
	insurance_no varchar(15) NOT NULL DEFAULT '<NEW>',
	insurance_type varchar(5),
	membership_no varchar(15),
	insurance_detail varchar(100),
	insurance_approve decimal(15,2) DEFAULT 0,
	insurance_balance decimal(15,2) DEFAULT 0,
	insurance_period decimal(15,2) DEFAULT 0,
	insurance_period_amount decimal(15,2) DEFAULT 0,
	start_keep_date timestamp,
	last_period double precision DEFAULT 0,
	insurance_arrear decimal(15,2) DEFAULT 0,
	insurance_arrear_old decimal(15,2) DEFAULT 0,
	insurance_arrear_pending decimal(15,2) DEFAULT 0,
	insurance_status char(1) DEFAULT '0',
	entry_id varchar(16),
	entry_pc varchar(6),
	entry_date timestamp,
	entry_br varchar(6),
	cancel_status char(1) DEFAULT '0',
	cancel_id varchar(16),
	cancel_pc varchar(6),
	cancel_date timestamp,
	cancel_br varchar(6),
	keeping_status char(1) DEFAULT '0',
	pending_amount decimal(15,2) DEFAULT 0,
	insurance_cost decimal(15,2) DEFAULT 0,
	latest_insurance_cost decimal(15,2) DEFAULT 0,
	calc_insurance decimal(15,2) DEFAULT 0,
	ref_contract varchar(50),
	ref_insurance_no varchar(15),
	begining_of_contract timestamp,
	company_send_status char(1) DEFAULT '0',
	company_send_amount decimal(15,2) DEFAULT 0,
	company_return decimal(15,2) DEFAULT 0,
	company_add decimal(15,2) DEFAULT 0,
	company_date timestamp,
	company_status char(1) DEFAULT '0',
	cost_last_year decimal(15,2) DEFAULT 0,
	keep_year double precision DEFAULT 0,
	keep_month double precision DEFAULT 0,
	drop_payment char(1) DEFAULT '0',
	post_to_fin char(1) DEFAULT '0',
	count_krom integer,
	protec_begin timestamp,
	protec_end timestamp,
	calc_insurance_cost decimal(15,2) DEFAULT 0,
	calc_continue char(1) DEFAULT '2',
	prakan_yperiod decimal(15,2) DEFAULT 0,
	insure_year double precision DEFAULT 0,
	doc_no varchar(15),
	seq_no double precision,
	company_code varchar(15),
	insuer_com_1 decimal(15,2),
	insuer_com_2 decimal(15,2),
	insuer_com_3 decimal(15,2),
	prename_code varchar(6),
	member_name varchar(50),
	member_surname varchar(50),
	sex char(1),
	date_of_birth timestamp,
	remark varchar(250),
	date_of_death timestamp,
	id_card varchar(13),
	last_up_amount decimal(15,2),
	advan_amount decimal(15,2),
	receive_advance_date timestamp,
	paid_advance_date timestamp,
	ins_loan_amount decimal(15,2),
	ins_loanc_receive_date timestamp,
	ins_loanc_pay_date timestamp,
	fund_amount decimal(15,2),
	ins_loan_receive_date timestamp,
	ins_loan_pay_date timestamp,
	insurance_reimburse decimal(15,2),
	insurance_trial_payment decimal(15,2),
	insurance_money_waiting decimal(15,2),
	insurance_money_wait_bal decimal(15,2),
	insurance_accumulate_money decimal(15,2),
	ins_dep_pro_amt decimal(15,2),
	ins_dep_amt decimal(15,2),
	ins_dep_rdate timestamp,
	ins_sfplan_pro_amt decimal(15,2),
	ins_sfplan_amt decimal(15,2),
	ins_sfplan_rdate timestamp,
	money_insur_status char(1),
	pay_status char(1),
	advan_amount_temp decimal(15,2) DEFAULT 0,
	insurance_cost_temp decimal(15,2) DEFAULT 0,
	receive_advance_date_temp timestamp,
	protec_begin_temp timestamp,
	protec_end_temp timestamp,
	insurance_mobile varchar(15),
	reason_resign varchar(2)
) ;
COMMENT ON COLUMN sc_mem_m_insure.money_insur_status IS E'0 เงินทดรอง 1 เงินรอนำส่ง
';
COMMENT ON COLUMN sc_mem_m_insure.pay_status IS E'0 จ่ายเอง 1 รายเดือน';
ALTER TABLE sc_mem_m_insure ADD PRIMARY KEY (insurance_no);
ALTER TABLE sc_mem_m_insure ALTER COLUMN insurance_no SET NOT NULL;


