CREATE TABLE sc_mem_m_ucf_member_group_old (
	member_group_no char(15) NOT NULL,
	member_group_name char(100),
	member_group_control char(15),
	member_group_type char(6),
	member_group_old char(50),
	member_group_level double precision,
	member_group_major char(6),
	district_code char(2),
	member_group_keeping char(6),
	province_code char(2),
	group_loan char(6),
	present_address char(200),
	present_road char(30),
	present_tambol char(50),
	district_group char(10),
	keeping_group char(2),
	member_group_fin char(6),
	keep_dep char(1),
	branch_id char(2),
	retire_age smallint,
	lost_salary char(1),
	age_limit smallint,
	position_name char(100),
	head_name char(100),
	int_calc_lastprocess char(1),
	member_group_ref char(15),
	group_section char(6),
	district_group_atm char(7),
	keeping_fingroup char(3) NOT NULL,
	pre_group_name char(30),
	bank_acc_no char(15),
	cheque_code char(2),
	ignor_retire_date char(1) NOT NULL,
	control_id smallint,
	bank_code char(6),
	mem_type_default char(2),
	salary_group char(15),
	ingore_dropshr_rule char(1),
	bank_branch char(6),
	member_group_prename char(15),
	poling_station char(15),
	desc_code char(100)
) ;
CREATE UNIQUE INDEX sc_mem_m_ucf_member_group_x ON sc_mem_m_ucf_member_group_old (member_group_no);
ALTER TABLE sc_mem_m_ucf_member_group_old ALTER COLUMN member_group_no SET NOT NULL;
ALTER TABLE sc_mem_m_ucf_member_group_old ALTER COLUMN keeping_fingroup SET NOT NULL;
ALTER TABLE sc_mem_m_ucf_member_group_old ALTER COLUMN ignor_retire_date SET NOT NULL;


