CREATE TABLE sc_mem_membership_preedit_old (
	membership_no char(7) NOT NULL,
	seq_no double precision NOT NULL,
	operate_date timestamp NOT NULL,
	entry_date timestamp NOT NULL,
	entry_user char(10) NOT NULL,
	member_group_no char(6),
	prename_code char(2),
	member_name char(35),
	member_surname char(35),
	member_status_code char(1),
	sex char(1),
	date_of_birth timestamp,
	nationality_code char(2),
	graduate_code char(2),
	father char(40),
	mother char(40),
	marriage_status char(1),
	spouse_name char(40),
	present_address char(100),
	present_road char(30),
	present_tambol char(50),
	present_district_code char(2),
	present_province_code char(2),
	present_postcode char(10),
	position_code char(2),
	level_code char(2),
	salary_id char(15),
	salary_rate_code decimal(15,2),
	salary_amount decimal(15,2),
	apply_date timestamp,
	approve_date timestamp,
	resignation_remark char(50),
	resignation_approve_id char(15),
	resignation_approve_date timestamp,
	drop_loanemer_status char(1),
	drop_loanspec_status char(1),
	drop_loannormal_status char(1),
	collactelral_status char(1),
	total_loan_int decimal(15,2),
	id_card char(15),
	mem_type char(2),
	other_loan decimal(15,2),
	working_date timestamp,
	retire_status char(1),
	debtor_code char(3),
	share_coll_status char(1),
	adj_payroll char(1),
	att_loan_permit char(1),
	drop_divident char(1),
	drop_average char(1),
	group_position char(2),
	eng_name char(50),
	app_type char(1),
	other_code char(3),
	shareloan_code char(3),
	share_stcok decimal(15,2),
	share_amount decimal(15,2),
	blood_code char(2),
	bank_code_backup char(6),
	remark char(200),
	bank_acc_no char(15),
	other_saving_member char(3),
	branch_id char(2),
	doc_place_status char(2),
	insurance_no char(15),
	salary_pure_amount decimal(15,2),
	other_amount decimal(15,2),
	position_amount decimal(15,2),
	salay_pure_amount decimal(15,2),
	keep_bank_status char(1),
	atm_accno char(10),
	method_recieve_dividend char(3),
	deposit_account_id char(20)
) ;
CREATE UNIQUE INDEX sc_mem_membership_preedit_x ON sc_mem_membership_preedit_old (membership_no, seq_no);
ALTER TABLE sc_mem_membership_preedit_old ALTER COLUMN membership_no SET NOT NULL;
ALTER TABLE sc_mem_membership_preedit_old ALTER COLUMN seq_no SET NOT NULL;
ALTER TABLE sc_mem_membership_preedit_old ALTER COLUMN operate_date SET NOT NULL;
ALTER TABLE sc_mem_membership_preedit_old ALTER COLUMN entry_date SET NOT NULL;
ALTER TABLE sc_mem_membership_preedit_old ALTER COLUMN entry_user SET NOT NULL;


