CREATE TABLE sc_ncb_consumer_detail (
	year double precision,
	month double precision,
	loan_contract_no char(15),
	pn_family_name1 varchar(50),
	pn_family_name2 varchar(26),
	pn_first_name varchar(30),
	pn_middle_name varchar(26),
	pn_marital_status char(4),
	pn_date_of_birth timestamp,
	pn_gender char(1),
	pn_title_prefix varchar(15),
	pn_nationality char(2),
	pn_number_of_childen char(2),
	pn_spouse_name varchar(45),
	pn_occupation char(1),
	pn_customer_type char(1),
	id_type char(2),
	id_number varchar(20),
	id_issue_country char(2),
	pa_address1 varchar(45),
	pa_address2 varchar(45),
	pa_address3 varchar(45),
	pa_subdistrict varchar(40),
	pa_district char(2),
	pa_province char(2),
	pa_country varchar(4),
	pa_postal_code varchar(10),
	pa_telephone varchar(20),
	pa_telephone_type char(1),
	pa_address_type char(1),
	pa_residential_status char(1),
	tl_member_code char(10),
	tl_member_name varchar(16),
	tl_accont_number varchar(25),
	tl_account_type char(2),
	tl_ownership char(1),
	tl_currency_code char(3),
	tl_future_use char(1),
	tl_date_account_opened timestamp,
	tl_date_of_last_payment timestamp,
	tl_date_account_close timestamp,
	tl_as_of_date timestamp,
	tl_original_loan_amount decimal(15,2),
	tl_amount_owned decimal(15,2),
	tl_amount_past_due decimal(15,2),
	tl_number_of_days_past_due char(3),
	tl_old_number_code varchar(10),
	tl_old_member_name varchar(16),
	tl_old_account_number varchar(25),
	tl_default_date timestamp,
	tl_installment_frequency char(1),
	tl_installment_amount decimal(15,2),
	tl_install_numberofpayment double precision,
	tl_account_status char(2),
	tl_loan_objective varchar(5),
	tl_collateral1 varchar(3),
	tl_collateral2 varchar(3),
	tl_collateral3 varchar(3),
	tl_date_of_last_restructure timestamp,
	tl_percent_payment char(4),
	tl_type_of_credit_card char(2),
	tl_number_of_co_borrower char(2),
	tl_unit_make varchar(15),
	tl_unit_model varchar(15),
	tl_credit_limit_type_flag char(3),
	create_file_status char(1),
	entry_id varchar(20),
	entry_date timestamp,
	auto_create_status char(1),
	create_file_entry varchar(20),
	create_file_entry_date timestamp,
	create_file_run double precision,
	principal_arr_start_date timestamp,
	past_due_days double precision,
	rm_start_date timestamp,
	principal_arr_all decimal(15,2),
	interest_arr_all decimal(15,2),
	interest_arr_all_adj decimal(15,2),
	pricipal_bal decimal(15,2)
) ;


