CREATE TABLE sc_ncb_commercial_detail (
	year double precision,
	month double precision,
	loan_contract_no char(15),
	membership_no char(7),
	pf_record_id double precision,
	customer_type_2 char(1),
	registration_type_3 double precision,
	company_thai_name_7 varchar(150),
	registration_date timestamp,
	id_type double precision,
	id_number varchar(20),
	ad_address_type double precision,
	address_1 varchar(100),
	address_2 varchar(100),
	sub_distinct varchar(50),
	district char(2),
	province_code char(2),
	post_code double precision,
	cr_banch_code char(4),
	account_number varchar(15),
	purpose_of_loan_1 double precision,
	date_account_opened timestamp,
	date_maturity timestamp,
	date_account_close timestamp,
	payment_terms double precision,
	credit_type double precision,
	initial_amount_of_loan decimal(15,2),
	number_of_installments double precision,
	payment_amount decimal(15,2),
	date_of_last_payment timestamp,
	account_status char(2),
	default_date timestamp,
	cr_past_due_days double precision,
	past_due_amount decimal(15,2),
	outstanding_amount decimal(15,2),
	ownership_indicator char(1),
	process_date timestamp,
	create_file_status char(1),
	entry_id varchar(20),
	entry_date timestamp,
	auto_create_status char(1),
	create_file_run double precision,
	create_file_entry varchar(20),
	create_file_entry_date timestamp,
	principal_arr_start_date timestamp,
	past_due_days double precision,
	rm_start_date timestamp,
	principal_arr_all decimal(15,2),
	interest_arr_all decimal(15,2),
	interest_arr_all_adj decimal(15,2),
	pricipal_bal decimal(15,2)
) ;


