CREATE TABLE sc_rep_mem_share_loan_bal (
	client_id char(3) NOT NULL,
	seq_no double precision NOT NULL DEFAULT 0,
	membership_no varchar(15),
	member_group_no varchar(15),
	share_balance decimal(15,2) DEFAULT 0,
	share_period double precision DEFAULT 0,
	share_installment decimal(15,2) DEFAULT 0,
	emer_contract varchar(15),
	emer_loantype varchar(6) DEFAULT '00',
	emer_balance decimal(15,2) DEFAULT 0,
	emer_period double precision DEFAULT 0,
	emer_installment decimal(15,2) DEFAULT 0,
	norm_contract varchar(15),
	norm_loantype varchar(6) DEFAULT '00',
	norm_balance decimal(15,2) DEFAULT 0,
	norm_period double precision DEFAULT 0,
	norm_installment decimal(15,2) DEFAULT 0,
	spec_contract varchar(15),
	spec_loantype varchar(6) DEFAULT '00',
	spec_balance decimal(15,2) DEFAULT 0,
	spec_period double precision DEFAULT 0,
	spec_installment decimal(15,2) DEFAULT 0,
	salary_amount decimal(15,2) DEFAULT 0,
	emer_intarr decimal(15,2) DEFAULT 0,
	norm_intarr decimal(15,2) DEFAULT 0,
	spec_intarr decimal(15,2) DEFAULT 0,
	balance_date timestamp,
	intarr_date timestamp,
	emer_paycode varchar(6) DEFAULT '00',
	emer_shot decimal(15,2) DEFAULT 0,
	emer_long decimal(15,2) DEFAULT 0,
	norm_paycode varchar(6) DEFAULT '00',
	norm_shot decimal(15,2) DEFAULT 0,
	norm_long decimal(15,2) DEFAULT 0,
	spec_paycode varchar(6) DEFAULT '00',
	spec_shot decimal(15,2) DEFAULT 0,
	spec_long decimal(15,2) DEFAULT 0,
	member_status_code char(1) DEFAULT '0',
	member_name varchar(100),
	emer_loan_code char(1) DEFAULT '0',
	norm_loan_code char(1) DEFAULT '0',
	spec_loan_code char(1) DEFAULT '0',
	emer_last_date timestamp,
	norm_last_date timestamp,
	spec_last_date timestamp,
	emer_last_calcint_date timestamp,
	norm_last_calcint_date timestamp,
	spec_last_calcint_date timestamp,
	mem_type varchar(6),
	fund_amount decimal(15,2) DEFAULT 0,
	emer_intarr_card decimal(15,2) DEFAULT 0,
	emer_last_cal timestamp,
	entry_id varchar(16),
	entry_date timestamp,
	other_code varchar(6),
	emer_prin_arr decimal(15,2) DEFAULT 0.00,
	norm_prin_arr decimal(15,2) DEFAULT 0.00,
	spec_prin_arr decimal(15,2) DEFAULT 0.00,
	emer_contact_status char(1),
	norm_contact_status char(1),
	spec_contact_status char(1),
	emer_drop_payment_status char(1)
) ;
CREATE INDEX idx_loan_bal ON sc_rep_mem_share_loan_bal (membership_no, emer_loantype, emer_balance, balance_date);
CREATE INDEX idx_other_code ON sc_rep_mem_share_loan_bal (other_code);
ALTER TABLE sc_rep_mem_share_loan_bal ADD PRIMARY KEY (client_id,seq_no);
ALTER TABLE sc_rep_mem_share_loan_bal ALTER COLUMN client_id SET NOT NULL;
ALTER TABLE sc_rep_mem_share_loan_bal ALTER COLUMN seq_no SET NOT NULL;


