CREATE TABLE sc_rep_receipt (
	client_id varchar(3) NOT NULL,
	seq_no double precision NOT NULL DEFAULT 0,
	receipt_no varchar(15),
	membership_no varchar(15),
	member_group_no varchar(15),
	receipt_date timestamp,
	receipt_status char(1),
	payment_type varchar(6),
	share_period double precision DEFAULT 0,
	share_amount decimal(16,2) DEFAULT 0,
	share_stock decimal(16,2) DEFAULT 0,
	emer_group varchar(5),
	emer_type varchar(5),
	emer_con_no varchar(15),
	emer_period double precision DEFAULT 0,
	emer_principal decimal(16,2) DEFAULT 0,
	emer_interest decimal(16,2) DEFAULT 0,
	emer_balance decimal(16,2) DEFAULT 0,
	norm_group varchar(5),
	norm_type varchar(5),
	norm_con_no varchar(15),
	norm_period double precision DEFAULT 0,
	norm_principal decimal(16,2) DEFAULT 0,
	norm_interest decimal(16,2) DEFAULT 0,
	norm_balance decimal(16,2) DEFAULT 0,
	spec_group varchar(5),
	spec_type varchar(5),
	spec_con_no varchar(15),
	spec_period double precision DEFAULT 0,
	spec_principal decimal(16,2) DEFAULT 0,
	spec_interest decimal(16,2) DEFAULT 0,
	spec_balance decimal(16,2) DEFAULT 0,
	etc_desc varchar(100),
	etc_amount decimal(16,2) DEFAULT 0,
	remark varchar(200),
	memgroup char(1),
	contract_status varchar(6),
	emer_loan_status char(1),
	norm_loan_status char(1),
	spec_loan_status char(1),
	coll_status char(1),
	insurance_amount decimal(15,2) DEFAULT 0,
	money_return decimal(15,2) DEFAULT 0,
	entry_id varchar(16),
	old_receipt_date timestamp,
	journal_date timestamp,
	money_income decimal(15,2) DEFAULT 0,
	total_amount decimal(15,2) DEFAULT 0,
	crem_amount double precision DEFAULT 0
) ;
COMMENT ON COLUMN sc_rep_receipt.receipt_status IS E'!V0-????,2-????????V!';
ALTER TABLE sc_rep_receipt ADD PRIMARY KEY (client_id,seq_no);


