CREATE TABLE sc_sch_child_members (
	child_member_no varchar(15),
	application_form_no varchar(15) NOT NULL,
	school_year decimal(15,2),
	scholarship_type varchar(6),
	seat_no varchar(15),
	membership_no varchar(15),
	member_group_no varchar(6),
	child_prename_code varchar(3),
	child_name varchar(50),
	child_surname varchar(50),
	child_birthday timestamp,
	child_age decimal(15,2),
	child_number decimal(15,2),
	graduate_type varchar(6),
	child_class_code varchar(6),
	child_school varchar(100),
	child_district_code varchar(6),
	child_province_code varchar(6),
	entry_id varchar(15),
	entry_date timestamp,
	branch_entry_id varchar(6),
	status char(1),
	approve_id varchar(15),
	approve_date timestamp,
	branch_approve_id varchar(6),
	totals_marks decimal(15,2),
	number_marks decimal(15,2),
	totals_marks_id varchar(15),
	totals_marks_date timestamp,
	totals_marks_branch_id varchar(6),
	child_int decimal(15,2),
	int_marks decimal(15,2)
) ;
ALTER TABLE sc_sch_child_members ADD PRIMARY KEY (application_form_no);


