CREATE TABLE sc_sch_mem_regis (
	requestment_no varchar(15) NOT NULL,
	receive_year double precision DEFAULT 0,
	membership_no varchar(15),
	operate_date timestamp,
	prename_code varchar(3) DEFAULT '00',
	receiver_name varchar(50),
	receiver_surname varchar(50),
	edu_locate varchar(100),
	receiver_type varchar(6) DEFAULT '00',
	sch_type varchar(6) DEFAULT '00',
	sch_receive decimal(15,2) DEFAULT 0,
	payment_type_code varchar(3),
	approve_date timestamp,
	approve_status char(1) DEFAULT '0',
	approve_id varchar(16),
	entry_id varchar(16),
	entry_date timestamp,
	entry_branch varchar(6),
	entry_clientid varchar(30),
	cancel_id varchar(16),
	cancel_date timestamp,
	cancel_branch varchar(6),
	average_grade decimal(15,2) DEFAULT 0,
	percent decimal(15,4) DEFAULT 0,
	cancel_status char(1) DEFAULT '0',
	school_code varchar(6),
	id_card varchar(15),
	sch_age double precision DEFAULT 0,
	school_dist_code varchar(6) DEFAULT '00',
	school_prov_code varchar(6) DEFAULT '00',
	school_class varchar(6) DEFAULT '00',
	remark_desc varchar(150),
	date_of_birth timestamp,
	bank_accno varchar(70),
	deposit_accno varchar(70),
	pure_income decimal(15,2) DEFAULT 0,
	cancel_approve_id varchar(16),
	cancel_approve_date timestamp,
	cancel_approve_br varchar(6),
	cancel_approve_dese varchar(100),
	approve_branch varchar(6),
	payment_remark_desc varchar(100),
	post_date timestamp,
	post_status char(1) DEFAULT '0',
	post_id varchar(16),
	tran_bank_status char(1) DEFAULT '0',
	bank_code varchar(6),
	request_amount decimal(15,2) DEFAULT 0,
	real_receive decimal(15,2) DEFAULT 0,
	bank_branch varchar(5),
	paid_date timestamp,
	school_name varchar(100),
	bank_acc_name varchar(100),
	average_grade_old decimal(15,2) DEFAULT 0,
	trans_bank_status char(1) DEFAULT '0'
) ;
ALTER TABLE sc_sch_mem_regis ADD PRIMARY KEY (requestment_no);
ALTER TABLE sc_sch_mem_regis ALTER COLUMN requestment_no SET NOT NULL;


