CREATE TABLE sc_sch_application_form (
	application_form_no varchar(15) NOT NULL,
	marriage_status_code char(1),
	scholarship_type varchar(6),
	apply_date timestamp,
	school_year decimal(15,2),
	seat_no varchar(15),
	member_group_no varchar(6),
	parent_status char(1),
	membership_no varchar(15),
	mem_prename_code varchar(6),
	mem_name varchar(50),
	mem_surname varchar(50),
	mem_age decimal(15,2),
	position_code varchar(3),
	district_code varchar(6),
	province_code varchar(6),
	mem_salary decimal(15,2),
	spouse_status_member char(1),
	spouse_prename_code varchar(3),
	spouse_occupation_code varchar(6),
	spouse_group_no varchar(6),
	spouse_member_no varchar(15),
	spouse_name varchar(50),
	spouse_surname varchar(50),
	spouse_age decimal(15,2),
	spouse_position_name varchar(50),
	spouse_salary decimal(15,2),
	child_amount decimal(15,2),
	child_study decimal(15,2),
	adopter_amount decimal(15,2),
	adopter_study decimal(15,2),
	child_status char(1),
	child_number decimal(15,2),
	child_prename_code varchar(3),
	child_name varchar(50),
	child_surname varchar(50),
	child_birthday timestamp,
	child_age decimal(15,2),
	child_class_code varchar(6),
	child_school varchar(100),
	child_district_code varchar(6),
	child_province_code varchar(6),
	entry_id varchar(15),
	entry_date timestamp,
	branch_entry_id varchar(6),
	approve_id varchar(15),
	approve_date timestamp,
	branch_approve_id varchar(6),
	status_approve char(1),
	remark varchar(100),
	number_marks decimal(15,2),
	totals_marks decimal(15,2),
	totals_marks_id varchar(15),
	totals_marks_date timestamp,
	totals_marks_branch_id varchar(6),
	grade decimal(4,2),
	paid_entry_id char(15),
	paid_entry_date timestamp,
	child_idcard char(13),
	moey_type_id char(3),
	paid_date timestamp,
	bank_code char(6),
	bank_branch char(5),
	bank_acc_no char(15),
	money_amount decimal(15,2),
	child_int decimal(15,2),
	int_marks decimal(15,2)
) ;
CREATE INDEX idx_sch_appform_app_date ON sc_sch_application_form (apply_date);
CREATE INDEX idx_sch_appform_group_no ON sc_sch_application_form (member_group_no);
CREATE INDEX idx_sch_appform_memno ON sc_sch_application_form (membership_no);
CREATE INDEX idx_sch_appform_parent_status ON sc_sch_application_form (parent_status);
CREATE INDEX idx_sch_appform_school_year ON sc_sch_application_form (school_year);
CREATE INDEX idx_sch_appform_status_code ON sc_sch_application_form (marriage_status_code);
ALTER TABLE sc_sch_application_form ADD PRIMARY KEY (application_form_no);


