CREATE TABLE sc_tge_send_rec_det (
	last_date timestamp NOT NULL,
	membership_no varchar(15) NOT NULL,
	receipt_date timestamp NOT NULL,
	member_group_no varchar(15) NOT NULL,
	det_type char(1) NOT NULL DEFAULT 'D',
	det_a varchar(200),
	det_b varchar(200),
	det_c varchar(200),
	det_d varchar(200),
	det_e varchar(200),
	det_f varchar(200),
	det_g varchar(200),
	det_h varchar(200),
	det_i varchar(200),
	det_j varchar(200),
	det_k varchar(200),
	det_l varchar(200),
	det_m varchar(200),
	det_n varchar(200),
	det_o varchar(200),
	det_p varchar(200),
	det_q varchar(200),
	det_r varchar(200),
	det_s varchar(200),
	det_t varchar(200),
	det_u varchar(200),
	det_v varchar(200),
	det_w varchar(200),
	det_x varchar(200),
	det_y varchar(200),
	det_z varchar(200),
	det_aa varchar(200),
	det_ab varchar(200),
	det_ac varchar(200),
	det_ad varchar(200),
	det_ae varchar(200),
	det_af varchar(200),
	det_ag varchar(200),
	det_ah varchar(200),
	det_ai varchar(200),
	det_aj varchar(200),
	det_ak varchar(200),
	det_al varchar(200),
	det_am varchar(200),
	det_an varchar(200),
	det_ao varchar(200),
	det_ap varchar(200),
	det_aq varchar(200),
	det_ar varchar(200),
	det_as varchar(200),
	det_at varchar(200),
	det_au varchar(200),
	det_av varchar(200),
	det_aw varchar(200),
	det_ax varchar(200),
	det_ay varchar(200),
	det_az varchar(200),
	det_ba varchar(200)
) ;
ALTER TABLE sc_tge_send_rec_det ADD PRIMARY KEY (last_date,membership_no,receipt_date,det_type);
ALTER TABLE sc_tge_send_rec_det ALTER COLUMN last_date SET NOT NULL;
ALTER TABLE sc_tge_send_rec_det ALTER COLUMN membership_no SET NOT NULL;
ALTER TABLE sc_tge_send_rec_det ALTER COLUMN receipt_date SET NOT NULL;
ALTER TABLE sc_tge_send_rec_det ALTER COLUMN member_group_no SET NOT NULL;
ALTER TABLE sc_tge_send_rec_det ALTER COLUMN det_type SET NOT NULL;


