CREATE TABLE sc_wef_req (
	requestment_no varchar(15) NOT NULL,
	wef_type varchar(6) NOT NULL,
	membership_no varchar(15) NOT NULL,
	operate_date timestamp NOT NULL,
	member_group_no varchar(15),
	entry_id varchar(16),
	entry_time timestamp,
	entry_pc varchar(3),
	entry_br varchar(6),
	cancel_status char(1) DEFAULT '0',
	cancel_id varchar(16),
	cancel_time timestamp,
	cancel_pc varchar(3),
	cancel_br varchar(6),
	approve_status char(1) DEFAULT '0',
	approve_date timestamp,
	approve_id varchar(16),
	approve_time timestamp,
	approve_pc varchar(3),
	approve_br varchar(6),
	remark varchar(100),
	total_receive decimal(15,2) DEFAULT 0,
	money_type varchar(6),
	bank_id varchar(6),
	bank_br varchar(6),
	bank_acc_no varchar(15),
	bank_fin varchar(6),
	paid_status char(1) DEFAULT '0',
	paid_date timestamp,
	bank_acc_name varchar(100),
	fin_status char(1) DEFAULT '0',
	vourcher_no varchar(30),
	bf_age_date timestamp,
	bf_count_all numeric(38) DEFAULT 0,
	paid_amount_all decimal(15,2) DEFAULT 0,
	last_paid_date timestamp,
	rec_doc_date timestamp,
	paid_amount_max_in_year double precision DEFAULT 0,
	wait_payment_status char(1) DEFAULT '0',
	payment_date timestamp,
	present_account_year numeric(38) DEFAULT 0,
	account_year numeric(38) DEFAULT 0,
	payment_id char(16),
	payment_time timestamp,
	loan_balance_all decimal(15,2) DEFAULT 0,
	share_stock decimal(15,2) DEFAULT 0,
	permit_max_amount decimal(15,2) DEFAULT 0,
	payment_entry_date timestamp,
	age_txt_calc varchar(50),
	trans_date timestamp,
	ref_wef_no varchar(15),
	money_type_id varchar(6)
) ;
ALTER TABLE sc_wef_req ADD PRIMARY KEY (requestment_no);
ALTER TABLE sc_wef_req ALTER COLUMN requestment_no SET NOT NULL;
ALTER TABLE sc_wef_req ALTER COLUMN wef_type SET NOT NULL;
ALTER TABLE sc_wef_req ALTER COLUMN membership_no SET NOT NULL;
ALTER TABLE sc_wef_req ALTER COLUMN operate_date SET NOT NULL;


