-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION execute_immedtate (as_file text) RETURNS varchar AS $body$
DECLARE

  ls_rerurn varchar(4000) := '0';

BEGIN

  EXECUTE as_file;

  return '1';
exception when others then CALL spa_dberror('execute_immedtate');return '-1';
end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION execute_immedtate (as_file text) FROM PUBLIC;

