-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION f_get_ins_case ( as_memno text ) RETURNS varchar AS $body$
DECLARE

    ldt_date timestamp(0);
    li_year integer;
    ls_code char(1);

BEGIN


    select left(pka_lon_reqsrv.fp_calc_agetext_m_live( as_memno  ),2) into STRICT li_year

;

--    li_year :=  Extract(Year from ldt_date ) ;
    if 15 < li_year and li_year <= 65 then
        ls_code := '1';
    elsif 65 < li_year and li_year <= 70 then
        ls_code := '2';
    else
        ls_code  := '3';
    end if;

return ls_code;

END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION f_get_ins_case ( as_memno text ) FROM PUBLIC;

