-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION f_get_ret ( as_memno text , as_code char , as_keeping_fingroup char ) RETURNS bigint AS $body$
DECLARE

 ldc_money_return bigint;

BEGIN

    if as_code = '1' then
        select 	coalesce( sum( sc_fin_money_return.money_return ) , 0 )  into STRICT ldc_money_return
        from  	sc_fin_money_return 
        ,		    sc_mem_m_ucf_member_group
        ,	      sc_fin_ucf_keeping_group
        ,          sc_kep_t_monthly_receive
        where sc_fin_money_return.operate_date = to_date('26/08/2025','dd/mm/yyyy')
        and sc_kep_t_monthly_receive.receive_year = 2025
        and sc_kep_t_monthly_receive.receive_month = 8 
        and		  sc_fin_money_return.return_method = 'KEP' 
        and	    sc_mem_m_ucf_member_group.member_group_no = sc_kep_t_monthly_receive.member_group_no
        and    sc_mem_m_ucf_member_group.keeping_fingroup = as_keeping_fingroup
        and     sc_fin_money_return.cancel_status = '0'  
;

    else 

        select sum(kep_method_amount) into STRICT ldc_money_return
        from sc_kep_t_monthly_receive
        ,sc_mem_m_ucf_member_group
        where receive_year = 2025
        and receive_month = 8
        and sc_mem_m_ucf_member_group.member_group_no = sc_kep_t_monthly_receive.member_group_no
        and sc_mem_m_ucf_member_group.keeping_fingroup = as_keeping_fingroup
;

    end if;

    
  RETURN ldc_money_return;

END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION f_get_ret ( as_memno text , as_code char , as_keeping_fingroup char ) FROM PUBLIC;

