-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION f_get_kep_contract_status ( ai_year integer,ai_month integer,as_loan_contract text ) RETURNS varchar AS $body$
DECLARE


 ls_contact_status  sc_lon_m_loan_card.loan_code%type;


BEGIN

   select loan_status into STRICT ls_contact_status
    from sc_kep_t_monthly_receive_det
    where receive_month = ai_month
    and receive_year = ai_year
    and receive_description = as_loan_contract
--    where loan_contract_no = as_loan_contract
;



  RETURN ls_contact_status;

END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION f_get_kep_contract_status ( ai_year integer,ai_month integer,as_loan_contract text ) FROM PUBLIC;

