-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION f_lon_get_intrate ( as_loan_type text , adtm_date timestamp(0) ) RETURNS bigint AS $body$
DECLARE

  ldc_int_rate  bigint;
  ldtm_date timestamp(0);

BEGIN
    begin							
      select 	loan_interest_rate
      into STRICT 		ldc_int_rate
      from 		sc_lon_m_int_step_rate
      Where  	loan_type = as_loan_type  
      and   	effective_date =(   SELECT max( effective_date ) 
                                    from 		sc_lon_m_int_step_rate 
                                    where 		effective_date  <= adtm_date
                                    and   		loan_type =  as_loan_type  );
	exception when others then return 0;
    end;

    return ldc_int_rate;

exception when others then return 0;
end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION f_lon_get_intrate ( as_loan_type text , adtm_date timestamp(0) ) FROM PUBLIC;

