-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fp_calc_agetextday (adt_dateFr timestamp(0), adt_dateTo timestamp(0),as_fyear text,as_mformat text,as_fDay text) RETURNS varchar AS $body$
DECLARE

  li_year integer := 0; --Default
  li_month integer := 0;
  li_day integer := 0;

  ldt_dateFrCur timestamp(0);
  ldt_dateTo timestamp(0);
  ls_agetext varchar(100);

BEGIN
  --Set Default
  ldt_dateFrCur := adt_dateFr;
  ldt_dateTo := adt_dateTo;

  loop
    --นับปี
    ldt_dateFrCur := pka_srv_datetime.fp_relativemonth(ldt_dateFrCur,12);--เพิ่มทีละปี
    if ldt_dateFrCur <= ldt_dateTo then
      li_year := li_year + 1;
    else
      ldt_dateFrCur := pka_srv_datetime.fp_relativemonth(ldt_dateFrCur,-12);
      exit;
    end if;
  end loop;

  loop
     --นับเดือน
    ldt_dateFrCur := pka_srv_datetime.fp_relativemonth(ldt_dateFrCur,1);--เพิ่มทีละเดือน
    if ldt_dateFrCur <= ldt_dateTo then --Check month ว่าถึงเดือนหรือไม่
        li_month := li_month + 1;
    else
      ldt_dateFrCur := pka_srv_datetime.fp_relativemonth(ldt_dateFrCur,-1);--ลดเดือนไม่ถึงเดือน
      exit;
    end if;
  end loop;

  if to_char(ldt_dateFrCur,'dd/mm') = '29/02' and to_char(adt_dateFr,'dd/mm') = '28/02' then  --เฉพาะปีที่มี 366 วันเท่านั้นเพราะ
    li_day := abs(ldt_dateTo - ldt_dateFrCur) + 1;
  else
    li_day := abs(ldt_dateTo - ldt_dateFrCur);
  end if;

  if li_year <> 0 then
    ls_agetext  := ls_agetext||replace(as_fyear,'Y',li_year);
  end if;

  if li_month <> 0 then
    ls_agetext  := ls_agetext||replace(as_mformat,'M',li_month);
  end if;

  if li_day <> 0 then
    ls_agetext  := ls_agetext||replace(as_fDay,'D',li_day);
  end if;

  if coalesce(ls_agetext::text, '') = '' or length(trim(both ls_agetext)) = 0 then
    ls_agetext  := '<>'; -- เมื่อการคำนวณไม่ได้ข้อมูลใดๆ จะ return <>
  else
    if ldt_dateTo < ldt_dateFrCur then
      ls_agetext  := '- '||trim(both ls_agetext);
    end if;
  end if;

  return ls_agetext;
exception when others then CALL spa_dberror('fp_calc_ageTextDay');return null;
end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fp_calc_agetextday (adt_dateFr timestamp(0), adt_dateTo timestamp(0),as_fyear text,as_mformat text,as_fDay text) FROM PUBLIC;

