-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fp_get_group_control (as_group_no char) RETURNS varchar AS $body$
DECLARE

ls_group_ctrl sc_mem_m_ucf_member_group.member_group_control%type;

BEGIN
  select member_group_control
  into STRICT ls_group_ctrl
  from sc_mem_m_ucf_member_group
  where member_group_no = as_group_no;
  return ls_group_ctrl;
END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fp_get_group_control (as_group_no char) FROM PUBLIC;

