-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fp_get_coll_memno (as_memcoll char , as_memlon char ) RETURNS varchar AS $body$
DECLARE


  type tabrowi_coll is table of sc_lon_m_contract_coll%rowtype index by integer;ltabrowi_coll tabrowi_coll;
cur_coll_mem CURSOR FOR
    SELECT  sc_lon_m_contract_coll.loan_contract_no
    from sc_lon_m_contract_coll,
    sc_lon_m_contract,
    sc_lon_m_loan_card  ,
    sc_mem_m_share_mem	,
    sc_lon_m_coll_rule
    where ( sc_lon_m_contract.loan_contract_no = sc_lon_m_contract_coll.loan_contract_no )
    and ( sc_lon_m_loan_card.loan_contract_no = sc_lon_m_contract.loan_contract_no )
    and ( sc_lon_m_loan_card.loan_type = sc_lon_m_coll_rule.loan_type )
    and ( sc_mem_m_share_mem.membership_no  = sc_lon_m_loan_card.membership_no)
    and ( sc_lon_m_contract_coll.ref_own_no = as_memcoll )
    and sc_lon_m_loan_card.membership_no = as_memlon
    and ( sc_lon_m_contract_coll.collateral_type_code = '01' )
    and  	( ( sc_lon_m_loan_card.principal_balance > 0 )or ( sc_lon_m_contract.atm_status = '1' and sc_lon_m_loan_card.close_status = '0' ))
    and ( sc_lon_m_contract_coll.status = '0' );
  type tabrow_mem is table of cur_coll_mem%rowtype index by integer;ltabrow_mem tabrow_mem;
  li_count  integer;
  ls_collateral  varchar(4000);
BEGIN

  open cur_coll_mem;fetch cur_coll_mem bulk collect into ltabrow_mem;close cur_coll_mem;
  li_count  := ltabrow_mem.Count;
  for i in 1 .. li_count loop
    if length(trim(both ls_collateral)) > 0  then
      ls_collateral := ls_collateral||' , ';
    end if;
    ls_collateral :=  ls_collateral||trim(both ltabrow_mem[i].loan_contract_no);
  end  loop;
  return trim(both ls_collateral);

END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fp_get_coll_memno (as_memcoll char , as_memlon char ) FROM PUBLIC;

