-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fp_get_countrow (as_table text) RETURNS bigint AS $body$
DECLARE

--cursor cur_table is select table_name from  user_tables ;
--type tab_table is table of cur_table%rowtype index by pls_integer ;ltab_table tab_table;
 li_count integer;
 ls_table_name varchar(100);
 ls_sql varchar(300);


BEGIN
/*
    select   count(1)
    into    li_count
    from    user_tables
    where   table_name = (as_table);*/
   -- ls_sql := 'select count(1) from ' || trim(as_table);
    --execute immediate ls_sql ;   into li_count ;
    EXECUTE 'select count(1) from '||as_table into STRICT li_count;

return trim(both li_count);
exception when others then CALL spa_dberror('fp_get_countrow');
END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fp_get_countrow (as_table text) FROM PUBLIC;

