-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpa_tel_remark_from_reqno (as_conno char) RETURNS varchar AS $body$
DECLARE

  ls_return varchar(100);

BEGIN

  select	sc_lon_m_loan_request.remark into STRICT ls_return
  from		sc_lon_m_loan_request
      ,	  sc_lon_m_contract
  where (sc_lon_m_loan_request.loan_requestment_no = sc_lon_m_contract.loan_requestment_no)
  and (sc_lon_m_contract.loan_contract_no = as_conno);
  return ls_return;
exception when others then return '';

--exception when others then spa_dberror('fpa_tel_remark_from_reqno');
end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpa_tel_remark_from_reqno (as_conno char) FROM PUBLIC;

