-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpa_tel_rsg_loan_bal (as_docno char) RETURNS bigint AS $body$
DECLARE

ldc_bal bigint;

BEGIN
  select  sum(coalesce(principal_balance,0) + coalesce(interest,0) + coalesce(interest_arrear,0))   into STRICT ldc_bal
  from    sc_mem_m_resign_loan
  where ( sc_mem_m_resign_loan.resign_doc_no = as_docno );

  return coalesce(ldc_bal,0);

  exception when others then CALL spa_dberror('FPA_TEL_RSG_LOAN_BAL');
END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpa_tel_rsg_loan_bal (as_docno char) FROM PUBLIC;

