-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpa_kep_paid_by_mem ( as_memno text ) RETURNS bigint AS $body$
DECLARE

ldc_paid_by_mem  bigint;

BEGIN
    select  coalesce( sum( kep_amount - kep_limit ), 0 )  into STRICT ldc_paid_by_mem
    from sc_kep_t_monthly_receive
    where 1=1
    and  receipt_date = ( SELECT max( receipt_date )
                  from sc_kep_t_monthly_receive
                  where  membership_no = as_memno )
    and membership_no = as_memno;

  return(ldc_paid_by_mem);
exception when others then CALL spa_dberror('FPA_KEP_PAID_BY_MEM');
END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpa_kep_paid_by_mem ( as_memno text ) FROM PUBLIC;

