-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpa_cnv_numberic_to_thai (as_number_txt text) RETURNS varchar AS $body$
DECLARE

    li_count integer;
    ls_char char;
    ls_number_txt_new varchar(1000) := '';
    li_number_no integer;
BEGIN

    li_count := len(trim(both as_number_txt));
    for i in 1..li_count loop
        ls_char := substr(as_number_txt,i,1);
        if ascii(ls_char) < 48 or ascii(ls_char) > 57 then return as_number_txt;end if;
        li_number_no := (ls_char)::numeric;

        begin
            select number_thai
            into STRICT   ls_char
            from    sc_mem_m_ucf_number_thai
            where   number_no = li_number_no
;
            ls_number_txt_new := ls_number_txt_new || ls_char;
        end;
    end loop;

    return ls_number_txt_new;
exception
when no_data_found then return as_number_txt;
when too_many_rows then return as_number_txt;
when others then CALL spa_dberror('FPA_CNV_NUMBERIC_TO_THAI');
end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpa_cnv_numberic_to_thai (as_number_txt text) FROM PUBLIC;

