-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpa_rep_loanreq_inttime (as_reqno char) RETURNS varchar AS $body$
DECLARE

  ldt_datefr timestamp(0);
  ldt_dateto timestamp(0);
  li_dayafter integer;
  ls_rc varchar(100);

BEGIN

  select begining_of_contract
  into STRICT  ldt_datefr
  from sc_lon_m_loan_request
  where loan_requestment_no = as_reqno;

  ldt_dateto := pka_srv_datetime.fp_lastdayofmonth(ldt_datefr);

  li_dayafter := to_date(ldt_dateto) - to_date(ldt_datefr) + 1;

  if li_dayafter > 0 then
    return '( ดบ. '||trim(both to_char(li_dayafter,'9,90'))||' วัน)';
  end if;
  return null;
exception when others then return null;
END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpa_rep_loanreq_inttime (as_reqno char) FROM PUBLIC;

