-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpa_get_bal_loan_history (as_lon_reqno char ) RETURNS bigint AS $body$
DECLARE

ldc_total bigint;

BEGIN
 select  sum(coalesce(interest_amount,0)) + sum(coalesce(interest_amount,0)) into STRICT ldc_total
 from   sc_lon_m_loan_history
 where  loan_requestment_no = as_lon_reqno;

  RETURN ldc_total;
END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpa_get_bal_loan_history (as_lon_reqno char ) FROM PUBLIC;

