-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpa_tel_lon_notpaid (as_conno char,adt_dateto timestamp(0),as_type char) RETURNS integer AS $body$
DECLARE

  ldc_period_pay bigint;
  ldt_start_keep timestamp(0);
  ldt_end_date timestamp(0);
  li_month_count integer;
  ldc_money_target bigint;
  ldc_money_paid bigint;
  ldc_money_cancel bigint;

  ldc_money_not bigint;
  ldc_period_count bigint;

BEGIN
  /* ----------- จำนวนงวดที่ยังไม่ชำระ ------------------------  */

  -- จำนวนเงิดงวดส่ง
  ldc_period_pay := fpa_tel_lon_fristperiod(as_conno);

  begin
    select start_keep_date into STRICT ldt_start_keep
    from sc_lon_m_contract
    where (loan_contract_no = as_conno);
  exception when others then CALL spa_dberror('fpa_tel_lon_notpaid_count:ไม่พบสัญญาเงินกู้('||trim(both as_conno)||')');
  end;
  ldt_start_keep := to_date('01'||to_char(ldt_start_keep,'/mm/yyyy'),'dd/mm/yyyy');
  ldt_end_date := to_date('01'||to_char(adt_dateto,'/mm/yyyy'),'dd/mm/yyyy');

  li_month_count := months_between(ldt_end_date,ldt_start_keep);
  if coalesce(li_month_count::text, '') = '' or li_month_count <= 0 then
    return 0; -- จำนวนเดือนน้อยกว่า
  end if;

  ldc_money_target := ldc_period_pay*li_month_count; -- จำนวนเงินที่ต้องได้
  -- จำนวนเงินที่ชำระ
  select sum(coalesce(payment_amount,0)) into STRICT ldc_money_paid
  from sc_lon_m_loan_card_detail tld
  where exists (
    SELECT null from sc_lon_m_ucf_loan_card_item
    where (item_type_code = tld.item_type_code)
    and (sign_status < 0)
  )and (loan_contract_no = as_conno);
  -- จำนวนเงินที่ยกเลิก
  select sum(coalesce(payment_amount,0)) into STRICT ldc_money_cancel
  from sc_lon_m_loan_card_detail tld
  where exists (
    SELECT null from sc_lon_m_ucf_loan_card_item
    where (item_type_code = tld.item_type_code)
    and (sign_status > 0)
  )and (loan_contract_no = as_conno);

  -- จำนวนเงินที่เก็บได้ไม่ครบ
  ldc_money_not := coalesce(ldc_money_target,0) - (coalesce(ldc_money_paid,0) - coalesce(ldc_money_cancel,0));
  if ldc_money_not <= 0 then
    return 0;-- ไม่มีเงินที่เก็บไม่ได้เลย
  end if;

  if as_type = 'P' then
    return ldc_money_not; -- จำนวนเงินที่เก็บไมได้(เฉพาะเงินต้น)
  end if;

  -- จำนวนงวดที่ผิดนัด
  if ldc_period_pay > 0 then
    ldc_period_count := ldc_money_not/ldc_period_pay;
    if ldc_period_count > 0 then
      if mod(ldc_period_count,1) > 0 then
        return ldc_period_count + 1;
      else
        return ldc_period_count;
      end if;
    else
      return 0;
    end if;
  else
    return 0;
  end if;

end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpa_tel_lon_notpaid (as_conno char,adt_dateto timestamp(0),as_type char) FROM PUBLIC;

