-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpa_lon_sum_bal_by_loan_type (as_loan_type char) RETURNS bigint AS $body$
DECLARE

ldc_sum_bal bigint;

BEGIN
  select sum(sc_lon_m_loan_card.principal_balance)
  into STRICT ldc_sum_bal
  from sc_lon_m_loan_card
  where loan_type = as_loan_type
  and principal_balance > 0;
  return coalesce(ldc_sum_bal,0);
end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpa_lon_sum_bal_by_loan_type (as_loan_type char) FROM PUBLIC;

