-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpa_gos_cmem_prov (ai_year bigint,ai_month bigint,as_kep char,as_kcode char,as_pcode char) RETURNS bigint AS $body$
DECLARE

  ldc_count bigint;

BEGIN
  select count(1) into STRICT ldc_count
  from sc_kep_t_monthly_receive kh
      ,sc_kep_t_monthly_receive_det kd
      ,sc_mem_m_ucf_member_group
      ,sc_mem_m_ucf_province
  where (kd.receive_year = kh.receive_year)
  and (kd.receive_month = kh.receive_month)
  and (kd.membership_no = kh.membership_no)
  and (kd.seq_no = kh.seq_no)
  and (kh.member_group_no = sc_mem_m_ucf_member_group.member_group_no)
  and (sc_mem_m_ucf_member_group.province_code = sc_mem_m_ucf_province.province_code)
  and (kh.kep_method_amount > 0)
  and (kh.receive_year = ai_year)
  and (kh.receive_month = ai_month)
  and (kh.kep_method = as_kep)
  and (kd.keeping_type_code = as_kcode)
  and (sc_mem_m_ucf_province.province_code = as_pcode)
  group by sc_mem_m_ucf_province.province_code;

  if coalesce(ldc_count::text, '') = '' then ldc_count := ' ';
  end if;
  return ldc_count;

exception
when no_data_found then return null;
when others then CALL spa_dberror('fpa_gos_cmem_prov');
end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpa_gos_cmem_prov (ai_year bigint,ai_month bigint,as_kep char,as_kcode char,as_pcode char) FROM PUBLIC;

