-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpa_gos_period_share (as_memno char, ai_year bigint,ai_month bigint,ai_seq bigint) RETURNS bigint AS $body$
DECLARE

  li_period sc_kep_t_monthly_receive_det.period%type;

BEGIN
  select period into STRICT li_period
  from sc_kep_t_monthly_receive_det
  where (membership_no = as_memno)
  and (receive_year = ai_year)
  and (receive_month = ai_month)
  and (seq_no = ai_seq)
  and (keeping_type_code = 'MS00');

  return nvn(li_period);
exception
when too_many_rows then return 0;
when no_data_found then return 0;
when others then CALL spa_dberror('FPA_GOS_PERIOD_SHARE('||trim(both as_memno)
||','||trim(both ai_year)||','||trim(both ai_month)||','||trim(both ai_seq)||')');return null;
END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpa_gos_period_share (as_memno char, ai_year bigint,ai_month bigint,ai_seq bigint) FROM PUBLIC;

