-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpa_get_share_resign (as_reqno char , as_name char) RETURNS bigint AS $body$
DECLARE

ldc_number bigint;

BEGIN
  if upper(trim(both as_name)) = 'LON_BAL' then
    select  sum(coalesce(principal_balance,0)) into STRICT ldc_number
    from    sc_mem_m_resign_loan
    where   resign_doc_no = as_reqno;
  elsif  upper(trim(both as_name)) = 'LON_INT' then
    select  sum(coalesce(interest,0) + coalesce(interest_arrear,0)) into STRICT ldc_number
    from    sc_mem_m_resign_loan
    where   resign_doc_no = as_reqno;
  else
    ldc_number := 0;
  end if;

  return coalesce(ldc_number,0);
 exception when others then CALL spa_dberror('E18 : FPA_GET_SHARE_RESIGN ');

END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpa_get_share_resign (as_reqno char , as_name char) FROM PUBLIC;

