-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpa_tel_reg_amount_return (as_docno char) RETURNS bigint AS $body$
DECLARE

ldc_number bigint;
ldc_shr bigint;

BEGIN
   begin
      select   coalesce(sc_mem_m_resign_share.shr_value,0) into STRICT ldc_shr
      from     sc_mem_m_resign_share
      where    resign_doc_no  = as_docno;
      exception
      when no_data_found then ldc_shr := 0;
      when others then CALL spa_dberror('E10 : select หุ้น');
  end;
  begin
  select   sum(coalesce(principal_balance,0)+ coalesce(interest,0) + coalesce(interest_arrear,0)) into STRICT ldc_number
  from     sc_mem_m_resign_loan
  where    resign_doc_no = as_docno;
  exception
     when no_data_found then return  ldc_shr;
     when others then CALL spa_dberror('E10 : select หนี้');
  end;

  if coalesce(ldc_number::text, '') = '' then ldc_number := '0';end if;

  ldc_shr := coalesce(ldc_shr,0) - coalesce(ldc_number,0);


 return ldc_shr;


END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpa_tel_reg_amount_return (as_docno char) FROM PUBLIC;

