-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpa_kep_m_dividend_cal_shr (ai_month bigint,adc_number bigint) RETURNS bigint AS $body$
DECLARE

  ldc_div_rate bigint;
  li_month bigint;
  ldc_return bigint;
  li_number bigint;

BEGIN
  li_month := ai_month;
  li_number := adc_number;
--select rate อัตราการปันผล
 select dividend_rate into STRICT ldc_div_rate from sc_cnt_m_coop;
 -- หาเดือนที่ส่งเข้ามาเป็นเดือนอะไร
 if li_month > 12 then li_month := 12;end if;
 ldc_return := (adc_number*(12- coalesce(li_month,0)))/12;
 --ldc_return := ldc_return * (ldc_div_rate/100) ;
 return coalesce(ldc_return,0);
exception when others then CALL spa_dberror('FPA_KEP_M_DIVIDEND_CAL_SHR');return null;
END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpa_kep_m_dividend_cal_shr (ai_month bigint,adc_number bigint) FROM PUBLIC;

