-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpa_lon_get_memno_by_conno (as_conno char) RETURNS varchar AS $body$
DECLARE

ls_memno sc_lon_m_contract.membership_no%type;

BEGIN
  select membership_no into STRICT ls_memno
  from   sc_lon_m_contract
  where (loan_contract_no = as_conno);
  if coalesce(ls_memno::text, '') = '' then ls_memno := '';end if;
  return ls_memno;

END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpa_lon_get_memno_by_conno (as_conno char) FROM PUBLIC;

