-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpa_dep_chq_clearing_date (as_item_type text , as_slip_no text ) RETURNS timestamp(0) AS $body$
DECLARE

  ldt_date timestamp(0);

BEGIN
--Niorn 2024-08-29 MWA เพิ่ม OCQ
--if as_item_type = 'DCQ'  then
if as_item_type = 'DCQ' or  as_item_type = 'OCQ' then

    --Niorn 2024-05-26 MWA กรณีเคลียริ่งก่อนกำหนด ไปเอาจาก  cheque_tobank
--    select nvl(max( chq_date ), to_date( sysdate , 'dd/mm/yyyy') )
--    into ldt_date
--    from sc_dep_t_deposit_slip_item
--    where deposit_slip_no = as_slip_no
--    ;    
    select coalesce(max( clearing_bankdate ), to_date(clock_timestamp() ,'dd/mm/yyyy') )
    into STRICT ldt_date
    from sc_fin_cheque_tobank
    where cheque_no = ( 
            SELECT max( chq_no )
             from sc_dep_t_deposit_slip_item
             where deposit_slip_no =as_slip_no  )  
;

else
    return null;
end if;

return  ldt_date;
exception when others then CALL spa_dberror('FPA_DEP_CHQ_CLEARING_DATE');return null;
END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpa_dep_chq_clearing_date (as_item_type text , as_slip_no text ) FROM PUBLIC;

