-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpa_com_read_interes (as_number bigint ) RETURNS varchar AS $body$
DECLARE

 ls_return varchar(400):= ' ';
 ls_number varchar(100);
 ls_part_head char(1);
 ls_replace_1 varchar(100):= ' ';
 ls_replace_2 varchar(100):= ' ';
 ls_replace_3 varchar(100):= ' ';
 li_count integer;
 li_count_dot integer;
 li_row integer := 0;
BEGIN
 -- ฟังก์ชั่นเร่งด่วน อ่านดอกเบี้ยได้เเค่หลักสิบนะคับ เช่น 12.2345678909876
  li_count := length(as_number::text);
    for i in 1..li_count loop
      ls_part_head := substr(trim(both as_number),i,1);
      if ls_part_head = '.' then
       li_count_dot := length(substr(trim(both as_number),1,i));
       goto end_loop;
      else
       li_row := li_row+1;
      end if;
    end  loop;
    <<end_loop>>
    --ใช้ในกรณีไม่มีจุดคับ
    if li_row >= 2 and coalesce(li_count_dot::text, '') = '' then
        li_count_dot := 2;
    end if;
    for i in 1..li_count loop
     ls_part_head := substr(trim(both as_number),i,1);
     -- อ่านหลักแรก
      if  li_count_dot >= 2 and i = 1 and li_row >= 2 then
        ls_replace_1 := replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(trim(both ls_part_head)
            ,'1','สิบ'),'2','ยี่สิบ '),'3','สามสิบ'),'4','สี่สิบ'),'5','ห้าสิบ'),'6','หกสิบ'),'7','เจ็ดสิบ'),'8','แปดสิบ'),'9','เก้าสิบ '),'0', ' ')
;
       elsif li_count_dot >= 2 and i = 2  and li_row <> 1 then
     --อ่านหลักสอง
        ls_replace_2 := replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(trim(both ls_part_head)
            ,'1','เอ็ด'),'2','สอง '),'3','สาม'),'4','สี่'),'5','ห้า'),'6','หก'),'7','เจ็ด'),'8','แปด'),'9','เก้า'),'0', ' '),'.','จุด')
;
       else
     --อ่านหลักสาม สี่
      ls_replace_3 := replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(trim(both ls_part_head)
            ,'1','หนึ่ง'),'2','สอง '),'3','สาม'),'4','สี่'),'5','ห้า'),'6','หก'),'7','เจ็ด'),'8','แปด'),'9','เก้า'),'0', 'ศูนย์'),'.','จุด')
;
       ls_number := trim(both ls_number) || trim(both ls_replace_3);
       end if;
   end loop;
     ls_return := trim(both ls_replace_1)||trim(both ls_replace_2)||ls_number;

   return  ls_return;
Exception
 when others then CALL spa_dberror('FPA_COM_READ_INTERES');
END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpa_com_read_interes (as_number bigint ) FROM PUBLIC;

