-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpa_fin_pay_chq ( as_vourcher_no text ) RETURNS bigint AS $body$
DECLARE

  ldc_chq_amount bigint;

BEGIN

    SELECT coalesce( sum(sc_fin_cheque_print_item.print_amount) , 0 ) into STRICT ldc_chq_amount
    from sc_fin_cheque_print
    ,sc_fin_cheque_print_item
    where 1=1
    and sc_fin_cheque_print.bank_fin = sc_fin_cheque_print_item.bank_fin
    and sc_fin_cheque_print.book_no = sc_fin_cheque_print_item.book_no
    and sc_fin_cheque_print.cheque_no = sc_fin_cheque_print_item.cheque_no
    and sc_fin_cheque_print.seq_no = sc_fin_cheque_print_item.seq_no
    and sc_fin_cheque_print.cancel_status = '0'
    and sc_fin_cheque_print_item.vourcher_no = as_vourcher_no
;

  return coalesce(ldc_chq_amount,0);

exception when others then return 0;
END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpa_fin_pay_chq ( as_vourcher_no text ) FROM PUBLIC;

