-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpa_lon_get_conno_by_reqno (as_reqno char) RETURNS varchar AS $body$
DECLARE

ls_conno sc_lon_m_contract.loan_contract_no%type;

BEGIN
  select loan_contract_no into STRICT ls_conno
  from   sc_lon_m_contract
  where (loan_requestment_no = as_reqno);
  if coalesce(ls_conno::text, '') = '' then ls_conno := '';end if;
  return ls_conno;

END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpa_lon_get_conno_by_reqno (as_reqno char) FROM PUBLIC;

