-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpa_lon_count_concoll_by_type (as_loan_type char,as_coll_type char,ai_case bigint) RETURNS bigint AS $body$
DECLARE

ldc_sum_used_amount bigint;
li_count integer;

BEGIN
  if as_coll_type = '02' or as_coll_type = '03' then  --หาจำนวนเงินค้ำ
    select sum(sc_lon_m_contract_coll.used_amount)
    into STRICT ldc_sum_used_amount
    from sc_lon_m_contract_coll
    ,sc_lon_m_loan_card
    where (sc_lon_m_contract_coll.loan_contract_no = sc_lon_m_loan_card.loan_contract_no)
    and (sc_lon_m_loan_card.loan_type = as_loan_type)
    and (sc_lon_m_contract_coll.collateral_type_code = as_coll_type)
    and (sc_lon_m_loan_card.principal_balance > 0)
    and (sc_lon_m_contract_coll.status = '0');
    return coalesce(ldc_sum_used_amount,0);
  elsif as_coll_type = '01' then  --หาจำนวนสัญญาที่มีคนค้ำ 1 คน
    if ai_case = 1 then
      select count(tab_h.loan_contract_no)
      into STRICT li_count
      from sc_lon_m_loan_card tab_h
      where exists (
        SELECT sc_lon_m_loan_card.loan_contract_no
        from sc_lon_m_contract_coll,sc_lon_m_loan_card
        where (sc_lon_m_contract_coll.loan_contract_no = sc_lon_m_loan_card.loan_contract_no)
        and (sc_lon_m_loan_card.principal_balance > 0)
        and (sc_lon_m_contract_coll.collateral_type_code = '01')
        and (sc_lon_m_contract_coll.status = '0')
        and (sc_lon_m_contract_coll.loan_contract_no = tab_h.loan_contract_no)
        having(count(sc_lon_m_contract_coll.loan_contract_no) = 1)
        group by sc_lon_m_loan_card.loan_contract_no
      )
      and (tab_h.loan_type = as_loan_type);
      return li_count;
    elsif ai_case = 2 then  --หาจำนวนสัญญาที่มีคนค้ำมากกว่า 1 คน
      select count(tab_h.loan_contract_no)
      into STRICT li_count
      from sc_lon_m_loan_card tab_h
      where exists (
        SELECT sc_lon_m_loan_card.loan_contract_no
        from sc_lon_m_contract_coll,sc_lon_m_loan_card
        where (sc_lon_m_contract_coll.loan_contract_no = sc_lon_m_loan_card.loan_contract_no)
        and (sc_lon_m_loan_card.principal_balance > 0)
        and (sc_lon_m_contract_coll.collateral_type_code = '01')
        and (sc_lon_m_contract_coll.status = '0')
        and (sc_lon_m_contract_coll.loan_contract_no = tab_h.loan_contract_no)
        having(count(sc_lon_m_contract_coll.loan_contract_no) > 1)
        group by sc_lon_m_loan_card.loan_contract_no
      )
      and (tab_h.loan_type = as_loan_type);
      return li_count;
    elsif ai_case = 0 then  --หาจำนวนสัญญาที่มีคนค้ำทั้งหมด
      select count(tab_h.loan_contract_no)
      into STRICT li_count
      from sc_lon_m_loan_card tab_h
      where exists (
        SELECT sc_lon_m_loan_card.loan_contract_no
        from sc_lon_m_contract_coll,sc_lon_m_loan_card
        where (sc_lon_m_contract_coll.loan_contract_no = sc_lon_m_loan_card.loan_contract_no)
        and (sc_lon_m_loan_card.principal_balance > 0)
        and (sc_lon_m_contract_coll.collateral_type_code = '01')
        and (sc_lon_m_contract_coll.status = '0')
        and (sc_lon_m_contract_coll.loan_contract_no = tab_h.loan_contract_no)
      )
      and (tab_h.loan_type = as_loan_type);
      return li_count;
    end if;
  else
    select sum(sc_lon_m_contract_coll.used_amount)
    into STRICT ldc_sum_used_amount
    from sc_lon_m_contract_coll
    ,sc_lon_m_loan_card
    where (sc_lon_m_contract_coll.loan_contract_no = sc_lon_m_loan_card.loan_contract_no)
    and (sc_lon_m_loan_card.loan_type = as_loan_type)
    and (sc_lon_m_contract_coll.collateral_type_code not in ('01','02','03'))
    and (sc_lon_m_loan_card.principal_balance > 0)
    and (sc_lon_m_contract_coll.status = '0');
    return coalesce(ldc_sum_used_amount,0);
  end if;
  return 0;
end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpa_lon_count_concoll_by_type (as_loan_type char,as_coll_type char,ai_case bigint) FROM PUBLIC;

