-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpa_tel_lon_amt_atdate (as_memno char,as_conno char,adt_date timestamp(0)) RETURNS bigint AS $body$
DECLARE

  ldc_return bigint;

BEGIN
   begin  --หาจากค่า new จากวันที่ document_no ที่ max(operate_date) <= วันที่ที่ต้องการ
      select	sc_mem_m_chg_loan_det.period_payment_new  into STRICT ldc_return
      from		sc_mem_m_chang_request	tab_chh
        ,	    sc_mem_m_chg_loan_det
      where (sc_mem_m_chg_loan_det.membership_no = tab_chh.membership_no)
      and (tab_chh.document_no = sc_mem_m_chg_loan_det.document_no)
      and (tab_chh.membership_no = as_memno)
      and (sc_mem_m_chg_loan_det.loan_contract = as_conno)
      and (tab_chh.approve_status = '1')
      and		  (tab_chh.document_no  = (
              --หา doc_no ที่มากที่สุดของวันนั้น
              SELECT	min(tab_chd.document_no)
              from		sc_mem_m_chang_request	tab_chd
              where (tab_chh.document_no = tab_chd.document_no)
              and		(tab_chd.approve_date =(
                    --หาวันที่ที่มากที่สุดหรือเท่ากับ วันที่ต้องการ
                     SELECT min(tab_chc.operate_date)
                     from   sc_mem_m_chang_request  tab_chc
                     where (tab_chc.operate_date <= adt_date)
                     )) 
              ));
  exception
  when no_data_found then null;
  when others then CALL spa_dberror('หาค่า period_payment_new ใน det');return null;
  end;
  if coalesce(ldc_return::text, '') = '' then
    begin  --หาจากค่า old จากวันที่ document_no ที่ min(operate_date) >= วันที่ที่ต้องการ
      select	sc_mem_m_chg_loan_det.period_payment_old  into STRICT ldc_return
      from		sc_mem_m_chang_request	tab_chh
        ,	    sc_mem_m_chg_loan_det
      where (sc_mem_m_chg_loan_det.membership_no = tab_chh.membership_no)
      and (tab_chh.document_no = sc_mem_m_chg_loan_det.document_no)
      and (sc_mem_m_chg_loan_det.loan_contract = as_conno)
      and (tab_chh.membership_no = as_memno)
      and (tab_chh.approve_status = '1')
      and		  (tab_chh.document_no  = (
              --หา doc_no ที่น้อยที่สุดของวันนั้น
              SELECT	min(tab_chd.document_no)
              from		sc_mem_m_chang_request	tab_chd
              where (tab_chh.document_no = tab_chd.document_no)
              and		(tab_chd.approve_date =(
                    --หาวันที่ที่น้อยที่สุด ที่มากกว่าวันที่ต้องการ
                     SELECT min(tab_chc.operate_date)
                     from   sc_mem_m_chang_request  tab_chc
                     where (tab_chc.operate_date > adt_date)
                     )) 
              ));
    exception
    when no_data_found then null;
    when others then CALL spa_dberror('หาค่า period_payment_old ใน det');return null;
    end;
    end if;
    --ถ้ายังไม่มีอีกให้หาจากค่า ใน loan_card
    if coalesce(ldc_return::text, '') = '' then
      select  period_payment_amount into STRICT ldc_return
      from    sc_lon_m_contract
      where (loan_contract_no = as_conno);
   end if;

return coalesce(ldc_return,0);
exception when others then CALL spa_dberror('FPA_TEL_LON_AMT_ATDATE');return null;
END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpa_tel_lon_amt_atdate (as_memno char,as_conno char,adt_date timestamp(0)) FROM PUBLIC;

