-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpa_lon_req_real_amount (as_reqno char) RETURNS bigint AS $body$
DECLARE

  type tabrowi_req is table of sc_lon_m_loan_request%rowtype index by integer;ltabrowi_req tabrowi_req;

  li_count integer;
  ldc_amount bigint := 0;

BEGIN
  select * bulk collect into STRICT ltabrowi_req from sc_lon_m_loan_request where loan_requestment_no = as_reqno;
  li_count := ltabrowi_req.count;
  if li_count > 0 then
    ldc_amount := ltabrowi_req[1].loan_request_amount - ltabrowi_req[1].buy_share
                - ltabrowi_req[1].total_old_loan - ltabrowi_req[1].total_oldint
                - ltabrowi_req[1].fee_amount;
  end if;

  return ldc_amount;
end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpa_lon_req_real_amount (as_reqno char) FROM PUBLIC;

