-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpa_fin_vourcher_date (as_vch_no char) RETURNS timestamp(0) AS $body$
DECLARE

  ldt_date timestamp(0);

BEGIN
  select  operate_date into STRICT ldt_date
  from    sc_fin_vourcher_head
  where (vourcher_no = as_vch_no)    LIMIT 1;

  return ldt_date;

exception
when no_data_found then return to_date('01/01/1900','dd mm yyyy');
when others then CALL spa_dberror('FPA_FIN_VOURCHER_DATE');
END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpa_fin_vourcher_date (as_vch_no char) FROM PUBLIC;

