-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpa_tel_chq_date_shr_docno (as_docno char) RETURNS timestamp(0) AS $body$
DECLARE

  ld_date timestamp(0);

BEGIN
  if upper(trim(both as_docno)) <> 'CNV' then   -- ป้องกันข้อมูล cnv ที่จะ retrun more_than_many_row ในส่วนของ cause
    begin
      select	cheque_date into STRICT ld_date
      from		sc_com_m_receipt
      where	  trim(both receipt_no) = trim(both as_docno);
     exception
     when no_data_found then ld_date := null;
     when others then CALL spa_dberror('select failed!');
     end;
   end if;

   return ld_date;

exception when others then CALL spa_dberror('fpa_tel_chq_date_shr_docno');
end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpa_tel_chq_date_shr_docno (as_docno char) FROM PUBLIC;

