-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpa_tel_money_type_id_join (as_receipt_no char,as_memno char) RETURNS varchar AS $body$
DECLARE

  ls_return varchar(100);

BEGIN
  begin
    select  money_type_id into STRICT ls_return
    from    sc_com_m_receipt
    where (receipt_no = as_receipt_no)
    and (money_type_id = 'TNL');
  exception
  when no_data_found then   ls_return := null;
  when others then CALL spa_dberror('select com_receipt failed!');
  end;
  if coalesce(ls_return::text, '') = '' then
    begin
      select  money_type_id into STRICT ls_return
      from    sc_com_m_receipt
      where   (receipt_no =
               (
               SELECT max(receipt_no)
               from   sc_com_m_receipt
               where (membership_no = as_memno)
               ));
      exception
      when no_data_found then ls_return := 'sc_com_m_receipt.money_type_id'; -- ถ้าไม่มีจริงๆส่ง money_type_id กลับไปจอยเหมือนเดิม
      when others then CALL spa_dberror('select max_receipt_no failed!');
   end;
  end if;
  return ls_return;

exception when others then CALL spa_dberror('FPA_TEL_MONEY_TYPE_ID_JOIN');
END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpa_tel_money_type_id_join (as_receipt_no char,as_memno char) FROM PUBLIC;

