-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpa_kep_group_address_name (as_group_no char) RETURNS varchar AS $body$
DECLARE

ls_return varchar(400);

BEGIN
  select  coalesce(address_no,' ')||coalesce(moo,' ')||coalesce(road ,' ') ||coalesce(soi ,' ')||coalesce(tambol ,' ')|| pka_com_function.fp_get_district_name(province_code,district_code )||pka_com_function.fp_get_province_name(province_code)|| postcode|| telephone
  into STRICT    ls_return
  from    sc_mem_m_ucf_member_group_addr
  where (member_group_no = as_group_no);

  return ls_return;

END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpa_kep_group_address_name (as_group_no char) FROM PUBLIC;

