-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpa_kep_cal_drop_av (as_conno char,ai_year integer,ai_date integer) RETURNS varchar AS $body$
DECLARE

  ldt_bdate timestamp(0);
  ldt_edate timestamp(0);
  li_count integer;
  li_count_sub integer;
  ls_return varchar(1000);
  li_pl integer;
  li_rc integer;
  li_factor integer := 0;
  li_count_rm integer := 0;

  type tabrowi_conno is table of sc_lon_m_loan_card_detail%rowtype index by integer;
  ltabrowi_conno tabrowi_conno;
  ltabrowi_sub tabrowi_conno;
  ltabrowi_empty tabrowi_conno;
BEGIN
  begin  --หาวันที่มาจาก  table ปิดสิ้นปีระบบหุ้นหนี้
    select  start_date , end_date
    into STRICT    ldt_bdate  , ldt_edate
    from    sc_lon_m_close_year
    where (lon_year = ai_year);
  exception when others then CALL spa_dberror('sc_lon_m_close_year');
  end;
  --เลือกวันที่
  select * bulk collect into STRICT ltabrowi_conno
  from  sc_lon_m_loan_card_detail
  where (loan_payment_date between ldt_bdate and ldt_edate )
  and (loan_contract_no = as_conno)
  order by seq_no;
  --หาวันที่ที่มีการคืนใบเสร็จ
  li_count := ltabrowi_conno.count;
  for i in 1..li_count loop
    if trim(both ltabrowi_conno[i].item_type_code) = 'RM' then
    -- หาวันที่ระหว่างเดือน ถึงเดือนที่อนุโลม
      ldt_bdate := pka_srv_datetime.fp_firstdayofmonth(ltabrowi_conno[i].loan_payment_date) + ai_date;
      ldt_edate := pka_srv_datetime.fp_lastdayofmonth(ltabrowi_conno[i].loan_payment_date) + ai_date;
    --หาว่าระหว่างวันที่กำหนดมีการมาชำระหรือเปล่า
      ltabrowi_sub := ltabrowi_empty;--เคลียร์ค่าในแต่ละช่วง
      -------- เก็บค่า --------
      for i_sub in 1..li_count loop
        if ltabrowi_conno[i_sub].loan_payment_date >= ldt_bdate and ltabrowi_conno[i_sub].loan_payment_date <= ldt_edate then
          ltabrowi_sub(ltabrowi_sub.count + 1) := ltabrowi_conno(i_sub);
        end if;
      end loop;
      li_count_sub := ltabrowi_sub.count;
      -------- แสดงค่า --------
      li_pl := 0; --เคลียร์ค่า
      li_rc := 0;
      li_factor := 0;
      for j in 1..li_count_sub loop
        li_rc := li_rc + 1;
      --ถ้ามีการคืนใบเสร็จประจำเดือนแล้วมีการมาชำระพิเศษหรือเปล่า
        if trim(both ltabrowi_sub[j].item_type_code) = 'PL' then
        li_pl := li_pl + 1;
        --ต้องหาทั้งปีว่าใบเสร็จชำระพิเศษใบนียกเลิกหรือเปล่า้
           for k in 1..li_count loop
           --ถ้ามีการมาชำระแล้วมีการยกเลิกใบเสร็จหรือเปล่า
             if trim(both ltabrowi_conno[k].item_type_code) = 'RC'then
             --ถ้ายกเลิกใบเสร็จชำระพิเศษนับ 1
                if ltabrowi_sub[j].ref_loan_doc_no = ltabrowi_conno[k].ref_loan_doc_no then
                   li_factor := li_factor + 1;--ลบกลับเผื่อว่าชำระหลายที
                end if;
             end if;
           end loop;
         --ถ้าแอดมือ seq_no ต้องอยู่ +1 แน่นอน
        elsif trim(both ltabrowi_sub[j].item_type_code) = 'PL' and trim(both ltabrowi_sub[j+1].item_type_code) = 'RC' then
          li_pl := li_pl + 1;
          if lower(trim(both ltabrowi_sub[j+1].ref_loan_doc_no)) = 'cnv' then --แอดมือ default 'cnv'
            if ltabrowi_sub[j+1].payment_amount = ltabrowi_sub[j].payment_amount and ltabrowi_sub[j+1].interest_amout = ltabrowi_sub[j].interest_amout then
            --ยอดเงินที่ชำระ ดอกเบี้ย จะต้องเท่ากัน บวกรวมกันไม่ได้ป้องกัน 1+4 = 2+3
             li_factor := li_factor + 1;--ลบกลับเผื่อว่าแอดมือหลายที
            end if;
          end if;
        end if;
      end loop;
      if li_pl =  li_factor then  --กรณีที่ 1 ชำระเท่าไหร่ ยกเลิกเท่านั้น ถือว่าผิดนัด
          ls_return := trim(both ls_return) ||','||pka_com_function.fp_get_thaidate(ltabrowi_conno[i].loan_payment_date,'MONYY')::text;
          li_count_rm := li_count_rm + 1;
      elsif li_pl = 0 and li_rc > 0 then  --กรณีที่ 2 ไม่มีรายการชำระพิเศษเลย
          ls_return := trim(both ls_return) ||','||pka_com_function.fp_get_thaidate(ltabrowi_conno[i].loan_payment_date,'MONYY')::text;
          li_count_rm := li_count_rm + 1;
      elsif li_pl > 0 and li_pl > li_factor then --กรณีที่ 3 รายการชำระมากกว่ารายการยกเลิก
          null;
      end if;

    end if;
  end loop;
  if coalesce(trim(both ls_return)::text, '') = '' then
    null;
  else
    ls_return := substr(ls_return,2,length(ls_return));
  end if;
return coalesce(ls_return,' ');
exception when others then CALL spa_dberror('fpa_kep_cal_drop_av');return null;
END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpa_kep_cal_drop_av (as_conno char,ai_year integer,ai_date integer) FROM PUBLIC;

