-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpa_get_gain_address (as_memno text , ai_recno integer ) RETURNS varchar AS $body$
DECLARE

ls_gain_address varchar(4000);

BEGIN

    begin
        select  gain_address 
        || ( select subdistrict_name  from sc_mem_m_ucf_subdistrict where subdistrict_code = sc_mem_m_member_recrieve_gain.tambol_code ) 
        || PKA_COM_FUNCTION.fp_get_district_name( province_code ,  district_code ) 
        || PKA_COM_FUNCTION.fp_get_province_name( province_code  ) 
        || gain_postcode into STRICT ls_gain_address
        from sc_mem_m_member_recrieve_gain
        where 1=1
        and membership_no =as_memno
        and rec_no = ai_recno
;
    exception
    when others then return ' ';
    end;

  return ls_gain_address;

end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpa_get_gain_address (as_memno text , ai_recno integer ) FROM PUBLIC;

