-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpa_kep_receipt_item_show (as_type_name char ,as_desc char , as_type char) RETURNS varchar AS $body$
DECLARE

ls_name varchar(400);
ls_group_type sc_lon_m_rule.loan_group_code%type;

BEGIN
  if upper(trim(both as_type)) in ('ML01','ML02','ML03') then
    if upper(trim(both as_type)) = 'ML01' then
      ls_name := 'ฉุกเฉิน ' ||trim(both as_desc);
    elsif  upper(trim(both as_type)) = 'ML02' then
      ls_name := 'สามัญ ' ||trim(both as_desc);
    else
      ls_name := 'พิเศษ ' ||trim(both as_desc);
    end if;
  elsif  upper(substr(trim(both as_type),1,2)) = 'FE' then
     -- goto  end_ret ;
     ls_name :=  trim(both as_type_name);
  elsif upper(substr(trim(both as_type),1,2)) = 'MS' then
     -- goto  end_ret ;
     ls_name :=  trim(both as_type_name);
  elsif upper(substr(trim(both as_type),1,2)) = 'MD' then
      ls_name := 'เงินฝาก ' ||trim(both as_desc);
  else
      --goto  end_ret ;
      ls_name :=  trim(both as_type_name);
  end if;


 -- <<end_ret>> ls_name :=  trim(as_desc) ;
  return ls_name;
END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpa_kep_receipt_item_show (as_type_name char ,as_desc char , as_type char) FROM PUBLIC;

