-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpa_dep_get_book_bank_desc (as_slip_no text) RETURNS varchar AS $body$
DECLARE

  ls_return varchar(4000);

BEGIN
    BEGIN
            select sc_fin_m_bank.bank_name
            || ' โอน '||  trim(both to_char( sc_fin_m_bank_statement.item_amount  , '999,999,999.99'))
            || ' วันที่ '|| to_char( sc_fin_m_bank_statement.operate_date  , 'dd/mm/')
            || (to_char( sc_fin_m_bank_statement.operate_date  , 'yyyy') + 543 )::text
            || '( #'|| (sc_fin_m_bank_statement.seq_no   )::text || '. '||item_desc ||' )'
            into STRICT ls_return
            from sc_fin_m_bank
            , sc_fin_m_bank_statement
            , sc_dep_t_deposit_slip_item
            where sc_fin_m_bank_statement.bank_fin = sc_fin_m_bank.bank_fin
            and sc_fin_m_bank_statement.seq_no = sc_dep_t_deposit_slip_item.book_bank_seq
            and sc_fin_m_bank_statement.bank_fin =sc_dep_t_deposit_slip_item.bank_to
            and  sc_dep_t_deposit_slip_item.deposit_slip_no = as_slip_no
            and sc_dep_t_deposit_slip_item.seq_no = ( SELECT min( seq_no )
                                                            from sc_dep_t_deposit_slip_item
                                                            where 1=1
                                                            and  deposit_slip_no = as_slip_no )  
;
    EXCEPTION when OTHERS then return ' ';
    END;

return   trim(both ls_return);
exception when others then CALL spa_dberror('FPA_DEP_GET_BOOK_BANK_DESC');
END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpa_dep_get_book_bank_desc (as_slip_no text) FROM PUBLIC;

