-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpa_get_prin_int_in_receipt (as_receipt_no char , as_status char) RETURNS bigint AS $body$
DECLARE

  ldc_total bigint;
  ldc_prin bigint;
  ldc_int bigint;
  ldc_item_amount bigint;
  ldc_balance bigint;
  ldc_return bigint;

BEGIN
  begin
    select sum( sc_com_m_receipt_item.principal_amount ) ,
          sum( sc_com_m_receipt_item.interest_amount ) ,
          sum( sc_com_m_receipt_item.item_amount ) ,
          sum( sc_com_m_receipt_item.balance )
    into STRICT ldc_prin , ldc_int , ldc_item_amount , ldc_balance
    from sc_com_m_receipt , sc_com_m_receipt_item
    where	sc_com_m_receipt.receipt_no = sc_com_m_receipt_item.receipt_no
    and		sc_com_m_receipt.receipt_no = as_receipt_no
    and		sc_com_m_receipt_item.item_type_id <> 'SB'
    and		( ( sc_com_m_receipt_item.interest_amount > 0 ) or ( sc_com_m_receipt_item.item_amount > 0 ) )
    and		sc_com_m_receipt.receipt_status = '0' 	;
    ldc_total := ldc_prin + ldc_int;
    exception when others then CALL spa_dberror('E:321 select error : ('||trim(both as_receipt_no)||')');
  end;

  case upper(as_status)
    when 'PRIN' then  -- ต้น
      ldc_return := ldc_prin;
    when 'INT' then  -- ยอด
      ldc_return := ldc_int;
    when 'ALL' then  -- ต้น + ดอก
      ldc_return := ldc_total;
    when 'ITEM' then  -- ยอดชำระ
      ldc_return := ldc_item_amount;
    when 'BALANCE' then  -- หนี้คงเหลือ
      ldc_return := ldc_balance;
    else
      ldc_return := 0;
  end case;

  return coalesce(ldc_return,0);
exception when others then CALL spa_dberror('fpa_get_prin_int_in_receipt');
end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpa_get_prin_int_in_receipt (as_receipt_no char , as_status char) FROM PUBLIC;

