-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpa_tel_req_coll_amt (as_req_no char) RETURNS varchar AS $body$
DECLARE

ls_amount bigint;
ls_type sc_lon_m_ucf_collateral_type.collateral_type_code%type;

BEGIN
  RETURN NULL;
END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpa_tel_req_coll_amt (as_req_no char) FROM PUBLIC;

