-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpa_kep_lon_shr_month (ai_year integer, ai_month integer ,as_memno char ,as_type char ) RETURNS bigint AS $body$
DECLARE

ldc_amount bigint;

BEGIN
if trim(both as_type) = 'NORM' then
  select	sum(coalesce(sc_kep_t_monthly_receive_rep.principal_of_norm_loan,0) + coalesce(sc_kep_t_monthly_receive_rep.interest_of_norm_loan,0))
  into STRICT    ldc_amount
  from 		sc_kep_t_monthly_receive
         	,	sc_kep_t_monthly_receive_rep
  where ( sc_kep_t_monthly_receive.membership_no = sc_kep_t_monthly_receive_rep.membership_no )
  and ( sc_kep_t_monthly_receive.receive_year = sc_kep_t_monthly_receive_rep.receive_year )
  and ( sc_kep_t_monthly_receive.receive_month = sc_kep_t_monthly_receive_rep.receive_month )
  and ( sc_kep_t_monthly_receive.receive_year = ai_year )
  and ( sc_kep_t_monthly_receive.receive_month = ai_month )
  and (sc_kep_t_monthly_receive_rep.norm_type IS NOT NULL AND sc_kep_t_monthly_receive_rep.norm_type::text <> '')
  and (sc_kep_t_monthly_receive.membership_no = as_memno );
 elsif trim(both as_type) = 'EMER' then
  select	sum(coalesce(sc_kep_t_monthly_receive_rep.principal_of_emer_loan,0) + coalesce(sc_kep_t_monthly_receive_rep.interest_of_emer_loan,0))
  into STRICT    ldc_amount
  from 		sc_kep_t_monthly_receive
         	,	sc_kep_t_monthly_receive_rep
  where ( sc_kep_t_monthly_receive.membership_no = sc_kep_t_monthly_receive_rep.membership_no )
  and ( sc_kep_t_monthly_receive.receive_year = sc_kep_t_monthly_receive_rep.receive_year )
  and ( sc_kep_t_monthly_receive.receive_month = sc_kep_t_monthly_receive_rep.receive_month )
  and ( sc_kep_t_monthly_receive.receive_year = ai_year )
  and ( sc_kep_t_monthly_receive.receive_month = ai_month )
  and (sc_kep_t_monthly_receive_rep.emer_type IS NOT NULL AND sc_kep_t_monthly_receive_rep.emer_type::text <> '')
  and (sc_kep_t_monthly_receive.membership_no = as_memno );
 end if;

 return coalesce(ldc_amount,0);

Exception
 when no_data_found then ldc_amount := 0;return ldc_amount;
 when others then CALL spa_dberror('FPA_KEP_LON_SHR_MONTH');

END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpa_kep_lon_shr_month (ai_year integer, ai_month integer ,as_memno char ,as_type char ) FROM PUBLIC;

