-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpa_get_age_live (as_memno char,adt_date timestamp(0)) RETURNS varchar AS $body$
DECLARE

  ls_agetext varchar(100);
  ldt_date_of_birth timestamp(0);

BEGIN
  select date_of_birth
  into STRICT ldt_date_of_birth
  from sc_mem_m_membership_registered
  where membership_no = as_memno;
    if coalesce(ldt_date_of_birth::text, '') = '' then
      ldt_date_of_birth := to_date('1900/1/1','yyyy/mm/dd');
    end if;
  ls_agetext := pka_lon_reqsrv.fp_calc_agetext(pka_srv_datetime.fp_monthsafter( ldt_date_of_birth , adt_date ));

return ls_agetext;
exception when others then CALL spa_dberror('FPA_GET_AGE_LIVE');return null;
END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpa_get_age_live (as_memno char,adt_date timestamp(0)) FROM PUBLIC;

