-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpa_tel_payment_date_by_mem (as_memno char ) RETURNS timestamp(0) AS $body$
DECLARE

ldt_receipt_date timestamp(0);

BEGIN
  select  sc_com_m_receipt.receipt_date into STRICT ldt_receipt_date
  from    sc_com_m_receipt , sc_com_m_receipt_item
  where (sc_com_m_receipt_item.item_type_id= 'MFE')
  and (sc_com_m_receipt.membership_no = as_memno)
  and (sc_com_m_receipt_item.item_type_id = sc_com_m_receipt.money_type_id);
  return ldt_receipt_date;
END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpa_tel_payment_date_by_mem (as_memno char ) FROM PUBLIC;

