-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpa_acc_loan_count_period_year (as_conno char,ai_year integer) RETURNS integer AS $body$
DECLARE

  li_count integer;
  li_return integer := 0;
  ldt_bdate timestamp(0);
  ldt_edate timestamp(0);

  cur_lon CURSOR(cdt_date_fr timestamp(0),cdt_date_ot timestamp(0)) is
  SELECT sc_lon_m_loan_card_detail.period
  ,sc_lon_m_loan_card_detail.ref_loan_doc_no
  ,sc_lon_m_ucf_loan_card_item.sign_status
  from sc_lon_m_loan_card_detail
  , sc_lon_m_ucf_loan_card_item
  where (sc_lon_m_loan_card_detail.item_type_code = sc_lon_m_ucf_loan_card_item.item_type_code)
  and (sc_lon_m_loan_card_detail.loan_payment_date between cdt_date_fr and cdt_date_ot)
  and (sc_lon_m_loan_card_detail.loan_contract_no = as_conno);
  type tabrowi_loan is table of cur_lon%rowtype index by integer;
  ltabrowi_loan tabrowi_loan;
BEGIN
  begin  --หาวันที่มาจาก  table ปิดสิ้นปีระบบหุ้นหนี้
    select  start_date , end_date
    into STRICT    ldt_bdate  , ldt_edate
    from    sc_lon_m_close_year
    where (lon_year = ai_year);
  exception when others then CALL spa_dberror('sc_lon_m_close_year');
  end;

  open cur_lon(ldt_bdate,ldt_edate);
  fetch cur_lon bulk collect into ltabrowi_loan;
  close cur_lon;
  li_count := ltabrowi_loan.count;
  for i in 1..li_count loop
    if ltabrowi_loan[i].period > 0 and ltabrowi_loan[i].sign_status = -1 then
      for j in 1..li_count loop
        if ltabrowi_loan[j].period > 0 and ltabrowi_loan[j].sign_status = 1
          and trim(both ltabrowi_loan[j].ref_loan_doc_no) = trim(both ltabrowi_loan[i].ref_loan_doc_no) then
          goto end_if;
        end if;
      end loop;
      li_return := li_return + 1;
    end if;<<end_if>>null;
  end loop;

  return coalesce(li_return,0);
exception when others then CALL spa_dberror('fpa_acc_loan_count_period_year');
end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpa_acc_loan_count_period_year (as_conno char,ai_year integer) FROM PUBLIC;

