-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpa_tel_appprove_date_by_mem (as_appno char ) RETURNS timestamp(0) AS $body$
DECLARE

ldt_approve_date timestamp(0);

BEGIN
  select approve_date into STRICT ldt_approve_date
  from   sc_mem_m_membership_registered
  where application_form_no = as_appno;

  return ldt_approve_date;
END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpa_tel_appprove_date_by_mem (as_appno char ) FROM PUBLIC;

