-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpa_acc_begining_of_acc () RETURNS timestamp(0) AS $body$
DECLARE

ldt_begining_of_contract sc_acc_m_account_constant.beginning_of_account%type;

BEGIN
  select beginning_of_account into STRICT ldt_begining_of_contract
  from   sc_acc_m_account_constant;

  return ldt_begining_of_contract;
END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpa_acc_begining_of_acc () FROM PUBLIC;

