-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpa_gos_wef_get_date (as_date text) RETURNS varchar AS $body$
DECLARE

ls_date varchar(20);
ls_set  varchar(20);
ls_day  varchar(20);

BEGIN
  ls_set := trim(both as_date);

  --spa_dberror('Sard'+ls_set);
  if (ls_set IS NOT NULL AND ls_set::text <> '') then
          ls_date := trim(both substr(ls_set,position(' ' in ls_set),6));
          case ls_date
            when 'ม.ค.' then ls_date := '01';
            when 'ก.พ.' then ls_date := '02';
            when 'มี.ค.' then ls_date := '03';
            when 'เม.ย.' then ls_date := '04';
            when 'พ.ค.' then ls_date := '05';
            when 'มิ.ย.' then ls_date := '06';
            when 'ก.ค.' then ls_date := '07';
            when 'ส.ค.' then ls_date := '08';
            when 'ก.ย.' then ls_date := '09';
            when 'ต.ค.' then ls_date := '10';
            when 'พ.ย.' then ls_date := '11';
            when 'ธ.ค.' then ls_date := '12';
            else ls_date := null;
          end case;
          ls_date :=substr(ls_set,1,2)||'/'||trim(both substr(ls_date,position(' ' in ls_date),6))||'/'||'20'||right(ls_set,2);
       else
          NULL;
       end if;
    /*
    ls_day := trim(substr(ls_date,1,2)) ;
      if instr(ls_day,' ',2)>0   then
        ls_day := lpad(ls_day,2,0);
      else
        null;
      end if;

       ls_date := trim(ls_day)||'/'||trim(substr(ls_date,instr(ls_date,' ',1),6))||'/'||'20'||right(ls_set,2);
      */
  RETURN ls_date;
exception when others then CALL spa_dberror('');
END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpa_gos_wef_get_date (as_date text) FROM PUBLIC;

