-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpa_tel_desc_admstatus (as_memno char , as_column char) RETURNS varchar AS $body$
DECLARE

ls_desc varchar(200);

BEGIN
  select  sc_mem_m_member_permit_changed.remark_desc into STRICT ls_desc
  from    sc_mem_m_member_permit_changed
  where   membership_no = as_memno
  and     trim(both permit_name) = as_column
  and     seq_no = ( SELECT  max(a.seq_no)
                    from     sc_mem_m_member_permit_changed a
                    where    sc_mem_m_member_permit_changed.membership_no = a.membership_no
                    and      a.new_status = '1'
                    );

 exception
  when no_data_found then ls_desc := '';
  when others then CALL spa_dberror('FPA_TEL_DESC_ADMSTATUS ');

  return coalesce(ls_desc,' ');

END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpa_tel_desc_admstatus (as_memno char , as_column char) FROM PUBLIC;

