-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpa_tel_doc_passdate_frm_reqno (as_conno char) RETURNS timestamp(0) AS $body$
DECLARE

  ld_date timestamp(0);

BEGIN
  select	sc_lon_m_loan_request.apvdoc_date into STRICT ld_date
  from		sc_lon_m_loan_request
  where (trim(both sc_lon_m_loan_request.loan_requestment_no) = trim(both as_conno));

  return ld_date;
exception
when no_data_found then return null;
when others then CALL spa_dberror('fpa_tel_doc_passdate_frm_conno');
end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpa_tel_doc_passdate_frm_reqno (as_conno char) FROM PUBLIC;

