-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpa_com_receipt_ddm_stat (as_voc_no char) RETURNS varchar AS $body$
DECLARE

ls_repno sc_com_m_receipt.ppm_status%type;

BEGIN
  select  sc_com_m_receipt.ppm_status into STRICT ls_repno
  FROM sc_com_m_receipt
LEFT OUTER JOIN sc_fin_vourcher_head ON (sc_com_m_receipt.vourcher_no = sc_fin_vourcher_head.vourcher_no)
WHERE (sc_fin_vourcher_head.vourcher_no = as_voc_no );

  return ls_repno;

  END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpa_com_receipt_ddm_stat (as_voc_no char) FROM PUBLIC;

