-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpa_com_marriage (as_memno char) RETURNS varchar AS $body$
DECLARE

l_member_name sc_mem_m_member_spouse_info.spouse_name%type;
l_member_surname sc_mem_m_member_spouse_info.spouse_surname%type;
ls_prename_code sc_mem_m_member_spouse_info.prename_code%type;
l_prename sc_mem_m_ucf_prename.prename%type;
ls_spname varchar(200);
ls_marriage_status char(1);

BEGIN
    select marriage_status into STRICT ls_marriage_status
    from sc_mem_m_membership_registered
    where membership_no = as_memno
;

    if ls_marriage_status = '2' then
        ls_spname := pka_com_function.fp_get_member_spname(as_memno);
    else
        ls_spname := null;
    end if;

    return ls_spname;
end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpa_com_marriage (as_memno char) FROM PUBLIC;

