-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpa_acc_calc_keep_back_premium (as_offno char,adt_opdate timestamp(0)) RETURNS bigint AS $body$
DECLARE

  --สำรองบำเหน็จเจ้าหน้าที่
  cur_off CURSOR FOR
  SELECT salary_amount
  ,working_date
  from sc_hr_off_member
  where (official_no = as_offno);
  type tabrowi_off is table of cur_off%rowtype index by integer;
  ltabrowi_off tabrowi_off;
  li_year integer;
  li_month integer;
  ldc_value bigint;

BEGIN
  open cur_off;fetch cur_off bulk collect into ltabrowi_off;close cur_off;
  if ltabrowi_off.count <> 1 then return 0;end if;
  li_month := months_between(adt_opdate, ltabrowi_off[1].working_date);
  li_year := date_trunc(12, li_month);
  li_month := mod(li_month,12);
  if li_month >= 6 then
    li_year := li_year + 1;
  end if;
  ldc_value := ltabrowi_off[1].salary_amount * li_year;
  return coalesce(ldc_value,0);
exception when others then CALL spa_dberror('fpa_acc_calc_keep_back_premium');
end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpa_acc_calc_keep_back_premium (as_offno char,adt_opdate timestamp(0)) FROM PUBLIC;

