-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpa_getnumber (as_val text) RETURNS varchar AS $body$
DECLARE

  li_count integer;
  ls_val varchar(1000);
BEGIN
  li_count := length(as_val);
  for i in 1..li_count loop
    if substr(as_val,i,1) in ('0','1','2','3','4','5','6','7','8','9') then
      ls_val := ls_val||substr(as_val,i,1);
    end if;
  end loop;
  return ls_val;
end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpa_getnumber (as_val text) FROM PUBLIC;

