-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpa_gos_controlid (as_memno char) RETURNS integer AS $body$
DECLARE

  ls_province_code sc_mem_m_ucf_province.province_code%type;
  li_control_id integer;

BEGIN



  select control_id into STRICT li_control_id
  from sc_mem_m_ucf_province
  where province_code = ls_province_code;

  RETURN NULL;
END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpa_gos_controlid (as_memno char) FROM PUBLIC;

