-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpa_lon_valid_refinance ( as_conno char) RETURNS char AS $body$
DECLARE

  ls_valid char;
  li_count integer;

BEGIN
  select count(sc_lon_m_contract.loan_contract_no) into STRICT li_count
  from sc_lon_m_contract
  , sc_lon_m_loan_request
  , sc_lon_m_loan_history
  where (sc_lon_m_contract.loan_contract_no = as_conno)
  and (sc_lon_m_contract.loan_requestment_no = sc_lon_m_loan_request.loan_requestment_no)
  and (sc_lon_m_loan_request.loan_requestment_no = sc_lon_m_loan_history.loan_requestment_no)
  and (sc_lon_m_loan_history.clear_target = '1');
  if li_count > 0 then
    return '1';
  else
    return '0';
  end if;

exception when others then CALL spa_dberror('fpa_lon_valid_refinance');
end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpa_lon_valid_refinance ( as_conno char) FROM PUBLIC;

