-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpa_kep_get_kep_type_code (as_memno char,as_kep_code char,ai_year integer,ai_month integer,adc_amount bigint) RETURNS varchar AS $body$
DECLARE

  ls_return varchar(100);
  ls_kep_det sc_kep_t_monthly_receive_det.keeping_type_code%type;

BEGIN
  case trim(both as_kep_code)
   when 'IBA' then
    ls_return := 'สามัญ';
   when 'IBB' then
    ls_return := 'ฉุกเฉิน';
  when 'IBC' then
   begin
    select receive_description , keeping_type_code into STRICT ls_return ,ls_kep_det
    from   sc_kep_t_monthly_receive_det
    where (membership_no = as_memno)
    and (receive_month = ai_month)
    and (receive_year = ai_year)
    and (money_amount = adc_amount);
   exception
   when no_data_found then null;
   when others then CALL spa_dberror('sc_kep_t_monthly_receive_det');return null;
   end;
     if substr(trim(both ls_kep_det),1,2) = 'MS' then
        ls_return := 'หุ้น';
     elsif substr(trim(both ls_kep_det),1,2) = 'MD' then
        ls_return := 'เงินฝาก';
     else
        ls_return := ls_return;
     end if;
   else
     CALL spa_dberror('not case support');
  end case;

return coalesce(trim(both ls_return),' ');
exception when others then CALL spa_dberror('FPA_KEP_GET_KEP_TYPE_CODE');return null;
END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpa_kep_get_kep_type_code (as_memno char,as_kep_code char,ai_year integer,ai_month integer,adc_amount bigint) FROM PUBLIC;

