-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpa_com_receipt_balance (as_voc_no char) RETURNS bigint AS $body$
DECLARE

ldc_amount bigint;

BEGIN
select 	sum(tab_vd.item_amount + fpa_tel_receipt_lon_int(tab_vh.vourcher_no,tab_vd.seq_no)  )
into STRICT    ldc_amount
from 		sc_fin_vourcher_head tab_vh ,
        sc_fin_vourcher_detail tab_vd
where (tab_vh.vourcher_no = as_voc_no  )
and (tab_vh.vourcher_no= tab_vd.vourcher_no)
and (tab_vd.account_id in (
			SELECT 	sc_acc_m_account_master.account_id
			from		sc_acc_m_account_master
			where (tab_vd.account_id = sc_acc_m_account_master.account_id) ))
and (tab_vd.account_id not in (
			SELECT 	sc_lon_m_rule.int_account_id
			from 		sc_lon_m_rule
			where (tab_vd.account_id = sc_lon_m_rule.int_account_id) ))
and (tab_vh.cancel_status = '0');

  return coalesce(ldc_amount,0);

  END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpa_com_receipt_balance (as_voc_no char) FROM PUBLIC;

