-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpa_dberror () RETURNS varchar AS $body$
DECLARE

  ls_sqlerrtext varchar(4000);
  ls_client_id sc_cnt_m_client_registered.client_id%type;

BEGIN
  ls_client_id := pka_com_function.fp_login_pc;

  select sqlerrtext into STRICT ls_sqlerrtext
  from sc_dev_dberror
  where client_id = ls_client_id;

  return ls_sqlerrtext;

exception when others then return null;
end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpa_dberror () FROM PUBLIC;

