-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpa_tel_c_conno_by_shln_atdate (as_group_no char,as_cilent_id char,as_loan_type char) RETURNS bigint AS $body$
DECLARE

  li_count integer;

BEGIN
 if upper(trim(both as_loan_type)) = 'NORM' then
  select  sum(case length(trim(both sc_rep_mem_share_loan_bal.norm_contract)) when 9  then 1 when 10 then 1 else 0 end )
  into STRICT    li_count
  from    sc_rep_mem_share_loan_bal
  where (member_group_no = as_group_no)
  and (client_id = as_cilent_id);
 elsif  upper(trim(both as_loan_type)) = 'EMER' then
  select  sum(case length(trim(both sc_rep_mem_share_loan_bal.emer_contract)) when 9  then 1 when 10 then 1 else 0 end )
  into STRICT    li_count
  from    sc_rep_mem_share_loan_bal
  where (member_group_no = as_group_no)
  and (client_id = as_cilent_id);
 end if;


return   li_count;

exception when others then CALL spa_dberror('FPA_TEL_C_CONNO_BY_SHLN_ATDATE');return null;
END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpa_tel_c_conno_by_shln_atdate (as_group_no char,as_cilent_id char,as_loan_type char) FROM PUBLIC;

