-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpa_kep_mem_bank_acc_no (as_memno char) RETURNS varchar AS $body$
DECLARE

  ls_return varchar(30);

BEGIN
  select  bank_acc_no  into STRICT ls_return
  from    sc_mem_m_member_bank_accno
  where (paid_dividen = '1')
  and (membership_no = as_memno);


return  ls_return;
exception
when no_data_found then return null;
when others then CALL spa_dberror('FPA_KEP_MEM_BANK_ACC_NO');return null;
END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpa_kep_mem_bank_acc_no (as_memno char) FROM PUBLIC;

