-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpa_sum_lon_bal_by_pcode (as_pcode char,as_lcode char,adt_atdate sc_lon_m_loan_card.last_calcint_date%type) RETURNS bigint AS $body$
DECLARE

  ldc_value bigint;

BEGIN
        select sum(pka_com_function.fp_lon_get_balance_atdate(sc_lon_m_loan_card.loan_contract_no,sc_lon_m_loan_card.last_calcint_date)) into STRICT ldc_value
        from sc_lon_m_loan_card
            ,sc_lon_m_rule
            ,sc_mem_m_ucf_member_group
            ,sc_mem_m_ucf_province
        where (sc_lon_m_loan_card.loan_type = sc_lon_m_rule.loan_type)
        and (Rpad(pka_com_function.fp_get_member_group(sc_lon_m_loan_card.membership_no),15) = sc_mem_m_ucf_member_group.member_group_no)
        and (sc_mem_m_ucf_member_group.province_code = sc_mem_m_ucf_province.province_code)
        and (sc_lon_m_loan_card.principal_balance > 0)
        and (trim(both sc_mem_m_ucf_province.province_code) = as_pcode)
        and (trim(both sc_lon_m_rule.loan_group_code) = as_lcode)
        and (sc_lon_m_loan_card.last_calcint_date = adt_atdate);
  return coalesce(ldc_value,0);

exception
when no_data_found then return 0;
when others then CALL spa_dberror('fpa_sum_lon_bal_by_pcode');

end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpa_sum_lon_bal_by_pcode (as_pcode char,as_lcode char,adt_atdate sc_lon_m_loan_card.last_calcint_date%type) FROM PUBLIC;

