-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpa_tel_receipt_lon_int (as_vno char,ai_vseq integer) RETURNS bigint AS $body$
DECLARE

  ls_ref_docno sc_fin_vourcher_detail.ref_docno%type;
  li_ref_seqno sc_fin_vourcher_detail.ref_seqno%type;
  ldc_interest_amount bigint;

BEGIN
  -- ดอกเบี้ยเงินกู้ที่จ่าย เพื่อออกใบเสร็จจาก vourcher
  select ref_docno,ref_seqno
  into STRICT ls_ref_docno,li_ref_seqno
  from sc_fin_vourcher_detail
  where (seq_no = ai_vseq)
  and (vourcher_no = as_vno);

  select interest_amount into STRICT  ldc_interest_amount
  from sc_com_m_receipt_item
  where (seq_no = li_ref_seqno)
  and (receipt_no = ls_ref_docno);

  return coalesce(ldc_interest_amount,0);
exception when others then return 0;
end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpa_tel_receipt_lon_int (as_vno char,ai_vseq integer) FROM PUBLIC;

