-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpa_lon_count_memno_all_year (as_group_no char,ai_year integer,as_lon_grp_type char) RETURNS bigint AS $body$
DECLARE

  li_count integer;
  ldt_bdate timestamp(0);
  ldt_edate timestamp(0);

BEGIN
  begin
    select  start_date , end_date
    into STRICT    ldt_bdate  , ldt_edate
    from    sc_lon_m_close_year
    where (lon_year = ai_year);
  exception when others then CALL spa_dberror('กรุณาตรวจสอบ sc_lon_m_close_year');
  end;
  select  count(distinct sc_mem_m_membership_registered.membership_no)
  into STRICT    li_count
  from    sc_lon_m_contract
      ,   sc_lon_m_rule
      ,   sc_mem_m_membership_registered
      ,   sc_mem_m_ucf_member_group

  where (sc_mem_m_membership_registered.membership_no = sc_lon_m_contract.membership_no)
  and (sc_lon_m_rule.loan_type = sc_lon_m_contract.loan_type)
  and (sc_mem_m_ucf_member_group.member_group_no = sc_mem_m_membership_registered.member_group_no)
  and (sc_lon_m_rule.loan_group_code = as_lon_grp_type)
  and (sc_mem_m_ucf_member_group.member_group_no = as_group_no)
  and (sc_lon_m_contract.begining_of_contract between ldt_bdate and ldt_edate)
;

return  li_count;

exception when others then CALL spa_dberror('fpa_lon_count_memno_all_year');return null;
END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpa_lon_count_memno_all_year (as_group_no char,ai_year integer,as_lon_grp_type char) FROM PUBLIC;

