-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpa_com_rec_money_thai (as_recno char) RETURNS varchar AS $body$
DECLARE

ls_money_thai varchar(1000);
ldc_amt bigint;

BEGIN
  ls_money_thai := '';
  SELECT sum( sc_com_m_receipt_item.item_amount  ) into STRICT ldc_amt
    FROM sc_com_m_receipt_item
   WHERE sc_com_m_receipt_item.receipt_no =  as_recno;

  ls_money_thai  := pka_com_function.fp_get_moneythai( ldc_amt );

return   trim(both ls_money_thai);
exception when others then CALL spa_dberror('FPA_COM_REC_MONEY_THAI');return null;
END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpa_com_rec_money_thai (as_recno char) FROM PUBLIC;

