-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpa_get_count_blacklist (as_conno char) RETURNS varchar AS $body$
DECLARE

li_count integer;

BEGIN
  select	count(receive_description) into STRICT li_count
  from		sc_kep_t_monthly_receive_det
  where	  unkeep_principal_of_loan	>	0
  and		  receive_description	=	trim(both as_conno)
;
  return li_count;
end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpa_get_count_blacklist (as_conno char) FROM PUBLIC;

