-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpa_gget_province_by_payment (as_bank char ,ai_sq bigint ,adt_date timestamp(0)) RETURNS varchar AS $body$
DECLARE

  ls_province sc_mem_m_ucf_province.province_name%type;

BEGIN
  select sc_mem_m_ucf_province.province_name into STRICT ls_province
		from sc_fin_m_bank_payment payment
			,sc_mem_m_membership_registered
			,sc_mem_m_ucf_member_group
			,sc_mem_m_ucf_province
		where (payment.membership_no = sc_mem_m_membership_registered.membership_no)
		and (sc_mem_m_membership_registered.member_group_no = sc_mem_m_ucf_member_group.member_group_no)
		and (sc_mem_m_ucf_member_group.province_code = sc_mem_m_ucf_province.province_code)
		and (payment.bank_fin = as_bank)
		and (payment.seq_no = ai_sq)
		and (payment.receipt_date = adt_date);
  return trim(both ls_province);
exception
when no_data_found then return null;
when too_many_rows then return null;
when others then CALL spa_dberror('fpa_gget_province_by_payment');
end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpa_gget_province_by_payment (as_bank char ,ai_sq bigint ,adt_date timestamp(0)) FROM PUBLIC;

