-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpa_lon_req_refinance_amt (as_reqno char) RETURNS bigint AS $body$
DECLARE

  ldc_amount bigint;

BEGIN
  select sum(coalesce(principal_balance_of_loan,0)) + sum(coalesce(interest_amount,0)) into STRICT ldc_amount
  from sc_lon_m_loan_history
  where loan_requestment_no = as_reqno;
  return coalesce(ldc_amount,0);
  exception
  when no_data_found then return 0;
  when others then CALL spa_dberror('fpa_lon_req_refinance_amt(เลขที่คำขอ('||trim(both as_reqno)||'))');
end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpa_lon_req_refinance_amt (as_reqno char) FROM PUBLIC;

