-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpb_get_fund_return_amount (AS_REQNO CHAR) RETURNS bigint AS $body$
DECLARE

  ldc_fund_ret bigint;
  ldc_fund_new  bigint;
  ldc_return   bigint;

BEGIN

  select coalesce(sum(fund_real),0)
  into STRICT ldc_fund_ret
  from sc_lon_m_req_fund_ret
  where loan_requestment_no = AS_REQNO
  and fund_ret > 0;

  select coalesce(sum(fund_new),0)
  into STRICT ldc_fund_new
  from sc_lon_m_req_fund_new
  where loan_requestment_no = AS_REQNO;

  ldc_return := ldc_fund_new - ldc_fund_ret;

  return nvn(ldc_return);
end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpb_get_fund_return_amount (AS_REQNO CHAR) FROM PUBLIC;

