-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpb_fin_get_journal_date (as_voucher char ) RETURNS timestamp(0) AS $body$
DECLARE

ldtm_jourdate sc_fin_vourcher_head.journal_date%type;

BEGIN
  SELECT sc_fin_vourcher_head.journal_date
  INTO STRICT   ldtm_jourdate
    FROM sc_fin_vourcher_head
   WHERE sc_fin_vourcher_head.vourcher_no = as_voucher;

  RETURN ldtm_jourdate;
END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpb_fin_get_journal_date (as_voucher char ) FROM PUBLIC;

