-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpb_tel_loan_history_in_rec_a ( as_conno char , as_item_type char ) RETURNS bigint AS $body$
DECLARE

ldc_total_loan  sc_com_m_receipt_item.principal_amount% TYPE;


BEGIN

    SELECT sum( sc_com_m_receipt_item.item_amount )
    INTO STRICT  ldc_total_loan
    FROM  sc_com_m_receipt,
          sc_com_m_receipt_item,
          sc_lon_m_contract,
          sc_lon_m_rule
    WHERE ( sc_com_m_receipt_item.receipt_no = sc_com_m_receipt.receipt_no ) and (  sc_lon_m_contract.receipt_no = sc_com_m_receipt.receipt_no ) and ( sc_com_m_receipt_item.loan_type = sc_lon_m_rule.loan_type ) and ( sc_com_m_receipt.receipt_status = '0' ) AND (  sc_com_m_receipt_item.item_type_id = as_item_type ) and ( sc_lon_m_contract.loan_contract_no = as_conno );

        if coalesce(ldc_total_loan::text, '') = '' then ldc_total_loan := 0;end if;

return ldc_total_loan;

END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpb_tel_loan_history_in_rec_a ( as_conno char , as_item_type char ) FROM PUBLIC;

