-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpb_get_age_day (adt_date_from timestamp(0), adt_date_to timestamp(0)) RETURNS varchar AS $body$
DECLARE

  li_age_year integer;
  li_age_month integer;
  li_age_day integer;
  ls_age varchar(50);

BEGIN
  select date_trunc(0, pka_lon_reqsrv.fp_calc_install_m_live(adt_date_from,adt_date_to) / 12) as live_age_year
        ,pka_srv_datetime.fp_MonthsAfter(adt_date_from,adt_date_to)
        - (date_trunc(0, pka_lon_reqsrv.fp_calc_install_m_live(adt_date_from,adt_date_to) / 12) * 12) as live_age_month
        ,(case
          when   to_char(adt_date_to,'dd')  >= to_char(adt_date_from,'dd') then
            adt_date_to - to_date(to_char(adt_date_from,'dd') || to_char(adt_date_to,'/mm/yyyy')  ,'dd/mm/yyyy')
          else
            adt_date_to - to_date(to_char(adt_date_from,'dd') || to_char(adt_date_to + -1*'1 month'::interval,'mm/yyyy'),'dd/mm/yyyy')
        end ) as live_age_day
  into STRICT li_age_year,li_age_month,li_age_day
;
  ls_age := NVN(li_age_year)||' ปี '||NVN(li_age_month)||' เดือน '||NVN(li_age_day)||' วัน ';
  return ls_age;
exception WHEN OTHERS then CALL spa_dberror('FPB_GET_AGE_DAY');return ' ';
END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpb_get_age_day (adt_date_from timestamp(0), adt_date_to timestamp(0)) FROM PUBLIC;

