-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpb_tel_get_loan_approve (as_conno text) RETURNS bigint AS $body$
DECLARE

ldc_approve sc_lon_m_contract.loan_approve_amount%type;


BEGIN
    SELECT sc_lon_m_contract.loan_approve_amount
    INTO STRICT ldc_approve
    FROM sc_lon_m_contract
   WHERE ( sc_lon_m_contract.loan_contract_no = as_conno );
  if coalesce(ldc_approve::text, '') = '' then ldc_approve := 0;end if;

  RETURN ldc_approve;
END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpb_tel_get_loan_approve (as_conno text) FROM PUBLIC;

