-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpb_kep_get_count_rec (adt_date timestamp(0) , as_arg CHAR , as_case CHAR ) RETURNS bigint AS $body$
DECLARE

   lcur_select REFCURSOR;

  cur_data CURSOR FOR
  SELECT count(membership_no) as c_count
  from sc_kep_t_monthly_receive;
  type tabrowi_data is table of cur_data%rowtype index by integer;ltabrowi_data tabrowi_data;
  ldc_count  bigint;
  ls_select varchar(4000);
  ls_date varchar(10);

BEGIN
  --ยาสูบ ต้องการจำนวนสมาชิกที่ออกใบเสร็จ  มีรายงาน สี่ตัว
  --GL ตามกลุ่มหนี้ Group_loan
  --GP ตามกลุ่มงาน  group_positionl
  --GR ตามกลุ่มของกลุ่มงาน  group_report
  --GC หน่วยคุม  Group_control
  ls_select := 'SELECT 	count( distinct ( sc_kep_t_monthly_receive.membership_no ) )
                FROM 		sc_kep_t_monthly_receive ,
                    sc_mem_m_membership_registered  ,
                    sc_mem_m_member_work_info,
                    sc_mem_m_ucf_member_group,
                    sc_mem_m_ucf_member_type,
                    sc_mem_m_ucf_group_position,
                    sc_mem_m_ucf_coop_control
                WHERE  	( sc_kep_t_monthly_receive.membership_no = sc_mem_m_membership_registered.membership_no ) and
                      ( sc_mem_m_membership_registered.membership_no = sc_kep_t_monthly_receive.membership_no ) and
                      ( sc_mem_m_member_work_info.membership_no = sc_mem_m_membership_registered.membership_no ) and
                      ( sc_mem_m_ucf_member_group.member_group_no = sc_kep_t_monthly_receive.member_group_no ) and
                      ( sc_mem_m_ucf_member_type.mem_type_code = sc_mem_m_membership_registered.mem_type ) and
                      ( sc_mem_m_ucf_group_position.group_position = sc_mem_m_member_work_info.group_position ) and
                      ( sc_mem_m_ucf_member_group.control_id = sc_mem_m_ucf_coop_control.control_id )  ';

      ls_date := to_char( adt_date , 'dd/mm/yyyy' );
      --ls_sql  := ls_sql||"where( receipt_date = to_date('||trim( ls_date )||','dd/mm/yyyy') )";
      ls_select := ls_select ||' and  sc_kep_t_monthly_receive.receipt_date = to_date('''||trim(both ls_date )||''',''dd/mm/yyyy'') ';


    case upper( trim(both as_case))
    when 'GL' then   --group_loan
      ls_select := ls_select || '  and  sc_mem_m_ucf_member_group.group_loan  =  '|| trim(both as_arg );
      ls_select := ls_select || '  group by   sc_mem_m_ucf_member_group.group_loan    ';
    when 'GP' then  -- group_position
      ls_select := ls_select || ' and  sc_mem_m_ucf_group_position.group_position  ='|| trim(both as_arg );
      ls_select := ls_select || '  group by   sc_mem_m_ucf_group_position.group_position    ';
    when 'GR' then  -- group_report
      ls_select := ls_select || 'and  sc_mem_m_ucf_group_position.group_report  = '  ||  trim(both as_arg );
      ls_select := ls_select || '  group by   sc_mem_m_ucf_group_position.group_report    ';
    when 'GC' then   --group_control
      ls_select := ls_select + 'and  sc_mem_m_ucf_member_group.member_group_control  ='||as_arg;
      ls_select := ls_select || '  group by   sc_mem_m_ucf_member_group.member_group_control    ';
    else
      null;
    end case;

    open lcur_select for EXECUTE ls_select;fetch lcur_select bulk collect into ltabrowi_data;close lcur_select;

    ldc_count := coalesce(ltabrowi_data[1].c_count,0);

    RETURN ldc_count;
END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpb_kep_get_count_rec (adt_date timestamp(0) , as_arg CHAR , as_case CHAR ) FROM PUBLIC;

