-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpb_get_loan_at_date_v2 (as_memno char,as_loan_group char, adt_date timestamp(0)) RETURNS bigint AS $body$
DECLARE

ldc_loan bigint := 0;
ldc_loan2 bigint := 0;
cur_memloan CURSOR FOR
    SELECT	sc_lon_m_loan_card_detail.principal_balance
    from		sc_lon_m_loan_card_detail ,
          sc_lon_m_loan_card ,
          sc_lon_m_contract ,
          sc_lon_m_rule
    where ( sc_lon_m_loan_card.loan_contract_no = sc_lon_m_loan_card_detail.loan_contract_no )
    and ( sc_lon_m_contract.loan_contract_no = sc_lon_m_loan_card.loan_contract_no )
    and ( sc_lon_m_rule.loan_type = sc_lon_m_contract.loan_type )
    and ( sc_lon_m_loan_card.membership_no = as_memno )
    and ( sc_lon_m_rule.loan_group_code = as_loan_group )
    and ( sc_lon_m_loan_card_detail.loan_payment_date <= adt_date )
    and ( sc_lon_m_contract.loan_type <> 'สร' )
    and ( sc_lon_m_loan_card_detail.item_type_code not in ( 'IR' , 'RI' ) )
    order by sc_lon_m_contract.begining_of_contract desc ,
          sc_lon_m_loan_card_detail.loan_payment_date desc ,
          sc_lon_m_loan_card_detail.seq_no desc	;

cur_memloan2 CURSOR FOR
    SELECT	sc_lon_m_loan_card_detail.principal_balance
    from		sc_lon_m_loan_card_detail ,
          sc_lon_m_loan_card ,
          sc_lon_m_contract ,
          sc_lon_m_rule
    where ( sc_lon_m_loan_card.loan_contract_no = sc_lon_m_loan_card_detail.loan_contract_no )
    and ( sc_lon_m_contract.loan_contract_no = sc_lon_m_loan_card.loan_contract_no )
    and ( sc_lon_m_rule.loan_type = sc_lon_m_contract.loan_type )
    and ( sc_lon_m_loan_card.membership_no = as_memno )
    and ( sc_lon_m_rule.loan_group_code = as_loan_group )
    and ( sc_lon_m_contract.loan_type = 'สร' )
    and ( sc_lon_m_loan_card_detail.loan_payment_date <= adt_date )
    and ( sc_lon_m_loan_card_detail.item_type_code not in ( 'IR' , 'RI' ) )
    order by sc_lon_m_contract.begining_of_contract desc ,
          sc_lon_m_loan_card_detail.loan_payment_date desc ,
          sc_lon_m_loan_card_detail.seq_no desc	;
  type tabrowi_data is table of cur_memloan%rowtype index by integer;ltabrowi_data tabrowi_data;
  type tabrowi_data2 is table of cur_memloan2%rowtype index by integer;ltabrowi_data2 tabrowi_data2;

  li_count integer;

BEGIN
  open cur_memloan;fetch cur_memloan bulk collect into ltabrowi_data;close cur_memloan;
  li_count := ltabrowi_data.count;
  if li_count > 0 then
    ldc_loan := ltabrowi_data[1].principal_balance;
  end if;
  if as_loan_group = '02' then
    open cur_memloan2;fetch cur_memloan2 bulk collect into ltabrowi_data2;close cur_memloan2;
    li_count := ltabrowi_data2.count;
    if li_count > 0 then
      ldc_loan2 := ltabrowi_data2[1].principal_balance;
    end if;
  end if;
  return ldc_loan + ldc_loan2;
end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpb_get_loan_at_date_v2 (as_memno char,as_loan_group char, adt_date timestamp(0)) FROM PUBLIC;

