-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpb_get_collused_amount_sum (as_memno text ) RETURNS bigint AS $body$
DECLARE

  cur_data CURSOR FOR
  SELECT  FPB_GET_COUNT_COLL(sc_lon_m_contract.loan_contract_no) as count_coll ,
          sc_lon_m_loan_card.principal_balance - ( sc_mem_m_share_mem.share_stock * sc_lon_m_coll_rule.percent_shareperloan_drop ) as used_amount
  from    sc_lon_m_contract_coll,
          sc_lon_m_contract,   
          sc_lon_m_loan_card  ,
          sc_mem_m_share_mem	,
          sc_lon_m_coll_rule  
   where ( sc_lon_m_contract.loan_contract_no = sc_lon_m_contract_coll.loan_contract_no )  
   and ( sc_lon_m_loan_card.loan_contract_no = sc_lon_m_contract.loan_contract_no )
   and ( sc_lon_m_loan_card.loan_type = sc_lon_m_coll_rule.loan_type )    
   and ( sc_mem_m_share_mem.membership_no  = sc_lon_m_contract.membership_no)
   and ( sc_lon_m_contract_coll.ref_own_no = trim(both as_memno) )
   and ( sc_lon_m_contract_coll.collateral_type_code = '01' )
   and ( sc_lon_m_loan_card.principal_balance > 0 )
   and ( sc_lon_m_contract_coll.status = '0' )
   and ( sc_mem_m_share_mem.share_stock * sc_lon_m_coll_rule.percent_shareperloan_drop < sc_lon_m_loan_card.principal_balance );
type tabrow_data is table of cur_data%rowtype index by integer;

  ltabrow_data tabrow_data;
  li_count  integer;
  ldc_used_amount bigint;
  ldc_used_coll_amount bigint := 0;
  li_count_coll integer;
BEGIN

     open cur_data;fetch cur_data bulk collect INTO ltabrow_data;close cur_data;
      li_count := ltabrow_data.count;

      for i in 1..  li_count LOOP
        ldc_used_amount := ltabrow_data[i].used_amount /  ltabrow_data[i].count_coll;
        ldc_used_coll_amount := ldc_used_coll_amount + ldc_used_amount;
      end loop;

      if coalesce(ldc_used_coll_amount::text, '') = '' then ldc_used_coll_amount := 0;end if;

    return ldc_used_coll_amount;
exception when others then return 0;

end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpb_get_collused_amount_sum (as_memno text ) FROM PUBLIC;

