-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpb_get_loan_amount (as_loan_no text) RETURNS bigint AS $body$
DECLARE

  ldc_loan_period_amount bigint;

BEGIN
  select period_payment_amount into STRICT ldc_loan_period_amount  from sc_lon_m_contract where trim(both loan_contract_no) = trim(both as_loan_no);

  return ldc_loan_period_amount;
exception WHEN OTHERS then CALL spa_dberror('fpb_get_loan_amount : ไม่พบเลขที่สัญญา '|| as_loan_no);return ' ';
END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpb_get_loan_amount (as_loan_no text) FROM PUBLIC;

