-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpb_mem_province (as_memno char) RETURNS varchar AS $body$
DECLARE

  ls_rc varchar(100);

BEGIN

  select  trim(both mp.province_code)
  /*trim(mp.province_code)||'-'||trim(mp.shot_name)*/

  into STRICT ls_rc
  from sc_mem_m_membership_registered mb
      , sc_mem_m_ucf_member_group mg
      , sc_mem_m_ucf_province mp
  where mb.membership_no = as_memno
  and mb.member_group_no = mg.member_group_no
  and mg.province_code = mp.province_code;

  return trim(both ls_rc);


exception when others then return ' ';
end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpb_mem_province (as_memno char) FROM PUBLIC;

