-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpb_get_bank_fin_name ( as_bank_fin text) RETURNS varchar AS $body$
DECLARE

ls_bank_name sc_fin_m_bank.bank_name% TYPE;

BEGIN

  select bank_name
  into STRICT   ls_bank_name
  from   sc_fin_m_bank
  where bank_fin = as_bank_fin
;

  return trim(both ls_bank_name);
end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpb_get_bank_fin_name ( as_bank_fin text) FROM PUBLIC;

