-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpb_tel_get_loan_history_real ( as_reqno char , as_type char ) RETURNS bigint AS $body$
DECLARE

ldc_bal  sc_lon_m_loan_history.principal_balance_of_loan%type;
ldc_int  sc_lon_m_loan_history.interest_amount%type;
ldc_pend sc_lon_m_loan_card.pending_amount%type;

BEGIN
    SELECT  sum( sc_lon_m_loan_card.principal_balance ) ,
            sum( sc_lon_m_loan_history.interest_amount ),
            sum( sc_lon_m_loan_card.pending_amount )
    INTO STRICT ldc_bal  , ldc_int
 ,ldc_pend   FROM sc_lon_m_loan_request,
         sc_lon_m_loan_card,
         sc_lon_m_loan_history,
         sc_lon_m_rule
   WHERE ( sc_lon_m_loan_history.loan_contract_no = sc_lon_m_loan_card.loan_contract_no ) and ( sc_lon_m_loan_history.loan_requestment_no = sc_lon_m_loan_request.loan_requestment_no ) and ( sc_lon_m_rule.loan_type = sc_lon_m_loan_card.loan_type ) and ( sc_lon_m_loan_history.clear_target = '1'  ) and (sc_lon_m_loan_request.loan_requestment_no = as_reqno);
    if coalesce(ldc_bal::text, '') = '' then ldc_bal := 0;end if;
    if coalesce(ldc_int::text, '') = '' then ldc_int := 0;end if;
    if coalesce(ldc_pend::text, '') = '' then ldc_pend := 0;end if;


   case trim(both as_type )
   when 'real' THEN
      return ldc_bal;
   when 'pending' THEN
      ldc_bal := ldc_bal - ldc_pend;
      return ldc_bal;
   else
      return ldc_bal;
   end case;


END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpb_tel_get_loan_history_real ( as_reqno char , as_type char ) FROM PUBLIC;

