-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpb_kep_get_lon_blacklist_desc (as_conno char) RETURNS varchar AS $body$
DECLARE

cur_data CURSOR FOR
  SELECT sc_kep_t_monthly_receive_det.receive_year,
         sc_kep_t_monthly_receive_det.receive_month
  FROM sc_kep_t_monthly_receive_det
  WHERE ( sc_kep_t_monthly_receive_det.unkeep_money_amount	>	0) and ( trim(both sc_kep_t_monthly_receive_det.receive_description)	=	trim(both as_conno));
type tabrow_data is table of cur_data%rowtype index by integer;
ltabrow_data tabrow_data;

li_count  integer;
ldt_date  timestamp(0);
ls_date varchar(200);
BEGIN
  open cur_data;fetch cur_data bulk collect INTO ltabrow_data;close cur_data;
  li_count := ltabrow_data.count;
  for i in 1..  li_count LOOP
    ldt_date := to_date('1/'||ltabrow_data[i].receive_month::text||'/'||ltabrow_data[i].receive_year::text,'dd/mm/yyyy');
    ls_date  := trim(both ls_date)||','|| pka_com_function.fp_get_thaidate(ldt_date,'monyy');
  end loop;
  if  length(trim(both ls_date)) > 0 then
    ls_date  := substr(trim(both ls_date),2,length(trim(both ls_date))-1);
  end if;
  return ls_date;
end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpb_kep_get_lon_blacklist_desc (as_conno char) FROM PUBLIC;

