-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpb_fin_get_money_agent_amount ( as_agentno sc_fin_money_agent.agent_no%type , ai_item sc_fin_money_agent.item_no%type ) RETURNS bigint AS $body$
DECLARE

  ldc_paid bigint;

BEGIN
  -- ใช้ที่ฟอร์มใบสำคัญจ่ายค่าตอบแทนหน่วยงาน ( rxForm )
  select sum(coalesce(sc_fin_money_agent.money_return,0))into ldc_paid
  from sc_fin_money_agent ,
   		 sc_fin_money_agent_det ,
   		 sc_fin_vourcher_head
  where sc_fin_vourcher_head.cancel_status ='0'     
  and   sc_fin_vourcher_head.post_journal = '1'
  and   sc_fin_vourcher_head.vourcher_no = sc_fin_money_agent_det.voucher_no 
  and   sc_fin_money_agent.agent_no = sc_fin_money_agent_det.agent_no
  and   sc_fin_money_agent.item_no = sc_fin_money_agent_det.item_no
  and   sc_fin_money_agent_det.item_type != 'EN'
  and   sc_fin_money_agent_det.status = '0'
  and   sc_fin_money_agent_det.agent_no = as_agentno
  and   sc_fin_vourcher_head.journal_date = FPB_FIN_GET_MONEY_AGENT_DATE( as_agentno , ai_item );

  return  coalesce(ldc_paid,0);

END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpb_fin_get_money_agent_amount ( as_agentno sc_fin_money_agent.agent_no%type , ai_item sc_fin_money_agent.item_no%type ) FROM PUBLIC;

