-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpb_get_dep_item_name ( as_dep_itemtype text ) RETURNS varchar AS $body$
DECLARE

ls_dep_item_name sc_dep_m_ucf_dep_item_type.deposit_item_description% TYPE;

BEGIN
  select deposit_item_description
  into STRICT   ls_dep_item_name
  from   sc_dep_m_ucf_dep_item_type
  where  deposit_item_type = as_dep_itemtype
;

  return trim(both ls_dep_item_name);
end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpb_get_dep_item_name ( as_dep_itemtype text ) FROM PUBLIC;

