-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpb_acc_get_begin (ai_year bigint ,as_accid char ) RETURNS bigint AS $body$
DECLARE

ldc_begin sc_acc_m_account_begin.balance_begin%type;

BEGIN

    select  sum( balance_begin )
    into STRICT    ldc_begin
    from    sc_acc_m_account_begin
    where   account_year  = ai_year
    and     account_id    = as_accid;

   if coalesce(ldc_begin::text, '') = '' then ldc_begin := 0;end if;
  RETURN ldc_begin;
END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpb_acc_get_begin (ai_year bigint ,as_accid char ) FROM PUBLIC;

