-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpb_get_monthly_receive_status (as_memno char ,ai_year integer ,ai_month integer ,as_keeptype char ,as_conno char) RETURNS char AS $body$
DECLARE

li_count integer;
ldc_amount  bigint;


BEGIN

      select	sc_kep_t_monthly_receive_det.unkeep_money_amount
      into STRICT		ldc_amount
      from		sc_kep_t_monthly_receive_det
      where	sc_kep_t_monthly_receive_det.membership_no = as_memno
      and		sc_kep_t_monthly_receive_det.receive_year = ai_year
      and		sc_kep_t_monthly_receive_det.receive_month = ai_month
      and		sc_kep_t_monthly_receive_det.keeping_type_code = as_keeptype
      and		sc_kep_t_monthly_receive_det.unkeep_money_amount > 0
      and		trim(both sc_kep_t_monthly_receive_det.receive_description) = trim(both as_conno);

    return ldc_amount;
  exception when others then return 0;

end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpb_get_monthly_receive_status (as_memno char ,ai_year integer ,ai_month integer ,as_keeptype char ,as_conno char) FROM PUBLIC;

