-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpb_get_share_operate_date ( as_memno sc_mem_m_share_holding_detail.membership_no%type , ai_seqno sc_mem_m_share_holding_detail.seq_no%type ) RETURNS timestamp(0) AS $body$
DECLARE

  ls_item_type sc_mem_m_share_holding_detail.item_type%type;
  ldtm_operate_date sc_mem_m_share_holding_detail.operate_date%type;
  ldtm_entry_date sc_mem_m_share_holding_detail.entry_date%type;
  ldtm_operate_return timestamp(0);

BEGIN

    select  sc_mem_m_share_holding_detail.item_type ,
            sc_mem_m_share_holding_detail.entry_date ,
            sc_mem_m_share_holding_detail.operate_date
    into STRICT    ls_item_type , ldtm_entry_date ,  ldtm_operate_date
    from    sc_mem_m_share_holding_detail
    where   sc_mem_m_share_holding_detail.membership_no = as_memno
    and     sc_mem_m_share_holding_detail.seq_no = ai_seqno;

    --NIGHT 2020/12/18 KTM สอ.กทม. กรณีรหัสรายการ RM ,RC วันที่รายการให้ใช้ entry_date แสดงผล
    if pka.isCoop('KTM') = '1' then
        if ldtm_operate_date < '08/07/2020' then    -- สอ.กทม. วันที่ทำรายการ ก่อนเริ่มใช้ระบบใหม่ใช้ loan_payment_date จะถูกอยู่แล้ว
            ldtm_operate_return := ldtm_operate_date;
        else            
            if ls_item_type = 'RC' or ls_item_type = 'RM' then
                ldtm_operate_return := ldtm_entry_date;
            else
                ldtm_operate_return := ldtm_operate_date;
            end if;
        end if;
     else
        ldtm_operate_return := ldtm_operate_date;
     end if;
        
  return ldtm_operate_return;

END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpb_get_share_operate_date ( as_memno sc_mem_m_share_holding_detail.membership_no%type , ai_seqno sc_mem_m_share_holding_detail.seq_no%type ) FROM PUBLIC;

