-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpb_get_collused_amount (as_memno text ,as_conno text ) RETURNS bigint AS $body$
DECLARE

  ldc_used_amount bigint;
  ldc_used_coll_amount bigint;
  li_count_coll integer;

BEGIN

    select  FPB_GET_COUNT_COLL(sc_lon_m_contract.loan_contract_no),
            sc_lon_m_loan_card.principal_balance - ( sc_mem_m_share_mem.share_stock * sc_lon_m_coll_rule.percent_shareperloan_drop )
    into STRICT    li_count_coll,  ldc_used_amount
    from 	  sc_lon_m_contract_coll,
            sc_lon_m_contract,   
            sc_lon_m_loan_card  ,
            sc_mem_m_share_mem	,
            sc_lon_m_coll_rule
   where ( sc_lon_m_contract.loan_contract_no = sc_lon_m_contract_coll.loan_contract_no )  
   and ( sc_lon_m_loan_card.loan_contract_no = sc_lon_m_contract.loan_contract_no )
   and ( sc_lon_m_loan_card.loan_type = sc_lon_m_coll_rule.loan_type )    
   and ( sc_mem_m_share_mem.membership_no  = sc_lon_m_contract.membership_no)
   and ( sc_lon_m_contract_coll.ref_own_no = as_memno )
   and ( sc_lon_m_contract.loan_contract_no = as_conno )
   and ( sc_lon_m_contract_coll.collateral_type_code = '01' )
   and ( sc_lon_m_loan_card.principal_balance > 0 )
   and ( sc_lon_m_contract_coll.status = '0' )
   and ( sc_mem_m_share_mem.share_stock * sc_lon_m_coll_rule.percent_shareperloan_drop < sc_lon_m_loan_card.principal_balance );

   ldc_used_coll_amount := ldc_used_amount / li_count_coll;

  return ldc_used_coll_amount;
exception when others then return 0;

end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpb_get_collused_amount (as_memno text ,as_conno text ) FROM PUBLIC;

