-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpb_get_keep_return_month (as_groupno char ,ai_year integer ,ai_month integer) RETURNS bigint AS $body$
DECLARE

li_count integer;
ldc_amount  bigint;
ldt_bdate timestamp(0);
ldt_lastmonth timestamp(0);
ldc_return_share bigint;
ldc_return_loan bigint;
ldc_fee bigint;
ldt_daydate timestamp(0) :=to_date('01/'||ai_month::text||'/'||ai_year::text,'dd/mm/yyyy');

BEGIN
  ldt_lastmonth := PKA_SRV_DATETIME.fp_LastDayOfMonth(ldt_daydate);
  begin
    select	sum( sc_kep_t_monthly_receive_det.unkeep_money_amount)
    into STRICT		ldc_return_share
    from		sc_kep_t_monthly_receive,   sc_kep_t_monthly_receive_det
    where	sc_kep_t_monthly_receive.receive_year = sc_kep_t_monthly_receive_det.receive_year
    and		sc_kep_t_monthly_receive.receive_month = sc_kep_t_monthly_receive_det.receive_month
    and   sc_kep_t_monthly_receive.membership_no = sc_kep_t_monthly_receive_det.membership_no
    and		substr( sc_kep_t_monthly_receive_det.keeping_type_code ,1, 2 ) = 'MS'
    and		sc_kep_t_monthly_receive.receipt_status = '2'
    and ( sc_kep_t_monthly_receive.receive_year = ai_year )
    and ( sc_kep_t_monthly_receive.receive_month = ai_month )
    and ( trim(both sc_kep_t_monthly_receive.member_group_no) = as_groupno )    		;
    if coalesce(ldc_return_share::text, '') = '' or ldc_return_share < 0 then ldc_return_share := 0;end if;
  exception when others then ldc_return_share := 0;
  end;

  begin
    select	sum( sc_kep_t_monthly_receive_det.unkeep_money_amount)
    into STRICT		ldc_return_loan
    from		sc_kep_t_monthly_receive,   sc_kep_t_monthly_receive_det
    where	sc_kep_t_monthly_receive.receive_year = sc_kep_t_monthly_receive_det.receive_year
    and		sc_kep_t_monthly_receive.receive_month = sc_kep_t_monthly_receive_det.receive_month
    and   sc_kep_t_monthly_receive.membership_no = sc_kep_t_monthly_receive_det.membership_no
    and		substr( sc_kep_t_monthly_receive_det.keeping_type_code ,1, 2 ) = 'ML'
    and		sc_kep_t_monthly_receive.receipt_status = '2'
    and ( sc_kep_t_monthly_receive.receive_year = ai_year )
    and ( sc_kep_t_monthly_receive.receive_month = ai_month )
    and ( trim(both sc_kep_t_monthly_receive.member_group_no) = as_groupno ) 	;
    if coalesce(ldc_return_loan::text, '') = '' or ldc_return_loan < 0 then ldc_return_loan := 0;end if;
  exception when others then ldc_return_loan := 0;
  end;

  begin
    select	sum(sc_kep_t_monthly_receive_det.unkeep_money_amount)
    into STRICT    ldc_fee
    from		sc_kep_t_monthly_receive ,sc_kep_t_monthly_receive_det
    where	sc_kep_t_monthly_receive.receive_year = sc_kep_t_monthly_receive_det.receive_year
    and		sc_kep_t_monthly_receive.receive_month = sc_kep_t_monthly_receive_det.receive_month
    and   sc_kep_t_monthly_receive.membership_no = sc_kep_t_monthly_receive_det.membership_no
    and		substr( sc_kep_t_monthly_receive_det.keeping_type_code ,1, 2 ) = 'FE'
    and		sc_kep_t_monthly_receive.receipt_status = '2'
    and   sc_kep_t_monthly_receive.receive_year = ai_year
    and		sc_kep_t_monthly_receive.receive_month = ai_month
    and		trim(both sc_kep_t_monthly_receive.member_group_no) = as_groupno
;
    if coalesce(ldc_fee::text, '') = '' or ldc_fee < 0 then ldc_fee := 0;end if;
  exception when others then ldc_fee := 0;
  end;
  ldc_amount := ldc_return_share + ldc_return_loan + ldc_fee;
  return ldc_amount;
  exception when others then return 0;

end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpb_get_keep_return_month (as_groupno char ,ai_year integer ,ai_month integer) FROM PUBLIC;

