-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpb_fin_get_cut_verify_date (as_bank_fin sc_fin_m_bank_statement.bank_fin%type , ai_seq sc_fin_m_bank_statement.seq_no%type ) RETURNS timestamp(0) AS $body$
DECLARE


ldc_item_payable bigint;
ldtm_opdate timestamp(0);
ldtm_cut_date timestamp(0);


BEGIN

  begin
  select operate_date , item_payable
  into STRICT ldtm_opdate , ldc_item_payable
  from sc_fin_m_bank_statement
  where bank_fin = as_bank_fin
  and seq_no = ai_seq 
  and cancel_status ='0'
;

  exception    
  when others then CALL spa_dberror('FPB_FIN_GET_CUT_VERIFY_DATE');
  end;
  --ยังตัดไม่หมด ให้ตั้ง รตส ไว้ก่อน
  if ldc_item_payable > 0 then
   RETURN clock_timestamp();
  end if;

  begin
    select max( finance_date )
    into STRICT ldtm_cut_date
    from  sc_fin_m_bank_payment
    where bank_fin = as_bank_fin
    and   seq_no = ai_seq
    and   cancel_status ='0';
  exception
  when others then CALL spa_dberror('FPB_FIN_GET_CUT_VERIFY_DATE');
  end;

  RETURN ldtm_cut_date;


END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpb_fin_get_cut_verify_date (as_bank_fin sc_fin_m_bank_statement.bank_fin%type , ai_seq sc_fin_m_bank_statement.seq_no%type ) FROM PUBLIC;

