-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpb_get_keep_monthly_amount (as_memno char, ai_year bigint,ai_month bigint,ai_seq bigint) RETURNS bigint AS $body$
DECLARE

  ldc_amount bigint;

BEGIN
  select sum(money_amount)
  into STRICT  ldc_amount
  from sc_kep_t_monthly_receive_det
  where (membership_no = as_memno)
  and (receive_year = ai_year)
  and (receive_month = ai_month)
  and (seq_no = ai_seq);


  return coalesce(ldc_amount,0);
end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpb_get_keep_monthly_amount (as_memno char, ai_year bigint,ai_month bigint,ai_seq bigint) FROM PUBLIC;

