-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpb_get_cash_day_sum (as_branch_fin CHAR,adt_date timestamp(0),as_fin_book CHAR ,as_column CHAR) RETURNS bigint AS $body$
DECLARE

 ldc_sum_begin bigint;
 ldc_sum_receive bigint;
 ldc_sum_paid bigint;
 ldc_sum_forward bigint;
 ldc_return bigint;

BEGIN
     SELECT    sum(SC_FIN_JOURNAL_HEAD.BALANCE_BEGIN) ,
               sum( SC_FIN_JOURNAL_HEAD.TOTAL_RECEIVE),
               sum( SC_FIN_JOURNAL_HEAD.TOTAL_PAYMENT),
               sum( SC_FIN_JOURNAL_HEAD.BALANCE_FORWARD)
      into STRICT     ldc_sum_begin ,
               ldc_sum_receive ,
               ldc_sum_paid ,
               ldc_sum_forward
     FROM 		SC_FIN_JOURNAL_HEAD
     WHERE ( sc_fin_journal_head.journal_date = adt_date)
     AND ( sc_fin_journal_head.fin_book = as_fin_book )
     and ( sc_fin_journal_head.branch_fin = as_branch_fin )
     and ( sc_fin_journal_head.entry_fin = '63' )
;

    case as_column
      when 'BEGIN' then
        ldc_return := ldc_sum_begin;
      when 'RECEIVE'then
        ldc_return := ldc_sum_receive;
      when 'PAID' then
        ldc_return := ldc_sum_paid;
      when 'FORWARD'then
        ldc_return := ldc_sum_forward;
      else
        ldc_return := 0;
    end case;

    return ldc_return;
   EXCEPTION when no_data_found then RETURN 0;


end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpb_get_cash_day_sum (as_branch_fin CHAR,adt_date timestamp(0),as_fin_book CHAR ,as_column CHAR) FROM PUBLIC;

