-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpb_get_multi_dep_balance (as_line_str text) RETURNS bigint AS $body$
DECLARE

  ls_line_str varchar(1000);
  ls_dep_no varchar(1000);
  li_count integer;
  ldc_sum_balance bigint := 0;
BEGIN
  ls_line_str := as_line_str;
  li_count := (SELECT count(*) FROM regexp_matches(ls_line_str, ',', 'g') )+1;
  for i in 1..li_count loop
    if i <> li_count then
      ls_dep_no := substr(ls_line_str,1,instr(ls_line_str,',',1,1)-1);
    else
      ls_dep_no := replace(ls_line_str,',',null);
    end if;
    ldc_sum_balance := ldc_sum_balance +  pka_com_function.fp_get_deposit_balance(ls_dep_no);
    ls_line_str := replace(ls_line_str, (ls_dep_no||','), '');
  end loop;

  RETURN ldc_sum_balance;
exception WHEN OTHERS then CALL spa_dberror('FPB_GET_MULTI_DEP_BALANCE');
END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpb_get_multi_dep_balance (as_line_str text) FROM PUBLIC;

