-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpb_get_loan_emer2_by_date (adt_from timestamp(0), adt_to timestamp(0) ,as_group_no char,as_group_code char, al_count INOUT integer , OUT extra_param bigint) RETURNS record AS $body$
DECLARE


ldc_app_emer_after bigint;


BEGIN

select	sum( sc_lon_m_contract.loan_approve_amount ) ,
			count( sc_mem_m_membership_registered.membership_no )
into STRICT		ldc_app_emer_after , al_count
from		sc_lon_m_contract ,
			sc_lon_m_loan_card ,
			sc_lon_m_rule ,
			sc_mem_m_membership_registered ,
			sc_mem_m_ucf_member_group
where ( sc_lon_m_contract.loan_contract_no = sc_lon_m_loan_card.loan_contract_no )
and ( sc_mem_m_membership_registered.membership_no = sc_lon_m_loan_card.membership_no )
and ( sc_mem_m_ucf_member_group.member_group_no = sc_mem_m_membership_registered.member_group_no )
and ( sc_lon_m_contract.loan_type = sc_lon_m_rule.loan_type )
and ( sc_lon_m_contract.begining_of_contract between adt_from and adt_to )
and ( sc_lon_m_contract.loan_type = 'ฉ2' )
and ( sc_lon_m_rule.loan_group_code = as_group_code )
and ( sc_mem_m_ucf_member_group.member_group_no = as_group_no )
--and		( sc_mem_m_ucf_member_group.member_group_keeping <> '30' )
and ( sc_lon_m_contract.rec_rep_status = '1' )
and ( sc_lon_m_contract.create_loan_status = '1' )
and ( sc_lon_m_contract.loan_type <> 'สร' ) 	;


if coalesce(ldc_app_emer_after::text, '') = '' then
  ldc_app_emer_after := 0;
end if;
if coalesce(al_count::text, '') = '' then
  al_count := 0;
end if;
extra_param := ldc_app_emer_after;
RETURN;
exception when others then  extra_param := 0;  RETURN;

end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpb_get_loan_emer2_by_date (adt_from timestamp(0), adt_to timestamp(0) ,as_group_no char,as_group_code char, al_count INOUT integer , OUT extra_param bigint) FROM PUBLIC;

