-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpb_fin_get_money_agent_date ( as_agentno sc_fin_money_agent.agent_no%type , ai_item sc_fin_money_agent.item_no%type ) RETURNS timestamp(0) AS $body$
DECLARE

ldtm_jourdate sc_fin_vourcher_head.journal_date%type;
ls_return_status sc_fin_money_agent.return_status%type;
li_rkeep_year   sc_fin_money_agent.receive_year%type;
li_rkeep_month  sc_fin_money_agent.receive_month%type;

BEGIN
  begin
    select	return_status ,receive_year , receive_month
    into STRICT ls_return_status ,li_rkeep_year , li_rkeep_month 
    from 		sc_fin_money_agent
    where 	agent_no = as_agentno
    and 		item_no = ai_item;
  exception when no_data_found then CALL spa_dberror('E18:ไม่มีรายการรอจ่าย');
  end;
  case ls_return_status
  when '0' then
    --ยังไม่คืน
    RETURN null;
  when '1' then
    --ตัดจ่ายจากหน้าจอ จ่ายรอจ่ายคืน
      begin
          select sc_fin_vourcher_head.journal_date
          into STRICT ldtm_jourdate
          from sc_fin_vourcher_head
          ,sc_fin_money_agent_det
          where sc_fin_vourcher_head.cancel_status ='0'     
          and sc_fin_vourcher_head.post_journal = '1'
          and sc_fin_vourcher_head.vourcher_no = sc_fin_money_agent_det.voucher_no 
          and sc_fin_money_agent_det.item_type != 'EN'
          and sc_fin_money_agent_det.status = '0'
          and sc_fin_money_agent_det.agent_no = as_agentno
          and sc_fin_money_agent_det.item_no = ai_item
;
          exception 
          when no_data_found then  return null;
          when others then CALL spa_dberror('FPB_FIN_GET_MONEY_AGENT_DATE');
      end;
  else
    spa_dberror('Not in Case');
  end case;


  RETURN ldtm_jourdate;

END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpb_fin_get_money_agent_date ( as_agentno sc_fin_money_agent.agent_no%type , ai_item sc_fin_money_agent.item_no%type ) FROM PUBLIC;

