-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpb_get_loan_month_period_ar (as_code char, as_memno char,ai_year integer , ai_month integer , ai_seqno integer ) RETURNS varchar AS $body$
DECLARE


li_installment_no integer;
li_period integer;
li_rowcount integer;
ls_return varchar(20) := '';
ls_group_code char(2);
 lcur_select REFCURSOR;
cur_det CURSOR FOR SELECT sc_lon_m_contract.loan_installment_amount , sc_lon_m_contract.loan_contract_no , sc_kep_t_monthly_receive_det.period
    from  sc_lon_m_rule , sc_lon_m_contract , sc_kep_t_monthly_receive , sc_kep_t_monthly_receive_det  where 1 = 2;
type tabrowi_det is table of cur_det%rowtype index by integer;ltabrowi_det tabrowi_det;
ls_sql_select varchar(2000);
BEGIN
  if trim(both as_code) in ('404','405','411') then
    if as_code = '404' then
      ls_group_code := '01';
    elsif as_code = '405' then
      ls_group_code := '02';
    else
      ls_group_code := '03';
    end if;
    ls_return := '';
    ls_sql_select := 'select sc_lon_m_contract.loan_installment_amount , sc_lon_m_contract.loan_contract_no , sc_kep_t_monthly_receive_det.period
    from  sc_lon_m_rule , sc_lon_m_contract , sc_kep_t_monthly_receive , sc_kep_t_monthly_receive_det
    where sc_lon_m_rule.loan_type = sc_lon_m_contract.loan_type
    and   trim(sc_kep_t_monthly_receive_det.receive_description) = trim(sc_lon_m_contract.loan_contract_no)
    and   sc_kep_t_monthly_receive.receive_year = sc_kep_t_monthly_receive_det.receive_year
    and   sc_kep_t_monthly_receive.receive_month = sc_kep_t_monthly_receive_det.receive_month
    and   sc_kep_t_monthly_receive.membership_no = sc_kep_t_monthly_receive_det.membership_no
    and   sc_kep_t_monthly_receive.receive_year = '||ai_year::text||'
    and   sc_kep_t_monthly_receive.receive_month = '||ai_month::text||'
    and   sc_kep_t_monthly_receive.seq_no = '||ai_seqno::text||'
    and   sc_kep_t_monthly_receive.membership_no = '''|| as_memno || '''
    and   sc_lon_m_rule.loan_group_code = '''|| ls_group_code || '''
    order by sc_lon_m_rule.loan_group_code,sc_lon_m_contract.loan_type,sc_lon_m_contract.loan_contract_no';

    open lcur_select for EXECUTE ls_sql_select;
    fetch lcur_select bulk collect into ltabrowi_det;close lcur_select;
    li_rowcount := ltabrowi_det.count;
    for i in 1..li_rowcount loop
      li_installment_no := ltabrowi_det[i].loan_installment_amount;
      li_period := ltabrowi_det[i].period;
      ls_return := ls_return || right('000'||(li_installment_no-li_period::text),3);
    end loop;
  else
    select sc_kep_t_monthly_receive_det.period
    into STRICT  li_period
    from  sc_kep_t_monthly_receive , sc_kep_t_monthly_receive_det
    where sc_kep_t_monthly_receive.receive_year = sc_kep_t_monthly_receive_det.receive_year
    and   sc_kep_t_monthly_receive.receive_month = sc_kep_t_monthly_receive_det.receive_month
    and   sc_kep_t_monthly_receive.membership_no = sc_kep_t_monthly_receive_det.membership_no
    and   sc_kep_t_monthly_receive.receive_year = ai_year
    and   sc_kep_t_monthly_receive.receive_month = ai_month
    and   sc_kep_t_monthly_receive.seq_no = ai_seqno
    and   sc_kep_t_monthly_receive.membership_no = as_memno
    and   sc_kep_t_monthly_receive_det.keeping_type_code = 'MS00';
    ls_return :=  right('000000'||(li_period::text),3);
  end if;

  RETURN substr(rpad(ls_return,6,'0'),1,6);
  exception when others then CALL spa_dberror('FPB_GET_LOAN_MONTH_PERIOD_AR');
-- exception WHEN others then return ls_return ;
END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpb_get_loan_month_period_ar (as_code char, as_memno char,ai_year integer , ai_month integer , ai_seqno integer ) FROM PUBLIC;

