-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpb_get_loan_interest (as_conno char,from_date timestamp(0),to_date timestamp(0)) RETURNS bigint AS $body$
DECLARE

li_interest bigint;

BEGIN





select sum(interest_amout*(sign_status)*(-1))
into STRICT li_interest
from sc_lon_m_loan_card_detail , sc_lon_m_ucf_loan_card_item
where sc_lon_m_loan_card_detail.item_type_code = sc_lon_m_ucf_loan_card_item.item_type_code
and	loan_contract_no = as_conno
and	loan_payment_date between  from_date and to_date;






  return li_interest;

exception when others then return 0;
end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpb_get_loan_interest (as_conno char,from_date timestamp(0),to_date timestamp(0)) FROM PUBLIC;

