-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpb_cal_payloan_emer_grp_count (adt_from timestamp(0), adt_to timestamp(0) ,as_group_no char,as_group_code char ) RETURNS integer AS $body$
DECLARE


ldc_loan_approve_amount bigint;
ldc_app_emer_after bigint;
ll_count_app integer;
ll_count_app_af integer;

BEGIN
  begin
      select	count(sc_lon_m_contract.loan_type)
      into STRICT    ll_count_app
      from		sc_lon_m_contract ,
            sc_lon_m_loan_card ,
            sc_lon_m_rule ,
            sc_mem_m_membership_registered ,
            sc_mem_m_ucf_member_group
      where ( sc_lon_m_contract.loan_contract_no = sc_lon_m_loan_card.loan_contract_no )
      and ( sc_mem_m_membership_registered.membership_no = sc_lon_m_loan_card.membership_no )
      and ( sc_mem_m_ucf_member_group.member_group_no = sc_mem_m_membership_registered.member_group_no )
      and ( sc_lon_m_contract.loan_type = sc_lon_m_rule.loan_type )
      and ( sc_lon_m_contract.approve_date between adt_from and adt_to )
      and ( sc_lon_m_rule.loan_group_code = as_group_code )
      and ( sc_mem_m_ucf_member_group.member_group_no = as_group_no )
      and ( sc_lon_m_contract.rec_rep_status = '1' )
      and ( sc_lon_m_contract.create_loan_status = '1' )
      and ( sc_lon_m_contract.loan_type not in ('ฉ2','สร','ฉอ')) 	;

      if coalesce(ll_count_app::text, '') = '' then
        ll_count_app := 0;
      end if;
    exception when others then ll_count_app := 0;
  end;

  begin
      select	count( sc_mem_m_membership_registered.membership_no )
      into STRICT		ll_count_app_af
      from		sc_lon_m_contract ,
            sc_lon_m_loan_card ,
            sc_lon_m_rule ,
            sc_mem_m_membership_registered ,
            sc_mem_m_ucf_member_group
      where ( sc_lon_m_contract.loan_contract_no = sc_lon_m_loan_card.loan_contract_no )
      and ( sc_mem_m_membership_registered.membership_no = sc_lon_m_loan_card.membership_no )
      and ( sc_mem_m_ucf_member_group.member_group_no = sc_mem_m_membership_registered.member_group_no )
      and ( sc_lon_m_contract.loan_type = sc_lon_m_rule.loan_type )
      and ( sc_lon_m_contract.begining_of_contract between adt_from and adt_to )
      and ( sc_lon_m_contract.loan_type = 'ฉ2' )
      and ( sc_lon_m_rule.loan_group_code = as_group_code )
      and ( sc_mem_m_ucf_member_group.member_group_no = as_group_no )
      --and		( sc_mem_m_ucf_member_group.member_group_keeping <> '30' )
      and ( sc_lon_m_contract.rec_rep_status = '1' )
      and ( sc_lon_m_contract.create_loan_status = '1' )
      and ( sc_lon_m_contract.loan_type <> 'สร' ) 	;

      if coalesce(ll_count_app_af::text, '') = '' then
        ll_count_app_af := 0;
      end if;
  exception when others then ll_count_app_af := 0;
  end;
  ll_count_app_af := ll_count_app_af + ll_count_app;
return ll_count_app_af;
exception when others then  return  0;

end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpb_cal_payloan_emer_grp_count (adt_from timestamp(0), adt_to timestamp(0) ,as_group_no char,as_group_code char ) FROM PUBLIC;

