-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpb_up_total_int_re_maxseqno (ai_year bigint, ai_month bigint, as_memprior char, as_memno char, adc_allacumint bigint) RETURNS bigint AS $body$
DECLARE

  ldc_max_seqno   sc_kep_t_monthly_receive_det.receive_seq%type;
  li_year         sc_kep_t_monthly_receive.receive_year%type;
  li_month        sc_kep_t_monthly_receive.receive_month%type;
  ls_memprior     sc_kep_t_monthly_receive.membership_no%type;
  ls_memno        sc_kep_t_monthly_receive_det.membership_no%type;
  ldc_allacumint  sc_kep_t_monthly_receive.total_interest_value%type;

BEGIN

  li_year   := ai_year;
  li_month  := ai_month;
  ls_memprior := as_memprior;
  ls_memno    := as_memno;
  ldc_allacumint  := adc_allacumint;

  -- update ดอกเบี้ยสะสมให้คนเดิม
  if (ls_memprior IS NOT NULL AND ls_memprior::text <> '') or ls_memprior <> '' then
    update	sc_kep_t_monthly_receive 
    set		  total_interest_value	= ldc_allacumint
    where ( receive_year		= li_year ) 
    and ( receive_month	  = li_month )
    and ( membership_no	  = ls_memprior)
    and ( seq_no				  =	1	);
  end if;

  --ดึง seq_no ล่าสุดมา
  select	coalesce(max( receive_seq ), 0 )
  into STRICT		ldc_max_seqno
  from		sc_kep_t_monthly_receive_det
  where ( membership_no		  = ls_memno ) 
  and ( receive_year	    = li_year ) 
  and ( receive_month	    = li_month );

  return coalesce(ldc_max_seqno,0);
end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpb_up_total_int_re_maxseqno (ai_year bigint, ai_month bigint, as_memprior char, as_memno char, adc_allacumint bigint) FROM PUBLIC;

