-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpb_get_loan_request_clear (AS_REQNO CHAR , AS_LON_GROUP CHAR , AS_METHOD CHAR) RETURNS bigint AS $body$
DECLARE

  ldc_return bigint;
  ldc_prin  bigint;
  ldc_int   bigint;

BEGIN

	select sum(sc_lon_m_loan_history.PRINCIPAL_BALANCE_OF_LOAN) , sum(sc_lon_m_loan_history.interest_arrear) + sum(SC_LON_M_LOAN_HISTORY.INTEREST_AMOUNT)
	into STRICT	ldc_prin  , ldc_int
	from sc_lon_m_loan_history , sc_lon_m_loan_card , sc_lon_m_rule
	where sc_lon_m_loan_history.loan_contract_no = sc_lon_m_loan_card.loan_contract_no
  and   sc_lon_m_rule.loan_type = sc_lon_m_loan_card.loan_type
  and   sc_lon_m_rule.loan_group_code = as_lon_group
  and   sc_lon_m_loan_history.loan_requestment_no = AS_REQNO
  and   sc_lon_m_loan_history.clear_target = '1'
	;

if as_method = 'P' then
  ldc_return := ldc_prin;
else
  ldc_return := ldc_int;
end if;

  return nvn(ldc_return);
end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpb_get_loan_request_clear (AS_REQNO CHAR , AS_LON_GROUP CHAR , AS_METHOD CHAR) FROM PUBLIC;

