-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpb_tel_get_loan_period (as_conno text) RETURNS bigint AS $body$
DECLARE

ldc_period sc_lon_m_contract.period_payment_amount%type;
li_salary_time sc_mem_m_ucf_group_position.salary_time%type;
ls_drop_prin sc_lon_m_rule.drop_prin_status%type;

BEGIN
    SELECT sc_lon_m_contract.period_payment_amount,
         sc_mem_m_ucf_group_position.salary_time,
         sc_lon_m_rule.drop_prin_status
    INTO STRICT ldc_period,li_salary_time , ls_drop_prin
    FROM sc_lon_m_contract,
         sc_mem_m_member_work_info,
         sc_mem_m_ucf_group_position,
         sc_lon_m_rule
   WHERE ( sc_lon_m_contract.membership_no = sc_mem_m_member_work_info.membership_no ) and ( sc_mem_m_ucf_group_position.group_position = sc_mem_m_member_work_info.group_position ) and ( sc_lon_m_rule.loan_type = sc_lon_m_contract.loan_type ) and (sc_lon_m_contract.loan_contract_no = as_conno);
  if coalesce(ldc_period::text, '') = '' then ldc_period := 0;end if;
  if coalesce(li_salary_time::text, '') = '' then li_salary_time := 1;end if;
  if coalesce(ls_drop_prin::text, '') = '' then ls_drop_prin := '0';end if;
  if ls_drop_prin = '1' then
    ldc_period := 0;
   else
    ldc_period := ldc_period / li_salary_time;
   end if;
  RETURN ldc_period;
END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpb_tel_get_loan_period (as_conno text) FROM PUBLIC;

