-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpb_get_vourcher_date (as_vourcherno char ) RETURNS timestamp(0) AS $body$
DECLARE

ldt_findate  timestamp(0);

BEGIN
      select	operate_date
      into STRICT		ldt_findate
      from		sc_fin_vourcher_head
      where	vourcher_no = as_vourcherno
;
    return ldt_findate;

  exception when others then return null;
end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpb_get_vourcher_date (as_vourcherno char ) FROM PUBLIC;

