-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpb_kromss_get_keepamt (as_memno char,ai_year integer,ai_month integer,ai_seqno integer, as_kep_group CHAR ) RETURNS bigint AS $body$
DECLARE

ldc_keepin_amount bigint;
ldc_money_return bigint;

BEGIN

    case as_kep_group
      when 'COP' then
       -- เอาที่เรียกเก็บไป ( ยังไม่ลดเงินจ่ายคืน ) เฉพาะในส่วนของสหกรณ์ ( goods_code = 0 )
         -- ยอดเรียกเก็บเดือนนี้
         select  sum(money_amount) into STRICT ldc_keepin_amount
         from sc_kep_t_monthly_receive_det
         ,sc_kep_m_ucf_keeping_item_type
         where sc_kep_m_ucf_keeping_item_type.keeping_type_code = sc_kep_t_monthly_receive_det.keeping_type_code
         and (sc_kep_t_monthly_receive_det.membership_no    = as_memno)
         and (sc_kep_t_monthly_receive_det.receive_year       = ai_year)
         and (sc_kep_t_monthly_receive_det.receive_month      = ai_month)
         and (sc_kep_t_monthly_receive_det.keeping_type_code <> 'MR00')
         and (sc_kep_m_ucf_keeping_item_type.goods_status = '0')
         and (seq_no = ai_seqno);

      when 'KEP' then
        -- เอาที่เรียกเก็บไป ( ยังไม่ลดเงินจ่ายคืน )
         -- ยอดเรียกเก็บเดือนนี้
         select  sum(money_amount) into STRICT ldc_keepin_amount
         from sc_kep_t_monthly_receive_det
         where (membership_no    = as_memno)
         and (receive_year       = ai_year)
         and (receive_month      = ai_month)
         and (keeping_type_code <> 'MR00')
         and (seq_no = ai_seqno);

      when 'NET' then
         --เงินที่เรียกเก็บ = ยอดเรียเก็บ  - ยอดเงินจ่ายคืน
         -- ยอดเรียกเก็บเดือนนี้
         select  sum(money_amount) into STRICT ldc_keepin_amount
         from sc_kep_t_monthly_receive_det
         where (membership_no    = as_memno)
         and (receive_year       = ai_year)
         and (receive_month      = ai_month)
         and (keeping_type_code <> 'MR00')
         and (seq_no = ai_seqno);

         -- ยอดเงินจ่ายคืน
         select  sum(money_amount) into STRICT ldc_money_return
         from sc_kep_t_monthly_receive_det
         where (membership_no    = as_memno)
         and (receive_year       = ai_year)
         and (receive_month      = ai_month)
         and (keeping_type_code = 'MR00')
         and (seq_no = ai_seqno);

         ldc_keepin_amount := nvn(ldc_keepin_amount) - nvn(ldc_money_return);
         if ldc_keepin_amount < 0 then
           ldc_keepin_amount := 0;
         end if;

      else
         -- เลือกตามกลุ่มเรียกเก็บ
         select  	sum(money_amount) into STRICT ldc_keepin_amount
         from 		sc_kep_t_monthly_receive_det
			           ,sc_kep_m_ucf_keeping_item_type
         where ( sc_kep_t_monthly_receive_det.keeping_type_code  = sc_kep_m_ucf_keeping_item_type.keeping_type_code )
         and (sc_kep_t_monthly_receive_det.membership_no 			= as_memno )
         and (sc_kep_t_monthly_receive_det.receive_year 				= ai_year)
         and (sc_kep_t_monthly_receive_det.receive_month 			= ai_month)
         and (sc_kep_t_monthly_receive_det.seq_no 						  = ai_seqno)
         and (sc_kep_m_ucf_keeping_item_type.keeping_type_group 	= as_kep_group )
;
         ldc_keepin_amount := nvn(ldc_keepin_amount);
     end case;



  RETURN ldc_keepin_amount;
END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpb_kromss_get_keepamt (as_memno char,ai_year integer,ai_month integer,ai_seqno integer, as_kep_group CHAR ) FROM PUBLIC;

