-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpb_pl_get_dep_must_loan_bal ( as_memno char ) RETURNS bigint AS $body$
DECLARE

ldc_withdrawable sc_dep_m_creditor.withdrawable_amount%type;

BEGIN
    SELECT  sum( sc_dep_m_creditor.withdrawable_amount )
    INTO STRICT    ldc_withdrawable
    FROM    sc_mem_m_member_bank_accno,
            sc_dep_m_creditor
   WHERE ( sc_mem_m_member_bank_accno.bank_acc_no = sc_dep_m_creditor.deposit_account_no ) and
         ( ( sc_mem_m_member_bank_accno.membership_no = as_memno ) AND ( sc_mem_m_member_bank_accno.bank_id = '00' ) AND ( sc_mem_m_member_bank_accno.mustcoll_loan = '1' ) );
      if coalesce(ldc_withdrawable::text, '') = '' then ldc_withdrawable := 0;end if;
  RETURN ldc_withdrawable;
END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpb_pl_get_dep_must_loan_bal ( as_memno char ) FROM PUBLIC;

