-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpb_get_msg_collused (as_memno text ,as_msg_code char) RETURNS varchar AS $body$
DECLARE

  ls_msg_str varchar(1000);
  ls_loan_type varchar(2);
  ls_mem_level varchar(100);
  ls_member_term varchar(100);
  ls_share_holding varchar(100);
  ls_loan_amount varchar(100);
  ls_share_per_loan varchar(100);
  ls_loan_by_salary varchar(100);
  ldc_used_amount bigint;
  ldc_used_coll_bal bigint;
  ldc_maxpermit bigint;

BEGIN
  select  normshare_mix_loantype,
          FPB_GET_COLLUSED_AMOUNT_SUM(as_memno)
  into STRICT    ls_loan_type ,ldc_used_amount
  from    sc_lon_m_constant;

  ls_mem_level      :=  pka_lon_reqsrv.fp_rule_loanpermit_levelcustom(ls_loan_type ,as_memno ,to_date(clock_timestamp()) ,'mem_level');
  ls_member_term    :=  pka_lon_reqsrv.fp_rule_loanpermit_levelcustom(ls_loan_type ,as_memno ,to_date(clock_timestamp()) ,'member_term');
  ls_share_holding  :=  pka_lon_reqsrv.fp_rule_loanpermit_levelcustom(ls_loan_type ,as_memno ,to_date(clock_timestamp()) ,'share_holding');
  ls_loan_by_salary :=  pka_lon_reqsrv.fp_rule_loanpermit_levelcustom(ls_loan_type ,as_memno ,to_date(clock_timestamp()) ,'loan_by_salary');
  ls_loan_amount    :=  pka_lon_reqsrv.fp_rule_loanpermit_levelcustom(ls_loan_type ,as_memno ,to_date(clock_timestamp()) ,'loan_amount');
  ls_share_per_loan :=  pka_lon_reqsrv.fp_rule_loanpermit_levelcustom(ls_loan_type ,as_memno ,to_date(clock_timestamp()) ,'percent_share_per_loan');
  ldc_maxpermit     :=  pka_lon_reqsrv.fp_calc_loanpermit_levelcustom(ls_loan_type ,as_memno, to_date(clock_timestamp()) );
  ldc_used_coll_bal :=  ldc_maxpermit - ldc_used_amount;
  ls_msg_str := '';

  case trim(both as_msg_code )
    when '01' then  
      ls_msg_str := ls_msg_str||'ชั้นที่ --> '||ls_mem_level||'  อายุสมาชิกตั้งแต่ '||ls_member_term||' เดือน '||' มีทุนเรือนหุ้นตั้งแต่ '||to_snumber(ls_share_holding)||' บาท';
      ls_msg_str := ls_msg_str||'!NL!'||' ได้สิทธิการกู้ '||ls_loan_by_salary||' เท่าของเงินเดือน แต่ไม่เกิน '||to_snumber(ls_loan_amount)||' บาท';
      ls_msg_str := ls_msg_str||'!NL!'||' และต้องถือหุ้นไม่น้อยกว่า '||ls_share_per_loan||'%'||' ของวงเงินกู้';
    when '02' then
      ls_msg_str := ls_msg_str|| '--> สิทธิการกู้ = '||to_snumber(ldc_maxpermit)||'  ใช้สิทธิค้ำประกันไปแล้ว = '||to_snumber(ldc_used_amount)||'  เหลือสิทธิค้ำ = '||to_snumber(ldc_used_coll_bal)||' บาท';
    else
      null;
    end case;

  return trim(both ls_msg_str);

exception when others then return '';
end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpb_get_msg_collused (as_memno text ,as_msg_code char) FROM PUBLIC;

