-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION fpb_get_chk_mem_resign_date (as_ref_own_no char) RETURNS timestamp(0) AS $body$
DECLARE

ld_resign_date timestamp(0);

BEGIN

  select   resignation_approve_date
  into STRICT ld_resign_date
  from sc_mem_m_membership_registered
  where membership_no = as_ref_own_no
  and member_status_code = '3';


  return ld_resign_date;

end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION fpb_get_chk_mem_resign_date (as_ref_own_no char) FROM PUBLIC;

