-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION getvalue (as_express text,as_keyname text,as_find_case char DEFAULT null) RETURNS varchar AS $body$
DECLARE

    ls_express varchar(1999) := as_express;
    li_fr integer;li_to integer;
    ls_find varchar(1999);ls_value varchar(1999);

BEGIN
    -- key1=val1|key2=val2|key3=val3
    -- return : val
    if coalesce(trim(both ls_express)::text, '') = '' then
        return null;
    end if;

    if substr(ls_express,1,1) != '|' then
        ls_express := '|'||ls_express;
    end if;

    if substr(length(ls_express),1) != '|' then
        ls_express := ls_express||'|';
    end if;

    if as_find_case = 'U' then
        ls_find := '|'||Upper(as_keyname)||'=';
    elsif as_find_case = 'L' then
        ls_find := '|'||Lower(as_keyname)||'=';
    else
        ls_find := '|'||as_keyname||'=';
    end if;

    li_fr := position(ls_find in ls_express);
    if li_fr > 0 then
        li_to  := instr(ls_express,'|',li_fr + 1);
        if li_to > 0 and li_to - li_fr > 0  then
            return substr(ls_express , li_fr + length(ls_find) , li_to - li_fr - length(ls_find) );
        end if;
    end if;

    if coalesce(as_find_case::text, '') = '' then
        if as_keyname != Lower(as_keyname) then 
             ls_value := getvalue(ls_express, Lower(as_keyname), 'L');
            if (ls_value IS NOT NULL AND ls_value::text <> '') then
                return ls_value;
            end if;
        end if;
        if as_keyname != Upper(as_keyname) then
            return getvalue(ls_express, Upper(as_keyname), 'U');
        end if;
    end if;

    return null;

exception when others then return null;
end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION getvalue (as_express text,as_keyname text,as_find_case char DEFAULT null) FROM PUBLIC;

