-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION is_number (as_text text) RETURNS char AS $body$
DECLARE

  ldc_value bigint;

BEGIN
  if coalesce(trim(both as_text)::text, '') = '' then
    return '0';
  end if;
  ldc_value := (as_text)::numeric;
  return '1';
exception when others then return '0';
end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION is_number (as_text text) FROM PUBLIC;

