-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION isdate ( p_string text, p_fmt text DEFAULT null) RETURNS boolean AS $body$
DECLARE

    l_date timestamp(0);

BEGIN
    l_date := to_date(p_string,  p_fmt);
    return true;
exception
   when others then
       return False;
end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION isdate ( p_string text, p_fmt text DEFAULT null) FROM PUBLIC;

