-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION to_tsdate (adt_date timestamp(0)) RETURNS varchar AS $body$
BEGIN
  if adt_date = to_date('01/01/1900') then
    return null;
  end if;
  return to_char(adt_date,'dd-mm-')||substr(trim(both (to_char(adt_date,'yyyy'))::numeric  + 543),3);
end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION to_tsdate (adt_date timestamp(0)) FROM PUBLIC;

