-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION to_tdate (adt_date timestamp(0),as_format_date text default null) RETURNS varchar AS $body$
BEGIN
--  if pka_com_valid.var_date(adt_date) = '0' then
--    return '  /  /    ';
--  end if;
--  return  trim(To_char(adt_date,'dd/mm/'))||trim(To_char(Extract(Year from adt_date) + 543));
  if coalesce(adt_date::text, '') = '' then
    return regexp_replace(regexp_replace(coalesce(as_format_date,'dd/mm/yyyy'),'\d',null, 'g'),'\w','#', 'g');
  else
    return to_char(adt_date,coalesce(as_format_date,'dd/mm/yyyy'), 'NLS_CALENDAR=''THAI BUDDHA'' NLS_DATE_LANGUAGE=THAI');
  end if;

exception WHEN OTHERS then CALL spa_dberror('to_tdate');return ' ';

end;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION to_tdate (adt_date timestamp(0),as_format_date text default null) FROM PUBLIC;

