-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION top_test (as_docno text) RETURNS varchar AS $body$
DECLARE

  ls_docno varchar(100);

BEGIN

  ls_docno := as_docno;
  -- แปลง
  return ls_docno;

exception when others then CALL spa_dberror('TOP_TEST');
END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION top_test (as_docno text) FROM PUBLIC;

