-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

CREATE OR REPLACE VIEW vf_vourcher_rec (vourcher_no, operate_date, entry_id, journal_date, entry_fin, vourcher_desc, vourcher_owner, vourcher_name, pay_type, pay_chq, account_name, item_amount) AS select vourcher_no
, operate_date
, entry_id
, journal_date
, entry_fin
, vourcher_desc
, vourcher_owner
, vourcher_name
, pay_type
, pay_chq

,  account_name
,  item_amount
FROM 
( 
/*Amount all */

  SELECT sc_fin_vourcher_head.vourcher_no

,sc_fin_vourcher_head.operate_date
,sc_fin_vourcher_head.entry_id

,CASE WHEN  sc_fin_vourcher_head.money_accept='0' THEN ''  ELSE sc_fin_vourcher_head.journal_date END as journal_date 
,CASE WHEN  sc_fin_vourcher_head.money_accept='0' THEN ''  ELSE sc_fin_vourcher_head.entry_fin END  as entry_fin


,sc_fin_vourcher_head.vourcher_desc
,sc_fin_vourcher_head.vourcher_owner
,sc_fin_vourcher_head.vourcher_name
,FPA_FIN_PAY_TYPE( sc_fin_vourcher_head.vourcher_no  ) as  pay_type
,FPA_FIN_PAY_CHQ(  sc_fin_vourcher_head.vourcher_no  ) as pay_chq

,tb_det.account_name
,sum( tb_det.item_amount ) as  item_amount
from sc_fin_vourcher_head

, ( 		select   sc_fin_vourcher_detail.vourcher_no  
		, sc_fin_vourcher_detail.item_amount  
		,sc_acc_m_account_master.account_id
		,sc_acc_m_account_master.account_name
		from sc_fin_vourcher_detail  
		,sc_acc_m_account_master
		where  1=1
		and  sc_fin_vourcher_detail.account_id = sc_acc_m_account_master.account_id
) tb_det

where  1=1
and tb_det.vourcher_no = sc_fin_vourcher_head.vourcher_no   
/*WHERE*/

group by sc_fin_vourcher_head.vourcher_no

,sc_fin_vourcher_head.operate_date
,sc_fin_vourcher_head.entry_id

,CASE WHEN  sc_fin_vourcher_head.money_accept='0' THEN ''  ELSE sc_fin_vourcher_head.journal_date END 
,CASE WHEN  sc_fin_vourcher_head.money_accept='0' THEN ''  ELSE sc_fin_vourcher_head.entry_fin END  


,sc_fin_vourcher_head.vourcher_desc
,sc_fin_vourcher_head.vourcher_owner
,sc_fin_vourcher_head.vourcher_name
,FPA_FIN_PAY_TYPE( sc_fin_vourcher_head.vourcher_no  ) 
,FPA_FIN_PAY_CHQ(  sc_fin_vourcher_head.vourcher_no  ) 
,tb_det.account_name 


union all
 
/*TAX*/

  SELECT sc_fin_vourcher_head.vourcher_no

,sc_fin_vourcher_head.operate_date
,sc_fin_vourcher_head.entry_id

,CASE WHEN  sc_fin_vourcher_head.money_accept='0' THEN ''  ELSE sc_fin_vourcher_head.journal_date END as journal_date 
,CASE WHEN  sc_fin_vourcher_head.money_accept='0' THEN ''  ELSE sc_fin_vourcher_head.entry_fin END  as entry_fin


,sc_fin_vourcher_head.vourcher_desc
,sc_fin_vourcher_head.vourcher_owner
,sc_fin_vourcher_head.vourcher_name
,FPA_FIN_PAY_TYPE( sc_fin_vourcher_head.vourcher_no  ) as  pay_type
,FPA_FIN_PAY_CHQ(  sc_fin_vourcher_head.vourcher_no  ) as pay_chq

,tb_det.account_name
,sum( tb_det.item_amount ) * (-1 ) as  item_amount
from sc_fin_vourcher_head

, ( 		select   sc_fin_vourcher_detail.vourcher_no  
		, sc_fin_vourcher_detail.item_amount  
		,sc_acc_m_account_master.account_id
		,'     '||sc_acc_m_account_master.account_name as account_name
		from sc_fin_vourcher_detail  
		,sc_acc_m_account_master
		where  1=1
		and  sc_fin_vourcher_detail.account_tr = sc_acc_m_account_master.account_id
        --and sc_fin_vourcher_detail.bank_id is null        
        and sc_fin_vourcher_detail.account_tr not in ( select account_id  from sc_fin_m_bank where (account_id IS NOT NULL AND account_id::text <> '')  ) --Not in Bank fin
        and  coalesce( sc_fin_vourcher_detail.pay_type , ' ' ) <> 'Q' 
) tb_det

where  1=1
and tb_det.vourcher_no = sc_fin_vourcher_head.vourcher_no   
/*WHERE*/

group by sc_fin_vourcher_head.vourcher_no

,sc_fin_vourcher_head.operate_date
,sc_fin_vourcher_head.entry_id

,CASE WHEN  sc_fin_vourcher_head.money_accept='0' THEN ''  ELSE sc_fin_vourcher_head.journal_date END 
,CASE WHEN  sc_fin_vourcher_head.money_accept='0' THEN ''  ELSE sc_fin_vourcher_head.entry_fin END  


,sc_fin_vourcher_head.vourcher_desc
,sc_fin_vourcher_head.vourcher_owner
,sc_fin_vourcher_head.vourcher_name
,FPA_FIN_PAY_TYPE( sc_fin_vourcher_head.vourcher_no  ) 
,FPA_FIN_PAY_CHQ(  sc_fin_vourcher_head.vourcher_no  ) 
,tb_det.account_name 

)  tb 
where 1=1
/*WHERE*/

--and  vourcher_no = 'R6701774'    
order by  item_amount desc;

