-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

CREATE OR REPLACE VIEW vf_vourcher_pay_mreturn (vourcher_no, operate_date, entry_id, journal_date, entry_fin, vourcher_desc, vourcher_owner, vourcher_name, vourcher_group, pay_type, account_name, item_amount, sum_item_amount_thai, entry_fin_name, coop_name, status_code, copy_desc, pay_chq, pay_chq_desc, membership_no, item_no) AS select vourcher_no
, operate_date
, entry_id
, journal_date
, entry_fin
, vourcher_desc
, vourcher_owner
, vourcher_name
, vourcher_group
, pay_type


,  account_name
,  item_amount
,  sum_item_amount_thai
,  entry_fin_name

,  coop_name
,  status_code
,  copy_desc
,  pay_chq
,  pay_chq_desc

,  membership_no
,  item_no
FROM 
( 
/*MONEY RETURN */

SELECT   sc_fin_money_return_det.voucher_no as vourcher_no 
, sc_fin_money_return.operate_date 
, sc_fin_money_return.entry_id as entry_id
, sc_fin_money_return.paid_date as journal_date
, sc_fin_money_return.paid_id  as  entry_fin
,sc_fin_money_return.request_method || ' '
|| case 
when  sc_fin_money_return.request_method in ( 'CSH','CHQ' ) then  
		'เลขที่บัตร '||sc_mem_m_membership_registered.id_card
when  sc_fin_money_return.request_method in ( 'TRB','TRD' ) then     
        'เข้าบัญชี ' || sc_fin_money_return.request_bankac
  else 
		''
end     as vourcher_desc 

, sc_fin_money_return.membership_no as vourcher_owner
, CASE WHEN   coalesce(sc_fin_money_return.remark::text, '') = '' THEN  pka_com_function.fp_get_member_name( sc_fin_money_return.membership_no )   ELSE sc_fin_money_return.remark END  as vourcher_name
, '' as vourcher_group
, case 
 when  sc_fin_money_return.request_method =  'CHQ' then
	'Q'
when sc_fin_money_return.request_method =  'CSH'  then
	'C'
else
    'T' 
end as pay_type
,(select return_desc from sc_fin_ucf_money_retrun where return_method = sc_fin_money_return.return_method ) as account_name
,sc_fin_money_return.money_return  as item_amount 
 ,( select user_name from si_security_user where user_id =  sc_fin_money_return.paid_id ) as entry_fin_name 
,pka_com_function.fp_get_moneythai( sc_fin_money_return.money_return ) as sum_item_amount_thai   


,sc_cnt_m_coop.coop_name
,sc_cnt_m_status_01.status_code
,CASE WHEN  sc_cnt_m_status_01.status_code ='0' THEN  'ต้นฉบับ'   ELSE 'สำเนา' END  as copy_desc

,FPA_FIN_PAY_CHQ( sc_fin_money_return_det.voucher_no ) as  pay_chq
,FPA_FIN_PAY_CHQ_DESC( sc_fin_money_return_det.voucher_no ) as  pay_chq_desc

, sc_fin_money_return.membership_no
, sc_fin_money_return.item_no 

FROM sc_fin_money_return
,sc_fin_money_return_det
,sc_mem_m_membership_registered
,sc_fin_vourcher_head
,sc_cnt_m_coop
,sc_cnt_m_status_01

WHERE  1 = 1
and sc_fin_money_return_det.membership_no = sc_fin_money_return.membership_no
and sc_fin_money_return_det.item_no = sc_fin_money_return.item_no 
and sc_fin_money_return_det.item_type = 'RT'
and sc_fin_money_return_det.status  = '0'
and sc_fin_money_return_det.voucher_no = sc_fin_vourcher_head.vourcher_no
and sc_fin_money_return.membership_no = sc_mem_m_membership_registered.membership_no
and sc_cnt_m_status_01.status_code in ( '0' ,'1' )   

)  tb 
where 1=1
/*WHERE*/

--and membership_no = '04758'
--AND item_no = '11'
order by    membership_no  , item_no , status_code;

