-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

CREATE OR REPLACE VIEW view_fin_tax_company (tax_date, tax_seq, id_card, prename, memname, memsurname, paid_amount, tax_amount, company_id, vourcher_no) AS SELECT sc_fin_vourcher_head.journal_date AS TAX_DATE
  ,row_number() OVER () AS TAX_SEQ
  ,sc_fin_ucf_company.tax_id AS ID_CARD
  ,'-' AS PRENAME
  , left( sc_fin_ucf_company.company_name , 50 ) AS MEMNAME
  , left( sc_fin_ucf_company.service_des, 50 )  AS MEMSURNAME
  , sc_fin_vourcher_head.vourcher_value AS PAID_AMOUNT
  , sc_fin_vourcher_detail.item_amount AS TAX_AMOUNT
  
  ,sc_fin_vourcher_head.company_id AS COMPANY_ID
  ,sc_fin_vourcher_head.vourcher_no AS VOURCHER_NO
    FROM sc_fin_vourcher_head,   
         sc_fin_ucf_company,   
         sc_fin_vourcher_detail  
   WHERE ( sc_fin_vourcher_head.company_id = sc_fin_ucf_company.company_id ) and ( sc_fin_vourcher_head.vourcher_no = sc_fin_vourcher_detail.vourcher_no ) and ( sc_fin_vourcher_detail.account_tr = '214215' )     

and sc_fin_vourcher_head.cancel_status ='0'
and sc_fin_vourcher_head.post_journal = '1'

--AND TAX_DATE = '26/5/2023'
 

ORDER BY sc_fin_vourcher_head.journal_date ASC
,sc_fin_vourcher_head.vourcher_no;

