-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

CREATE OR REPLACE VIEW view_fin_tax_hr (tax_date, tax_seq, id_card, prename, memname, memsurname, paid_amount, tax_amount, official_no, sal_year, sal_month) AS SELECT sc_hr_off_salary_paid.post_date AS TAX_DATE
  ,row_number() OVER () AS TAX_SEQ
  ,sc_hr_off_member.id_card AS ID_CARD
  ,sc_mem_m_ucf_prename.prename AS PRENAME
  ,sc_hr_off_member.member_name AS MEMNAME
  ,sc_hr_off_member.member_surname AS MEMSURNAME
  ,sc_hr_off_salary_income_other.income_amount  AS PAID_AMOUNT

  ,coalesce( (select tb_tax.income_amount
        FROM sc_hr_off_salary_income_other tb_tax
        where tb_tax.income_code ='1015'
        and tb_tax.sal_year = sc_hr_off_salary_income_other.sal_year
        and tb_tax.sal_month = sc_hr_off_salary_income_other.sal_month
        and  tb_tax.official_no = sc_hr_off_salary_income_other.official_no ), 0 ) AS TAX_AMOUNT

  ,sc_hr_off_salary_income_other.official_no AS OFFICIAL_NO
  ,sc_hr_off_salary_income_other.sal_year AS SAL_YEAR
  ,sc_hr_off_salary_income_other.sal_month AS SAL_MONTH
    FROM sc_hr_off_salary_income_other,   
         sc_hr_off_member,   
         sc_mem_m_ucf_prename,   
         sc_hr_off_salary_paid  
   WHERE ( sc_hr_off_salary_income_other.official_no = sc_hr_off_member.official_no ) and ( sc_hr_off_member.prename_code = sc_mem_m_ucf_prename.prename_code ) and ( sc_hr_off_salary_income_other.sal_year = sc_hr_off_salary_paid.sal_year ) and ( sc_hr_off_salary_income_other.sal_month = sc_hr_off_salary_paid.sal_month ) and ( sc_hr_off_salary_income_other.official_no = sc_hr_off_salary_paid.official_no ) and ( sc_hr_off_salary_income_other.income_code = '0005' )   

and sc_hr_off_salary_paid.post_status = '1'

--AND TAX_DATE = '26/5/2023'
 

ORDER BY sc_hr_off_salary_income_other.official_no ASC;

