-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

CREATE OR REPLACE VIEW view_tel_get_creamation (coop_type, crem_coop, crem_code, crem_name, crem_type_code, crem_type, membership_no, cream_amount) AS select tab.COOP_TYPE,tab.CREM_COOP,tab.CREM_CODE,tab.CREM_NAME, tab.CREM_TYPE_CODE  , tab.CREM_TYPE,tab.MEMBERSHIP_NO,tab.CREAM_AMOUNT
    FROM (
            select 'crem_1' as coop_type
            ,'ส.ฌ.น.ม' as crem_coop
            ,crem_code as crem_code
            ,trim(both crem_prename.prename)||trim(both crm_master.memname)||' '||trim(both crm_master.surname) as crem_name
            ,crm_master.crem_type as CREM_TYPE_CODE
            ,crem_rule.description as crem_type
            ,right('000000'||trim(both membership_no),6) as membership_no
            ,420000 as cream_amount

            from sc_crem_master@db_crem_1 crm_master
            ,SC_CREM_RULE@db_crem_1 crem_rule
            ,sc_mem_m_ucf_prename@db_crem_1 crem_prename
            
            where crm_master.crem_type = crem_rule.crem_type
            and crm_master.prename_code = crem_prename.prename_code
            
            
union

            
            select 'crem_2' as coop_type
            ,'ฌ.ส.น.ม' as crem_coop
            ,crem_code as crem_code
            ,trim(both crem_prename.prename)||trim(both crm_master.memname)||' '||trim(both crm_master.surname) as crem_name
            ,crm_master.crem_type as CREM_TYPE_CODE
            ,crem_rule.description as crem_type
            ,right('000000'||trim(both membership_no),6) as membership_no
            ,390000 as cream_amount
            
            from sc_crem_master@db_crem_2 crm_master
            ,SC_CREM_RULE@db_crem_2 crem_rule
            ,sc_mem_m_ucf_prename@db_crem_2 crem_prename
            
            where crm_master.crem_type = crem_rule.crem_type
            and crm_master.prename_code = crem_prename.prename_code
            
            
union

            
            select 'crem_3' as coop_type
            ,'ส.ส.น.ม' as crem_coop
            ,no_coop as crem_code
            ,trim(both pre_ssnm)||trim(both name_ssnm)||' '||trim(both surname_ssnm) as crem_name
            ,'01' as CREM_TYPE_CODE
            ,'' as crem_type
            ,right('000000'||trim(both no_coop),6) as membership_no
            ,460000 as cream_amount
            
            from off_detail_ssnm
        
        ) tab 
    where 1=1
    --and   tab.membership_no = '069737'
    order by tab.CREM_TYPE_CODE 
    ,tab.crem_code;

