-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

CREATE OR REPLACE VIEW view_tel_det_lon_zero (membership_no, loan_contract_no, begining_of_contract, loan_approve_amount, loan_installment_amount, period_payment_amount, last_calcint_date, last_access_date, tran_to_coll, last_period, principal_balance, year_total_interest, loan_status, interest_arrear, loan_type, loan_style, close_status, atm_status, loan_looping, modify_status, loan_group, paid_able, loan_period_payment, loan_group_code, pay_loan_period, drop_payment_status, pending_amount, cal_shr_auto) AS select   sc_lon_m_contract.membership_no ,
        sc_lon_m_contract.loan_contract_no,
        sc_lon_m_contract.begining_of_contract,
        sc_lon_m_contract.loan_approve_amount,
        sc_lon_m_contract.loan_installment_amount ,
        sc_lon_m_contract.period_payment_amount,
        sc_lon_m_loan_card.last_calcint_date,
        sc_lon_m_loan_card.last_access_date,
        sc_lon_m_contract.tran_to_coll,
        sc_lon_m_loan_card.last_period,
        sc_lon_m_loan_card.principal_balance,
        sc_lon_m_loan_card.year_total_interest,

        sc_lon_m_loan_card.drop_payment_status as loan_status,

        sc_lon_m_loan_card.interest_arrear,
        sc_lon_m_loan_card.loan_type, 

        '' as loan_style,

        sc_lon_m_loan_card.close_status,
        sc_lon_m_rule.atm_status,
        sc_lon_m_rule.loan_looping,
       (pka_mem_det.fp_atm_status_desc_conno(sc_lon_m_contract.loan_contract_no)) as modify_status,
       '0' as loan_group,  
        0 as paid_able,
        0 as loan_period_payment,
        sc_lon_m_rule.loan_group_code,
        sc_lon_m_rule.pay_loan_period,
        sc_lon_m_loan_card.drop_payment_status ,
        0 as pending_amount
         ,'0' as cal_shr_auto 
    FROM sc_lon_m_contract,
      sc_lon_m_loan_card,
      sc_lon_m_rule
    where ( sc_lon_m_loan_card.loan_contract_no = sc_lon_m_contract.loan_contract_no )
    and ( sc_lon_m_loan_card.loan_type = sc_lon_m_rule.loan_type )

    and ( sc_lon_m_loan_card.principal_balance = 0 ) 
    order by sc_lon_m_loan_card.loan_contract_no;

