-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

CREATE OR REPLACE VIEW view_kep_return_piority (seq_no, keep_type, cut_status, type_money) AS select seq_no , keep_type ,cut_status ,type_money
FROM (
        select seq_no , keep_type ,cut_status ,type_money
        from sc_kep_return_piority
        where (keep_type != 'MR00')
        and keep_type not like 'ML%'  
       

union all

        select  min(seq_no ) as seq_no
        ,'ML00' as keep_type
        , '0'  as cut_status
        ,'I' as type_money
        from sc_kep_return_piority
        where (keep_type != 'MR00')
        and keep_type  like 'ML%' 
	  and type_money = 'I' 
       

union all

        select  min(seq_no ) as seq_no
        ,'ML00' as keep_type
        , '0'  as cut_status
        , 'P' as  type_money
        from sc_kep_return_piority
        where (keep_type != 'MR00')
        and keep_type  like 'ML%' 
	  and type_money = 'P' 
) tb 
order by seq_no;

