-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

CREATE OR REPLACE VIEW view_tge_dep_coll_share (membership_no, seq_no, operate_date, item_type, share_amount, share_value, share_stock, sign_flag, item_type_desc, value_amount) AS SELECT sc_mem_m_share_holding_detail.membership_no,
sc_mem_m_share_holding_detail.seq_no,   
sc_mem_m_share_holding_detail.operate_date,   
sc_mem_m_share_holding_detail.item_type,   
sc_mem_m_share_holding_detail.share_amount,   
sc_mem_m_share_holding_detail.share_value,   
sc_mem_m_share_holding_detail.share_stock,   

sc_mem_m_ucf_share_item_type.sign_flag,   
sc_mem_m_ucf_share_item_type.item_type_description AS item_type_desc,

0 AS value_amount

FROM sc_mem_m_share_holding_detail
,sc_mem_m_ucf_share_item_type
WHERE  1=1
and sc_mem_m_share_holding_detail.item_type = sc_mem_m_ucf_share_item_type.item_type
--and sc_mem_m_share_holding_detail.membership_no = 'memno'
--and  sc_mem_m_share_holding_detail.operate_date >= 'dd/mm/yyyy'
ORDER BY sc_mem_m_share_holding_detail.seq_no;

