-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

CREATE OR REPLACE VIEW view_sctransdiv (data_code, bank_code, trandate, seq_tran, seq_no, membership_no, cmember_name, amount, acc_no, member_group_no, c_reference, eng_name, item_type, branch_bank_code, fee_amount, begining_of_contract, branch_id, loan_type, trans_bank_status, item_seq_no) AS SELECT
        ' ' as data_code,  
        sc_mem_m_capital_pay.bank_code as bank_code , 
        ' ' as trandate,  
        ' ' as seq_tran,  
        row_number() OVER () as seq_no,
        sc_mem_m_capital_pay.membership_no as membership_no ,
        sc_mem_m_ucf_prename.prename || '' ||
        sc_mem_m_membership_registered.member_name || ' ' ||
        sc_mem_m_membership_registered.member_surname as cmember_name ,
        sc_mem_m_capital_pay.item_amount as amount,
        sc_mem_m_capital_pay.bank_acc_no as acc_no,
        sc_mem_m_membership_registered.member_group_no as member_group_no,
        sc_mem_m_capital_stock_detail.account_year as c_reference,
        sc_mem_m_membership_registered.eng_name as eng_name ,
        'DIV' as item_type,
        left((trim(both sc_mem_m_capital_pay.bank_acc_no)),3) as branch_bank_code,
        0 as fee_amount,
        sc_acc_m_account_year.beginning_of_account  as begining_of_contract
,'01' as branch_id
,' ' as loan_type
,sc_mem_m_capital_pay.trans_bank_status as trans_bank_status
,sc_mem_m_capital_pay.seq_no as item_seq_no
FROM 
    sc_mem_m_membership_registered,
    sc_mem_m_ucf_prename,
    sc_mem_m_capital_stock_detail,
    sc_mem_m_ucf_member_group,
    sc_mem_m_capital_pay
  ,sc_acc_m_account_year
where 1=1
    and sc_mem_m_membership_registered.prename_code = sc_mem_m_ucf_prename.prename_code
    and sc_mem_m_membership_registered.membership_no = sc_mem_m_capital_stock_detail.membership_no
    and sc_mem_m_capital_stock_detail.member_group_no = sc_mem_m_ucf_member_group.member_group_no
    and sc_mem_m_capital_stock_detail.ending_balance > 0 
    and sc_mem_m_capital_pay.account_year = sc_mem_m_capital_stock_detail.account_year 
    and sc_mem_m_capital_pay.membership_no = sc_mem_m_capital_stock_detail.membership_no 
    and	sc_mem_m_capital_pay.item_amount > 0 
    and sc_mem_m_capital_pay.group_pay_code in ('TRB')
    and sc_mem_m_capital_pay.post_status = '0'
    and sc_acc_m_account_year.account_year = sc_mem_m_capital_pay.account_year
/*WHERE*/

--and sc_acc_m_account_year.account_year = ai_year
--and sc_mem_m_ucf_member_group.member_group_no between as_bgroup and as_egroup
 
order by 
    sc_mem_m_membership_registered.membership_no asc;

