-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

CREATE OR REPLACE VIEW view_lon_restruc_det (membership_no, loan_contract_no, sort_payment, last_period, balance, int_arrear, drop_status_old, installment_old, paytype_code_old, payment_amount_old, fixed_payment_old, fixed_int_rate_old) AS select membership_no,
         loan_contract_no,
         sort_payment,   
         last_period,   
         balance,   
         int_arrear,   
         drop_status_old,   
         installment_old,   
         paytype_code_old,  
         payment_amount_old,
         fixed_payment_old,   
         fixed_int_rate_old  
      
FROM ( 
         select sc_mem_m_share_mem.membership_no as membership_no ,
         'SHARE' as loan_contract_no  ,
         1 as sort_payment ,   
         sc_mem_m_share_mem.period_recrieve as last_period ,   
         sc_mem_m_share_mem.share_stock as balance,   
         0 as int_arrear,   
         sc_mem_m_share_mem.drop_status as drop_status_old ,   
         0 as  installment_old  ,   
         '' as  paytype_code_old ,   
         CASE WHEN  sc_mem_m_share_mem.drop_status ='1' THEN  0   ELSE sc_mem_m_share_mem.share_amount END   as payment_amount_old ,    
         CASE WHEN  sc_mem_m_share_mem.drop_status ='1' THEN  0   ELSE sc_mem_m_share_mem.share_amount END  as fixed_payment_old,   
         0 as fixed_int_rate_old  
        from sc_mem_m_share_mem
        where 1=1
       --and sc_mem_m_share_mem.membership_no = '044411'
       

union all

    select  membership_no,
         loan_contract_no,   
         row_number() OVER () + 1 as sort_payment  ,   
         last_period,   
         balance,   
         int_arrear,   
         drop_status_old,   
         installment_old,   
         paytype_code_old,  
         payment_amount_old,
         fixed_payment_old,   
         fixed_int_rate_old  
    from ( 
    select sc_lon_m_loan_card.membership_no as membership_no  ,
         sc_lon_m_loan_card.loan_contract_no as loan_contract_no,              
         sc_lon_m_loan_card.last_period as last_period ,   
         sc_lon_m_loan_card.principal_balance as balance ,   
         sc_lon_m_loan_card.interest_arrear as int_arrear,   
         sc_lon_m_loan_card.drop_payment_status as drop_status_old,   
         sc_lon_m_contract.loan_installment_amount as installment_old  ,   
         sc_lon_m_contract.loan_payment_type_code as paytype_code_old ,   
         sc_lon_m_contract.period_payment_amount as payment_amount_old,   
         CASE WHEN  sc_lon_m_loan_card.fixed_payment =0 THEN  sc_lon_m_contract.period_payment_amount   ELSE sc_lon_m_loan_card.fixed_payment END  as fixed_payment_old ,         
         sc_lon_m_loan_card.fixed_interest_rate   as fixed_int_rate_old
        from sc_lon_m_loan_card
        ,sc_lon_m_contract
        where 1=1
        and sc_lon_m_contract.loan_contract_no = sc_lon_m_loan_card.loan_contract_no
        and sc_lon_m_loan_card.principal_balance > 0 
        --and sc_lon_m_loan_card.membership_no = '044411'
        order by sc_lon_m_contract.begining_of_contract
       ) loan_table  

) tb 
where 1=1
--and membership_no = '044411'
order by SORT_PAYMENT;

