-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

CREATE OR REPLACE VIEW view_tel_mem_wef (membership_no, wef_type, wef_desc, operate_date, total_receive, approve_status, approve_date, paid_status, paid_date, wef_detail, wef_money) AS SELECT sc_wef_req.membership_no ,
         sc_wef_ucf_type.wef_type,
         sc_wef_ucf_type.wef_desc,        
         sc_wef_req.operate_date,   
         sc_wef_req.total_receive,   
         CASE WHEN  sc_wef_req.approve_status ='1' THEN  'อนุมัติ'   ELSE 'รออนุมัติ' END  as approve_status ,   
         CASE WHEN  sc_wef_req.approve_status ='1' THEN  sc_wef_req.approve_date   ELSE NULL END  as  approve_date,   
	     --decode( sc_wef_req.paid_status , '1' , 'จ่ายแล้ว' , 'รอจ่าย' ) as paid_status ,   
         CASE WHEN  sc_wef_req.paid_status ='1' THEN  '1'               ELSE ( select coalesce( min( return_status ) , '0' )             FROM sc_fin_money_return             where 1=1             and cancel_status = '0'             and refno1 = sc_wef_req.requestment_no ) END  as paid_status , 
         
         CASE WHEN  sc_wef_req.paid_status ='1' THEN  sc_wef_req.paid_date            ELSE ( select coalesce( min( paid_date ) , null )             from sc_fin_money_return             where 1=1             and cancel_status = '0'             and refno1 = sc_wef_req.requestment_no ) END    as  paid_date ,
         pka_wef.fp_wef_paid_desc( sc_wef_req.wef_type , sc_wef_req.requestment_no ) as wef_detail    
         ,pka_wef.fp_wef_paid_money( sc_wef_req.wef_type , sc_wef_req.requestment_no ) as wef_money
    FROM sc_wef_ucf_type,   
         sc_wef_req  
   WHERE ( sc_wef_ucf_type.wef_type = sc_wef_req.wef_type ) and  
         ( sc_wef_req.cancel_status = '0'  AND  sc_wef_req.approve_status <> '0' )    
--and sc_wef_req.membership_no = '058184'
 
order by wef_type , operate_date desc;

