-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

CREATE OR REPLACE VIEW view_tel_det_insure (membership_no, loan_contract_no, begining_of_contract, insure_cost, insure_period, insure_amt, protec_begin, protec_end, per_year, insure_status, insure_desc) AS SELECT MEMBERSHIP_NO, LOAN_CONTRACT_NO,BEGINING_OF_CONTRACT, INSURE_COST, INSURE_PERIOD, INSURE_AMT,PROTEC_BEGIN, PROTEC_END
,INSURE_AMT / CASE WHEN  INSURE_PERIOD =0 THEN 1   ELSE INSURE_PERIOD END   as PER_YEAR,
INSURE_STATUS,INSURE_DESC
FROM (
     select sc_mem_m_insure_loan.membership_no  as MEMBERSHIP_NO ,
	sc_mem_m_insure_loan.loan_contract_no as LOAN_CONTRACT_NO  ,
       sc_lon_m_contract.begining_of_contract AS BEGINING_OF_CONTRACT,  

         sc_lon_m_contract.loan_approve_amount  AS  INSURE_COST, 
         ceil( PKA_SRV_DATETIME.fp_MonthsAfter( sc_mem_m_insure_loan.protec_begin ,  sc_mem_m_insure_loan.protec_end ) /12  ) AS INSURE_PERIOD,
        sc_mem_m_insure_loan.insurance_amount  AS INSURE_AMT ,  
        sc_mem_m_insure_loan.protec_begin AS PROTEC_BEGIN ,
        sc_mem_m_insure_loan.protec_end  AS PROTEC_END  ,
        sc_mem_m_insure_loan.insurance_amount    as PER_YEAR ,
       CASE WHEN  sc_mem_m_insure_loan.approve_status ='1' THEN  ''   ELSE 'WaitApprove' END  as INSURE_STATUS ,
       '' as INSURE_DESC  
from sc_mem_m_insure_loan
,sc_lon_m_contract

where sc_mem_m_insure_loan.loan_contract_no = sc_lon_m_contract.loan_contract_no
and sc_mem_m_insure_loan.cancel_status = '0'
) alias2 

order by begining_of_contract , protec_begin;

