-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

CREATE OR REPLACE VIEW view_deppaidloan (membership_no, memname, deposit_account_no, deposit_balance, loan_contract_no, principal_balance, period_payment_amount, withdrawable_amount, interest_arrear, last_calcint_date, int_amount, minbalanceforwithdraw, can_pay_status, can_pay_amount, total_amount, journal_date, drop_payment_status) AS select  MEMBERSHIP_NO, MEMNAME, DEPOSIT_ACCOUNT_NO, DEPOSIT_BALANCE, LOAN_CONTRACT_NO, PRINCIPAL_BALANCE
    , ( case DROP_PAYMENT_STATUS
     when '1' then
		0
      when '2' then
		INT_AMOUNT + INTEREST_ARREAR
     else
		PERIOD_PAYMENT_AMOUNT
     end )  as PERIOD_PAYMENT_AMOUNT



  , WITHDRAWABLE_AMOUNT
  ,  INTEREST_ARREAR  as INTEREST_ARREAR
  , LAST_CALCINT_DATE
  ,  INT_AMOUNT  as INT_AMOUNT
  , MINBALANCEFORWITHDRAW
,( case    
when  deposit_balance - minbalanceforwithdraw  >= CASE WHEN  loan_payment_type_code                                                         ='01' THEN  PERIOD_PAYMENT_AMOUNT + INT_AMOUNT + INTEREST_ARREAR                                                         WHEN  loan_payment_type_code                                                         ='02' THEN   PERIOD_PAYMENT_AMOUNT  END   then
	'1'
else
	'0'
end ) as CAN_PAY_STATUS

,( case    
when  deposit_balance - minbalanceforwithdraw  >= PERIOD_PAYMENT_AMOUNT   then
	CASE WHEN  loan_payment_type_code ='01' THEN  PERIOD_PAYMENT_AMOUNT + INT_AMOUNT + INTEREST_ARREAR                                    WHEN  loan_payment_type_code ='02' THEN   PERIOD_PAYMENT_AMOUNT  END 
else
	deposit_balance - minbalanceforwithdraw
end ) as CAN_PAY_AMOUNT


    , ( case DROP_PAYMENT_STATUS
     when '1' then
		0
      when '2' then
		INT_AMOUNT + INTEREST_ARREAR
     else
		CASE WHEN  loan_payment_type_code                ='01' THEN  PERIOD_PAYMENT_AMOUNT + INT_AMOUNT + INTEREST_ARREAR                WHEN  loan_payment_type_code                ='02' THEN   PERIOD_PAYMENT_AMOUNT  END      
     end )  as TOTAL_AMOUNT
     
  
  , JOURNAL_DATE 
  , DROP_PAYMENT_STATUS

FROM (
select	sc_mem_m_member_cremation.membership_no
,pka_com_function.fp_get_member_name(sc_mem_m_membership_registered.membership_no	) as memname
,sc_mem_m_member_cremation.deposit_account_no
,sc_dep_m_creditor.deposit_balance
,sc_lon_m_loan_card.loan_contract_no
,sc_lon_m_loan_card.principal_balance
,sc_lon_m_contract.period_payment_amount


,sc_dep_m_creditor.withdrawable_amount
,( sc_lon_m_loan_card.interest_arrear + sc_lon_m_loan_card.old_interest_arrear ) as interest_arrear
,sc_lon_m_loan_card.last_calcint_date
,PKA_LON_INTSRV.FP_CALINT(sc_lon_m_loan_card.loan_contract_no  , sc_fin_m_close_day.journal_date )  AS int_amount  
,sc_dep_m_rule.minbalanceforwithdraw
,sc_fin_m_close_day.journal_date
,sc_lon_m_loan_card.drop_payment_status
,sc_lon_m_contract.loan_payment_type_code
from		sc_mem_m_member_cremation
			,sc_mem_m_membership_registered
			,sc_dep_m_creditor
,sc_dep_m_rule
,sc_lon_m_loan_card
,sc_lon_m_contract
,sc_lon_m_rule
,sc_fin_m_close_day
where	1=1
and     sc_fin_m_close_day.branch_fin ='01'
and 	sc_lon_m_contract.loan_contract_no = sc_lon_m_loan_card.loan_contract_no
and 	sc_lon_m_loan_card.membership_no = sc_mem_m_membership_registered.membership_no	
and	    sc_dep_m_rule.deposit_type_code = sc_dep_m_creditor.deposit_type_code
and 	sc_lon_m_rule.loan_type = sc_lon_m_loan_card.loan_type
and     sc_lon_m_loan_card.principal_balance > 0 
and 	sc_lon_m_rule.crem_type = sc_mem_m_member_cremation.crem_type

and 	sc_mem_m_membership_registered.membership_no		=	sc_mem_m_member_cremation.membership_no
and		sc_dep_m_creditor.deposit_account_no				=	sc_mem_m_member_cremation.deposit_account_no
and		sc_mem_m_membership_registered.member_status_code	=		'0'
and		sc_mem_m_member_cremation.deposit_status	        =		'1'

and ( sc_lon_m_loan_card.last_calcint_date < sc_fin_m_close_day.journal_date or sc_lon_m_loan_card.interest_arrear + sc_lon_m_loan_card.old_interest_arrear  > 0 )  
) tm 

where 1=1
/*WHERE*/

--and journal_date = '28/9/2024'
--and loan_contract_no = '3200018257'
order by can_pay_status
,membership_no;

