-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

CREATE OR REPLACE VIEW view_sctransloan (data_code, bank_code, trandate, seq_tran, seq_no, membership_no, cmember_name, amount, acc_no, member_group_no, c_reference, eng_name, item_type, branch_bank_code, fee_amount, begining_of_contract, branch_id, loan_type, trans_bank_status, item_seq_no) AS SELECT
        data_code,  
        bank_code , 
        trandate,  
        seq_tran,  
        row_number() OVER () as seq_no,
        membership_no ,
        cmember_name ,
        amount ,
        acc_no,
        member_group_no,
        c_reference ,
        eng_name ,
        item_type,
        branch_bank_code,
        fee_amount,
        begining_of_contract
,branch_id
,loan_type
,trans_bank_status
,item_seq_no
FROM
(   SELECT  
        ' ' as data_code,  
        sc_lon_m_contract_multi_paid.bank_code as bank_code , 
        ' ' as trandate,  
        ' ' as seq_tran,  
        row_number() OVER () as seq_no,
        sc_lon_m_contract.membership_no as membership_no ,
        sc_mem_m_ucf_prename.prename || '' ||
        sc_mem_m_membership_registered.member_name || ' ' ||
        sc_mem_m_membership_registered.member_surname as cmember_name ,   
        sc_lon_m_contract_multi_paid.paid_amount  as  amount ,
        trim(both sc_lon_m_contract_multi_paid.bank_acc_no)  as  acc_no,
        sc_mem_m_membership_registered.member_group_no as member_group_no,
        sc_lon_m_contract.loan_contract_no as c_reference ,
        sc_mem_m_membership_registered.eng_name as eng_name ,
        'D'||(sc_lon_m_rule.loan_group_code) as item_type,
        left((trim(both sc_lon_m_contract_multi_paid.bank_acc_no)),3) as branch_bank_code,
        0 as fee_amount,
        sc_lon_m_contract.begining_of_contract  as begining_of_contract
,sc_lon_m_contract.branch_id as branch_id
,sc_lon_m_contract.loan_type as loan_type
,sc_lon_m_contract.trans_bank_status as trans_bank_status
,0 as item_seq_no
    FROM 
        sc_lon_m_contract ,
        sc_mem_m_membership_registered ,
        sc_mem_m_ucf_prename ,
        sc_lon_m_rule ,
        sc_mem_m_ucf_member_group
,sc_lon_m_contract_multi_paid
    WHERE 1=1
and sc_lon_m_contract_multi_paid.loan_contract_no = sc_lon_m_contract.loan_contract_no
        and ( sc_lon_m_contract.membership_no = sc_mem_m_membership_registered.membership_no )
        and ( sc_mem_m_membership_registered.prename_code = sc_mem_m_ucf_prename.prename_code ) 
        and ( sc_lon_m_contract.loan_type = sc_lon_m_rule.loan_type ) 
        and ( sc_mem_m_membership_registered.member_group_no = sc_mem_m_ucf_member_group.member_group_no )         
        and ( ( sc_lon_m_contract.rec_rep_status = '1' ) 
--        and ( sc_lon_m_contract.create_loan_status = '2' ) 
        and ( sc_lon_m_contract_multi_paid.type_pay_money  in ( 'TRB') ) 
--        and ( sc_lon_m_contract.create_loan_status <> '0' ) )
        and ( sc_lon_m_contract.create_loan_status = '1' ) ) 


union all
 

  SELECT  
        ' ' as data_code,  
        sc_lon_m_loan_addloan.bank_code as bank_code , 
        ' ' as trandate,  
        ' ' as seq_tran,  
        row_number() OVER () as seq_no,
        sc_lon_m_contract.membership_no as membership_no ,
        sc_mem_m_ucf_prename.prename || '' ||
        sc_mem_m_membership_registered.member_name || ' ' ||
        sc_mem_m_membership_registered.member_surname as cmember_name ,

        sc_lon_m_loan_addloan.addloan_real  as  amount ,
        trim(both sc_lon_m_loan_addloan.bank_acc_no)  as  acc_no,
        sc_mem_m_membership_registered.member_group_no as member_group_no,
        sc_lon_m_contract.loan_contract_no as c_reference ,
        sc_mem_m_membership_registered.eng_name as eng_name ,
        'A'||(sc_lon_m_rule.loan_group_code) as item_type,
        left((trim(both sc_lon_m_loan_addloan.bank_acc_no)),3) as branch_bank_code,
        0 as fee_amount,
        sc_lon_m_loan_addloan.operate_date  as begining_of_contract
,sc_lon_m_loan_addloan.entry_br as branch_id
,sc_lon_m_contract.loan_type as loan_type
,sc_lon_m_loan_addloan.trans_bank_status as trans_bank_status
,0 as item_seq_no
   FROM 
        sc_lon_m_contract ,
        sc_mem_m_membership_registered ,
        sc_mem_m_ucf_prename ,
        sc_lon_m_rule ,
        sc_mem_m_ucf_member_group
,sc_lon_m_loan_addloan
    WHERE 1=1
and sc_lon_m_loan_addloan.loan_contract_no = sc_lon_m_contract.loan_contract_no
        and ( sc_lon_m_contract.membership_no = sc_mem_m_membership_registered.membership_no )
        and ( sc_mem_m_membership_registered.prename_code = sc_mem_m_ucf_prename.prename_code ) 
        and ( sc_lon_m_contract.loan_type = sc_lon_m_rule.loan_type ) 
        and ( sc_mem_m_membership_registered.member_group_no = sc_mem_m_ucf_member_group.member_group_no )         
        and ( ( sc_lon_m_loan_addloan.fin_status = '1' ) 
        and ( sc_lon_m_loan_addloan.cancel_status = '0' ) 
        and ( sc_lon_m_loan_addloan.money_type_id  in ( 'TRB') ) 
        and ( sc_lon_m_contract.create_loan_status <> '0' ) ) 
) tb 
    ORDER BY 
        tb.membership_no ASC;

