-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

CREATE OR REPLACE VIEW view_sctransint (data_code, bank_code, trandate, seq_tran, seq_no, membership_no, cmember_name, amount, acc_no, member_group_no, c_reference, eng_name, item_type, branch_bank_code, fee_amount, begining_of_contract, branch_id, loan_type, trans_bank_status, item_seq_no) AS select  DATA_CODE, BANK_CODE, TRANDATE, SEQ_TRAN, SEQ_NO, MEMBERSHIP_NO, CMEMBER_NAME, AMOUNT, ACC_NO, MEMBER_GROUP_NO, C_REFERENCE, ENG_NAME, ITEM_TYPE, BRANCH_BANK_CODE, FEE_AMOUNT, BEGINING_OF_CONTRACT, BRANCH_ID, LOAN_TYPE , TRANS_BANK_STATUS ,ITEM_SEQ_NO

FROM (
    select
  ' ' as data_code,
 '006' as bank_code , 
        ' ' as trandate,  
        ' ' as seq_tran,  
       sum(1)over ( order by sc_dep_m_interest_paid.operate_date ,sc_dep_m_interest_paid.account_bank )as seq_no,
     sc_dep_m_creditor.membership_no as membership_no ,
  sc_dep_m_creditor.deposit_account_name  as cmember_name ,
  coalesce(sum(sc_dep_m_interest_paid.interest_paid),0) - 0 as amount ,
  trim(both sc_dep_m_interest_paid.account_bank)  as  acc_no,
' ' as member_group_no,
' '  as c_reference ,
'' as eng_name ,
 'INT' as item_type ,
 left((trim(both sc_dep_m_interest_paid.account_bank)),3) as branch_bank_code,
0 as fee_amount,
sc_dep_m_interest_paid.operate_date  as begining_of_contract 
,'01' as branch_id
,' ' as loan_type 

,sc_dep_m_interest_paid.trans_bank_status as trans_bank_status
,0 as item_seq_no
    from sc_dep_m_interest_paid 
,sc_dep_m_creditor

    where  sc_dep_m_interest_paid.deposit_account_no  = sc_dep_m_creditor.deposit_account_no 
   and sc_dep_m_interest_paid.fixed_due_status = 'M'
    and sc_dep_m_interest_paid.paid_status = '0'
    /*WHERE*/

    group by sc_dep_m_interest_paid.operate_date 
,sc_dep_m_interest_paid.account_bank 
,sc_dep_m_creditor.membership_no
,sc_dep_m_creditor.deposit_account_name
,sc_dep_m_interest_paid.trans_bank_status
    order by sc_dep_m_interest_paid.operate_date ,
        sc_dep_m_interest_paid.account_bank
,sc_dep_m_creditor.membership_no
) tm 
where tm.amount > 0
/*WHERE*/

--and 1=2
;

