-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

CREATE OR REPLACE VIEW vm_com_m_receipt (membership_no, receipt_no, receipt_date, calcint_date, memname, member_group_no, groupname, recept_amount, recept_amount_thai, money_type_id, money_type_name, manager_name, entry_id, user_name) AS SELECT sc_com_m_receipt.membership_no,
         sc_com_m_receipt.receipt_no,   
         sc_com_m_receipt.receipt_date,   
         sc_com_m_receipt.calcint_date,           
         pka_com_function.fp_get_member_name(sc_com_m_receipt.membership_no ) as memname,   
         sc_com_m_receipt.member_group_no,   
         ( select member_group_name FROM sc_mem_m_ucf_member_group where sc_mem_m_ucf_member_group.member_group_no = sc_com_m_receipt.member_group_no ) as groupname,   
         sc_com_m_receipt.recept_amount,   
         pka_com_function.fp_get_moneythai(sc_com_m_receipt.recept_amount )  as recept_amount_thai,   
         sc_com_m_receipt.money_type_id,   
         sc_com_m_ucf_money_type.money_type_name,   
         sc_cnt_m_coop.manager_name,   
         
         sc_com_m_receipt.entry_id ,
         si_security_user.user_name 
         --TGE เงินโอน ให้ออกลายเซนต์ หัวหน้าการเงิน
         --decode( sc_com_m_receipt.money_type_id , 'CSH' , sc_com_m_receipt.entry_id , 'SUWIMOL') as entry_id ,   
         --decode( sc_com_m_receipt.money_type_id , 'CSH' , si_security_user.user_name , (   select user_name from si_security_user where user_id =  'SUWIMOL' ))  as  user_name 
         
    FROM sc_com_m_receipt,   
         sc_com_m_ucf_money_type,   
         sc_cnt_m_coop,   
         si_security_user,
         sc_mem_m_membership_registered
         ,sc_acc_m_account_year
   WHERE 1=1
   and  sc_com_m_receipt.money_type_id = sc_com_m_ucf_money_type.money_type_id   
   and  sc_com_m_receipt.entry_id = si_security_user.user_id    
   and  sc_mem_m_membership_registered.membership_no = sc_com_m_receipt.membership_no
   and  sc_mem_m_membership_registered.member_status_code = '0'
   and  sc_com_m_receipt.receipt_status = '0' 

   and  sc_acc_m_account_year.account_year = 2020
   and  sc_com_m_receipt.receipt_date >= sc_acc_m_account_year.beginning_of_account;

