-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

CREATE OR REPLACE VIEW vm_dep_m_ucf_dep_item_type (deposit_item_type, deposit_item_description, sign_flag, print_code, item_group) AS select DEPOSIT_ITEM_TYPE
,DEPOSIT_ITEM_DESCRIPTION
,SIGN_FLAG
,PRINT_CODE
,ITEM_GROUP FROM sc_dep_m_ucf_dep_item_type;

