-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

CREATE OR REPLACE VIEW vm_doc_inout (io, tdata, requestment_no, loan_contract_no, membership_no, operate_date, doc_type, doc_desc, doc_status, doc_status_desc, doc_amount, remark, remark2, remark3, entry_name) AS select io , tdata , requestment_no ,loan_contract_no, membership_no  ,operate_date , doc_type
,doc_desc , doc_status , doc_status_desc , doc_amount , remark1 , remark2 , remark3 , entry_name

FROM 


( ---- R = receive
  SELECT 'R'as io ,
    'WEF'                AS tdata ,
    sc_wef_req.requestment_no AS requestment_no ,  
    trim(both sc_wef_req.membership_no) AS loan_contract_no ,
    sc_wef_req.membership_no  AS membership_no ,    
    sc_wef_req.operate_date   AS operate_date ,
    sc_wef_req.wef_type       AS doc_type ,
    sc_wef_ucf_type.wef_desc  AS doc_desc ,
    sc_wef_req.approve_status     AS doc_status ,
    CASE sc_wef_req.approve_status
      WHEN '0'
      THEN 'ไม่อนุมัติ'
      WHEN '1'
      THEN 'อนุมัติ'
      ELSE 'รออนุมัติ' 
    END                        AS doc_status_desc ,
    sc_wef_req.total_receive   AS doc_amount ,
    coalesce( sc_wef_req.remark , ' ' )          AS remark1 ,
    coalesce( sc_wef_req.money_type , ' ' )      AS remark2 ,
    coalesce( sc_wef_req.BANK_ACC_NO , ' ' )     AS REMARK3 ,
    si_security_user.user_name AS entry_name
  FROM sc_wef_req ,
    sc_wef_ucf_type ,
    si_security_user 
    ,sc_acc_m_account_constant
  WHERE 1                        =1
  AND sc_wef_req.entry_id        = si_security_user.user_id
  AND sc_wef_req.wef_type        = sc_wef_ucf_type.wef_type
  AND sc_wef_req.cancel_status   = '0'
  and sc_wef_req.operate_date >= sc_acc_m_account_constant.beginning_of_account 


  
UNION ALL


  SELECT 'R'as io ,
    'REQ'                                AS tdata ,
    sc_lon_m_loan_request.loan_requestment_no AS requestment_no , 
    trim(both sc_lon_m_loan_request.membership_no) AS loan_contract_no ,
    sc_lon_m_loan_request.membership_no       AS membership_no ,    
    sc_lon_m_loan_request.requestment_date    AS operate_date ,
    sc_lon_m_loan_request.loan_type           AS doc_type ,
    sc_lon_m_rule.loan_type_description       AS doc_desc ,
    sc_lon_m_loan_request.approve_status     AS doc_status ,
    CASE sc_lon_m_loan_request.approve_status
      WHEN '0'
      THEN 'ไม่อนุมัติ'
      WHEN '1'
      THEN 'อนุมัติ'
      ELSE 'รออนุมัติ'
    END                                      AS doc_status_desc ,
    sc_lon_m_loan_request.mem_request_amount AS doc_amount ,
    coalesce( sc_lon_m_loan_request.remark , ' ' )              AS remark1 ,
    coalesce(( select mpaid.type_pay_money 
      from sc_lon_m_loan_request_mpaid mpaid
      where 1=1
      and seq_no = 1 
      and mpaid.loan_requestment_no = sc_lon_m_loan_request.loan_requestment_no ) , ' ' )      AS remark2 ,
    coalesce(( select mpaid.bank_acc_no 
      from sc_lon_m_loan_request_mpaid mpaid
      where 1=1
      and seq_no = 1 
      and mpaid.loan_requestment_no = sc_lon_m_loan_request.loan_requestment_no ) , ' ' )         AS REMARK3 ,

    si_security_user.user_name AS entry_name
  FROM sc_lon_m_loan_request ,
    sc_lon_m_rule ,
    si_security_user
    ,sc_acc_m_account_constant
  WHERE 1                                       =1
  AND sc_lon_m_loan_request.entry_id            = si_security_user.user_id
  AND sc_lon_m_rule.loan_type                   = sc_lon_m_loan_request.loan_type
  AND sc_lon_m_loan_request.cancel_status       = '0'
  and sc_lon_m_loan_request.requestment_date >= sc_acc_m_account_constant.beginning_of_account 

  
UNION ALL


  SELECT 'R'as io ,
    'DOC'                           AS tdata ,
    sc_eoff_doc_inout.doc_no        AS requestment_no , 
    trim(both sc_eoff_doc_inout.doc_no) as loan_contract_no ,
    sc_eoff_doc_inout.member_fr AS membership_no , 
    sc_eoff_doc_inout.doc_date          AS operate_date ,
    sc_eoff_doc_inout.doc_headcode      AS doc_type ,
    sc_eoff_ucf_doc_headcode.doc_desc              AS doc_desc ,
    sc_eoff_doc_inout.finish_status AS doc_status ,
    CASE sc_eoff_doc_inout.finish_status
      WHEN '1'
      THEN 'เรียบร้อยแล้ว'
      ELSE 'รอดำเนินการ'
    END                           AS doc_status_desc ,
    0                             AS doc_amount ,
    coalesce( sc_eoff_doc_inout.doc_remark , ' ') AS remark1 ,
    coalesce( sc_eoff_doc_inout.doc_signature , ' ') AS remark2 ,
    ' '                            AS REMARK3 ,
    si_security_user.user_name AS entry_name
  FROM sc_eoff_doc_inout ,
    sc_eoff_ucf_doc_headcode ,
    sc_mem_m_membership_registered ,  
    si_security_user
    ,sc_acc_m_account_constant
  WHERE 1                                  =1
  AND sc_eoff_doc_inout.entry_id          = si_security_user.user_id
  AND sc_eoff_doc_inout.doc_headcode      = sc_eoff_ucf_doc_headcode.doc_headcode
  AND sc_eoff_doc_inout.member_fr = sc_mem_m_membership_registered.membership_no
  AND sc_eoff_doc_inout.inout_status      = 'R'    
  AND sc_eoff_doc_inout.cancel_status     = '0' 
  and sc_eoff_doc_inout.doc_date >= sc_acc_m_account_constant.beginning_of_account 

 
UNION ALL


  SELECT 'R'as io ,
    'CTL'                AS tdata ,
    sc_mem_m_chang_request.document_no AS requestment_no ,  
    trim(both sc_mem_m_chang_request.membership_no) AS loan_contract_no ,
    sc_mem_m_chang_request.membership_no  AS membership_no ,    
    sc_mem_m_chang_request.operate_date   AS operate_date ,
    'SHR'       AS doc_type ,
    'CHANGE SHARE'  AS doc_desc ,
    sc_mem_m_chang_request.approve_status     AS doc_status ,
    CASE sc_mem_m_chang_request.approve_status
      WHEN '0'
      THEN 'ไม่อนุมัติ'
      WHEN '1'
      THEN 'อนุมัติ'
      ELSE 'รออนุมัติ'
    END                        AS doc_status_desc ,
    sc_mem_m_chg_share_det.shr_value_new   AS doc_amount ,
    coalesce( sc_mem_m_chg_share_det.remark , ' ')          AS remark1 ,
    ' '      AS remark2 ,
    ' '     AS REMARK3 ,
    si_security_user.user_name AS entry_name
  FROM sc_mem_m_chang_request ,
    sc_mem_m_chg_share_det ,
    si_security_user
    ,sc_acc_m_account_constant
  WHERE 1                        =1
  AND sc_mem_m_chang_request.entry_id        = si_security_user.user_id
  AND sc_mem_m_chang_request.document_no     = sc_mem_m_chg_share_det.document_no
  AND sc_mem_m_chang_request.approve_status   <> '3'  
  and sc_mem_m_chang_request.operate_date >= sc_acc_m_account_constant.beginning_of_account 

 
UNION ALL


  SELECT 'R'as io ,
    'CTL'                AS tdata ,
    sc_mem_m_chang_request.document_no AS requestment_no , 
    trim(both sc_mem_m_chg_loan_det.loan_contract ) AS loan_contract_no ,
    sc_mem_m_chang_request.membership_no  AS membership_no ,    
    sc_mem_m_chang_request.operate_date   AS operate_date ,
    'LON'       AS doc_type ,
    'CHANGE LOAN'  AS doc_desc ,
    sc_mem_m_chang_request.approve_status     AS doc_status ,
    CASE sc_mem_m_chang_request.approve_status
      WHEN '0'
      THEN 'ไม่อนุมัติ'
      WHEN '1'
      THEN 'อนุมัติ'
      ELSE 'รออนุมัติ'
    END                        AS doc_status_desc ,
    sc_mem_m_chg_loan_det.period_payment_new   AS doc_amount ,
    coalesce( sc_mem_m_chg_loan_det.remark , ' ' )          AS remark1 ,
    ' '      AS remark2 ,
    ' '     AS REMARK3 ,
    si_security_user.user_name AS entry_name
  FROM sc_mem_m_chang_request ,
    sc_mem_m_chg_loan_det ,
    si_security_user
    ,sc_acc_m_account_constant
  WHERE 1                        =1
  AND sc_mem_m_chang_request.entry_id        = si_security_user.user_id
  AND sc_mem_m_chang_request.document_no     = sc_mem_m_chg_loan_det.document_no
  AND sc_mem_m_chang_request.approve_status   <> '3'  
  and sc_mem_m_chang_request.operate_date >= sc_acc_m_account_constant.beginning_of_account 

 
UNION ALL
 
 ------ Send 
 SELECT 'S'as io ,
    'DOC'                           AS tdata ,
    sc_hr_doc_inout.doc_no        AS requestment_no ,  
    trim(both sc_hr_doc_inout.doc_no) AS loan_contract_no ,
    sc_hr_doc_inout.member_to AS membership_no ,     
    sc_hr_doc_inout.doc_date          AS operate_date ,
    sc_hr_doc_inout.doc_headcode      AS doc_type ,
    sc_hr_ucf_doc_headcode.doc_desc              AS doc_desc ,
    sc_hr_doc_inout.finish_status AS doc_status ,
    CASE sc_hr_doc_inout.express_status
      WHEN '0' THEN 'ปกติ'
      WHEN '1' THEN 'ด่วน'
      WHEN '2' THEN 'ด่วนมาก'
      WHEN '3' THEN 'ด่วนที่สุด'
      ELSE 'ปกติ'
    END                           AS doc_status_desc ,
    0                             AS doc_amount ,
    coalesce( sc_hr_doc_inout.doc_headline , ' ' ) AS remark1 ,
    coalesce( sc_hr_doc_inout.doc_detailline , ' ' ) AS remark2 ,
    coalesce( sc_hr_doc_inout.doc_remark , ' ' )  AS REMARK3 ,
    si_security_user.user_name AS entry_name
  FROM sc_hr_doc_inout ,
    sc_hr_ucf_doc_headcode ,
    sc_mem_m_membership_registered ,  
    si_security_user
    ,sc_acc_m_account_constant
  WHERE 1                                  =1
  AND sc_hr_doc_inout.entry_id          = si_security_user.user_id
  AND sc_hr_doc_inout.doc_headcode      = sc_hr_ucf_doc_headcode.doc_headcode
  AND sc_hr_doc_inout.member_to = sc_mem_m_membership_registered.membership_no
  AND sc_hr_doc_inout.inout_status      = 'S'        
  AND sc_hr_doc_inout.cancel_status     = '0'   
  and sc_hr_doc_inout.doc_date >= sc_acc_m_account_constant.beginning_of_account 

) tb 
where 1=1
--and tb.membership_no = '015343'
;

