-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

CREATE OR REPLACE VIEW vm_kep_t_monthly_receive (membership_no, receive_year, receive_month, receipt_no, receipt_status, total_share_value, total_interest_value, receipt_effectdate, receipt_paytype, posting_status, seq_no, receipt_date, clearloan_date, kep_method, kep_method_ref, member_group_no, posted_run, kep_method_amount, keeping_amount, amount_from_file, ppm_desc) AS SELECT sc_kep_t_monthly_receive.membership_no,
         sc_kep_t_monthly_receive.receive_year,
         sc_kep_t_monthly_receive.receive_month,
         sc_kep_t_monthly_receive.receipt_no,
         sc_kep_t_monthly_receive.receipt_status,
         sc_kep_t_monthly_receive.total_share_value,
         sc_kep_t_monthly_receive.total_interest_value,
         sc_kep_t_monthly_receive.receipt_effectdate,
         ' ' as receipt_paytype, --Not used
         '0' as posting_status, --Not used
         sc_kep_t_monthly_receive.seq_no,
         sc_kep_t_monthly_receive.receipt_date,
         null as  clearloan_date, --Not used
         sc_kep_t_monthly_receive.kep_method,
         sc_kep_t_monthly_receive.kep_method_ref,
         sc_kep_t_monthly_receive.member_group_no  ,
         sc_kep_t_monthly_receive.posted_run ,

         sc_kep_t_monthly_receive.kep_method_amount,--ยอดที่เก็บได้             
        sc_kep_t_monthly_receive.kep_amount  AS keeping_amount,   --ยอดเรียกเก็บ                           
        sc_kep_t_monthly_receive.amount_form_file  --ตัวแทนนำส่ง
,CASE WHEN  sc_kep_t_monthly_receive.posted_run ='0' THEN 'รอเรียกเก็บ'          ELSE CASE WHEN  receipt_status ='2' THEN  CASE WHEN  ppm_status ='1' THEN  'หักไม่ได้ ตามมาชำระแล้ววันที่ ' || pka_com_function.fp_get_thaidate( ppm_date , 'dd/mm/yyyy' )                                                                    ELSE 'หักไม่ได้/หักไม่ครบ' END                                          ELSE 'เรียกเก็บแล้ว' END  END  as ppm_desc

    FROM sc_kep_t_monthly_receive
    ,sc_acc_m_account_year
    ,sc_mem_m_membership_registered
    WHERE   sc_kep_t_monthly_receive.receipt_date >= sc_acc_m_account_year.beginning_of_account
    AND sc_acc_m_account_year.account_year = 2020
    and sc_mem_m_membership_registered.membership_no = sc_kep_t_monthly_receive.membership_no
--    and sc_mem_m_membership_registered.member_status_code = '0'
    and sc_kep_t_monthly_receive.receipt_date >= sc_acc_m_account_year.beginning_of_account
--    and sc_kep_t_monthly_receive.receipt_date >= '31/3/2021'  --krabi sync 31/3/2021    
--    AND (  sc_kep_t_monthly_receive.receive_year >= 2022 or SC_KEP_T_MONTHLY_RECEIVE.RECEIPT_STATUS = '0' )  --Amnat Only;y;;y
    --Niorn 2023-05-07 TGE agent_active only
    and sc_kep_t_monthly_receive.agent_active = '1';

