-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

CREATE OR REPLACE VIEW vm_kep_crem_web (membership_no, receive_year, receive_month, seq_no, receipt_no, receipt_date, receipt_status, posted_run, crem_code, crem_name, member_group_no, member_group_name, dead_num, money_amount, money_amount_thai, treasurer_name, auditor_name) AS SELECT sc_mem_m_membership_registered.crem_memno as membership_no,
         sc_kep_t_monthly_receive.receive_year,   
         sc_kep_t_monthly_receive.receive_month,   
          sc_kep_t_monthly_receive.seq_no,   
         sc_kep_t_monthly_receive.receipt_no,   
         sc_kep_t_monthly_receive.receipt_date,
         sc_kep_t_monthly_receive.receipt_status,
         sc_kep_t_monthly_receive.posted_run,
   
         sc_kep_t_monthly_receive.membership_no as crem_code,   
         pka_com_function.fp_get_member_name( sc_kep_t_monthly_receive.crem_memno ) as crem_name,   
        sc_kep_t_monthly_receive.member_group_no,   
         sc_mem_m_ucf_member_group.member_group_name,
         sc_kep_t_monthly_receive_det.money_amount_not/20 as dead_num,
         sc_kep_t_monthly_receive_det.money_amount_not as money_amount ,   
         pka_com_function.fp_get_moneythai( sc_kep_t_monthly_receive_det.money_amount_not ) as money_amount_thai,      
         sc_cnt_m_coop.treasurer_name,   
         sc_cnt_m_coop.auditor_name
    FROM sc_kep_t_monthly_receive,   
         sc_mem_m_membership_registered,  
         sc_kep_t_monthly_receive_det,
         sc_mem_m_ucf_member_group,
         sc_cnt_m_coop  
   WHERE ( sc_kep_t_monthly_receive.membership_no = sc_mem_m_membership_registered.membership_no ) and ( sc_kep_t_monthly_receive.membership_no = sc_kep_t_monthly_receive_det.membership_no ) and ( sc_kep_t_monthly_receive.receive_year = sc_kep_t_monthly_receive_det.receive_year ) and ( sc_kep_t_monthly_receive.receive_month = sc_kep_t_monthly_receive_det.receive_month ) and ( sc_kep_t_monthly_receive.seq_no = sc_kep_t_monthly_receive_det.seq_no ) and ( sc_mem_m_ucf_member_group.member_group_no = sc_kep_t_monthly_receive.member_group_no ) 
         and sc_kep_t_monthly_receive.agent_active = '1'
 and pka.isCoop('TGE')= '1';

