-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

CREATE OR REPLACE VIEW vm_mem_m_member_recrieve_gain (membership_no, rec_no, change_doc_no, condition_1, rec_date, order_number, gain_name, related_na, gain_address, gain_percent, gain_id_card, gain_telephone) AS SELECT sc_mem_m_member_recrieve_gain.membership_no,
         sc_mem_m_member_recrieve_gain.rec_no,  
         sc_mem_m_member_recrieve_gain_head.change_doc_no,   
         sc_mem_m_member_recrieve_gain_head.condition_1,   
         --Niorn 2023-06-24 Use book_date 
         sc_mem_m_member_recrieve_gain.book_date as rec_date  ,     

         sc_mem_m_member_recrieve_gain.order_number,  
         ( trim(both sc_mem_m_ucf_prename.prename ) || trim(both sc_mem_m_member_recrieve_gain.gain_name )  || '  ' || trim(both sc_mem_m_member_recrieve_gain.gain_surname )  ) as gain_name,   
         sc_mem_m_ucf_concern.related_na,  
        sc_mem_m_member_recrieve_gain.gain_address,   
         sc_mem_m_member_recrieve_gain.gain_percent,       
         
         sc_mem_m_member_recrieve_gain.gain_id_card,   
         sc_mem_m_member_recrieve_gain.gain_telephone         
           
    FROM sc_mem_m_member_recrieve_gain,   
         sc_mem_m_member_recrieve_gain_head,   
         sc_mem_m_ucf_prename,   
         sc_mem_m_ucf_concern  ,
         sc_mem_m_membership_registered
   WHERE ( sc_mem_m_member_recrieve_gain.membership_no = sc_mem_m_member_recrieve_gain_head.membership_no ) and ( sc_mem_m_member_recrieve_gain.change_doc_no = sc_mem_m_member_recrieve_gain_head.change_doc_no ) and ( sc_mem_m_member_recrieve_gain.prename_code = sc_mem_m_ucf_prename.prename_code ) and ( sc_mem_m_member_recrieve_gain.conceern_code = sc_mem_m_ucf_concern.conceern_code )   
         
   and sc_mem_m_membership_registered.membership_no  = sc_mem_m_member_recrieve_gain.membership_no
   and  sc_mem_m_member_recrieve_gain.gain_status = '0'   
   and sc_mem_m_membership_registered.member_status_code = '0';

