-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

CREATE OR REPLACE VIEW vm_mem_m_ucf_subdistrict (subdistrict_code, subdistrict_name, district_code) AS select SUBDISTRICT_CODE,SUBDISTRICT_NAME,DISTRICT_CODE
FROM SC_MEM_M_UCF_SUBDISTRICT;

