-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

CREATE OR REPLACE VIEW vm_mem_m_member_crem_rec_det (receipt_no, seq_no, item_type, item_amount, description, crem_type, ref_cremmemno, balance) AS select SC_MEM_M_MEMBER_CREM_REC_DET.RECEIPT_NO,
SC_MEM_M_MEMBER_CREM_REC_DET.SEQ_NO,
SC_MEM_M_MEMBER_CREM_REC_DET.ITEM_TYPE,
SC_MEM_M_MEMBER_CREM_REC_DET.ITEM_AMOUNT,
SC_MEM_M_MEMBER_CREM_REC_DET.DESCRIPTION,
SC_MEM_M_MEMBER_CREM_REC_DET.CREM_TYPE,
SC_MEM_M_MEMBER_CREM_REC_DET.REF_CREMMEMNO,
SC_MEM_M_MEMBER_CREM_REC_DET.BALANCE
FROM SC_MEM_M_MEMBER_CREM_REC_DET;

