-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

CREATE OR REPLACE VIEW vm_mem_m_ucf_share_item_type (item_type, item_type_description, sign_flag, cancel_item_ref, cancel_status) AS select
ITEM_TYPE
,ITEM_TYPE_DESCRIPTION
,SIGN_FLAG
,CANCEL_ITEM_REF
,CANCEL_STATUS
FROM SC_MEM_M_UCF_SHARE_ITEM_TYPE;

