-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

CREATE OR REPLACE VIEW vm_msg_send_d (operate_date, msg_no, entry_id, seq_no, membership_no, mobile_no, head_msg, det_msg, send_mode, entry_date, send_date, status_code) AS SELECT
    SC_MSG_SEND_D.OPERATE_DATE,
    SC_MSG_SEND_D.MSG_NO,
    SC_MSG_SEND_D.ENTRY_ID ,
    SC_MSG_SEND_D.SEQ_NO,
    SC_MSG_SEND_D.MEMBERSHIP_NO,
    SC_MSG_SEND_D.MOBILE_NO,
    SC_CNT_M_STATUS_ACTIVE.CODE_DESC as HEAD_MSG,
    SC_MSG_SEND_H.MESSAGES as DET_MSG,
    SC_MSG_SEND_H.SEND_MODE ,
    SC_MSG_SEND_H.ENTRY_DATE ,
    statement_timestamp() as  SEND_DATE ,
    SC_MSG_SEND_H.STATUS_CODE
FROM SC_MSG_SEND_D 
,SC_MSG_SEND_H
,SC_CNT_M_STATUS_ACTIVE
WHERE SC_CNT_M_STATUS_ACTIVE.STATUS_CODE = SC_MSG_SEND_H.STATUS_CODE
AND SC_MSG_SEND_H.OPERATE_DATE = SC_MSG_SEND_D.OPERATE_DATE
AND SC_MSG_SEND_H.MSG_NO = SC_MSG_SEND_D.MSG_NO
AND SC_MSG_SEND_H.ENTRY_ID = SC_MSG_SEND_D.ENTRY_ID
AND SC_MSG_SEND_H.SEND_MODE = 'I'

/*WHERE*/

ORDER BY     SC_MSG_SEND_D.OPERATE_DATE,
    SC_MSG_SEND_D.MSG_NO,
    SC_MSG_SEND_D.SEQ_NO;

