-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

CREATE OR REPLACE VIEW vm_mem_m_ucf_prename (prename_code, prename, sex, marriage_status) AS select PRENAME_CODE
,PRENAME
,SEX
,MARRIAGE_STATUS
FROM sc_mem_m_ucf_prename;

