-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

CREATE OR REPLACE VIEW vr_bon_sum (account_year, membership_no, loan_11, loan_50, mcn_amt, loan_define, all_amt) AS SELECT DISTINCT sc_kep_cut_bonus_item.account_year
, sc_kep_cut_bonus_item.membership_no

,( 	SELECT coalesce( sum( sub.item_amount  ) , 0 ) 
	 FROM sc_kep_cut_bonus_item  sub
	WHERE sub.account_year =  sc_kep_cut_bonus_item.account_year   
	AND		sub.membership_no =   sc_kep_cut_bonus_item.membership_no   
	AND		sub.keeping_type_group =  'LON'    
     AND  		sub.loan_percent  > 0 
	AND		sub.loan_type = '11'    ) as lon_11

,( 	SELECT coalesce( sum( sub.item_amount  ) , 0 ) 
	 FROM sc_kep_cut_bonus_item  sub
	WHERE sub.account_year =  sc_kep_cut_bonus_item.account_year   
	AND		sub.membership_no =   sc_kep_cut_bonus_item.membership_no   
	AND		sub.keeping_type_group =  'LON'    
     AND  		sub.loan_percent  > 0 
	AND		sub.loan_type = '50'    ) as lon_50

,( 	SELECT coalesce( sum( sub.item_amount  ) , 0 ) 
	 FROM sc_kep_cut_bonus_item  sub
	WHERE sub.account_year =  sc_kep_cut_bonus_item.account_year   
	AND		sub.membership_no =   sc_kep_cut_bonus_item.membership_no   
	AND		sub.keeping_type_group =  'MCN'      ) as mcn_amt

,( 	SELECT coalesce( sum( sub.item_amount  ) , 0 ) 
	 FROM sc_kep_cut_bonus_item  sub
	WHERE sub.account_year =  sc_kep_cut_bonus_item.account_year   
	AND		sub.membership_no =   sc_kep_cut_bonus_item.membership_no   
	AND		sub.keeping_type_group =  'LON'    
     AND  		sub.loan_percent  = 0  ) as lon_define


,( 	SELECT coalesce( sum( sub.item_amount  ) , 0 ) 
	 FROM sc_kep_cut_bonus_item  sub
	WHERE sub.account_year =  sc_kep_cut_bonus_item.account_year   
	AND		sub.membership_no =   sc_kep_cut_bonus_item.membership_no    ) as all_amt

    FROM sc_kep_cut_bonus_item   
   WHERE 1=1
  ORDER BY sc_kep_cut_bonus_item.membership_no ASC;

