-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

CREATE OR REPLACE VIEW vr_dep_m_acc_type_date (account_id, account_name, journal_date, dr_amount, cr_amount) AS SELECT sc_acc_m_account_master.account_id,
sc_acc_m_account_master.account_name,
sc_acc_m_general_ledger.journal_date,
sum( sc_acc_m_general_ledger.dr_amount ) as dr_amount,
sum( sc_acc_m_general_ledger.cr_amount ) as cr_amount
FROM sc_acc_m_general_ledger,
sc_acc_m_account_master
WHERE ( sc_acc_m_general_ledger.account_id = sc_acc_m_account_master.account_id ) /*and
( ( sc_acc_m_account_master.account_control_id = '2121000' ) AND
( sc_acc_m_general_ledger.journal_date >= '1/1/2000' ) )*/
GROUP BY sc_acc_m_account_master.account_id,
sc_acc_m_account_master.account_name,
sc_acc_m_general_ledger.journal_date
ORDER BY sc_acc_m_account_master.account_id ASC,
sc_acc_m_general_ledger.journal_date ASC;

