-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

CREATE OR REPLACE VIEW vr_isu_loan_con (membership_no, loan_name, loan_type_description, loan_contract_no, loan_approve_amount, insurance_cost, total_share_value, insure_rate, insure_full, duty, tax, insurance_approve, company_desc, protec_begin) AS SELECT sc_lon_m_contract.membership_no,
         sc_lon_m_contract.loan_name,   
         sc_lon_m_rule.loan_type_description,  
         sc_lon_m_contract.loan_contract_no ,
         sc_lon_m_contract.loan_approve_amount, 
         sc_mem_m_insure.insurance_cost,   
         sc_mem_m_share_mem.share_stock as total_share_value,   
         0.34 AS INSURE_RATE ,
         PKA_LON_REQFEE.fp_port_calc_insure_full(  sc_mem_m_insure.latest_insurance_cost ) as INSURE_FULL ,
         PKA_LON_REQFEE.fp_port_calc_insure_duty(  PKA_LON_REQFEE.fp_port_calc_insure_full(  sc_mem_m_insure.latest_insurance_cost ) ) as DUTY ,
         PKA_LON_REQFEE.fp_port_calc_insure_tax( PKA_LON_REQFEE.fp_port_calc_insure_full(  sc_mem_m_insure.latest_insurance_cost )   , PKA_LON_REQFEE.fp_port_calc_insure_duty(  PKA_LON_REQFEE.fp_port_calc_insure_full(  sc_mem_m_insure.latest_insurance_cost )    )   ) as TAX ,
         sc_mem_m_insure.insurance_approve ,   
         sc_mem_m_ucf_insure_status.company_desc AS COMPANY_DESC,
         sc_mem_m_insure.protec_begin 
         FROM sc_lon_m_contract,   
         sc_mem_m_share_mem,   
         sc_mem_m_insure,   
         sc_lon_m_rule ,
         sc_mem_m_ucf_insure_status
   WHERE ( sc_lon_m_contract.membership_no = sc_mem_m_share_mem.membership_no ) and ( sc_lon_m_contract.loan_contract_no = sc_mem_m_insure.insurance_no ) and ( sc_lon_m_contract.loan_type = sc_lon_m_rule.loan_type ) and ( sc_mem_m_ucf_insure_status.company_status =  sc_mem_m_insure.company_status )
and sc_mem_m_ucf_insure_status.company_status != 'NEW' 

/*WHERE*/

--and sc_mem_m_insure.protec_begin = '31/3/2024'     
 

order by  sc_mem_m_insure.protec_begin, sc_lon_m_contract.loan_contract_no;

