-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

CREATE OR REPLACE VIEW vr_lon_m_kep_over (receive_year, receive_month, membership_no, keeping_type_code, receive_description, principal_not, interest_not, money_amount_not) AS SELECT sc_kep_t_monthly_receive_det.receive_year,
sc_kep_t_monthly_receive_det.receive_month,
sc_kep_t_monthly_receive_det.membership_no,
sc_kep_t_monthly_receive_det.keeping_type_code,
sc_kep_t_monthly_receive_det.receive_description,
sc_kep_t_monthly_receive_det.principal_not,
sc_kep_t_monthly_receive_det.interest_not,
sc_kep_t_monthly_receive_det.money_amount_not
FROM sc_kep_t_monthly_receive_det
WHERE ( sc_kep_t_monthly_receive_det.money_amount = 0 ) AND ( sc_kep_t_monthly_receive_det.money_amount_not > 0 );

