-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

CREATE OR REPLACE VIEW vr_lon_coll_amlo (seq_no, operate_date, loan_contract_no, law_appraise, appraised_rate, loan_reason, coll_ref_des, membership_no) AS select sc_rep_lon_coll_amlo.SEQ_NO,
sc_rep_lon_coll_amlo.OPERATE_DATE,
sc_rep_lon_coll_amlo.LOAN_CONTRACT_NO,
sc_rep_lon_coll_amlo.LAW_APPRAISE,
sc_rep_lon_coll_amlo.APPRAISED_RATE,
sc_rep_lon_coll_amlo.LOAN_REASON,
sc_rep_lon_coll_amlo.COLL_REF_DES,
sc_rep_lon_coll_amlo.membership_no
FROM sc_rep_lon_coll_amlo;

