-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

CREATE OR REPLACE VIEW vr_mcn_mon (crem_type, crem_name_shot, member_group_no, member_group_name, membership_no, memname, crem_number, register_round, crem_arrear, fee_arrear, fee_year_arrear, period_of_month) AS select  sc_mem_m_member_crem_type.crem_type
  , sc_mem_m_member_crem_type.crem_name_shot
  , sc_mem_m_ucf_member_group.member_group_no
  , sc_mem_m_ucf_member_group.member_group_name
  , sc_mem_m_membership_registered.membership_no
  , pka_com_function.fp_get_member_name( sc_mem_m_membership_registered.membership_no)  as memname

  ,sc_mem_m_member_cremation.crem_number
 ,sc_mem_m_member_cremation.register_round
 ,sc_mem_m_member_cremation.crem_arrear
 ,sc_mem_m_member_cremation.fee_arrear
 ,sc_mem_m_member_cremation.fee_year_arrear
 ,sc_mem_m_member_cremation.period_of_month
 
  FROM 		sc_mem_m_membership_registered
  ,sc_mem_m_ucf_member_group
,sc_mem_m_member_cremation
,sc_mem_m_member_crem_type
  where	1=1
  and sc_mem_m_member_crem_type.crem_type = sc_mem_m_member_cremation.crem_type
  and sc_mem_m_membership_registered.member_group_no = sc_mem_m_ucf_member_group.member_group_no 
  and sc_mem_m_membership_registered.member_status_code 	= '0'    
  and sc_mem_m_member_cremation.membership_no = sc_mem_m_membership_registered.membership_no  
  and sc_mem_m_member_cremation.monthly_pay_status = '1' 
  and sc_mem_m_member_cremation.period_of_month > 0 
  and sc_mem_m_member_cremation.crem_status = '0' 
  
  order by  sc_mem_m_member_crem_type.crem_type
  , sc_mem_m_ucf_member_group.member_group_no 
  , sc_mem_m_membership_registered.membership_no;

