-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

CREATE OR REPLACE VIEW vr_nsk_015_012000 (membership_no, deposit_account_no, deposit_account_name, seq_no, item_type, operate_date, last_calcint_date, calpaidintdate, deposit_balance, total_balance, deposit_type_code, deposit_name) AS SELECT sc_dep_m_creditor.membership_no,
         sc_dep_m_creditor.deposit_account_no,   
         sc_dep_m_creditor.deposit_account_name,   
         sc_dep_m_creditor_item.seq_no,   
         sc_dep_m_creditor_item.item_type,   
         sc_dep_m_creditor_item.operate_date,   
         sc_dep_m_creditor_item.last_calcint_date,   
         sc_dep_m_creditor_item.calpaidintdate,   
         sc_dep_m_creditor_item.deposit_balance,   
         sc_dep_m_creditor_item.total_balance  ,
         sc_dep_m_rule.deposit_type_code ,
         sc_dep_m_rule.deposit_name
    FROM sc_dep_m_creditor,   
         sc_dep_m_creditor_item  ,
         sc_dep_m_rule
   WHERE ( sc_dep_m_rule.deposit_type_code = sc_dep_m_creditor.deposit_type_code) and ( sc_dep_m_creditor.deposit_account_no = sc_dep_m_creditor_item.deposit_account_no ) and ( sc_dep_m_rule.invest_status = '0' ) 
  
--and sc_dep_m_creditor_item.operate_date between '1/11/2024' and '31/12/2024' 
 
ORDER BY sc_dep_m_creditor.deposit_account_no ASC,   
         sc_dep_m_creditor_item.seq_no ASC;

