-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

CREATE OR REPLACE VIEW vr_nsk_010_025000 (resignation_approve_date, resignation_approve_id, membership_no, memname, member_group_no, member_group_name, approve_date, mem_type_code, mem_type_desc) AS SELECT sc_mem_m_membership_registered.resignation_approve_date,
         sc_mem_m_membership_registered.resignation_approve_id,
         sc_mem_m_membership_registered.membership_no,   
         pka_com_function.fp_get_member_name(  sc_mem_m_membership_registered.membership_no ) as memname,   
         sc_mem_m_ucf_member_group.member_group_no,   
         sc_mem_m_ucf_member_group.member_group_name,   
         sc_mem_m_membership_registered.approve_date,   
         sc_mem_m_ucf_member_type.mem_type_code,   
         sc_mem_m_ucf_member_type.mem_type_desc  
    FROM sc_mem_m_membership_registered,   
         sc_mem_m_ucf_member_group,   
         sc_mem_m_ucf_member_type  
   WHERE ( sc_mem_m_membership_registered.member_group_no = sc_mem_m_ucf_member_group.member_group_no ) and ( sc_mem_m_membership_registered.mem_type = sc_mem_m_ucf_member_type.mem_type_code ) and ( sc_mem_m_ucf_member_type.invest_status = '0' ) 
 --and sc_mem_m_membership_registered.resignation_approve_date between '1/1/2024' and '31/12/2024'
 
ORDER BY sc_mem_m_membership_registered.resignation_approve_date ASC,   
         sc_mem_m_membership_registered.membership_no ASC;

