-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

CREATE OR REPLACE VIEW vr_nsk_015_005000 (membership_no, prename, member_name, member_surname, receive_month_year, receipt_no, period_of_share, money_of_share, deposit_amount, emer_type, contract_of_emer_loan, period_of_emer_loan, principal_of_emer_loan, interest_of_emer_loan, emer_bal, norm_type, contract_of_norm_loan, period_of_norm_loan, principal_of_norm_loan, interest_of_norm_loan, norm_bal, special_type, contract_of_special_loan, period_of_special_loan, principal_of_special_loan, interest_of_special_loan, spec_bal, receive_year, receive_month, member_group_no) AS SELECT sc_kep_t_monthly_receive_rep.membership_no,
         sc_mem_m_ucf_prename.prename,   
         sc_mem_m_membership_registered.member_name,   
         sc_mem_m_membership_registered.member_surname,   
         ( sc_kep_t_monthly_receive_rep.receive_month  || '-' ||(sc_kep_t_monthly_receive_rep.receive_year + 543 ) ) as receive_month_year ,          
         sc_kep_t_monthly_receive_rep.receipt_no,   
         sc_kep_t_monthly_receive_rep.period_of_share,   
         sc_kep_t_monthly_receive_rep.money_of_share,   
         sc_kep_t_monthly_receive_rep.deposit_amount,   
         sc_kep_t_monthly_receive_rep.emer_type,   
         sc_kep_t_monthly_receive_rep.contract_of_emer_loan,   
         sc_kep_t_monthly_receive_rep.period_of_emer_loan,   
         sc_kep_t_monthly_receive_rep.principal_of_emer_loan,   
         sc_kep_t_monthly_receive_rep.interest_of_emer_loan,   
         sc_kep_t_monthly_receive_rep.emer_bal,   
         sc_kep_t_monthly_receive_rep.norm_type,   
         sc_kep_t_monthly_receive_rep.contract_of_norm_loan,   
         sc_kep_t_monthly_receive_rep.period_of_norm_loan,   
         sc_kep_t_monthly_receive_rep.principal_of_norm_loan,   
         sc_kep_t_monthly_receive_rep.interest_of_norm_loan,   
         sc_kep_t_monthly_receive_rep.norm_bal,   
         sc_kep_t_monthly_receive_rep.special_type,   
         sc_kep_t_monthly_receive_rep.contract_of_special_loan,   
         sc_kep_t_monthly_receive_rep.period_of_special_loan,   
         sc_kep_t_monthly_receive_rep.principal_of_special_loan,   
         sc_kep_t_monthly_receive_rep.interest_of_special_loan,   
         sc_kep_t_monthly_receive_rep.spec_bal ,
         sc_kep_t_monthly_receive_rep.receive_year ,
         sc_kep_t_monthly_receive_rep.receive_month ,
         sc_kep_t_monthly_receive_rep.member_group_no
    FROM sc_mem_m_ucf_prename,   
         sc_mem_m_membership_registered,   
         sc_kep_t_monthly_receive_rep  
   WHERE ( sc_mem_m_membership_registered.prename_code = sc_mem_m_ucf_prename.prename_code ) and ( sc_mem_m_membership_registered.membership_no = sc_kep_t_monthly_receive_rep.membership_no ) and ( sc_kep_t_monthly_receive_rep.receive_type = 'KEP' )
--sc_kep_t_monthly_receive_rep.receive_year = 2024         
--sc_kep_t_monthly_receive_rep.receive_month = 1         
 
ORDER BY sc_kep_t_monthly_receive_rep.membership_no , 
          sc_kep_t_monthly_receive_rep.receive_year ,
         sc_kep_t_monthly_receive_rep.receive_month ,
         sc_kep_t_monthly_receive_rep.seq_no;

