-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

CREATE OR REPLACE VIEW vr_nsk_010_009000 (balance_date, loan_code, loan_code_desc, member_status_code, member_status_name, loan_type, loan_type_description, count_con, emer_balance, emer_intarr, emer_shot, emer_long) AS SELECT sc_rep_mem_share_loan_bal.balance_date,
         sc_lon_m_ucf_loan_code.loan_code,   
         sc_lon_m_ucf_loan_code.loan_code_desc,   
         sc_mem_m_ucf_member_status.member_status_code,   
         sc_mem_m_ucf_member_status.member_status_name,   
         sc_lon_m_rule.loan_type,   
         sc_lon_m_rule.loan_type_description,   
         count( sc_rep_mem_share_loan_bal.emer_contract ) as count_con,   
         sum( sc_rep_mem_share_loan_bal.emer_balance ) as emer_balance,   
         sum( sc_rep_mem_share_loan_bal.emer_intarr ) as emer_intarr,   
         sum( sc_rep_mem_share_loan_bal.emer_shot ) as emer_shot,   
         sum( sc_rep_mem_share_loan_bal.emer_long ) as emer_long  
    FROM sc_rep_mem_share_loan_bal,   
         sc_mem_m_ucf_member_group,   
         sc_mem_m_ucf_member_status,   
         sc_lon_m_ucf_loan_code,   
         sc_lon_m_rule  
   WHERE ( sc_rep_mem_share_loan_bal.member_group_no = sc_mem_m_ucf_member_group.member_group_no ) and ( sc_rep_mem_share_loan_bal.member_status_code = sc_mem_m_ucf_member_status.member_status_code ) and ( sc_rep_mem_share_loan_bal.emer_loan_code = sc_lon_m_ucf_loan_code.loan_code ) and ( sc_rep_mem_share_loan_bal.emer_loantype = sc_lon_m_rule.loan_type ) and ( sc_rep_mem_share_loan_bal.emer_balance <> 0 ) AND ( sc_lon_m_rule.invest_status = '0' )
         
--AND sc_rep_mem_share_loan_bal.balance_date = '30/11/2024'         
 
GROUP BY sc_rep_mem_share_loan_bal.balance_date,   
         sc_lon_m_ucf_loan_code.loan_code,   
         sc_lon_m_ucf_loan_code.loan_code_desc,   
         sc_mem_m_ucf_member_status.member_status_code,   
         sc_mem_m_ucf_member_status.member_status_name,   
         sc_lon_m_rule.loan_type,   
         sc_lon_m_rule.loan_type_description  
ORDER BY sc_rep_mem_share_loan_bal.balance_date ASC,   
         sc_lon_m_ucf_loan_code.loan_code ASC,   
         sc_mem_m_ucf_member_status.member_status_code ASC,   
         sc_lon_m_rule.loan_type ASC;

