-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

CREATE OR REPLACE VIEW vr_nsk_015_008000 (membership_no, deposit_account_no, memname, operate_date, item_type, deposit_balance, total_balance, deposit_type_code, deposit_name, deposit_item_description, seq_no, sign_flag) AS SELECT sc_dep_m_creditor.membership_no,
         sc_dep_m_creditor.deposit_account_no,   
         pka_com_function.fp_get_member_name( sc_dep_m_creditor.membership_no ) as memname,   
         sc_dep_m_creditor_item.operate_date,   
         sc_dep_m_creditor_item.item_type,   
         sc_dep_m_creditor_item.deposit_balance,   
         sc_dep_m_creditor_item.total_balance,   
         sc_dep_m_creditor.deposit_type_code,   
         sc_dep_m_rule.deposit_name,   
         sc_dep_m_ucf_dep_item_type.deposit_item_description,   
         sc_dep_m_creditor_item.seq_no ,
         sc_dep_m_ucf_dep_item_type.sign_flag
    FROM sc_dep_m_creditor,   
         sc_dep_m_creditor_item,   
         sc_dep_m_rule,   
         sc_dep_m_ucf_dep_item_type  
   WHERE ( sc_dep_m_creditor.deposit_account_no = sc_dep_m_creditor_item.deposit_account_no ) and ( sc_dep_m_creditor.deposit_type_code = sc_dep_m_rule.deposit_type_code ) and ( sc_dep_m_creditor_item.item_type = sc_dep_m_ucf_dep_item_type.deposit_item_type ) and ( sc_dep_m_rule.invest_status = '0' )
--and sc_dep_m_creditor_item.operate_date between '1/1/2024' and '31/1/2024'         
 
ORDER BY sc_dep_m_creditor.deposit_account_no ASC,   
         sc_dep_m_creditor_item.seq_no ASC;

