-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521
-- NOTE: Oracle PIVOT rewritten as conditional aggregation (FILTER) for PostgreSQL.

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

CREATE OR REPLACE VIEW vr_pivot_loan_app (begining_of_contract, "ฉฉ_c_count", "ฉฉ_c_sum", "สส_c_count", "สส_c_sum", "พพ_c_count", "พพ_c_sum", "สม_c_count", "สม_c_sum", "สพ_c_count", "สพ_c_sum", "สป_c_count", "สป_c_sum", "กป_c_count", "กป_c_sum", "ปค_c_count", "ปค_c_sum", "ปพ_c_count", "ปพ_c_sum", "ปก_c_count", "ปก_c_sum", "สก_c_count", "สก_c_sum", "สภ_c_count", "สภ_c_sum", "ส6_c_count", "ส6_c_sum") AS
select d.begining_of_contract
, count(1) filter (where account_id = '1151010') as "ฉฉ_c_count" , sum(loan_amount) filter (where account_id = '1151010') as "ฉฉ_c_sum"
, count(1) filter (where account_id = '1151020') as "สส_c_count" , sum(loan_amount) filter (where account_id = '1151020') as "สส_c_sum"
, count(1) filter (where account_id = '1151030') as "พพ_c_count" , sum(loan_amount) filter (where account_id = '1151030') as "พพ_c_sum"
, count(1) filter (where account_id = '1151080') as "สม_c_count" , sum(loan_amount) filter (where account_id = '1151080') as "สม_c_sum"
, count(1) filter (where account_id = '1153010') as "สพ_c_count" , sum(loan_amount) filter (where account_id = '1153010') as "สพ_c_sum"
, count(1) filter (where account_id = '1153050') as "สป_c_count" , sum(loan_amount) filter (where account_id = '1153050') as "สป_c_sum"
, count(1) filter (where account_id = '1153060') as "กป_c_count" , sum(loan_amount) filter (where account_id = '1153060') as "กป_c_sum"
, count(1) filter (where account_id = '1153061') as "ปค_c_count" , sum(loan_amount) filter (where account_id = '1153061') as "ปค_c_sum"
, count(1) filter (where account_id = '1153062') as "ปพ_c_count" , sum(loan_amount) filter (where account_id = '1153062') as "ปพ_c_sum"
, count(1) filter (where account_id = '1153063') as "ปก_c_count" , sum(loan_amount) filter (where account_id = '1153063') as "ปก_c_sum"
, count(1) filter (where account_id = '1153066') as "สก_c_count" , sum(loan_amount) filter (where account_id = '1153066') as "สก_c_sum"
, count(1) filter (where account_id = '1153067') as "สภ_c_count" , sum(loan_amount) filter (where account_id = '1153067') as "สภ_c_sum"
, count(1) filter (where account_id = '1153070') as "ส6_c_count" , sum(loan_amount) filter (where account_id = '1153070') as "ส6_c_sum"
FROM (
 select sc_lon_m_contract.begining_of_contract , sc_lon_m_rule.account_id , sum(sc_lon_m_contract.loan_approve_amount) as loan_amount
 from sc_lon_m_contract
 ,sc_lon_m_rule
 where 1=1
 and sc_lon_m_rule.loan_type = sc_lon_m_contract.loan_type
 group by sc_lon_m_contract.begining_of_contract ,sc_lon_m_rule.account_id
    ) d
group by d.begining_of_contract
order by d.begining_of_contract;
