-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

CREATE OR REPLACE VIEW vr_tel_insu_info (member_group_no, member_group_name, membership_no, member_name, loan_contract_no, insurance_no, insurance_type, insurance_detail, insurance_approve, insurance_balance, insurance_period, insurance_period_amount, start_keep_date, last_period, insurance_arrear, insurance_arrear_old, insurance_arrear_pending, insurance_status, entry_id, entry_pc, entry_date, entry_br, cancel_status, cancel_id, cancel_pc, cancel_date, cancel_br, keeping_status, pending_amount, insurance_cost, latest_insurance_cost, calc_insurance, ref_contract, ref_insurance_no, begining_of_contract, company_send_status, company_send_amount, company_return, company_add, company_date, company_status, cost_last_year, keep_year, keep_month, drop_payment, post_to_fin, count_krom, protec_begin, protec_end, calc_insurance_cost, calc_continue, prakan_yperiod, insure_year, doc_no, seq_no, company_code, company_name, loan_balance, address_no, moo, soi, road, tambol, district, province, building_type, total_area) AS SELECT
    sc_mem_m_ucf_member_group.member_group_no,
    sc_mem_m_ucf_member_group.member_group_name,
    sc_mem_m_insure.membership_no,
    pka_com_function.fp_get_member_name(sc_mem_m_insure.membership_no)                 AS member_name,
    sc_lon_m_contract.loan_contract_no,
    sc_mem_m_insure.insurance_no,
    sc_mem_m_insure.insurance_type,
    sc_mem_m_insure.insurance_detail,
    sc_mem_m_insure.insurance_approve,
    sc_mem_m_insure.insurance_balance,
    sc_mem_m_insure.insurance_period,
    sc_mem_m_insure.insurance_period_amount,
    sc_mem_m_insure.start_keep_date,
    sc_mem_m_insure.last_period,
    sc_mem_m_insure.insurance_arrear,
    sc_mem_m_insure.insurance_arrear_old,
    sc_mem_m_insure.insurance_arrear_pending,
    sc_mem_m_insure.insurance_status,
    sc_mem_m_insure.entry_id,
    sc_mem_m_insure.entry_pc,
    sc_mem_m_insure.entry_date,
    sc_mem_m_insure.entry_br,
    sc_mem_m_insure.cancel_status,
    sc_mem_m_insure.cancel_id,
    sc_mem_m_insure.cancel_pc,
    sc_mem_m_insure.cancel_date,
    sc_mem_m_insure.cancel_br,
    sc_mem_m_insure.keeping_status,
    sc_mem_m_insure.pending_amount,
    sc_mem_m_insure.insurance_cost,
    sc_mem_m_insure.latest_insurance_cost,
    sc_mem_m_insure.calc_insurance,
    sc_mem_m_insure.ref_contract,
    sc_mem_m_insure.ref_insurance_no,
    sc_mem_m_insure.begining_of_contract,
    sc_mem_m_insure.company_send_status,
    sc_mem_m_insure.company_send_amount,
    sc_mem_m_insure.company_return,
    sc_mem_m_insure.company_add,
    sc_mem_m_insure.company_date,
    sc_mem_m_insure.company_status,
    sc_mem_m_insure.cost_last_year,
    sc_mem_m_insure.keep_year,
    sc_mem_m_insure.keep_month,
    sc_mem_m_insure.drop_payment,
    sc_mem_m_insure.post_to_fin,
    sc_mem_m_insure.count_krom,
    sc_mem_m_insure.protec_begin,
    sc_mem_m_insure.protec_end,
    sc_mem_m_insure.calc_insurance_cost,
    sc_mem_m_insure.calc_continue,
    sc_mem_m_insure.prakan_yperiod,
    sc_mem_m_insure.insure_year,
    sc_mem_m_insure.doc_no,
    sc_mem_m_insure.seq_no,
    sc_mem_m_insure.company_code,
    (select company_name
    FROM sc_fin_ucf_company
    where company_id = sc_mem_m_insure.company_code) as company_name,
    pka_com_function.fp_get_loan_balance_by_mem(sc_mem_m_insure.membership_no)         AS loan_balance,
    pka_rep_estate.fp_get_deed_no(sc_lon_req_coll_law_head.doc_no,'ADD_NO') AS address_no,
    pka_rep_estate.fp_get_deed_no(sc_lon_req_coll_law_head.doc_no,'MOO') AS moo,
    pka_rep_estate.fp_get_deed_no(sc_lon_req_coll_law_head.doc_no,'SOI') as soi,
    pka_rep_estate.fp_get_deed_no(sc_lon_req_coll_law_head.doc_no,'ROAD') as road,
    pka_rep_estate.fp_get_deed_no(sc_lon_req_coll_law_head.doc_no,'TAMBOL') as tambol,
    pka_rep_estate.fp_get_deed_no(sc_lon_req_coll_law_head.doc_no,'DISTRICT') as district,
    pka_rep_estate.fp_get_deed_no(sc_lon_req_coll_law_head.doc_no,'PROVINCE') as province,
    pka_rep_estate.fp_get_home_info(sc_mem_m_insure.doc_no,'BUILDING_TYPE') as building_type,
    pka_rep_estate.fp_get_home_info(sc_mem_m_insure.doc_no,'TOTAL_AREA') as total_area
FROM
    sc_mem_m_insure,
    sc_mem_m_ucf_member_group,
    sc_mem_m_membership_registered,
    sc_lon_req_coll_law_head,
    sc_lon_m_contract_coll,
    sc_lon_m_contract
WHERE sc_lon_req_coll_law_head.doc_no = sc_mem_m_insure.doc_no
    AND sc_lon_m_contract_coll.ref_own_no = sc_lon_req_coll_law_head.doc_no
    AND sc_lon_m_contract.loan_contract_no = sc_lon_m_contract_coll.loan_contract_no
    AND sc_mem_m_membership_registered.membership_no = sc_mem_m_insure.membership_no
    AND sc_mem_m_ucf_member_group.member_group_no = sc_mem_m_membership_registered.member_group_no;

