-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

CREATE OR REPLACE VIEW vr_unkeep_coll (receive_year, receive_month, membership_no, receipt_date, kep_amount, kep_method_amount, unkeep_amount, ref_own_no, loan_contract_no, begining_of_contract, loan_approve_amount, interest_arrear) AS SELECT sc_kep_t_monthly_receive.receive_year
, sc_kep_t_monthly_receive.receive_month
, sc_kep_t_monthly_receive.membership_no  /*ผู้กู้*/
, sc_kep_t_monthly_receive.receipt_date
, sc_kep_t_monthly_receive.kep_amount
, sc_kep_t_monthly_receive.kep_method_amount
, sc_kep_t_monthly_receive.kep_amount   - sc_kep_t_monthly_receive.kep_method_amount as unkeep_amount

, sc_lon_m_contract_coll.ref_own_no /*ผู้ค้ำ*/
, sc_lon_m_contract.loan_contract_no 
, sc_lon_m_contract.begining_of_contract 
, sc_lon_m_contract.loan_approve_amount   
--, sc_lon_m_loan_card.interest_arrear + PKA_LON_INTSRV.fp_calint(  sc_lon_m_contract.loan_contract_no   , to_date(  '!cal_date_1!' , 'dd/mm/yyyy'  ) )  as int_arr  
--, to_date(  '!cal_date_1!' , 'dd/mm/yyyy'  )  as cal_date 
, sc_lon_m_loan_card.interest_arrear
FROM sc_kep_t_monthly_receive  
,sc_lon_m_contract
,sc_lon_m_contract_coll
,sc_lon_m_loan_card
WHERE 1=1
and sc_kep_t_monthly_receive.membership_no = sc_lon_m_contract.membership_no
and sc_lon_m_contract.loan_contract_no = sc_lon_m_contract_coll.loan_contract_no
and sc_lon_m_contract.loan_contract_no = sc_lon_m_loan_card.loan_contract_no
and sc_lon_m_contract_coll.status = '0' 
and sc_lon_m_contract_coll.collateral_type_code = '01' 
and sc_lon_m_loan_card.principal_balance > 0   

and sc_kep_t_monthly_receive.receipt_status = '2'
and sc_kep_t_monthly_receive.kep_amount  > sc_kep_t_monthly_receive.kep_method_amount
and sc_kep_t_monthly_receive.ppm_status = '0'
/*WHERE*/

--and sc_kep_t_monthly_receive.receive_year = 2024   
--and sc_kep_t_monthly_receive.receive_month = 6   
ORDER BY sc_kep_t_monthly_receive.membership_no ASC
,sc_lon_m_contract_coll.ref_own_no;

