-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

CREATE OR REPLACE VIEW vr_unkeep (receive_year, receive_month, membership_no, receipt_date, kep_amount, kep_method_amount, unkeep_amount) AS SELECT  sc_kep_t_monthly_receive.receive_year
, sc_kep_t_monthly_receive.receive_month
, sc_kep_t_monthly_receive.membership_no
, sc_kep_t_monthly_receive.receipt_date
, sc_kep_t_monthly_receive.kep_amount  
, sc_kep_t_monthly_receive.kep_method_amount
, sc_kep_t_monthly_receive.kep_amount   - sc_kep_t_monthly_receive.kep_method_amount as unkeep_amount

FROM sc_kep_t_monthly_receive  
WHERE 1=1
and sc_kep_t_monthly_receive.receipt_status = '2'
and sc_kep_t_monthly_receive.kep_amount  > sc_kep_t_monthly_receive.kep_method_amount
and sc_kep_t_monthly_receive.ppm_status = '0'
/*WHERE*/

--and sc_kep_t_monthly_receive.receive_year = 2024   
--and sc_kep_t_monthly_receive.receive_month = 6   
ORDER BY sc_kep_t_monthly_receive.membership_no ASC;

