-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

CREATE OR REPLACE VIEW vr_wef_sgl_by_day (membership_no, requestment_no, member_group_no, date_of_birth, age_life, mem_approve_date, age_mem, paid_date, total_receive, remark, operate_date, approve_date, wef_type, bank_acc_no, money_type_id, return_status) AS select sc_wef_req.membership_no,
       sc_wef_req.requestment_no,
       sc_mem_m_membership_registered.member_group_no,
       sc_wef_req_sgl.date_of_birth,
       sc_wef_req_sgl.age_life,
       sc_wef_req_sgl.approve_date as mem_approve_date,
       sc_wef_req_sgl.age_mem,
       (select max(paid_date) FROM sc_fin_money_return where sc_wef_req.requestment_no = sc_fin_money_return.refno1) as paid_date,
       sc_wef_req.total_receive,
       sc_wef_req_sgl.remark,
       sc_wef_req.operate_date,
       sc_wef_req.approve_date,
       sc_wef_req.wef_type,
       sc_wef_req.bank_acc_no,
       sc_wef_req.money_type_id,
       sc_fin_money_return.return_status
from sc_wef_req,sc_wef_req_sgl,sc_fin_money_return,sc_mem_m_membership_registered
where sc_wef_req.requestment_no = sc_wef_req_sgl.requestment_no
and sc_mem_m_membership_registered.membership_no = sc_wef_req.membership_no
and sc_wef_req.requestment_no = sc_fin_money_return.refno1
and sc_fin_money_return.cancel_status = '0'
and sc_wef_req.cancel_status = '0'
and sc_wef_req.approve_status = '1'
and sc_wef_req.wef_type = 'SGL';

