-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS tai_sc_lon_m_rule ON sc_lon_m_rule CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_tai_sc_lon_m_rule() RETURNS trigger AS $BODY$
BEGIN
  null;
--  if :old.loan_type is null and :new.loan_type is not null then
--    insert into sc_lon_m_ucf_loan_obj    (loan_type, loan_objective_code , loan_objective_description)
--    values(:new.loan_type,'00','<ไม่ระบุ>');
--  end if;
RETURN NEW;
end
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_tai_sc_lon_m_rule() FROM PUBLIC;

CREATE TRIGGER tai_sc_lon_m_rule
	AFTER INSERT ON sc_lon_m_rule FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_tai_sc_lon_m_rule();

