-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS taiu_sc_mem_m_ucf_salary_level ON sc_mem_m_ucf_salary_level CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_taiu_sc_mem_m_ucf_salary_level() RETURNS trigger AS $BODY$
declare
  li_count integer;
BEGIN
  /*S.Nikom 2009-02-22
  */
  -- กำหนดค่า Default ของแต่ละระดับ;
  if coalesce(OLD.level_code::text, '') = '' or (NEW.level_code IS NOT NULL AND NEW.level_code::text <> '') then
    select count(1) into STRICT li_count
    from sc_mem_m_ucf_salary_rate
    where level_code = NEW.level_code
    and salary_rate_code = 0;
    if coalesce(li_count::text, '') = '' or li_count = 0 then
      insert into sc_mem_m_ucf_salary_rate(
        level_code ,  salary_rate_code)
      values ( NEW.level_code , 0);
    end if;
  end if;

RETURN NEW;
end
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_taiu_sc_mem_m_ucf_salary_level() FROM PUBLIC;

CREATE TRIGGER taiu_sc_mem_m_ucf_salary_level
	AFTER INSERT OR UPDATE ON sc_mem_m_ucf_salary_level FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_taiu_sc_mem_m_ucf_salary_level();

