-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS tau_sc_crem_receive_head ON sc_crem_receive_head CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_tau_sc_crem_receive_head() RETURNS trigger AS $BODY$
BEGIN

--update
 if (NEW.receipt_no IS NOT NULL AND NEW.receipt_no::text <> '')   then

    delete from sc_kep_t_monthly_receive_crm
    where membership_no   =   NEW.membership_no
    and receive_year      =   NEW.receive_year
    and receive_month     =   NEW.receive_month;

    insert into sc_kep_t_monthly_receive_crm( membership_no    ,   receive_year    ,   receive_month   ,   money_amount  ,   crem_code  )
    SELECT membership_no , NEW.receive_year  , NEW.receive_month , sum( amount ) , min( crem_code )
    from sc_crem_receive_det
    where receive_year  = NEW.receive_year
    and receive_month   = NEW.receive_month
    and membership_no   = NEW.membership_no
    group by membership_no
    having sum( amount ) > 0;

  end if;


RETURN NEW;
END
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_tau_sc_crem_receive_head() FROM PUBLIC;

CREATE TRIGGER tau_sc_crem_receive_head
	AFTER UPDATE ON sc_crem_receive_head FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_tau_sc_crem_receive_head();

