-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS tbd_sc_mem_m_ucf_shareloan_sta ON sc_mem_m_ucf_shareloan_status CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_tbd_sc_mem_m_ucf_shareloan_sta() RETURNS trigger AS $BODY$
declare
    li_count integer;
BEGIN
  if pka.auto_entry then
      select count(1) into STRICT li_count 
      from sc_mem_m_membership_registered
      where  shareloan_code = OLD.shareloan_code;
      if li_count > 0 then
          CALL spa_dberror('T12:รหัส('||OLD.shareloan_code||') ถูกใช้งานแล้ว ไม่สามารถลบได้');
      end if;
  end if;
RETURN OLD;
end
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_tbd_sc_mem_m_ucf_shareloan_sta() FROM PUBLIC;

CREATE TRIGGER tbd_sc_mem_m_ucf_shareloan_sta
	BEFORE DELETE ON sc_mem_m_ucf_shareloan_status FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_tbd_sc_mem_m_ucf_shareloan_sta();

