-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS tbd_sc_mem_m_ucf_member_group ON sc_mem_m_ucf_member_group CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_tbd_sc_mem_m_ucf_member_group() RETURNS trigger AS $BODY$
declare
  li_count integer;
BEGIN
  null;
  --ลบหน่วยงานจะทำการเพิ่มแถวข้อมูลในที่อยู่ของหน่วยงานให้
  select count(1) into STRICT li_count
  from sc_mem_m_ucf_member_group_addr
  where member_group_no = OLD.member_group_no;
  if li_count > 0 then
    delete from sc_mem_m_ucf_member_group_addr
    where member_group_no = OLD.member_group_no;
  end if;

RETURN OLD;
end
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_tbd_sc_mem_m_ucf_member_group() FROM PUBLIC;

CREATE TRIGGER tbd_sc_mem_m_ucf_member_group
	BEFORE DELETE ON sc_mem_m_ucf_member_group FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_tbd_sc_mem_m_ucf_member_group();

