-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS tbd_sc_mem_m_ucf_other_code ON sc_mem_m_ucf_other_code CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_tbd_sc_mem_m_ucf_other_code() RETURNS trigger AS $BODY$
declare
    li_count integer;
BEGIN
    if pka.auto_entry then
        select count(1) into STRICT li_count 
        from sc_mem_m_membership_registered
        where  other_code = OLD.MEM_TYPE_CODE;
        if li_count > 0 then
            CALL spa_dberror('T12:รหัส('||OLD.MEM_TYPE_CODE||') ถูกใช้งานแล้ว ไม่สามารถลบได้');
        end if;
    end if;
RETURN OLD;
end
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_tbd_sc_mem_m_ucf_other_code() FROM PUBLIC;

CREATE TRIGGER tbd_sc_mem_m_ucf_other_code
	BEFORE DELETE ON sc_mem_m_ucf_other_code FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_tbd_sc_mem_m_ucf_other_code();

