-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS tbi_si_security_user ON si_security_user CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_tbi_si_security_user() RETURNS trigger AS $BODY$
declare
 ls_valid si_security_user.user_id%type;
 li_valid integer;
BEGIN
  select upper(NEW.user_id) into STRICT ls_valid
;

  select  count( 1 ) into STRICT li_valid
  from    si_security_user
  where   upper( user_id ) = ls_valid;


  if (li_valid > 0 ) then 
     CALL spa_dberror( 'User ID ซ้ำ '||ls_valid);
  end if;
RETURN NEW;
end
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_tbi_si_security_user() FROM PUBLIC;

CREATE TRIGGER tbi_si_security_user
	BEFORE INSERT ON si_security_user FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_tbi_si_security_user();

