-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS tbi_sc_mid_sync ON sc_mid_sync CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_tbi_sc_mid_sync() RETURNS trigger AS $BODY$
BEGIN

  if coalesce(NEW.OPERATE_TIME::text, '') = '' then NEW.OPERATE_TIME :=   TO_CHAR(statement_timestamp(), 'DD/MM/YYYY HH24:MI:SS');end if;
  if coalesce(NEW.OPERATE_DATE::text, '') = '' then NEW.OPERATE_DATE := to_date(statement_timestamp(),'dd/mm/yyyy');end if;
  if coalesce(NEW.APP_NAME::text, '') = '' then NEW.APP_NAME :=  trim(both pka_com_login.login_app);end if;
  if coalesce(NEW.S_URL::text, '') = '' then NEW.S_URL :=  trim(both pka_com_login.login_CurDir);end if;
  if coalesce(NEW.ENTRY_DATE::text, '') = '' then NEW.ENTRY_DATE :=  statement_timestamp();end if;
  if coalesce(NEW.ENTRY_ID::text, '') = '' then NEW.ENTRY_ID :=  pka_com_function.fp_login_id;end if;
  if coalesce(NEW.ENTRY_BRANCH::text, '') = '' then NEW.ENTRY_BRANCH := pka_com_function.fp_login_br;end if;


RETURN NEW;
end
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_tbi_sc_mid_sync() FROM PUBLIC;

CREATE TRIGGER tbi_sc_mid_sync
	BEFORE INSERT ON sc_mid_sync FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_tbi_sc_mid_sync();

