-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS tbiu_sc_mem_m_ucf_prename ON sc_mem_m_ucf_prename CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_tbiu_sc_mem_m_ucf_prename() RETURNS trigger AS $BODY$
BEGIN

  if coalesce(NEW.SEX::text, '') = '' then
    NEW.SEX := pka_srv_dbattrib.getdefault('sc_mem_m_ucf_prename','SEX');
  else
    if coalesce(OLD.SEX::text, '') = '' or OLD.SEX <> NEW.SEX then
      if NEW.SEX  not in ('M','F') then
        CALL spa_dberrcol('sc_mem_m_ucf_prename','SEX',NEW.SEX );
      end if;
    end if;
  end if;

  if coalesce(NEW.MARRIAGE_STATUS::text, '') = '' then
    NEW.MARRIAGE_STATUS := '0';
  end if;

  if coalesce(NEW.group_rank::text, '') = '' or NEW.group_rank = ' ' then NEW.group_rank := 'E';end if;

RETURN NEW;
end
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_tbiu_sc_mem_m_ucf_prename() FROM PUBLIC;

CREATE TRIGGER tbiu_sc_mem_m_ucf_prename
	BEFORE INSERT OR UPDATE ON sc_mem_m_ucf_prename FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_tbiu_sc_mem_m_ucf_prename();

