-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS tbiu_sc_kep_m_ucf_keeping_item ON sc_kep_m_ucf_keeping_item_type CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_tbiu_sc_kep_m_ucf_keeping_item() RETURNS trigger AS $BODY$
BEGIN

  -- Detault
  if coalesce(NEW.priority::text, '') = '' then NEW.priority := 0;end if;
  if coalesce(NEW.sorting::text, '') = '' then NEW.sorting :=0;end if;
  if coalesce(NEW.keeping_type_group::text, '') = '' or NEW.keeping_type_group = ' ' then NEW.keeping_type_group :='ETC';end if;
  if coalesce(NEW.goods_status::text, '') = '' or NEW.goods_status <> '1' then NEW.goods_status :='0';end if;
  if coalesce(NEW.external_item::text, '') = '' or NEW.external_item =' ' then NEW.external_item :='0';end if;

RETURN NEW;
end
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_tbiu_sc_kep_m_ucf_keeping_item() FROM PUBLIC;

CREATE TRIGGER tbiu_sc_kep_m_ucf_keeping_item
	BEFORE INSERT OR UPDATE ON sc_kep_m_ucf_keeping_item_type FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_tbiu_sc_kep_m_ucf_keeping_item();

