-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS tbiu_sc_kep_return_piority ON sc_kep_return_piority CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_tbiu_sc_kep_return_piority() RETURNS trigger AS $BODY$
BEGIN

  if pka.auto_seqno then
    if coalesce(NEW.seq_no::text, '') = '' or NEW.seq_no = 0 then
      select max(seq_no)  into STRICT NEW.seq_no
      from sc_kep_return_piority;
      NEW.seq_no  := coalesce(NEW.seq_no,0) + 1;
    end if;
  end if;

  if coalesce(NEW.TYPE_MONEY::text, '') = '' or NEW.TYPE_MONEY = ' ' then
    NEW.TYPE_MONEY := 'M';
  else

    if coalesce(OLD.TYPE_MONEY::text, '') = '' or OLD.TYPE_MONEY <> NEW.TYPE_MONEY then
      if NEW.TYPE_MONEY not in ('M','P','I','A','T') then
        CALL spa_dberrcol('sc_kep_return_piority','TYPE_MONEY',NEW.TYPE_MONEY);
      end if;
    end if;
  end if;



  if NEW.type_money <> 'M' then
    if substr(NEW.keep_type,1,2) <> 'ML' then
      CALL spa_dberrcol('sc_kep_return_piority','keep_type','รายการเงินกู้เท่านั้นที่สามารถกำหนดเป็นเงินต้นดอกเบี้ยได้'||trim(both NEW.keep_type));
    end if;
  end if;

  if coalesce(NEW.CUT_STATUS::text, '') = '' or NEW.CUT_STATUS = ' ' then NEW.CUT_STATUS :='0';end if;

  if substr(NEW.keep_type,1,2) = 'MS' then
    NEW.TYPE_MONEY := 'M';
  end if;

  --Niorn 2023-03-07 TGE loan_type is not null 
  if coalesce(NEW.loan_type::text, '') = '' and substr(NEW.keep_type,1,2) = 'ML' then
    NEW.loan_type := trim(both substr( NEW.keep_type , 3,4 ));
  end if;


RETURN NEW;
end
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_tbiu_sc_kep_return_piority() FROM PUBLIC;

CREATE TRIGGER tbiu_sc_kep_return_piority
	BEFORE INSERT OR UPDATE ON sc_kep_return_piority FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_tbiu_sc_kep_return_piority();

