-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS tbiu_sc_lon_m_req_fund_ret ON sc_lon_m_req_fund_ret CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_tbiu_sc_lon_m_req_fund_ret() RETURNS trigger AS $BODY$
declare
  li_count integer;
  ls_memno sc_lon_m_loan_request.membership_no%type;
BEGIN

  if pka.auto_seqno then
    if coalesce(NEW.seq_no::text, '') = '' or NEW.seq_no = 0 then
      select max(seq_no) into STRICT NEW.seq_no
      from sc_lon_m_req_fund_ret
      where (loan_requestment_no = NEW.loan_requestment_no);
      NEW.seq_no := coalesce(NEW.seq_no,0) + 1;
    end if;
  end if;

  if coalesce(NEW.fund_ret::text, '') = '' then NEW.fund_ret :=0;end if;
  if coalesce(NEW.approve_amount::text, '') = '' then NEW.approve_amount :=0;end if;

  if coalesce(NEW.fund_int::text, '') = '' then NEW.fund_int :=0;end if;
  if coalesce(NEW.fund_real::text, '') = '' or NEW.fund_real = 0 then NEW.fund_real := NEW.fund_ret + NEW.fund_int;end if;

  
  --Niorn 20200930 KTM หนี้เก่าไม่ใช่ของตนเอง
  select membership_no into STRICT ls_memno from sc_lon_m_loan_request
  where loan_requestment_no = NEW.loan_requestment_no;

  if NEW.deposit_account_no = 'NEW' then
      select count(1) into STRICT li_count 
      from sc_fund_mem
      where membership_no = ls_memno;
      if coalesce(li_count::text, '') = '' or li_count = 0 then
        CALL spa_dberror('T34:กองทุน ไม่ใช่ของผู้กู้');
      end if;
  else
      select count(1) into STRICT li_count
      from sc_dep_m_creditor
      where membership_no = ls_memno
      and deposit_account_no = NEW.deposit_account_no;
      if coalesce(li_count::text, '') = '' or li_count = 0 then
        CALL spa_dberror('T42:เงินฝากสวัสดิการ ไม่ใช่ของผู้กู้');
      end if;
  end if;

RETURN NEW;
end
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_tbiu_sc_lon_m_req_fund_ret() FROM PUBLIC;

CREATE TRIGGER tbiu_sc_lon_m_req_fund_ret
	BEFORE INSERT OR UPDATE ON sc_lon_m_req_fund_ret FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_tbiu_sc_lon_m_req_fund_ret();

