-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS tbiu_sc_lon_ins_m_constant ON sc_lon_ins_m_constant CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_tbiu_sc_lon_ins_m_constant() RETURNS trigger AS $BODY$
BEGIN
  if coalesce(NEW.loan_insure_force::text, '') = '' then NEW.loan_insure_force := 0;end if;
  if coalesce(NEW.insure_rate::text, '') = '' then NEW.insure_rate := 0;end if;
RETURN NEW;
end
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_tbiu_sc_lon_ins_m_constant() FROM PUBLIC;

CREATE TRIGGER tbiu_sc_lon_ins_m_constant
	BEFORE INSERT OR UPDATE ON sc_lon_ins_m_constant FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_tbiu_sc_lon_ins_m_constant();

