-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS tbiu_sc_lon_m_coll_change_det ON sc_lon_m_coll_change_det CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_tbiu_sc_lon_m_coll_change_det() RETURNS trigger AS $BODY$
BEGIN
  if coalesce(NEW.seq_no::text, '') = '' or NEW.seq_no = 0 then
    select max(seq_no) into STRICT NEW.seq_no
    from sc_lon_m_coll_change_det
    where (change_doc_no = NEW.change_doc_no);
    NEW.seq_no := coalesce(NEW.seq_no,0) + 1;
  end if;
  if coalesce(NEW.new_collateral_amount::text, '') = '' then NEW.new_collateral_amount := 0;end if;
  if coalesce(NEW.evaluate_coll::text, '') = '' then NEW.evaluate_coll := 0;end if;
RETURN NEW;
end
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_tbiu_sc_lon_m_coll_change_det() FROM PUBLIC;

CREATE TRIGGER tbiu_sc_lon_m_coll_change_det
	BEFORE INSERT OR UPDATE ON sc_lon_m_coll_change_det FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_tbiu_sc_lon_m_coll_change_det();

