-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS tbiu_sc_fin_cheque_print ON sc_fin_cheque_print CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_tbiu_sc_fin_cheque_print() RETURNS trigger AS $BODY$
BEGIN

  if coalesce(NEW.set_cross_account::text, '') = '' or NEW.set_cross_account = ' ' then NEW.set_cross_account :='0';end if;
  if coalesce(NEW.set_cross_general::text, '') = '' or NEW.set_cross_general = ' ' then NEW.set_cross_general :='0';end if;
  if coalesce(NEW.set_cross_member::text, '') = '' or NEW.set_cross_member = ' ' then NEW.set_cross_member :='0';end if;
  if coalesce(NEW.set_without_date::text, '') = '' or NEW.set_without_date = ' ' then NEW.set_without_date :='0';end if;

  if coalesce(NEW.cancel_status::text, '') = '' or NEW.cancel_status = ' ' then NEW.cancel_status :='0';end if;
  if coalesce(NEW.paid_status::text, '') = '' or NEW.paid_status = ' ' then NEW.paid_status := '0';end if;
  if coalesce(NEW.bank_status::text, '') = '' or NEW.bank_status = ' ' then NEW.bank_status := '0';end if;

  if (coalesce(OLD.bank_fin::text, '') = '' and (NEW.bank_fin IS NOT NULL AND NEW.bank_fin::text <> '')) then
    if (pka.auto_entry) then 
      NEW.entry_id := current_setting('app.login_id', true);
      NEW.entry_date := statement_timestamp();
      NEW.entry_branch := current_setting('app.login_br', true);
      NEW.entry_client := pka_com_login.login_pc;
    end if;
  end if;

  if pka.auto_seqno then
        if NEW.seq_no = 0 or coalesce(NEW.seq_no::text, '') = '' then 
            select max(seq_no) into STRICT NEW.seq_no 
            from sc_fin_cheque_print
            where bank_fin = NEW.bank_fin
            and book_no = NEW.book_no 
            and cheque_no = NEW.cheque_no;
            NEW.seq_no := coalesce(NEW.seq_no,0) + 1;
        end if;
  end if;


RETURN NEW;
end
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_tbiu_sc_fin_cheque_print() FROM PUBLIC;

CREATE TRIGGER tbiu_sc_fin_cheque_print
	BEFORE INSERT ON sc_fin_cheque_print FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_tbiu_sc_fin_cheque_print();

