-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS tbiu_sc_rep_scq_form8_mis65 ON sc_rep_scq_form8_mis65 CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_tbiu_sc_rep_scq_form8_mis65() RETURNS trigger AS $BODY$
BEGIN
    if coalesce(NEW.time_now::text, '') = '' then NEW.time_now := 0;end if;
    if coalesce(NEW.time_d2_d7::text, '') = '' then NEW.time_d2_d7 :=0;end if;
    if coalesce(NEW.time_d8_m1::text, '') = '' then NEW.time_d8_m1 :=0;end if;
    if coalesce(NEW.time_m1g_m3::text, '') = '' then NEW.time_m1g_m3 :=0;end if;
    if coalesce(NEW.time_m3g_m6::text, '') = '' then NEW.time_m3g_m6 :=0;end if;
    if coalesce(NEW.time_m6g_m12::text, '') = '' then NEW.time_m6g_m12 :=0;end if;
    if coalesce(NEW.time_y1g_y5::text, '') = '' then NEW.time_y1g_y5 := 0;end if;
    if coalesce(NEW.time_y5g_y10::text, '') = '' then NEW.time_y5g_y10 :=0;end if;
    if coalesce(NEW.time_y10g::text, '') = '' then NEW.time_y10g :=0;end if;
    if coalesce(NEW.time_noterm::text, '') = '' then NEW.time_noterm :=0;end if;

    if coalesce(NEW.time_1m::text, '') = '' then NEW.time_1m :=0;end if;
    if coalesce(NEW.time_2m::text, '') = '' then NEW.time_2m :=0;end if;
    if coalesce(NEW.time_3m::text, '') = '' then NEW.time_3m :=0;end if;
    if coalesce(NEW.time_4m::text, '') = '' then NEW.time_4m :=0;end if;
    if coalesce(NEW.time_5m::text, '') = '' then NEW.time_5m :=0;end if;
    if coalesce(NEW.time_6m::text, '') = '' then NEW.time_6m :=0;end if;
    if coalesce(NEW.time_7m::text, '') = '' then NEW.time_7m :=0;end if;
    if coalesce(NEW.time_8m::text, '') = '' then NEW.time_8m :=0;end if;
    if coalesce(NEW.time_9m::text, '') = '' then NEW.time_9m :=0;end if;
    if coalesce(NEW.time_10m::text, '') = '' then NEW.time_10m :=0;end if;
    if coalesce(NEW.time_11m::text, '') = '' then NEW.time_11m :=0;end if;
    if coalesce(NEW.time_12m::text, '') = '' then NEW.time_12m :=0;end if;

RETURN NEW;
end
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_tbiu_sc_rep_scq_form8_mis65() FROM PUBLIC;

CREATE TRIGGER tbiu_sc_rep_scq_form8_mis65
	BEFORE INSERT OR UPDATE ON sc_rep_scq_form8_mis65 FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_tbiu_sc_rep_scq_form8_mis65();

