-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS tbiu_sc_mem_m_insure_det ON sc_mem_m_insure_det CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_tbiu_sc_mem_m_insure_det() RETURNS trigger AS $BODY$
BEGIN
  --seq_no
  if coalesce(NEW.seq_no::text, '') = '' or NEW.seq_no = 0 then
    select max(seq_no) into STRICT NEW.seq_no
    from SC_MEM_M_INSURE_DET
    where insurance_no  = NEW.insurance_no;
    NEW.seq_no := coalesce(NEW.seq_no,0) + 1;
  end if;

  if coalesce(trim(both NEW.entry_id)::text, '') = ''  then
    NEW.entry_id  := current_setting('app.login_id', true);
  end if;
  if coalesce(trim(both NEW.entry_date)::text, '') = ''  then
    NEW.entry_date  := statement_timestamp();
  end if;

  if coalesce(trim(both NEW.ref_docno)::text, '') = '' then
    NEW.ref_docno := 'CNV';
  end if;
  --ยอดเงินต่างๆ
  if coalesce(NEW.AMOUNT_PAY_ARREAR::text, '') = ''  then
    NEW.amount_pay_arrear := 0;
  end if;
  if coalesce(NEW.insurance_arrear_all::text, '') = '' then
    NEW.insurance_arrear_all := 0;
  end if;

RETURN NEW;
end
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_tbiu_sc_mem_m_insure_det() FROM PUBLIC;

CREATE TRIGGER tbiu_sc_mem_m_insure_det
	BEFORE INSERT OR UPDATE ON sc_mem_m_insure_det FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_tbiu_sc_mem_m_insure_det();

