-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS tbiu_sc_lon_m_loan_card_detail ON sc_lon_m_loan_card_detail CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_tbiu_sc_lon_m_loan_card_detail() RETURNS trigger AS $BODY$
BEGIN
  --//--Auto
  if pka.auto_seqno then
    if coalesce(NEW.seq_no::text, '') = '' or NEW.seq_no = 0 then
      select max(seq_no) into STRICT NEW.seq_no
      from sc_lon_m_loan_card_detail
      where (loan_contract_no = NEW.loan_contract_no);
      NEW.seq_no := coalesce(NEW.seq_no,0) + 1;
    end if;
  end if;
  --//--Insert    
  if (coalesce(OLD.loan_contract_no::text, '') = '' and (NEW.loan_contract_no IS NOT NULL AND NEW.loan_contract_no::text <> '')) then
    if (pka.auto_entry) then
      NEW.branch_id := current_setting('app.login_br', true);
      NEW.entry_id := current_setting('app.login_id', true);
      NEW.entry_date := statement_timestamp();
    end if;
  end if;
  --//--Default
  if coalesce(NEW.status::text, '') = ''  then NEW.status := '0';end if;

  if coalesce(NEW.finance_date::text, '') = '' then
    if pka_fin.fp_post2fin then
      NEW.finance_date := pka_fin_daily.fp_finance_date('1'); --Mobile ไม่มองวันที่การเงิน
    end if;
  end if;

  NEW.branch_id := current_setting('app.login_br', true);
  NEW.entry_id := current_setting('app.login_id', true);
  NEW.entry_date := statement_timestamp();
      
      
RETURN NEW;
end
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_tbiu_sc_lon_m_loan_card_detail() FROM PUBLIC;

CREATE TRIGGER tbiu_sc_lon_m_loan_card_detail
	BEFORE INSERT OR UPDATE ON sc_lon_m_loan_card_detail FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_tbiu_sc_lon_m_loan_card_detail();

