-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS tbiu_sc_cnt_m_salary_paid ON sc_cnt_m_salary_paid CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_tbiu_sc_cnt_m_salary_paid() RETURNS trigger AS $BODY$
BEGIN
  if coalesce(NEW.ACCOUNT_YEAR::text, '') = '' then NEW.ACCOUNT_YEAR := 0;end if;
  if coalesce(NEW.ACCOUNT_MONTH::text, '') = '' then NEW.ACCOUNT_MONTH := 0;end if;
RETURN NEW;
end
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_tbiu_sc_cnt_m_salary_paid() FROM PUBLIC;

CREATE TRIGGER tbiu_sc_cnt_m_salary_paid
	BEFORE INSERT OR UPDATE ON sc_cnt_m_salary_paid FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_tbiu_sc_cnt_m_salary_paid();

