-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS tbiu_sc_lon_m_loanamount_level ON sc_lon_m_loanamount_level CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_tbiu_sc_lon_m_loanamount_level() RETURNS trigger AS $BODY$
BEGIN

  if pka_com_valid.var_number(NEW.seq_no) = '0' then
    select max(seq_no) into STRICT NEW.seq_no
    from sc_lon_m_loanamount_level
    where loan_type = NEW.loan_type;
    if coalesce(NEW.seq_no::text, '') = '' then NEW.seq_no := 0;end if;
    NEW.seq_no := NEW.seq_no + 1;
  end if;

  if coalesce(NEW.OLD_PERCENT::text, '') = '' then NEW.OLD_PERCENT :=0;end if;
  if coalesce(NEW.PERCENT_SHARE_PER_LOAN::text, '') = '' then NEW.PERCENT_SHARE_PER_LOAN :=0;end if;
  if coalesce(NEW.NUM_COLL::text, '') = '' then NEW.NUM_COLL :=0;end if;
  if coalesce(NEW.PERCENT_SHARE_SUMCOLL::text, '') = '' then NEW.PERCENT_SHARE_SUMCOLL :=0;end if;
  if coalesce(NEW.LIMIT_INSTALL::text, '') = '' then NEW.LIMIT_INSTALL :=0;end if;
  if coalesce(NEW.OLD_PERIOD::text, '') = '' then NEW.OLD_PERIOD :=0;end if;
  if coalesce(NEW.LOAN_AMOUNT::text, '') = '' then NEW.LOAN_AMOUNT :=0;end if;

  if (coalesce(OLD.loan_type::text, '') = '' and (NEW.loan_type IS NOT NULL AND NEW.loan_type::text <> '')) then
    if (pka.auto_entry) then
      NEW.ENTRY_ID := current_setting('app.login_id', true);
      NEW.ENTRY_DATE := statement_timestamp();
    end if;
  end if;


  if coalesce(NEW.SALARY_BALANCE::text, '') = '' then NEW.SALARY_BALANCE := 0;end if;
  if coalesce(NEW.SALARY_LESS::text, '') = '' then NEW.SALARY_LESS :=0;end if;
  if coalesce(NEW.amount_share_per_loan::text, '') = '' then NEW.amount_share_per_loan := 0;end if;

RETURN NEW;
end
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_tbiu_sc_lon_m_loanamount_level() FROM PUBLIC;

CREATE TRIGGER tbiu_sc_lon_m_loanamount_level
	BEFORE INSERT OR UPDATE ON sc_lon_m_loanamount_level FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_tbiu_sc_lon_m_loanamount_level();

