-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS tbiu_sc_acc_m_expire_histroy ON sc_acc_m_expire_histroy CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_tbiu_sc_acc_m_expire_histroy() RETURNS trigger AS $BODY$
BEGIN

--  if :old.material_id is null and :new.material_id is not null then
--    if pka.auto_entry then
--       :new.entry_date := sysdate;
--       :new.entry_id := current_setting('app.login_id', true);
--    end if;
--  end if;
  if coalesce(NEW.entry_id::text, '') = '' then
      NEW.entry_id := current_setting('app.login_id', true);
  end if;

  if coalesce(NEW.entry_date::text, '') = '' then
      NEW.entry_date := statement_timestamp();
  end if;

  if coalesce(NEW.seq_no::text, '') = '' or NEW.seq_no = 0 then 
    select max(seq_no) into STRICT NEW.seq_no
    from sc_acc_m_expire_histroy
    where material_id = NEW.material_id;
    NEW.seq_no := coalesce(NEW.seq_no,0) + 1;
  end if;

RETURN NEW;
end
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_tbiu_sc_acc_m_expire_histroy() FROM PUBLIC;

CREATE TRIGGER tbiu_sc_acc_m_expire_histroy
	BEFORE INSERT OR UPDATE ON sc_acc_m_expire_histroy FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_tbiu_sc_acc_m_expire_histroy();

