-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS tbiu_sc_impfile_rec_loan ON sc_impfile_rec_loan CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_tbiu_sc_impfile_rec_loan() RETURNS trigger AS $BODY$
BEGIN

  if coalesce(NEW.entry_date::text, '') = '' then NEW.entry_date := statement_timestamp();end if;
  if coalesce(NEW.entry_id::text, '') = '' then NEW.entry_id := current_setting('app.login_id', true);end if;

RETURN NEW;
end
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_tbiu_sc_impfile_rec_loan() FROM PUBLIC;

CREATE TRIGGER tbiu_sc_impfile_rec_loan
	BEFORE INSERT OR UPDATE ON sc_impfile_rec_loan FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_tbiu_sc_impfile_rec_loan();

