-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS tbiu_sc_fin_cheque_registered ON sc_fin_cheque_registered CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_tbiu_sc_fin_cheque_registered() RETURNS trigger AS $BODY$
BEGIN

  if pka.auto_seqno then
    if coalesce(NEW.book_no::text, '') = '' or NEW.book_no = 0 then 
      select max(book_no) into STRICT NEW.book_no
      from sc_fin_cheque_registered
      where bank_fin = NEW.bank_fin;
      NEW.book_no := coalesce(NEW.book_no,0) + 1;
    end if;
  end if;

  --Validate
  if coalesce(NEW.cheque_no_BEGIN::text, '') = '' or NEW.cheque_no_BEGIN = ' ' then
    CALL spa_dberror('กรุณากำหนด เลขที่เช็คเริ่มต้น(cheque_no_begin)');
  end if;
  if coalesce(NEW.cheque_no_end::text, '') = '' or NEW.cheque_no_end = ' ' then
    CALL spa_dberror('กรุณากำหนด เลขที่เช็คสิ้นสุด(cheque_no_end)');
  end if;

  -- Default
  if coalesce(NEW.close_status::text, '') = '' or NEW.close_status = ' ' then NEW.close_status := '0';end if;

  --Entry
  if (coalesce(OLD.bank_fin::text, '') = '' and (NEW.bank_fin IS NOT NULL AND NEW.bank_fin::text <> '')) then
    if (pka.auto_entry) then 
      NEW.entry_date := statement_timestamp();
      NEW.entry_id := current_setting('app.login_id', true);
      NEW.entry_branch := current_setting('app.login_br', true);
      NEW.entry_client := pka_com_login.login_pc;
    end if;
  end if;


RETURN NEW;
end
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_tbiu_sc_fin_cheque_registered() FROM PUBLIC;

CREATE TRIGGER tbiu_sc_fin_cheque_registered
	BEFORE INSERT ON sc_fin_cheque_registered FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_tbiu_sc_fin_cheque_registered();

