-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS tbiu_sc_kep_m_ucf_process ON sc_kep_m_ucf_process CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_tbiu_sc_kep_m_ucf_process() RETURNS trigger AS $BODY$
BEGIN
  if coalesce(NEW.order_no::text, '') = '' then NEW.order_no := 0;end if;
  if coalesce(NEW.external_group::text, '') = '' then NEW.external_group :='0';end if;
  if coalesce(NEW.invisible_status::text, '') = '' or NEW.invisible_status = ' ' then NEW.invisible_status :='0';end if;
  if coalesce(NEW.month_proc::text, '') = '' or NEW.month_proc =' ' then NEW.month_proc := '0';end if;
  if coalesce(NEW.month_post::text, '') = '' or NEW.month_post =' ' then NEW.month_post :='0';end if;
  if coalesce(NEW.month_proc_default::text, '') = '' or NEW.month_proc_default =' ' then NEW.month_proc_default :='0';end if;
  if coalesce(NEW.month_post_default::text, '') = '' or NEW.month_post_default =' ' then NEW.month_post_default :='0';end if;
  if coalesce(NEW.real_keep_post::text, '') = '' or NEW.real_keep_post =' ' then NEW.real_keep_post :='0';end if;
  if coalesce(NEW.external_group::text, '') = '' or NEW.external_group =' ' then NEW.external_group :='0';end if;
  if coalesce(NEW.salary_time_active::text, '') = '' or NEW.salary_time_active =' ' then NEW.salary_time_active :='0';end if;
  if coalesce(NEW.magent_not::text, '') = '' or NEW.magent_not =' ' then NEW.magent_not :='0';end if;
RETURN NEW;
end
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_tbiu_sc_kep_m_ucf_process() FROM PUBLIC;

CREATE TRIGGER tbiu_sc_kep_m_ucf_process
	BEFORE INSERT OR UPDATE ON sc_kep_m_ucf_process FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_tbiu_sc_kep_m_ucf_process();

