-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS tbiu_sc_fin_cheque_paid ON sc_fin_cheque_paid CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_tbiu_sc_fin_cheque_paid() RETURNS trigger AS $BODY$
BEGIN

  if coalesce(NEW.paid_amount::text, '') = '' then NEW.paid_amount := 0;end if;
  if coalesce(NEW.cancel_status::text, '') = '' or NEW.cancel_status <> '1' then NEW.cancel_status := '0';end if;

  if (coalesce(OLD.bank_fin::text, '') = '' and (NEW.bank_fin IS NOT NULL AND NEW.bank_fin::text <> '')) then
    if (pka.auto_entry) then 
      NEW.entry_id := current_setting('app.login_id', true);
      NEW.entry_date := statement_timestamp();
      NEW.entry_branch := current_setting('app.login_br', true);
      NEW.entry_client := pka_com_login.login_pc;
    end if;
  end if;

  -- Auto item_no
  if (pka.auto_seqno) then
    if coalesce(NEW.item_no::text, '') = '' or NEW.item_no = 0 then
      select max(item_no) into STRICT NEW.item_no
      from sc_fin_cheque_paid
      where (bank_fin = NEW.bank_fin)
      and (book_no = NEW.book_no)
      and (cheque_no = NEW.cheque_no)
      and (seq_no = NEW.seq_no);
      if NEW.item_no > 0 then
        NEW.item_no := NEW.item_no + 1;
      else
        NEW.item_no := 1;
      end if;
    end if;
  end if;

  if OLD.cancel_status = '0' and NEW.cancel_status = '1' then
    NEW.cancel_id := current_setting('app.login_id', true);
    NEW.cancel_date := statement_timestamp();
    NEW.cancel_branch := current_setting('app.login_br', true);
  end if;

 --Niorn 2024-05-22 POT เช็ครอขึ้นเงิน ยอดขึ้นเงินต้องเป็น 0
 if NEW.cheque_status = '0'  then
    NEW.cut_amount := 0;
 end if;

RETURN NEW;
end
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_tbiu_sc_fin_cheque_paid() FROM PUBLIC;

CREATE TRIGGER tbiu_sc_fin_cheque_paid
	BEFORE INSERT OR UPDATE ON sc_fin_cheque_paid FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_tbiu_sc_fin_cheque_paid();

