-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS tbiu_sc_mem_m_member_sequester ON sc_mem_m_membership_sequester CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_tbiu_sc_mem_m_member_sequester() RETURNS trigger AS $BODY$
BEGIN
  if coalesce(NEW.membership_no::text, '') = '' then
    CALL spa_dberrcol('sc_mem_m_membership_sequester','membership_no',NEW.membership_no);
  end if;

  if coalesce(NEW.seq_no::text, '') = '' or NEW.seq_no = 0 then
    select max(seq_no) into STRICT NEW.seq_no
    from sc_mem_m_membership_sequester
    where (membership_no = NEW.membership_no);
    NEW.seq_no := coalesce(NEW.seq_no ,0) + 1;
  end if;

  if coalesce(NEW.sqter_status::text, '') = '' then NEW.sqter_status:='0';end if;
  if coalesce(NEW.sqter_share::text, '') = '' then NEW.sqter_share:='0';end if;
  if coalesce(NEW.sqter_div::text, '') = '' then NEW.sqter_div:='0';end if;
  if coalesce(NEW.sqter_aver::text, '') = '' then NEW.sqter_aver:='0';end if;
  if coalesce(NEW.sqter_other::text, '') = '' then NEW.sqter_other:='0';end if;
  if coalesce(NEW.fee_amount::text, '') = '' then NEW.fee_amount :=0;end if;

RETURN NEW;
end
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_tbiu_sc_mem_m_member_sequester() FROM PUBLIC;

CREATE TRIGGER tbiu_sc_mem_m_member_sequester
	BEFORE INSERT OR UPDATE ON sc_mem_m_membership_sequester FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_tbiu_sc_mem_m_member_sequester();

