-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS tbiu_sc_mem_m_ucf_othersaving ON sc_mem_m_ucf_othersaving CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_tbiu_sc_mem_m_ucf_othersaving() RETURNS trigger AS $BODY$
BEGIN
  null;
RETURN NEW;
end
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_tbiu_sc_mem_m_ucf_othersaving() FROM PUBLIC;

CREATE TRIGGER tbiu_sc_mem_m_ucf_othersaving
	BEFORE INSERT OR UPDATE ON sc_mem_m_ucf_othersaving FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_tbiu_sc_mem_m_ucf_othersaving();

