-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS tbiu_sc_kep_t_monthly_salaryin ON sc_kep_t_monthly_salaryin CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_tbiu_sc_kep_t_monthly_salaryin() RETURNS trigger AS $BODY$
BEGIN

  --udon เอาไฟล์เข้าซ้ำได้
  --if :new.salary_time is null then :new.salary_time := 1 ; end if;
 if coalesce(NEW.salary_time::text, '') = '' or NEW.salary_time = 0 then
    select max(salary_time) into STRICT NEW.salary_time
    from sc_kep_t_monthly_salaryin
    where (membership_no=NEW.membership_no)
    and (receive_year=NEW.receive_year)
    and (receive_month=NEW.receive_month)
;
    NEW.salary_time := coalesce(NEW.salary_time,0) + 1;
  end if;

  if coalesce(NEW.salary_total::text, '') = '' then NEW.salary_total :=0;end if;
  if coalesce(NEW.income_total::text, '') = '' then NEW.income_total :=0;end if;
  if coalesce(NEW.expend_total::text, '') = '' then NEW.expend_total :=0;end if;
  if coalesce(NEW.salary_balance::text, '') = '' then NEW.salary_balance :=0;end if;

  if coalesce(NEW.operate_date::text, '') = '' then NEW.operate_date := to_date(statement_timestamp() ,'DD/MM/YYYY');end if;

--Niorn 2023-12-28 TGE เพิ่มเก็บ คนทำ กับ วันเวลา 
NEW.entry_id := current_setting('app.login_id', true);
NEW.entry_date := statement_timestamp();

RETURN NEW;
end
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_tbiu_sc_kep_t_monthly_salaryin() FROM PUBLIC;

CREATE TRIGGER tbiu_sc_kep_t_monthly_salaryin
	BEFORE INSERT OR UPDATE ON sc_kep_t_monthly_salaryin FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_tbiu_sc_kep_t_monthly_salaryin();

