-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS tbiu_sc_mem_m_chg_loan_det ON sc_mem_m_chg_loan_det CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_tbiu_sc_mem_m_chg_loan_det() RETURNS trigger AS $BODY$
BEGIN


  if coalesce(NEW.new_count::text, '') = '' then 
    NEW.new_count := '0';
  end if;
  --0 ไม่เปลี่ยนแปล  4 เปลี่ยนงวดชำระ   
  --1 งดทั้งหมด 2 งดต้น 3 งดดอก
  if NEW.drop_status <> '0' and NEW.drop_status <> '4' and NEW.period_compomise = 0  then
    NEW.period_compomise := 999;
  end if;

RETURN NEW;
end
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_tbiu_sc_mem_m_chg_loan_det() FROM PUBLIC;

CREATE TRIGGER tbiu_sc_mem_m_chg_loan_det
	BEFORE INSERT OR UPDATE ON sc_mem_m_chg_loan_det FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_tbiu_sc_mem_m_chg_loan_det();

