-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS tbiu_sc_lon_m_keep_coll_det ON sc_lon_m_keep_coll_det CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_tbiu_sc_lon_m_keep_coll_det() RETURNS trigger AS $BODY$
BEGIN

  if coalesce(NEW.post_status::text, '') = '' or NEW.post_status = ' ' then NEW.post_status := '0';end if;
  if coalesce(NEW.keeping_status::text, '') = '' or NEW.keeping_status = ' ' then NEW.keeping_status := '0';end if;

  if coalesce(NEW.principal_keep::text, '') = ''  then NEW.principal_keep := 0;end if;
  if coalesce(NEW.interest_keep::text, '') = ''  then NEW.interest_keep := 0;end if;

   if coalesce(NEW.cancel_status::text, '') = '' or NEW.cancel_status = ' ' then NEW.cancel_status := '0';end if;

   if OLD.cancel_status = '0' and  NEW.cancel_status = '1' then 
        NEW.cancel_id := current_setting('app.login_id', true);
        NEW.cancel_date := statement_timestamp();
        NEW.cancel_br := current_setting('app.login_br', true);
   end if;

      
RETURN NEW;
end
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_tbiu_sc_lon_m_keep_coll_det() FROM PUBLIC;

CREATE TRIGGER tbiu_sc_lon_m_keep_coll_det
	BEFORE INSERT OR UPDATE ON sc_lon_m_keep_coll_det FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_tbiu_sc_lon_m_keep_coll_det();

