-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS tbiu_sc_mobile_regis ON sc_mobile_regis CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_tbiu_sc_mobile_regis() RETURNS trigger AS $BODY$
BEGIN

  if coalesce(NEW.seq_no::text, '') = '' or NEW.seq_no = 0 then
    select max(seq_no) into STRICT NEW.seq_no
    from sc_mobile_regis
    where (membership_no = NEW.membership_no);
    NEW.seq_no := NVN(NEW.seq_no) + 1;
  end if;

  if coalesce(NEW.entry_id::text, '') = '' then NEW.entry_id := trim(both pka_com_function.fp_login_id);end if;
  if coalesce(NEW.entry_date::text, '') = '' then NEW.entry_date := statement_timestamp();end if;
  if coalesce(NEW.entry_br::text, '') = '' then NEW.entry_br := trim(both pka_com_function.fp_login_br);end if;

  --Default เป็นยกเลิกไว้ก่อน 
  if coalesce(NEW.close_status::text, '') = '' or NEW.close_status = ' ' then NEW.close_status := '1';end if;
  if coalesce(NEW.mobile_lon::text, '') = '' or NEW.mobile_lon = ' ' then NEW.mobile_lon := 'N';end if;
  if coalesce(NEW.mobile_dep::text, '') = '' or NEW.mobile_dep = ' ' then NEW.mobile_dep := 'N';end if;
  if coalesce(NEW.mobile_trans::text, '') = '' or NEW.mobile_trans = ' ' then NEW.mobile_trans := 'N';end if;
  if coalesce(NEW.mobile_dep_spec::text, '') = '' or NEW.mobile_dep_spec = ' ' then NEW.mobile_dep_spec := 'N';end if;

  --Niorn 2023-06-16 TGE ทำรายการเงินฝากออมทรัพย์พิเศษ 
  if pka.isCoop('TGE') = '1' then
   if NEW.mobile_dep_spec = 'Y' then
        update sc_dep_m_creditor
        set join_status = '0'
        where deposit_type_code in ( '40' , '41')
        and join_status = '1'
        and close_status = '0'
        and membership_no = NEW.membership_no
;
    else
        update sc_dep_m_creditor
        set join_status = '1'
        where deposit_type_code in ( '40' , '41')
        and join_status = '0'
        and close_status = '0'
        and membership_no = NEW.membership_no
;
    end if;

  end if;

  
    --Niorn 2023-03-12 AOT ลงทะเบียนแล้ว ให้ Update เบอร์โทรใน memregis ด้วย
    --BEER 20250820 เปลี่ยนมาใช้ mobile_number ตาม AOT จะได้เข้าใจเหมือนกัน
    if coalesce(OLD.mobile_number::text, '') = '' then
        update sc_mem_m_membership_registered
        set mobile_number = NEW.mobile_number
        where membership_no = NEW.membership_no;
    end if;

RETURN NEW;
end
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_tbiu_sc_mobile_regis() FROM PUBLIC;

CREATE TRIGGER tbiu_sc_mobile_regis
	BEFORE INSERT OR UPDATE ON sc_mobile_regis FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_tbiu_sc_mobile_regis();

