-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS tbiu_sc_mem_m_member_bank ON sc_mem_m_member_bank_accno CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_tbiu_sc_mem_m_member_bank() RETURNS trigger AS $BODY$
declare
  ls_close_status char;
BEGIN
  BEGIN
--return ;
  NEW.entry_id := current_setting('app.login_id', true);
  NEW.entry_date := statement_timestamp();


--Niorn 2021-12-13 Amnat
if NEW.bank_id = '00' then
  NEW.bank_id := '000';
end if;
  if pka.auto_seqno then
    if coalesce(NEW.seq_no::text, '') = '' or NEW.seq_no = 0 then
      select max(seq_no) into STRICT NEW.seq_no
      from sc_mem_m_member_bank_accno
      where (membership_no = NEW.membership_no);
      NEW.seq_no := coalesce(NEW.seq_no,0) + 1;
    end if;
  end if;

  if (trim(both NEW.bank_acc_no) IS NOT NULL AND (trim(both NEW.bank_acc_no))::text <> '') then
    if is_number(NEW.bank_acc_no) = '0' then
      CALL spa_dberror('T17:ทะเบียน('||trim(both NEW.membership_no)||')เลขที่บัญชี('||trim(both NEW.bank_acc_no)||'), ใส่ได้เฉพาะตัวเลขเท่านั้น');
    end if;
  else
    CALL spa_dberror('T21:ทะเบียน('||trim(both NEW.membership_no)||')เลขที่บัญชี('||trim(both NEW.bank_acc_no)||'), กรุณากำหนดเลขที่บัญชี');
  end if;

  if NEW.bank_id = '000' then
    null;
    -- บัญชีเงินฝาก สอ.
    if coalesce(OLD.bank_acc_no,' ') <> coalesce(NEW.bank_acc_no,' ') then
      BEGIN
        select close_status into STRICT ls_close_status
        from sc_dep_m_creditor
        where (deposit_account_no = NEW.bank_acc_no);
      exception when others then CALL spa_dberror('E29:บัญชีเงินฝาก('||trim(both NEW.bank_acc_no)||'),ไม่มีอยู่จริง');
      end;
      if ls_close_status  = 'C' then
        CALL spa_dberror('E32:บัญชีเงินฝาก('||trim(both NEW.bank_acc_no)||'),ปิดบัญชีแล้ว');
      end if;
    end if;
  else
     --บัญชีเงินฝาก ธนาคาร 
    if length(trim(both NEW.bank_acc_no)) < 10 or length(trim(both NEW.bank_acc_no)) > 15 then
      CALL spa_dberror('T40:ทะเบียน('||trim(both NEW.membership_no)||')เลขที่บัญชี('||trim(both NEW.bank_acc_no)||'), บัญชีธนาคารต้องเป็น 10-15 หลักเท่านั้น');
    end if;
  end if;

  if coalesce(trim(both NEW.paid_loan)::text, '') = '' then NEW.paid_loan := '0';end if;
  if coalesce(trim(both NEW.paid_dividen)::text, '') = '' then NEW.paid_dividen :='0';end if;
  if coalesce(trim(both NEW.share_withdraw)::text, '') = '' then NEW.share_withdraw :='0';end if;
  if coalesce(trim(both NEW.atm_lon)::text, '') = '' then NEW.atm_lon := '0';end if;
  if coalesce(trim(both NEW.atm_dep)::text, '') = '' then NEW.atm_dep := '0';end if;
  if coalesce(trim(both NEW.mustcoll_loan)::text, '') = '' then NEW.mustcoll_loan := '0';end if;

  if coalesce(trim(both NEW.money_return)::text, '') = '' then NEW.money_return := '0';end if;
  if coalesce(trim(both NEW.paid_salary)::text, '') = '' then NEW.paid_salary := '0';end if;
  if coalesce(trim(both NEW.paid_agent)::text, '') = '' then NEW.paid_agent := '0';end if;
  if coalesce(trim(both NEW.keep_monthly)::text, '') = '' then NEW.keep_monthly := '0';end if;


--  --แก้ไข ธนาคาร
  if ( (OLD.bank_id IS NOT NULL AND OLD.bank_id::text <> '') and NEW.bank_id <> OLD.bank_id )
    or ( (OLD.bank_acc_no IS NOT NULL AND OLD.bank_acc_no::text <> '') and NEW.bank_acc_no <> OLD.bank_acc_no )
    or ( (OLD.bank_branch_id IS NOT NULL AND OLD.bank_branch_id::text <> '') and NEW.bank_branch_id <> OLD.bank_branch_id )
    or ( (OLD.paid_loan IS NOT NULL AND OLD.paid_loan::text <> '') and NEW.paid_loan <> OLD.paid_loan )
    or ( (OLD.paid_dividen IS NOT NULL AND OLD.paid_dividen::text <> '') and NEW.paid_dividen <> OLD.paid_dividen )
    or ( (OLD.atm_lon IS NOT NULL AND OLD.atm_lon::text <> '') and NEW.atm_lon <> OLD.atm_lon )
    or ( (OLD.atm_dep IS NOT NULL AND OLD.atm_dep::text <> '') and NEW.atm_dep <> OLD.atm_dep )
    or ( (OLD.share_withdraw IS NOT NULL AND OLD.share_withdraw::text <> '') and NEW.share_withdraw <> OLD.share_withdraw )
    or ( (OLD.paid_agent IS NOT NULL AND OLD.paid_agent::text <> '') and NEW.paid_agent <> OLD.paid_agent )
    or ( (OLD.paid_salary IS NOT NULL AND OLD.paid_salary::text <> '') and NEW.paid_salary <> OLD.paid_salary )    

  then 
    --insert  sc_mem_edit_bank
   INSERT INTO sc_mem_edit_bank( membership_no,           entry_date,             entry_id,   
           operate_date,            seq_no,    
           pre_bank_id,          pre_bank_acc_no,         pre_bank_branch_id,          
           bank_id,              bank_acc_no,             bank_branch_id,
           entry_br,
           pre_paid_loan,       pre_paid_dividen,         pre_atm_lon,
           pre_atm_dep,         pre_share_withdraw,       pre_paid_agent,
           pre_paid_salary,
           paid_loan,           paid_dividen,               atm_lon,
           atm_dep,             share_withdraw,             paid_agent,
           paid_salary)  
  VALUES ( NEW.membership_no,        statement_timestamp(),               current_setting('app.login_id', true),   
           TO_DATE( statement_timestamp() ),      NULL ,        
           OLD.bank_id,         OLD.bank_acc_no,     OLD.bank_branch_id,  
           NEW.bank_id,         NEW.bank_acc_no,     NEW.bank_branch_id,
           current_setting('app.login_br', true) ,
           OLD.paid_loan,       OLD.paid_dividen,         OLD.atm_lon,
           OLD.atm_dep,         OLD.share_withdraw,       OLD.paid_agent,
           OLD.paid_salary,
           NEW.paid_loan,       NEW.paid_dividen,         NEW.atm_lon,
           NEW.atm_dep,         NEW.share_withdraw,       NEW.paid_agent,
           NEW.paid_salary ) 
;
  end if;

  END;
RETURN NEW;
end
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_tbiu_sc_mem_m_member_bank() FROM PUBLIC;

CREATE TRIGGER tbiu_sc_mem_m_member_bank
	BEFORE INSERT OR UPDATE ON sc_mem_m_member_bank_accno FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_tbiu_sc_mem_m_member_bank();

