-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS tbiu_sc_atm_mem_regis ON sc_atm_mem_regis CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_tbiu_sc_atm_mem_regis() RETURNS trigger AS $BODY$
BEGIN
  if coalesce(trim(both NEW.open_lon)::text, '') = '' then NEW.open_lon := '0';end if;
  if coalesce(trim(both NEW.open_dep)::text, '') = '' then NEW.open_dep := '0';end if;
  if coalesce(trim(both NEW.atm_open_status)::text, '') = '' then NEW.atm_open_status := '0';end if;
RETURN NEW;
end
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_tbiu_sc_atm_mem_regis() FROM PUBLIC;

CREATE TRIGGER tbiu_sc_atm_mem_regis
	BEFORE INSERT OR UPDATE ON sc_atm_mem_regis FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_tbiu_sc_atm_mem_regis();

