-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS tbiu_sc_lon_m_rule_limitloan ON sc_lon_m_rule_limitloan CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_tbiu_sc_lon_m_rule_limitloan() RETURNS trigger AS $BODY$
BEGIN
  -- วงเงินกู้ของสัญญาใหม่ และ ประเภทสัญญาที่อยู่ในรายการควบคุม รวมกันจะต้องไม่เกิน ldc_loan_limit_control
  -- pka_lon_reqsrv.sp_savevalid_limitloancontrol
  --Validate
  if NEW.loan_type <> ' ' and NEW.loan_type_control <> ' ' then
    if NEW.loan_type = NEW.loan_type_control then
      CALL spa_dberror('วงเงินกู้คุม ไม่สามารถกำหนดประเภทเงินกู้(loan_type) และ ประเภทคุม(loan_type_control) เป็นประเภทเดียวกันได้');
    end if;
  end if;

RETURN NEW;
end
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_tbiu_sc_lon_m_rule_limitloan() FROM PUBLIC;

CREATE TRIGGER tbiu_sc_lon_m_rule_limitloan
	BEFORE INSERT ON sc_lon_m_rule_limitloan FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_tbiu_sc_lon_m_rule_limitloan();

