-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS tbiu_sc_mem_m_member_crem_pay ON sc_mem_m_member_crem_payment CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_tbiu_sc_mem_m_member_crem_pay() RETURNS trigger AS $BODY$
BEGIN


    if coalesce(NEW.seq_no::text, '') = '' then
        select coalesce( max(seq_no), 0 )  into STRICT NEW.seq_no
        from sc_mem_m_member_crem_payment
        where (membership_no = NEW.membership_no)
        and crem_type = NEW.crem_type
;
        NEW.seq_no := coalesce(NEW.seq_no,0) + 1;
    end if;

    -- Default
    if coalesce(NEW.officer_id::text, '') = '' then 
        NEW.officer_id := current_setting('app.login_id', true);
    end if;

    if coalesce(NEW.cancel_status::text, '') = '' then
        NEW.cancel_status := 0;
    end if;

     if NEW.cancel_status = '1' then 
        if coalesce(NEW.cancel_id::text, '') = ''  then NEW.cancel_id := current_setting('app.login_id', true);end if;
        if coalesce(NEW.cancel_date::text, '') = ''  then NEW.cancel_date := statement_timestamp();end if;
        if coalesce(NEW.cancel_br::text, '') = ''  then NEW.cancel_br := current_setting('app.login_br', true);end if;
     end if;

RETURN NEW;
end
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_tbiu_sc_mem_m_member_crem_pay() FROM PUBLIC;

CREATE TRIGGER tbiu_sc_mem_m_member_crem_pay
	BEFORE INSERT OR UPDATE ON sc_mem_m_member_crem_payment FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_tbiu_sc_mem_m_member_crem_pay();

