-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS tbiu_sc_amnat_insure_rep ON sc_amnat_insure_rep CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_tbiu_sc_amnat_insure_rep() RETURNS trigger AS $BODY$
BEGIN
  
  if coalesce(NEW.share_balance::text, '') = '' then NEW.share_balance := 0;end if;
  if coalesce(NEW.loan_balance::text, '') = '' then NEW.loan_balance := 0;end if;
  if coalesce(NEW.loan_coll_balance::text, '') = '' then NEW.loan_coll_balance := 0;end if;

  if coalesce(NEW.coop_paid_mem::text, '') = '' then NEW.coop_paid_mem := 0;end if;
  if coalesce(NEW.coop_paid_krom::text, '') = '' then NEW.coop_paid_krom := 0;end if;
  if coalesce(NEW.coop_paid_amount::text, '') = '' then NEW.coop_paid_amount := 0;end if;
  if coalesce(NEW.div_paid_mem::text, '') = '' then NEW.div_paid_mem := 0;end if;
  if coalesce(NEW.div_paid_krom::text, '') = '' then NEW.div_paid_krom := 0;end if;
  if coalesce(NEW.div_paid_amount::text, '') = '' then NEW.div_paid_amount := 0;end if;
  if coalesce(NEW.cash_paid_mem::text, '') = '' then NEW.cash_paid_mem := 0;end if;
  if coalesce(NEW.cash_paid_krom::text, '') = '' then NEW.cash_paid_krom := 0;end if;
  if coalesce(NEW.cash_paid_amount::text, '') = '' then NEW.cash_paid_amount := 0;end if;
  if coalesce(NEW.insure_paid_mem::text, '') = '' then NEW.insure_paid_mem := 0;end if;
  if coalesce(NEW.insure_paid_krom::text, '') = '' then NEW.insure_paid_krom := 0;end if;
  if coalesce(NEW.insure_paid_amount::text, '') = '' then NEW.insure_paid_amount := 0;end if;

  if coalesce(NEW.insure_status::text, '') = '' then NEW.insure_status := '0';end if;
  if coalesce(NEW.insure_add::text, '') = '' then NEW.insure_add := 0;end if;


RETURN NEW;
end
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_tbiu_sc_amnat_insure_rep() FROM PUBLIC;

CREATE TRIGGER tbiu_sc_amnat_insure_rep
	BEFORE INSERT ON sc_amnat_insure_rep FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_tbiu_sc_amnat_insure_rep();

