-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS tbiu_sc_fin_cheque_print_item ON sc_fin_cheque_print_item CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_tbiu_sc_fin_cheque_print_item() RETURNS trigger AS $BODY$
BEGIN

  if coalesce(NEW.print_amount::text, '') = '' then NEW.print_amount := 0;end if;

  -- ไม่กำหนด item_no ระบบจะ Gen ให้เอง
  if (pka.auto_seqno) then
    if coalesce(NEW.item_no::text, '') = '' or NEW.item_no = 0 then
      select max(item_no) into STRICT NEW.item_no
      from sc_fin_cheque_print_item
      where (bank_fin = NEW.bank_fin)
      and (book_no = NEW.book_no)
      and (cheque_no = NEW.cheque_no)
      and (seq_no = NEW.seq_no);
      if NEW.item_no > 0 then
        NEW.item_no := NEW.item_no + 1;
      else
        NEW.item_no := 1;
      end if;
    end if;
  end if;

  if coalesce(NEW.v_seq_no::text, '') = '' then NEW.v_seq_no :=0;end if;
  if coalesce(NEW.v_seq_fqp::text, '') = '' then NEW.v_seq_fqp :=0;end if;

RETURN NEW;
end
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_tbiu_sc_fin_cheque_print_item() FROM PUBLIC;

CREATE TRIGGER tbiu_sc_fin_cheque_print_item
	BEFORE INSERT ON sc_fin_cheque_print_item FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_tbiu_sc_fin_cheque_print_item();

