-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS tbiu_sc_lon_m_chglog_looping ON sc_lon_m_chglog_looping CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_tbiu_sc_lon_m_chglog_looping() RETURNS trigger AS $BODY$
BEGIN
    if coalesce(NEW.seq_no::text, '') = '' or NEW.seq_no = 0 then
        select max(seq_no) into STRICT NEW.seq_no
        from sc_lon_m_chglog_looping
        where loan_contract_no = NEW.loan_contract_no;
        NEW.seq_no := coalesce(NEW.seq_no,0) + 1;
    end if;

    if coalesce(OLD.loan_contract_no::text, '') = '' and (NEW.loan_contract_no IS NOT NULL AND NEW.loan_contract_no::text <> '') then
        -- Inesrt 
        NEW.entry_id := current_setting('app.login_id', true);
        NEW.entry_time := statement_timestamp();
        NEW.entry_br := current_setting('app.login_br', true);
    end if;
RETURN NEW;
end
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_tbiu_sc_lon_m_chglog_looping() FROM PUBLIC;

CREATE TRIGGER tbiu_sc_lon_m_chglog_looping
	BEFORE INSERT OR UPDATE ON sc_lon_m_chglog_looping FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_tbiu_sc_lon_m_chglog_looping();

