-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS tbiu_sc_lon_m_ucf_lon_card_it ON sc_lon_m_ucf_loan_card_item CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_tbiu_sc_lon_m_ucf_lon_card_it() RETURNS trigger AS $BODY$
BEGIN

  -- Defaul
  if coalesce(NEW.print_code::text, '') = '' or NEW.print_code =' ' then NEW.print_code := NEW.item_type_code;end if;
  if coalesce(NEW.SIGN_STATUS::text, '') = '' then NEW.SIGN_STATUS :=0;end if;

RETURN NEW;
end
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_tbiu_sc_lon_m_ucf_lon_card_it() FROM PUBLIC;

CREATE TRIGGER tbiu_sc_lon_m_ucf_lon_card_it
	BEFORE INSERT ON sc_lon_m_ucf_loan_card_item FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_tbiu_sc_lon_m_ucf_lon_card_it();

