-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS tbiu_sc_lon_m_loan_history ON sc_lon_m_loan_history CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_tbiu_sc_lon_m_loan_history() RETURNS trigger AS $BODY$
declare
  li_count integer;
  ls_memno sc_lon_m_loan_request.membership_no%type;
BEGIN

  if pka.auto_seqno then
    if coalesce(NEW.sequence_no::text, '') = '' or NEW.sequence_no = 0 then
      select max(sequence_no) into STRICT NEW.sequence_no
      from sc_lon_m_loan_history
      where (loan_requestment_no = NEW.loan_requestment_no);
      NEW.sequence_no := coalesce(NEW.sequence_no,0) + 1;
    end if;
  end if;

  if coalesce(NEW.principal_balance_of_loan::text, '') = '' then
    NEW.principal_balance_of_loan := 0;
  end if;

  if coalesce(NEW.principal_of_loan::text, '') = '' then
    NEW.principal_of_loan := 0;
  end if;

  if coalesce(NEW.interest_arrear::text, '') = '' then
    NEW.interest_arrear := 0;
  end if;

  if coalesce(NEW.interest_amount::text, '') = '' then
    NEW.interest_amount := 0;
  end if;

  if coalesce(NEW.payment_amount::text, '') = '' then
    NEW.payment_amount := 0;
  end if;

  if coalesce(NEW.last_period::text, '') = '' then
    NEW.last_period := 0;
  end if;

  if coalesce(NEW.clear_focus::text, '') = '' then
    NEW.clear_focus := '0';
  end if;

  if coalesce(NEW.interest_return::text, '') = '' then
    NEW.interest_return := 0;
  end if;

  if coalesce(NEW.principal_pending_holding::text, '') = '' then
    NEW.principal_pending_holding := 0;
  end if;

  if coalesce(NEW.LOAN_INSTALLMENT::text, '') = '' then
    NEW.LOAN_INSTALLMENT :=0;
  end if;

  if coalesce(NEW.loan_approve_amount::text, '') = '' then NEW.loan_approve_amount :=0;end if;

  if coalesce(NEW.salary_time::text, '') = '' or NEW.salary_time <= 0  then NEW.salary_time := 1;end if;

  if coalesce(NEW.monthly_pay_p::text, '') = '' then NEW.monthly_pay_p := 0;end if;
  if coalesce(NEW.monthly_pay_i::text, '') = '' then NEW.monthly_pay_i := 1;end if;

--  if :new.clear_target = '1' then ข้อมูลเก่าบางอันเป้น 0 
--    if :new.principal_balance_of_loan > 0 or :new.interest_amount > 0 then
--      null;
--    else
--      spa_dberror('เงินต้นหักกลบต้องมากกว่าศูนย์');
--    end if;
--  end if;
  if coalesce(NEW.fund_return::text, '') = '' then NEW.fund_return :=0;end if;

  if pka.auto_entry  then 
    --Niorn 20200930 KTM หนี้เก่าไม่ใช่ของตนเอง
    select membership_no into STRICT ls_memno from sc_lon_m_loan_request
    where loan_requestment_no = NEW.loan_requestment_no;

    select count(1) into STRICT li_count 
    from sc_lon_m_loan_card
    where membership_no = ls_memno
    and loan_contract_no = NEW.loan_contract_no;
    if coalesce(li_count::text, '') = '' or li_count = 0 then
      CALL spa_dberror('T95:หนี้ที่หักกลบ ไม่ใช่ของผู้กู้ req_no=' || NEW.loan_requestment_no || ' connno='||NEW.loan_contract_no );
    end if;
  end if;

RETURN NEW;
end
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_tbiu_sc_lon_m_loan_history() FROM PUBLIC;

CREATE TRIGGER tbiu_sc_lon_m_loan_history
	BEFORE INSERT OR UPDATE ON sc_lon_m_loan_history FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_tbiu_sc_lon_m_loan_history();

