-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS tbiu_sc_kep_m_agent_send ON sc_kep_m_agent_send CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_tbiu_sc_kep_m_agent_send() RETURNS trigger AS $BODY$
BEGIN

  if coalesce(NEW.salary_time::text, '') = '' then NEW.salary_time :=1;end if;
  if coalesce(NEW.agent_no::text, '') = '' then
    CALL spa_dberrcol('sc_kep_m_agent_send','agent_no',NEW.agent_no);
  end if;

  if coalesce(NEW.keeping_amount::text, '') = '' then NEW.keeping_amount :=0;end if;
  if coalesce(NEW.keeping_lock::text, '') = '' then NEW.keeping_lock :='0';end if;

  if (trim(both current_setting('app.login_id', true)) IS NOT NULL AND (trim(both current_setting('app.login_id', true)))::text <> '') then
    NEW.mod_id := current_setting('app.login_id', true);
    NEW.mod_date := statement_timestamp();
    NEW.mod_br := current_setting('app.login_br', true);
    NEW.mod_pc := pka_com_login.login_pc;
  end if;

  if coalesce(NEW.keeping_balance::text, '') = '' then NEW.keeping_balance :=0;end if;
  if coalesce(NEW.keeping_calc::text, '') = '' then NEW.keeping_calc :=0;end if;
  if coalesce(NEW.count_mem::text, '') = '' then NEW.count_mem :=0;end if;
  if coalesce(NEW.count_return::text, '') = '' then NEW.count_return :=0;end if;
  if coalesce(NEW.return_amount::text, '') = '' then NEW.return_amount :=0;end if;
  if coalesce(NEW.comp_amount::text, '') = '' then NEW.comp_amount :=0;end if;
  if coalesce(NEW.comp_post::text, '') = '' then NEW.comp_post :=0;end if;

  if coalesce(NEW.agent_status::text, '') = '' then NEW.agent_status := '0';end if;
  if coalesce(NEW.agent_amount::text, '') = '' then NEW.agent_amount :=0;end if;
  if coalesce(NEW.agent_balance::text, '') = '' then NEW.agent_balance :=0;end if;
  if coalesce(NEW.agent_count_return::text, '') = '' then NEW.agent_count_return :=0;end if;
  if coalesce(NEW.agent_return::text, '') = '' then NEW.agent_return :=0;end if;

RETURN NEW;
end
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_tbiu_sc_kep_m_agent_send() FROM PUBLIC;

CREATE TRIGGER tbiu_sc_kep_m_agent_send
	BEFORE INSERT OR UPDATE ON sc_kep_m_agent_send FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_tbiu_sc_kep_m_agent_send();

