-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS tbiu_sc_atm_m_chang_request ON sc_atm_m_chang_request CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_tbiu_sc_atm_m_chang_request() RETURNS trigger AS $BODY$
BEGIN
  if coalesce(NEW.approve_status::text, '') = '' then NEW.approve_status := '2';end if;
  if NEW.approve_status not in ('0','1','2','3') then
    CALL spa_dberrcol('sc_atm_m_chang_request','approve_status',NEW.approve_status);
  end if;

  if coalesce(OLD.DOCUMENT_NO::text, '') = '' and (NEW.DOCUMENT_NO IS NOT NULL AND NEW.DOCUMENT_NO::text <> '') then
     if pka.auto_entry then 
        NEW.entry_id := current_setting('app.login_id', true);
        NEW.entry_br := current_setting('app.login_br', true);
        NEW.entry_pc := pka_com_login.login_pc;
        NEW.entry_date := statement_timestamp();
    end if;
  end if;

  if OLD.approve_status = '2' and NEW.approve_status != '2' then
    NEW.approve_id := current_setting('app.login_id', true);
    NEW.approve_br := current_setting('app.login_br', true);
    NEW.approve_pc := pka_com_login.login_pc;
    NEW.approve_date := statement_timestamp();
  end if;
RETURN NEW;
end
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_tbiu_sc_atm_m_chang_request() FROM PUBLIC;

CREATE TRIGGER tbiu_sc_atm_m_chang_request
	BEFORE INSERT OR UPDATE ON sc_atm_m_chang_request FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_tbiu_sc_atm_m_chang_request();

