-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS tbiu_sc_mem_edit_shareloan_code ON sc_mem_edit_shareloan_code CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_tbiu_sc_mem_edit_shareloan_code() RETURNS trigger AS $BODY$
BEGIN

    if coalesce(NEW.seq_no::text, '') = '' or NEW.seq_no = 0 then
        select max(seq_no) into STRICT NEW.seq_no
        from SC_MEM_EDIT_SHARELOAN_CODE
        where 1=1
        and membership_no = NEW.membership_no;
        NEW.seq_no := coalesce(NEW.seq_no,0) + 1;
    end if;


  NEW.entry_date := statement_timestamp();
  NEW.entry_id := pka_com_function.fp_login_id;
  NEW.entry_br := pka_com_function.fp_login_br;
  NEW.operate_date := to_date(statement_timestamp(),'dd/mm/yyyy');


RETURN NEW;
end
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_tbiu_sc_mem_edit_shareloan_code() FROM PUBLIC;

CREATE TRIGGER tbiu_sc_mem_edit_shareloan_code
	BEFORE INSERT OR UPDATE ON sc_mem_edit_shareloan_code FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_tbiu_sc_mem_edit_shareloan_code();

