-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS tbiu_sc_lon_m_rule_share_hold ON sc_lon_m_rule_shareholding CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_tbiu_sc_lon_m_rule_share_hold() RETURNS trigger AS $BODY$
BEGIN
  if pka_com_valid.var_number(NEW.seqno) = '0' then
    select max(seqno) into STRICT NEW.seqno
    from sc_lon_m_rule_shareholding
    where loan_type = NEW.loan_type;
    if coalesce(NEW.seqno::text, '') = '' then NEW.seqno := 0;end if;
    NEW.seqno := NEW.seqno + 1;
  end if;

  if coalesce(NEW.LOAN_AMOUNT::text, '') = '' then NEW.LOAN_AMOUNT := 0;end if;
  if coalesce(NEW.SHARE_VALUE::text, '') = '' then NEW.SHARE_VALUE := 0;end if;

RETURN NEW;
end
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_tbiu_sc_lon_m_rule_share_hold() FROM PUBLIC;

CREATE TRIGGER tbiu_sc_lon_m_rule_share_hold
	BEFORE INSERT OR UPDATE ON sc_lon_m_rule_shareholding FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_tbiu_sc_lon_m_rule_share_hold();

