-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS tbiu_sc_dep_m_rule ON sc_dep_m_rule CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_tbiu_sc_dep_m_rule() RETURNS trigger AS $BODY$
declare
  li_rc integer;li_year integer;
BEGIN
  BEGIN

  if coalesce(trim(both NEW.opendate_at_firstdep)::text, '') = '' then NEW.opendate_at_firstdep := '0';end if;
  if coalesce(trim(both NEW.zero_withdraw)::text, '') = '' then NEW.zero_withdraw :=0;end if;
  if coalesce(trim(both NEW.tax_befor_dued)::text, '') = '' then NEW.tax_befor_dued := 0;end if;
  if coalesce(trim(both NEW.tax_status_bydep)::text, '') = '' then NEW.tax_status_bydep :=0;end if;
  if coalesce(trim(both NEW.intmonth_bydep)::text, '') = '' then NEW.intmonth_bydep :=0;end if;
  if coalesce(trim(both NEW.used_type_status)::text, '') = '' then
    NEW.used_type_status := '1'; -- 1-ใช้งาน ,0-ปิดใช้งาน
  end if;


  if coalesce(trim(both OLD.deposit_type_code)::text, '') = '' and (trim(both NEW.deposit_type_code) IS NOT NULL AND (trim(both NEW.deposit_type_code))::text <> '') then
    -- เพิ่มประเภทเงินฝาก
    -- // เพิ่มเลขที่เอกสาร
    select count(1) into STRICT li_rc
    from sc_cnt_m_document_no_control
    where document_code = 'DEPDEPSLIPNO'||trim(both NEW.deposit_type_code);
    if coalesce(li_rc::text, '') = '' or li_rc = 0 then
      -- ปีเอกสาร
      BEGIN
        select max(document_year)  into STRICT li_year
        from sc_cnt_m_document_no_control
        where document_code like 'DEPDEPSLIPNO%'
        and exists (
          SELECT null from sc_dep_m_rule
          where deposit_type_code = substr(sc_cnt_m_document_no_control.document_code,13,2)
        ) 
        order by document_code;
      exception when others then li_year := to_char(statement_timestamp(),'yyyy');
      end;
      -- เลขที่เอกสารสลิปฝากถอน
      insert into sc_cnt_m_document_no_control(
        document_code   , document_name   , last_document_no
        , document_year , application  ,visible_status
      )values (
        'DEPDEPSLIPNO'||trim(both NEW.deposit_type_code) , 'หมายเลขใบทำรายการ '||trim(both trim(both NEW.deposit_type_code)) , '00000'
        , li_year   , 'DEPOSIT'  ,'0'
      );

      -- เลขที่บัญชี
      insert into sc_cnt_m_document_no_control(
        document_code   , document_name   , last_document_no
        , document_year , application  ,visible_status
        , life_time
      )values (
        'DEPACCNO'||trim(both NEW.deposit_type_code) , 'หมายเลขบัญชีเงินฝาก '||trim(both trim(both NEW.deposit_type_code)) , '00000'
        , '0000'   , 'DEPOSIT'  ,'1'
        , '1'
      );

    end if;

  end if;

if coalesce(trim(both NEW.insure_status)::text, '') = '' then NEW.insure_status := '0';end if;

--Niorn 2023-01-31 Amnat รับดอกเบี้ยรายเดือน ถ้าไม่ระบุ จำนวนเดือน ให้เป็น 1 ไว้ก่อน
if coalesce(NEW.int_month_status::text, '') = '' then NEW.int_month_status := '0';end if;
if NEW.int_month_status = '1' and NEW.period_int_month = 0 then
    NEW.period_int_month := 1;
end if;

if coalesce(NEW.froce_close_acc::text, '') = '' then NEW.froce_close_acc := '0';end if;

--Niorn 2024-06-19 MWA invest_status
if coalesce(NEW.invest_status::text, '') = '' then NEW.invest_status := '0';end if;

--Niorn 2024-08-22 AOT Default use_dw_print
if coalesce(NEW.use_dw_print::text, '') = '' then NEW.use_dw_print :=0;end if;

--Niorn 2024-11-01 BOT เงินฝากประจำ ที่เลือกรับหรือไม่รับรายเดือนได้  ให้มองจาก สถานะใน สลิป 
if coalesce(NEW.choose_fixed_depmonth::text, '') = '' then NEW.choose_fixed_depmonth  :='0';end if;


  END;
RETURN NEW;
end
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_tbiu_sc_dep_m_rule() FROM PUBLIC;

CREATE TRIGGER tbiu_sc_dep_m_rule
	BEFORE INSERT OR UPDATE ON sc_dep_m_rule FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_tbiu_sc_dep_m_rule();

