-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS tbiu_sc_kep_m_agent_receive ON sc_kep_m_agent_receive CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_tbiu_sc_kep_m_agent_receive() RETURNS trigger AS $BODY$
BEGIN

  if (coalesce(OLD.receive_year::text, '') = '' and (NEW.receive_year IS NOT NULL AND NEW.receive_year::text <> '')) then
    if (pka.auto_entry) then 
      NEW.entry_id := current_setting('app.login_id', true);
      NEW.entry_pc := pka_com_login.login_pc;
      NEW.entry_br := current_setting('app.login_br', true);
      NEW.entry_date := statement_timestamp();
    end if;
  end if;


  if coalesce(trim(both NEW.cancel_status)::text, '') = '' then NEW.cancel_status := '0';end if;

  if coalesce(NEW.seq_no::text, '') = '' or NEW.seq_no = 0 then
    select max(seq_no) into STRICT NEW.seq_no
    from SC_KEP_M_AGENT_RECEIVE
    where (receive_year = NEW.receive_year)
    and (receive_month = NEW.receive_month)
    and (salary_time = NEW.salary_time)
    and (agent_no = NEW.agent_no);
    NEW.seq_no := nvn(NEW.seq_no) + 1;
  end if;

  if coalesce(NEW.receive_bymem::text, '') = '' then NEW.receive_bymem := '0';end if;
  if coalesce(trim(both NEW.link_bank_payment)::text, '') = '' then NEW.link_bank_payment :='0';end if;

  --Niorn 2023-10-04 TGE เก็บ รหัส วันเวลายกเลิก
  if trim(both OLD.cancel_status) = '0' and trim(both NEW.cancel_status) ='1'  then
    NEW.cancel_id := current_setting('app.login_id', true);
    NEW.cancel_entry := statement_timestamp();
  end if;
RETURN NEW;
end
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_tbiu_sc_kep_m_agent_receive() FROM PUBLIC;

CREATE TRIGGER tbiu_sc_kep_m_agent_receive
	BEFORE INSERT OR UPDATE ON sc_kep_m_agent_receive FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_tbiu_sc_kep_m_agent_receive();

