-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS tbiu_sc_lon_m_req_coll ON sc_lon_m_req_coll CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_tbiu_sc_lon_m_req_coll() RETURNS trigger AS $BODY$
BEGIN
    null;
  if pka.auto_seqno then
    if coalesce(NEW.seq_no::text, '') = '' or NEW.seq_no = 0 then
      select max(seq_no) into STRICT NEW.seq_no
      from sc_lon_m_req_coll
      where (loan_requestment_no = NEW.loan_requestment_no);
      NEW.seq_no := coalesce(NEW.seq_no, 0) + 1;
    end if;
  end if;

  if coalesce(NEW.evaluate_amount::text, '') = '' then
    NEW.evaluate_amount := 0;
  end if;

  if coalesce(NEW.req_amount::text, '') = '' then
    NEW.req_amount := 0;
  end if;

  if ( NEW.COLLATERAL_TYPE_CODE  = '01' or NEW.COLLATERAL_TYPE_CODE = '02' ) then
    NEW.REF_MEMBERSHIP_NO := substr(trim(both NEW.REF_OWN_NO),1,7);
  else
    NEW.REF_MEMBERSHIP_NO := null;
  end if;

  if ( NEW.COLLATERAL_TYPE_CODE  = '03' ) then
    NEW.REF_DEPOSIT_ACCOUNT_NO := substr(trim(both NEW.REF_OWN_NO),1,15);
  else
    NEW.REF_DEPOSIT_ACCOUNT_NO := null;
  end if;

  if coalesce(NEW.mustcoll_loan::text, '') = '' or NEW.mustcoll_loan = ' ' then NEW.mustcoll_loan := '0';end if;
  if coalesce(NEW.salary_amount::text, '') = '' then NEW.salary_amount :=0;end if; -- ?????????????
  if coalesce(NEW.salary_bal_percent::text, '') = '' then NEW.salary_bal_percent := 0;end if; -- % ???????????????????
  if coalesce(NEW.salary_bal_amount::text, '') = '' then NEW.salary_bal_amount :=0;end if; -- ??? ???????????????????
  if coalesce(NEW.status::text, '') = '' then NEW.status :='0';end if;

RETURN NEW;
end
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_tbiu_sc_lon_m_req_coll() FROM PUBLIC;

CREATE TRIGGER tbiu_sc_lon_m_req_coll
	BEFORE INSERT OR UPDATE ON sc_lon_m_req_coll FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_tbiu_sc_lon_m_req_coll();

