-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS tbiu_sc_hr_off_member_arrsal ON sc_hr_off_member_arrear_salary CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_tbiu_sc_hr_off_member_arrsal() RETURNS trigger AS $BODY$
BEGIN
  --validate
  if coalesce(trim(both NEW.cancel_status)::text, '') = '' then NEW.cancel_status := '0';end if;
  if coalesce(trim(both NEW.post_status)::text, '') = '' then NEW.post_status := '0';end if;
  if (coalesce(OLD.official_no::text, '') = '' and (NEW.official_no IS NOT NULL AND NEW.official_no::text <> '') ) then
    if (pka.auto_entry) then 
        NEW.entry_id := current_setting('app.login_id', true);
        NEW.entry_date := statement_timestamp();
        NEW.entry_branch := current_setting('app.login_br', true);
        NEW.entry_clientid := pka_com_login.login_pc;
    end if;
  end if;


  if (coalesce(NEW.salary_amount::text, '') = '' or NEW.salary_amount = 0) and NEW.cancel_status <> '1' then
    CALL spa_dberror('จำนวนเงิน bonus ที่ได้รับต้องมากกว่าศูนย์');
  end if;

  --run seq_no
  if coalesce(NEW.seq_no::text, '') = '' or NEW.seq_no = 0 then
    select max(seq_no )  into STRICT NEW.seq_no
    from sc_hr_off_member_arrear_salary
    where (official_no = NEW.official_no);
    if NEW.seq_no > 0 then
      NEW.seq_no := NEW.seq_no + 1;
    else
      NEW.seq_no := 1;
    end if;
  end  if;
RETURN NEW;
end
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_tbiu_sc_hr_off_member_arrsal() FROM PUBLIC;

CREATE TRIGGER tbiu_sc_hr_off_member_arrsal
	BEFORE INSERT OR UPDATE ON sc_hr_off_member_arrear_salary FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_tbiu_sc_hr_off_member_arrsal();

