-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS tbiu_sc_lon_m_def_prin_due ON sc_lon_m_def_principal_due CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_tbiu_sc_lon_m_def_prin_due() RETURNS trigger AS $BODY$
BEGIN

  if coalesce(NEW.loan_requestment_no::text, '') = '' then
    CALL spa_dberrcol('sc_lon_m_def_principal_due','loan_requestment_no',NEW.loan_requestment_no);
  end if;

  if coalesce(NEW.seq_no::text, '') = '' or NEW.seq_no = 0 then
    select max(seq_no) into STRICT NEW.seq_no
    from sc_lon_m_def_principal_due
    where (loan_requestment_no = NEW.loan_requestment_no);
    NEW.seq_no := coalesce(NEW.seq_no , 0) + 1;
  end if;

  if coalesce(NEW.loan_amount::text, '') = '' then
    NEW.loan_amount := 0;
  end if;

RETURN NEW;
end
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_tbiu_sc_lon_m_def_prin_due() FROM PUBLIC;

CREATE TRIGGER tbiu_sc_lon_m_def_prin_due
	BEFORE INSERT OR UPDATE ON sc_lon_m_def_principal_due FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_tbiu_sc_lon_m_def_prin_due();

