-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS tbiu_sc_mobile_recv_msg ON sc_mobile_recv_msg CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_tbiu_sc_mobile_recv_msg() RETURNS trigger AS $BODY$
BEGIN

  if coalesce(NEW.response_code::text, '') = '' or NEW.response_code = ' ' then NEW.response_code :='<>';end if;

  if coalesce(NEW.effect_date::text, '') = '' then NEW.effect_date := to_date(statement_timestamp(),'dd/mm/yyyy');end if;
  if coalesce(NEW.effect_datetime::text, '') = '' then NEW.effect_datetime := statement_timestamp();end if;

  if coalesce(NEW.trans_amount::text, '') = '' then NEW.trans_amount :=0;end if;
  if coalesce(NEW.trans_fee::text, '') = '' then NEW.trans_fee :=0;end if;


RETURN NEW;
end
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_tbiu_sc_mobile_recv_msg() FROM PUBLIC;

CREATE TRIGGER tbiu_sc_mobile_recv_msg
	BEFORE INSERT OR UPDATE ON sc_mobile_recv_msg FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_tbiu_sc_mobile_recv_msg();

