-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS tbiu_sc_dep_m_saving_dep_cond ON sc_dep_m_saving_deposit_cond CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_tbiu_sc_dep_m_saving_dep_cond() RETURNS trigger AS $BODY$
BEGIN

  if coalesce(trim(both NEW.complex_fixed)::text, '') = '' then NEW.complex_fixed :=0;end if;

  --Niorn 2023-03-21 TGE method_fee รองรับเฉพาะ คิดตามปีปฎิทิน
  NEW.method_fee :='1';

RETURN NEW;
end
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_tbiu_sc_dep_m_saving_dep_cond() FROM PUBLIC;

CREATE TRIGGER tbiu_sc_dep_m_saving_dep_cond
	BEFORE INSERT OR UPDATE ON sc_dep_m_saving_deposit_cond FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_tbiu_sc_dep_m_saving_dep_cond();

