-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS tbiu_sc_dep_m_fixed_item ON sc_dep_m_fixed_item CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_tbiu_sc_dep_m_fixed_item() RETURNS trigger AS $BODY$
BEGIN

  if (pka.auto_seqno) then
    if coalesce(NEW.ref_seq_no::text, '') = '' or NEW.ref_seq_no = 0 then
      select max(ref_seq_no) into STRICT NEW.ref_seq_no
      from sc_dep_m_fixed_item
      where deposit_account_no = NEW.deposit_account_no;
      NEW.ref_seq_no := coalesce(NEW.ref_seq_no,0) + 1;
    end if;
  end if;

  if coalesce(NEW.fixed_dued_int::text, '') = '' then NEW.fixed_dued_int :=0;end if;
  if coalesce(NEW.fixed_paid_monthly_int::text, '') = '' then NEW.fixed_paid_monthly_int := 0;end if;
  if coalesce(NEW.operate_date::text, '') = '' then NEW.operate_date := statement_timestamp();end if; -- entry Date
  if coalesce(trim(both NEW.officer_id)::text, '') = '' then NEW.officer_id := trim(both pka_com_function.fp_login_id);end if;
  if coalesce(trim(both NEW.branch_id)::text, '') = '' then NEW.branch_id := trim(both pka_com_function.fp_login_br);end if;
  if coalesce(NEW.working_day::text, '') = '' then NEW.working_day := pka_dep.fp_deposit_date();end if;
  if coalesce(NEW.start_int_cheque_date::text, '') = '' then NEW.start_int_cheque_date := NEW.fixed_date;end if; -- -- ให้ใช้เป็นวันที่เดียวกันกับวันที่ฝากเสมอ
  if coalesce(NEW.fixed_next_monthly_dued::text, '') = '' then NEW.fixed_next_monthly_dued := NEW.fixed_date;end if;

  if coalesce(NEW.fixed_monthly_int::text, '') = '' then NEW.fixed_monthly_int := 0;end if;
  if coalesce(NEW.first_monthly_int::text, '') = '' or NEW.first_monthly_int = 0 and NEW.fixed_monthly_int > 0 then
    NEW.first_monthly_int := NEW.fixed_monthly_int;
  end if;
  if coalesce(NEW.interest_rate::text, '') = '' then NEW.interest_rate :=0;end if;
  if coalesce(NEW.fixed_amount::text, '') = '' then NEW.fixed_amount :=0;end if;
  if coalesce(NEW.fixed_dued_month_count::text, '') = '' then NEW.fixed_dued_month_count :=0;end if;


RETURN NEW;
end
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_tbiu_sc_dep_m_fixed_item() FROM PUBLIC;

CREATE TRIGGER tbiu_sc_dep_m_fixed_item
	BEFORE INSERT OR UPDATE ON sc_dep_m_fixed_item FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_tbiu_sc_dep_m_fixed_item();

