-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS tbiu_sc_fund_mem_detail ON sc_fund_mem_detail CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_tbiu_sc_fund_mem_detail() RETURNS trigger AS $BODY$
BEGIN

  if coalesce(NEW.seq_no::text, '') = '' or NEW.seq_no = 0 then 
    select max(seq_no) into STRICT NEW.seq_no
    from sc_fund_mem_detail
    where loan_contract_no = NEW.loan_contract_no;
    NEW.seq_no := coalesce(NEW.seq_no,0) + 1;
  end if;

    if coalesce(NEW.user_id::text, '') = '' then NEW.user_id := current_setting('app.login_id', true);end if;
    if coalesce(NEW.branch_id::text, '') = '' then NEW.branch_id := current_setting('app.login_br', true);end if;
    if coalesce(NEW.user_date::text, '') = '' then NEW.user_date := statement_timestamp();end if;

RETURN NEW;
end
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_tbiu_sc_fund_mem_detail() FROM PUBLIC;

CREATE TRIGGER tbiu_sc_fund_mem_detail
	BEFORE INSERT OR UPDATE ON sc_fund_mem_detail FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_tbiu_sc_fund_mem_detail();

