-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS tbiu_sc_acc_journal_h_firm ON sc_acc_journal_heading_firm CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_tbiu_sc_acc_journal_h_firm() RETURNS trigger AS $BODY$
declare
ldc_dr bigint;
ldc_cr bigint;
BEGIN

  if coalesce(NEW.POST_TO_GL_STATUS::text, '') = '' then NEW.POST_TO_GL_STATUS := '0';end if;
  if coalesce(NEW.CANCEL_STATUS::text, '') = '' then NEW.CANCEL_STATUS := '0';end if;

/*
--  if :old.doc_no is null and :new.doc_no is not null then 
--    if pka.auto_entry then 
      :new.entry_date := sysdate ;
      :new.entry_name := current_setting('app.login_id', true);      
      :new.branch_id := current_setting('app.login_br', true); 
--    end if;
--  end if;
*/
    
 NEW.entry_date := statement_timestamp();

 --KTM set edit name    
  NEW.entry_name := current_setting('app.login_id', true);
 
  
 if coalesce(NEW.entry_name::text, '') = '' then
      NEW.entry_name := current_setting('app.login_id', true);
  end if;

 if coalesce(NEW.branch_id::text, '') = '' then
      NEW.branch_id := current_setting('app.login_br', true);
  end if;

  
  --สาขาที่บันทึกบัญชี ถ้ามาจากการ post to acc จะยึดตาม journal_detail
  if coalesce(NEW.entry_br_id::text, '') = '' then
      NEW.entry_br_id := current_setting('app.login_br', true);
  end if;

  if OLD.cancel_status = '0' and NEW.cancel_status  = '1' then
    NEW.cancel_date := statement_timestamp();
    if coalesce(NEW.cancel_id::text, '') = '' or NEW.cancel_id <> current_setting('app.login_id', true) then
      NEW.cancel_id := current_setting('app.login_id', true);
    end if;
    if coalesce(NEW.cancel_branchid::text, '') = '' or NEW.cancel_branchid <> current_setting('app.login_br', true) then
      NEW.cancel_branchid := current_setting('app.login_br', true);
    end if;
  end if;

  select coalesce(sum(dr_amount ),0) into STRICT NEW.total_amount
  from  sc_acc_journal_detail_firm  
  where doc_no = NEW.doc_no;

  if coalesce(NEW.total_amount::text, '') = '' then NEW.total_amount :=0;end if;

  --Det  Dr <>  Det Cr เป็นอะไรไม่รู้สาเหตุ  7.1 / 7.10 ด้านไม่ตรงกัน
  select coalesce( sum( dr_amount) ,0 )  into STRICT ldc_dr
  from sc_acc_journal_detail_firm
  where (doc_no = NEW.doc_no);

  select coalesce( sum( cr_amount) ,0 )  into STRICT ldc_cr
  from sc_acc_journal_detail_firm
  where (doc_no = NEW.doc_no);

  if ldc_dr <> ldc_cr then
      CALL spa_dberror('T67: dr <> cr ('||trim(both NEW.doc_no)||')');
  end if;

RETURN NEW;
end
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_tbiu_sc_acc_journal_h_firm() FROM PUBLIC;

CREATE TRIGGER tbiu_sc_acc_journal_h_firm
	BEFORE INSERT OR UPDATE ON sc_acc_journal_heading_firm FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_tbiu_sc_acc_journal_h_firm();

