-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS tbiu_sc_lon_m_rule_permitcoll ON sc_lon_m_rule_permitcoll CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_tbiu_sc_lon_m_rule_permitcoll() RETURNS trigger AS $BODY$
BEGIN
  if pka_com_valid.var_number(NEW.seq_no) = '0' then
    select max(seq_no) into STRICT NEW.seq_no
    from sc_lon_m_rule_permitcoll
    where loan_type = NEW.loan_type;
    if coalesce(NEW.seq_no::text, '') = '' then NEW.seq_no := 0;end if;
    NEW.seq_no := NEW.seq_no + 1;
  end if;

  if coalesce(NEW.LOAN_AMOUNT_1::text, '') = '' then NEW.LOAN_AMOUNT_1 := 0;end if;
  if coalesce(NEW.LOAN_AMOUNT_2::text, '') = '' then NEW.LOAN_AMOUNT_2 := 0;end if;
  if coalesce(NEW.LOAN_AMOUNT_3::text, '') = '' then NEW.LOAN_AMOUNT_3 := 0;end if;
RETURN NEW;
end
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_tbiu_sc_lon_m_rule_permitcoll() FROM PUBLIC;

CREATE TRIGGER tbiu_sc_lon_m_rule_permitcoll
	BEFORE INSERT OR UPDATE ON sc_lon_m_rule_permitcoll FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_tbiu_sc_lon_m_rule_permitcoll();

