-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS tbiu_sc_acc_m_account_constant ON sc_acc_m_account_constant CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_tbiu_sc_acc_m_account_constant() RETURNS trigger AS $BODY$
BEGIN
  if coalesce(NEW.vat::text, '') = '' then NEW.vat := 0;end if;
  if coalesce(NEW.reserve_money_percent::text, '') = '' then NEW.reserve_money_percent := 0;end if;
  if coalesce(NEW.present_account_year::text, '') = '' then NEW.present_account_year := 0;end if;
  if coalesce(NEW.len_doc_no::text, '') = '' then NEW.len_doc_no := 0;end if;
RETURN NEW;
end
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_tbiu_sc_acc_m_account_constant() FROM PUBLIC;

CREATE TRIGGER tbiu_sc_acc_m_account_constant
	BEFORE INSERT OR UPDATE ON sc_acc_m_account_constant FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_tbiu_sc_acc_m_account_constant();

