-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS tbiu_sc_mem_m_capital_rate ON sc_mem_m_capital_rate CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_tbiu_sc_mem_m_capital_rate() RETURNS trigger AS $BODY$
BEGIN

--return ;
  NEW.entry_date := statement_timestamp();
  NEW.entry_id := pka_com_function.fp_login_id;
  NEW.entry_br := pka_com_function.fp_login_br;
  NEW.entry_pc := pka_com_function.fp_login_pc;

  if coalesce(NEW.share_reward::text, '') = '' then NEW.share_reward := 0;end if;
  if coalesce(NEW.share_rate::text, '') = '' then NEW.share_rate := 0;end if;
  if coalesce(NEW.lonint_rate::text, '') = '' then NEW.lonint_rate := 0;end if;
  if coalesce(trim(both NEW.share_round_method)::text, '') = '' then NEW.share_round_method := '0';end if;
  if coalesce(trim(both NEW.lonint_round_method)::text, '') = '' then NEW.lonint_round_method := '0';end if;
  if coalesce(NEW.share_round_money::text, '') = '' then NEW.share_round_money := 0;end if;
  if coalesce(NEW.lonint_round_money::text, '') = '' then NEW.lonint_round_money := 0;end if;


if NEW.share_rate <> OLD.share_rate or NEW.share_round_method <> OLD.share_round_method
   or NEW.share_round_money <> OLD.share_round_money then

  update sc_mem_m_capital_stock_detail
  set dividend = 0
  where account_year = NEW.lon_year;

  delete from sc_mem_m_capital_pay
  where account_year = NEW.lon_year;

end if;

if NEW.lonint_rate <> OLD.lonint_rate or NEW.lonint_round_method <> OLD.lonint_round_method
   or NEW.lonint_round_money <> OLD.lonint_round_money then

  update sc_mem_m_capital_stock_detail
  set average_return = 0
  where account_year = NEW.lon_year;

  delete from sc_mem_m_capital_pay
  where account_year = NEW.lon_year;

end if;

if NEW.share_reward <> OLD.share_reward  then

  update sc_mem_m_capital_stock_detail
  set total_share_reward = 0
  where account_year = NEW.lon_year;

  delete from sc_mem_m_capital_pay
  where account_year = NEW.lon_year;

end if;


--Niorn 2023-12-26 Edit Money_reward ก้อต้องเคลียร์ ยอดทั้งหมดด้วย
if NEW.money_reward <> OLD.money_reward  then

  update sc_mem_m_capital_stock_detail
  set total_money_reward = 0
  where account_year = NEW.lon_year;

  delete from sc_mem_m_capital_pay
  where account_year = NEW.lon_year;

end if;

--Niorn Amnat share_round_money เป็น 0.25 ได้ แม้ share_round_method จะเป็น 0
--if :new.share_round_method  = '0' then :new.share_round_money  := 0 ; end if;
--if :new.lonint_round_method = '0' then :new.lonint_round_money := 0 ;end if;
RETURN NEW;
end
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_tbiu_sc_mem_m_capital_rate() FROM PUBLIC;

CREATE TRIGGER tbiu_sc_mem_m_capital_rate
	BEFORE INSERT OR UPDATE ON sc_mem_m_capital_rate FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_tbiu_sc_mem_m_capital_rate();

