-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS tbiu_sc_wef_req ON sc_wef_req CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_tbiu_sc_wef_req() RETURNS trigger AS $BODY$
BEGIN

  if coalesce(OLD.REQUESTMENT_NO::text, '') = '' and (NEW.REQUESTMENT_NO IS NOT NULL AND NEW.REQUESTMENT_NO::text <> '') then
    if pka.auto_entry then 
      NEW.entry_id := pka_com_function.fp_login_id;
      NEW.entry_time := statement_timestamp();
      NEW.entry_br := pka_com_function.fp_login_br;
      NEW.entry_pc := pka_com_function.fp_login_pc;
    end if;
  end if;

  if coalesce(trim(both NEW.entry_id)::text, '') = '' then NEW.entry_id := pka_com_function.fp_login_id;end if;
  if coalesce(trim(both NEW.entry_br)::text, '') = '' then NEW.entry_br := pka_com_function.fp_login_br;end if;

  if coalesce(trim(both NEW.cancel_status)::text, '') = '' then NEW.cancel_status := '0';end if;
  if coalesce(trim(both NEW.approve_status)::text, '') = '' then NEW.approve_status := '2';end if;-- ???????
  if coalesce(NEW.total_receive::text, '') = '' then NEW.total_receive := 0;end if;

  if OLD.cancel_status = '0' and NEW.cancel_status = '1' then
   NEW.cancel_id := trim(both current_setting('app.login_id', true));
   NEW.cancel_time := statement_timestamp();
   NEW.cancel_pc := pka_com_login.login_pc;
   NEW.cancel_br := current_setting('app.login_br', true);
  end if;

--  -- ทำเป็นปี ค.ศ.
--  :new.account_year := :new.account_year - 543 ;
  --ตัดเข้า รอจ่ายคืนทั้งหมด จะรับเป็นอะไร ไปทำต่อในระบบการเงิน
  if coalesce(NEW.money_type::text, '') = '' then NEW.money_type := 'WEL';end if;

RETURN NEW;
end
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_tbiu_sc_wef_req() FROM PUBLIC;

CREATE TRIGGER tbiu_sc_wef_req
	BEFORE INSERT OR UPDATE ON sc_wef_req FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_tbiu_sc_wef_req();

