-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS tbiu_sc_lon_m_amt_by_custom ON sc_lon_m_amt_by_custom CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_tbiu_sc_lon_m_amt_by_custom() RETURNS trigger AS $BODY$
BEGIN
  if coalesce(NEW.seq_no::text, '') = '' or NEW.seq_no = 0 then
    select max(seq_no) into STRICT NEW.seq_no
    from sc_lon_m_amt_by_custom
    where loan_type = NEW.loan_type
    and mem_level = NEW.mem_level;
    if coalesce(NEW.seq_no::text, '') = '' then NEW.seq_no := 0;end if;
    NEW.seq_no := NEW.seq_no + 1;
  end if;

  if coalesce(NEW.CAL_PERMIT_STYLE::text, '') = '' then NEW.CAL_PERMIT_STYLE :='0';end if;
  if coalesce(NEW.MEMBER_TERM::text, '') = '' then NEW.MEMBER_TERM := 0;end if;
  if coalesce(NEW.SHARE_HOLDING::text, '') = '' then NEW.SHARE_HOLDING := 0;end if;
  if coalesce(NEW.SALARY_AMOUNT::text, '') = '' then NEW.SALARY_AMOUNT := 0;end if;
  if coalesce(NEW.LOAN_AMOUNT::text, '') = '' then NEW.LOAN_AMOUNT := 0;end if;
  if coalesce(NEW.MEM_LEVEL::text, '') = '' then NEW.MEM_LEVEL := 0;end if;
  if coalesce(NEW.LOAN_BY_SALARY::text, '') = '' then NEW.LOAN_BY_SALARY := 0;end if;
  if coalesce(NEW.LOAN_BY_SHARE::text, '') = '' then NEW.LOAN_BY_SHARE := 0;end if;
  if coalesce(NEW.mem_live_age::text, '') = '' then NEW.mem_live_age := 0;end if;

RETURN NEW;
end
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_tbiu_sc_lon_m_amt_by_custom() FROM PUBLIC;

CREATE TRIGGER tbiu_sc_lon_m_amt_by_custom
	BEFORE INSERT OR UPDATE ON sc_lon_m_amt_by_custom FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_tbiu_sc_lon_m_amt_by_custom();

