-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS tbiu_sc_hr_off_member_income_other ON sc_hr_off_member_income_other CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_tbiu_sc_hr_off_member_income_other() RETURNS trigger AS $BODY$
BEGIN

--  if pka.auto_seqno then
--if :new.seq_no is null or :new.seq_no = 0 then
--select max(seq_no) into :new.seq_no
--from SC_HR_OFF_MEMBER_INCOME_OTHER
--where official_no = :new.official_no
--and income_status = :new.income_status;
--:new.seq_no := NVL(:new.seq_no,0) + 1;
if coalesce(NEW.seq_no::text, '') = '' or NEW.seq_no = 0 then
    select max(seq_no) into STRICT NEW.seq_no
    from SC_HR_OFF_MEMBER_INCOME_OTHER
    where official_no = NEW.official_no
    and income_status = NEW.income_status;
    if NEW.seq_no > 0 then
      NEW.seq_no := coalesce(NEW.seq_no,0) + 1;
    else
      NEW.seq_no := 1;
    end if;
  end if;


  if ( NEW.INCOME_CODE = '0005') then
      if ((coalesce(OLD.INCOME_AMOUNT::text, '') = '') or (NEW.INCOME_AMOUNT <> OLD.INCOME_AMOUNT) )  then
      INSERT INTO sc_hr_off_his_salary(official_no,           opporate_date,             salary)  
      VALUES (NEW.official_no,        TO_DATE( statement_timestamp() ),             NEW.INCOME_AMOUNT);

      end if;
  end if;

RETURN NEW;
end
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_tbiu_sc_hr_off_member_income_other() FROM PUBLIC;

CREATE TRIGGER tbiu_sc_hr_off_member_income_other
	BEFORE INSERT OR UPDATE ON sc_hr_off_member_income_other FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_tbiu_sc_hr_off_member_income_other();

