-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS tbiu_sc_rep_lon_coll_amlo ON sc_rep_lon_coll_amlo CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_tbiu_sc_rep_lon_coll_amlo() RETURNS trigger AS $BODY$
BEGIN
if pka.auto_seqno then
  if coalesce(NEW.seq_no::text, '') = '' or NEW.seq_no = 0 then
    select coalesce( max(seq_no), 0 ) + 1  into STRICT NEW.seq_no 
    from sc_rep_lon_coll_amlo
;
  end if;
end if;
RETURN NEW;
end
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_tbiu_sc_rep_lon_coll_amlo() FROM PUBLIC;

CREATE TRIGGER tbiu_sc_rep_lon_coll_amlo
	BEFORE INSERT OR UPDATE ON sc_rep_lon_coll_amlo FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_tbiu_sc_rep_lon_coll_amlo();

