-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS tbiu_sc_dep_m_passbook ON sc_dep_m_passbook CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_tbiu_sc_dep_m_passbook() RETURNS trigger AS $BODY$
BEGIN

  if pka.auto_seqno then
    if coalesce(NEW.seq_no::text, '') = '' or NEW.seq_no = 0 then 
      select max(seq_no) into STRICT NEW.seq_no
      from sc_dep_m_passbook
      where deposit_account_no = NEW.deposit_account_no
      and passbook_no = NEW.passbook_no;
      NEW.seq_no := coalesce(NEW.seq_no,0) + 1;
    end if;
  end if;

  if coalesce(NEW.amount_book_count::text, '') = '' or NEW.amount_book_count = 0 then
    select count(distinct passbook_no)  
    into STRICT NEW.amount_book_count 
    from sc_dep_m_passbook 
    where deposit_account_no = NEW.deposit_account_no;
    NEW.amount_book_count := coalesce(NEW.amount_book_count,0) + 1;
  end if;

  if pka.auto_entry then
    if coalesce(OLD.deposit_account_no::text, '') = '' then 
      -- Insert 
      NEW.entry_date := statement_timestamp();
      NEW.entry_id := pka_com_function.fp_login_id;
      NEW.branch_id := pka_com_function.fp_login_br;
      NEW.working_day := pka_dep.fp_deposit_date;
    end if;
  end if;

  -- Default 
  if coalesce(NEW.fee_charge::text, '') = '' then NEW.fee_charge :=0;end if;
  if coalesce(NEW.status::text, '') = '' then NEW.status := '0';end if;

RETURN NEW;
end
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_tbiu_sc_dep_m_passbook() FROM PUBLIC;

CREATE TRIGGER tbiu_sc_dep_m_passbook
	BEFORE INSERT OR UPDATE ON sc_dep_m_passbook FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_tbiu_sc_dep_m_passbook();

