-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS tbiu_sc_transbank_detail ON sc_transbank_detail CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_tbiu_sc_transbank_detail() RETURNS trigger AS $BODY$
BEGIN

  if pka.auto_seqno then
    if coalesce(NEW.SEQ_NO::text, '') = '' or NEW.SEQ_NO = 0 then
      select max(SEQ_NO) into STRICT NEW.SEQ_NO
      from sc_transbank_detail
      where 1=1
     and data_code  = NEW.data_code
     and bank_code  = NEW.bank_code
     and trandate  = NEW.trandate
     and seq_tran    = NEW.seq_tran  
;
      NEW.SEQ_NO := coalesce(NEW.SEQ_NO,0) + 1;
    end if;
  end if;


RETURN NEW;
end
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_tbiu_sc_transbank_detail() FROM PUBLIC;

CREATE TRIGGER tbiu_sc_transbank_detail
	BEFORE INSERT OR UPDATE ON sc_transbank_detail FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_tbiu_sc_transbank_detail();

