-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS tbiu_sc_law_asset_coop ON sc_law_asset_coop CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_tbiu_sc_law_asset_coop() RETURNS trigger AS $BODY$
BEGIN

  -- entry
  if coalesce(OLD.asset_no::text, '') = '' and (NEW.asset_no IS NOT NULL AND NEW.asset_no::text <> '') then
    if pka.auto_entry then
      NEW.entry_date := statement_timestamp();
      NEW.entry_id := current_setting('app.login_id', true);
      NEW.branch_id := current_setting('app.login_br', true);
    end if;
  end if;

  -- cancel
  if OLD.cancel_status = '0' and NEW.cancel_status = '1' then
    NEW.cancel_date :=statement_timestamp();
    NEW.cancel_id := pka_com_function.fp_login_id;
    NEW.cancel_br  := pka_com_function.fp_login_br;
  end if;

  -- default cancel_status
  if coalesce(trim(both NEW.cancel_status)::text, '') = '' then NEW.cancel_status := '0';end if;
RETURN NEW;
end
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_tbiu_sc_law_asset_coop() FROM PUBLIC;

CREATE TRIGGER tbiu_sc_law_asset_coop
	BEFORE INSERT OR UPDATE ON sc_law_asset_coop FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_tbiu_sc_law_asset_coop();

