-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS tbiu_sc_acc_m_account_budg_grp ON sc_acc_m_account_budget_group CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_tbiu_sc_acc_m_account_budg_grp() RETURNS trigger AS $BODY$
BEGIN

  -- Default value 
  if coalesce(NEW.total_budjet::text, '') = '' then NEW.total_budjet :=0;end if;
  if coalesce(NEW.month_status::text, '') = '' or NEW.month_status != '1' then NEW.month_status :='0';end if;
  if coalesce(NEW.total_transfer_budget::text, '') = '' then NEW.total_transfer_budget :=0;end if;
  if coalesce(NEW.account_group_id::text, '') = '' or NEW.account_group_id = ' ' then NEW.account_group_id :='00';end if;


RETURN NEW;
end
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_tbiu_sc_acc_m_account_budg_grp() FROM PUBLIC;

CREATE TRIGGER tbiu_sc_acc_m_account_budg_grp
	BEFORE INSERT OR UPDATE ON sc_acc_m_account_budget_group FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_tbiu_sc_acc_m_account_budg_grp();

