-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS tbiu_sc_mem_m_app_bank_accno ON sc_mem_m_app_bank_accno CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_tbiu_sc_mem_m_app_bank_accno() RETURNS trigger AS $BODY$
declare
  ls_close_status char;
BEGIN
  BEGIN

  if pka.auto_seqno then 
    if coalesce(NEW.seq_no::text, '') = '' or NEW.seq_no = 0 then
      select max(seq_no) into STRICT NEW.seq_no
      from sc_mem_m_app_bank_accno
      where (application_form_no = NEW.application_form_no);
      NEW.seq_no := coalesce(NEW.seq_no,0) + 1;
    end if;
  end if;

  if NEW.bank_id = '000' then -- เงินฝาก สอ.
    if coalesce(OLD.bank_acc_no,' ') <> coalesce(NEW.bank_acc_no,' ') then
      BEGIN
        select close_status into STRICT ls_close_status
        from sc_dep_m_creditor
        where (deposit_account_no = NEW.bank_acc_no);
      exception when others then CALL spa_dberror('E29:บัญชีเงินฝาก('||trim(both NEW.bank_acc_no)||'),ไม่มีอยู่จริง');
      end;
      if ls_close_status  = 'C' then
        CALL spa_dberror('E32:บัญชีเงินฝาก('||trim(both NEW.bank_acc_no)||'),ปิดบัญชีแล้ว');
      end if;
    end if;
  end if;

  if coalesce(trim(both NEW.paid_loan)::text, '') = '' then NEW.paid_loan := '0';end if;
  if coalesce(trim(both NEW.paid_dividen)::text, '') = '' then NEW.paid_dividen :='0';end if;
  if coalesce(trim(both NEW.share_withdraw)::text, '') = '' then NEW.share_withdraw :='0';end if;
  if coalesce(trim(both NEW.atm_lon)::text, '') = '' then NEW.atm_lon := '0';end if;
  if coalesce(trim(both NEW.atm_dep)::text, '') = '' then NEW.atm_dep := '0';end if;
  if coalesce(trim(both NEW.mustcoll_loan)::text, '') = '' then NEW.mustcoll_loan := '0';end if;

  END;
RETURN NEW;
end
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_tbiu_sc_mem_m_app_bank_accno() FROM PUBLIC;

CREATE TRIGGER tbiu_sc_mem_m_app_bank_accno
	BEFORE INSERT OR UPDATE ON sc_mem_m_app_bank_accno FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_tbiu_sc_mem_m_app_bank_accno();

