-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS tbiu_sc_sch_mem_regis ON sc_sch_mem_regis CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_tbiu_sc_sch_mem_regis() RETURNS trigger AS $BODY$
BEGIN

  if coalesce(NEW.requestment_no::text, '') = '' or NEW.requestment_no = ' ' then
    CALL spa_dberrcol('sc_sch_mem_regis','requestment_no',NEW.requestment_no);
  end if;

  if coalesce(OLD.requestment_no::text, '') = '' and (NEW.requestment_no IS NOT NULL AND NEW.requestment_no::text <> '') then
    -- Insert 
    if pka.auto_entry then 
      NEW.cancel_status := '0';
      NEW.entry_id := pka_com_function.fp_login_id();
      NEW.entry_date := statement_timestamp();
      NEW.entry_branch := pka_com_function.fp_login_br();
    end if;
  end if;

  -- Cancel
  if coalesce(NEW.cancel_status::text, '') = '' or NEW.cancel_status = ' '  then 
    NEW.cancel_status := 0;
  end if;

  if OLD.cancel_status = '0' and NEW.cancel_status  = '1' then
    NEW.cancel_date := statement_timestamp();
    if coalesce(NEW.cancel_id::text, '') = '' or NEW.cancel_id <> current_setting('app.login_id', true) then
      NEW.cancel_id := current_setting('app.login_id', true);
    end if;
    if coalesce(NEW.cancel_branch::text, '') = '' or NEW.cancel_branch <> current_setting('app.login_br', true) then
      NEW.cancel_branch := current_setting('app.login_br', true);
    end if;
  end if;

  if coalesce(NEW.trans_bank_status::text, '') = '' then NEW.trans_bank_status :='0';end if;
RETURN NEW;
end
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_tbiu_sc_sch_mem_regis() FROM PUBLIC;

CREATE TRIGGER tbiu_sc_sch_mem_regis
	BEFORE INSERT OR UPDATE ON sc_sch_mem_regis FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_tbiu_sc_sch_mem_regis();

