-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS tbiu_sc_mem_m_insur_gain ON sc_mem_m_insur_gain CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_tbiu_sc_mem_m_insur_gain() RETURNS trigger AS $BODY$
BEGIN

  if coalesce(NEW.rec_no::text, '') = '' or NEW.rec_no = 0 then
    select max(rec_no) into STRICT NEW.rec_no
    from SC_MEM_M_INSUR_GAIN
    where insurance_no  = NEW.insurance_no;
    NEW.rec_no := coalesce(NEW.rec_no,0) + 1;
  end if;

  if coalesce(trim(both NEW.entry_id)::text, '') = ''  then
    NEW.entry_id  := pka_com_function.fp_login_id;
  end if;
  if coalesce(trim(both NEW.entry_br)::text, '') = ''  then
    NEW.entry_br  := pka_com_function.fp_login_br;
  end if;
  if coalesce(trim(both NEW.entry_date)::text, '') = ''  then
    NEW.entry_date  := statement_timestamp();
  end if;

RETURN NEW;
end
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_tbiu_sc_mem_m_insur_gain() FROM PUBLIC;

CREATE TRIGGER tbiu_sc_mem_m_insur_gain
	BEFORE INSERT OR UPDATE ON sc_mem_m_insur_gain FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_tbiu_sc_mem_m_insur_gain();

