-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS tbiu_sc_fin_ucf_item_type ON sc_fin_ucf_item_type CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_tbiu_sc_fin_ucf_item_type() RETURNS trigger AS $BODY$
DECLARE
    li_chk integer;

BEGIN
  if coalesce(NEW.default_amount::text, '') = '' then NEW.default_amount :=0;end if;

    
  if coalesce(NEW.vourcher_group::text, '') = '' then NEW.vourcher_group := NEW.item_type;end if;
  
  
  select count(1) into STRICT li_chk
  from sc_fin_ucf_vourcher_group 
  where trim(both vourcher_group) = trim(both NEW.item_type)  
;

    --- 7.1 > 7.10 
    if NEW.sign_status <> '0' and li_chk <> 1  then  
      INSERT INTO sc_fin_ucf_vourcher_group( vourcher_group           ,vourcher_desc              ,sign_flag
                ,slip_group             ,post_to_acc 
              )  
      VALUES ( trim(both NEW.item_type)           ,trim(both NEW.item_description)     ,CASE WHEN  NEW.sign_status ='-' THEN  -1   ELSE 1 END 
                ,trim(both NEW.item_type)         ,'1'
               );

     ---  (Adjust)
      INSERT INTO sc_fin_ucf_vourcher_group( vourcher_group           ,vourcher_desc              ,sign_flag
                ,slip_group             ,post_to_acc 
              )  
      VALUES ( trim(both NEW.item_type)||'!'           ,trim(both NEW.item_description)||'(Adjust)'     ,CASE WHEN  NEW.sign_status ='-' THEN  1   ELSE -1 END  -- (Adjust)
                ,trim(both NEW.item_type)||'!'           ,'1'
               );
    end if;

   
RETURN NEW;
end
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_tbiu_sc_fin_ucf_item_type() FROM PUBLIC;

CREATE TRIGGER tbiu_sc_fin_ucf_item_type
	BEFORE INSERT OR UPDATE ON sc_fin_ucf_item_type FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_tbiu_sc_fin_ucf_item_type();

