-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS tbiu_sc_acc_m_ucf_bank ON sc_acc_m_ucf_bank CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_tbiu_sc_acc_m_ucf_bank() RETURNS trigger AS $BODY$
BEGIN
  if coalesce(NEW.contract_bank_status::text, '') = '' or NEW.contract_bank_status = ' ' then
    NEW.contract_bank_status := '0';
  else
    if coalesce(OLD.contract_bank_status::text, '') = '' or OLD.contract_bank_status <> NEW.contract_bank_status then
      if NEW.contract_bank_status not in ('0','1') then
        CALL spa_dberrcol('sc_acc_m_ucf_bank','contract_bank_status',trim(both NEW.contract_bank_status));
      end if;
    end if;
  end if;
  if coalesce(NEW.atm_status::text, '') = '' or NEW.atm_status = ' ' then
    NEW.atm_status := '0';
  else
    if coalesce(OLD.atm_status::text, '') = '' or OLD.atm_status <> NEW.atm_status then
      if NEW.atm_status not in ('0','1')  then
        CALL spa_dberrcol('sc_acc_m_ucf_bank','atm_status',trim(both NEW.atm_status));
      end if;
    end if;
  end if;
  if coalesce(NEW.edit_mask::text, '') = '' or NEW.edit_mask = ' ' then
    NEW.edit_mask := 'XXX-X-XXXXX-X';
  end if;

RETURN NEW;
end
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_tbiu_sc_acc_m_ucf_bank() FROM PUBLIC;

CREATE TRIGGER tbiu_sc_acc_m_ucf_bank
	BEFORE INSERT OR UPDATE ON sc_acc_m_ucf_bank FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_tbiu_sc_acc_m_ucf_bank();

