-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS tbiu_sc_mem_m_share_holding ON sc_mem_m_share_holding_detail CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_tbiu_sc_mem_m_share_holding() RETURNS trigger AS $BODY$
BEGIN

  if pka.auto_seqno then
    if coalesce(NEW.SEQ_NO::text, '') = '' or NEW.SEQ_NO = 0 then
      select max(SEQ_NO) into STRICT NEW.SEQ_NO
      from SC_MEM_M_SHARE_HOLDING_DETAIL
      where (MEMBERSHIP_NO = NEW.MEMBERSHIP_NO);
      NEW.SEQ_NO := coalesce(NEW.SEQ_NO,0) + 1;
    end if;
  end if;

  if coalesce(OLD.MEMBERSHIP_NO::text, '') = '' and (NEW.MEMBERSHIP_NO IS NOT NULL AND NEW.MEMBERSHIP_NO::text <> '') then
    if pka.auto_entry then 
      NEW.entry_id := current_setting('app.login_id', true);
      NEW.entry_date := statement_timestamp();
      NEW.branch_id := current_setting('app.login_br', true);
      NEW.client_pc := pka_com_login.login_pc;
    end if;
  end if;

  if coalesce(NEW.SHARE_AMOUNT::text, '') = '' then
    NEW.SHARE_AMOUNT := 0;
  end if;

  if coalesce(NEW.SHARE_VALUE::text, '') = '' then
    NEW.SHARE_VALUE := 0;
  end if;

  if coalesce(NEW.SHARE_STOCK::text, '') = '' then
    NEW.SHARE_STOCK := 0;
  end if;

  if coalesce(NEW.PERIOD::text, '') = '' then
    NEW.PERIOD  := 0;
  end if;

  if coalesce(NEW.SHARE_AMOUNT_ARREAR::text, '') = '' then
    NEW.SHARE_AMOUNT_ARREAR := 0;
  end if;

  if coalesce(NEW.PPM_STATUS::text, '') = '' then
    NEW.PPM_STATUS := '0';
  end if;

  if coalesce(NEW.CANCEL_STATUS::text, '') = '' then
    NEW.CANCEL_STATUS := '0';
  end if;

  if coalesce(NEW.REAL_BALANCE::text, '') = '' then
    NEW.REAL_BALANCE := 0;
  end if;

  if coalesce(NEW.finance_date::text, '') = '' then
    if pka_fin.fp_post2fin then       
      NEW.finance_date := pka_fin_daily.fp_finance_date('1'); --Mobile ไม่มองวันที่การเงิน
    end if;
  end if;

    if coalesce(NEW.pay_principal_arr::text, '') = '' then NEW.pay_principal_arr :=0;end if;
    if coalesce(NEW.div_date::text, '') = '' then NEW.div_date := NEW.operate_date;end if;

RETURN NEW;
end
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_tbiu_sc_mem_m_share_holding() FROM PUBLIC;

CREATE TRIGGER tbiu_sc_mem_m_share_holding
	BEFORE INSERT OR UPDATE ON sc_mem_m_share_holding_detail FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_tbiu_sc_mem_m_share_holding();

