-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS tbiu_sc_com_m_receipt_item ON sc_com_m_receipt_item CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_tbiu_sc_com_m_receipt_item() RETURNS trigger AS $BODY$
declare
  ls_loan_contract_no  sc_lon_m_loan_card.loan_contract_no%type;
  ls_group_item sc_com_m_ucf_receipt_item_type.group_item%type;
  ldc_amount bigint;
BEGIN
  BEGIN

  if pka.auto_seqno then
    if coalesce(NEW.seq_no::text, '') = '' or NEW.seq_no = 0 then
      select max(seq_no) into STRICT NEW.seq_no
      from sc_com_m_receipt_item
      where (receipt_no = NEW.receipt_no);
      NEW.seq_no := coalesce(NEW.seq_no,0) + 1;
    end if;
  end if;

  if coalesce(NEW.period::text, '') = '' then NEW.period := 0;end if;
  if coalesce(NEW.item_amount::text, '') = '' then NEW.item_amount := 0;end if;
  if coalesce(NEW.interest_amount::text, '') = '' then NEW.interest_amount := 0;end if;
  if coalesce(NEW.principal_amount::text, '') = '' then NEW.principal_amount := 0;end if;
  if coalesce(NEW.balance::text, '') = '' then NEW.balance := 0;end if;
  if coalesce(NEW.pending_amount::text, '') = '' then NEW.pending_amount :=0;end if;
  if coalesce(NEW.pending_interest::text, '') = '' then NEW.pending_interest :=0;end if;
  if coalesce(NEW.interest_arrear::text, '') = '' then NEW.interest_arrear :=0;end if;
  if coalesce(NEW.interest_calculate::text, '') = '' then NEW.interest_calculate := 0;end if;
  if coalesce(NEW.spec_calc_int::text, '') = '' then NEW.spec_calc_int :='01';end if;-- วิธีการคิดดอกเบี้ย 01:ยอดคงเหลือ 02:ยอดชำระ
  if coalesce(NEW.interest_notpay::text, '') = '' then NEW.interest_notpay :=0;end if;
  if coalesce(NEW.interest_return::text, '') = '' then NEW.interest_return :=0;end if;
  if coalesce(NEW.calint_active::text, '') = '' then NEW.calint_active :='0';end if;
  if coalesce(NEW.old_interest_arrear::text, '') = '' then NEW.old_interest_arrear :=0;end if;
  if coalesce(NEW.month_arr::text, '') = '' then NEW.month_arr :=0;end if;
  if coalesce(NEW.pay_principal_arr::text, '') = '' then NEW.pay_principal_arr :=0;end if; -- เงินต้นค้าง ณ วันที่ชำระ
  if coalesce(NEW.firstint_status::text, '') = '' then NEW.firstint_status :='0';end if;
  if coalesce(NEW.keeping_status::text, '') = '' then NEW.keeping_status := '0';end if;
  if coalesce(NEW.interest_period::text, '') = '' then NEW.interest_period := 0;end if;
  if coalesce(NEW.principal_over::text, '') = '' then NEW.principal_over :=0;end if;
  if coalesce(NEW.interest_overpay::text, '') = '' then NEW.interest_overpay :=0;end if;
  if coalesce(NEW.principal_overpay::text, '') = '' then NEW.principal_overpay :=0;end if;

  BEGIN  -- กลุ่มรหัสรายการ
    select group_item into STRICT ls_group_item
    from sc_com_m_ucf_receipt_item_type
    where (item_type_id = NEW.item_type_id);
  exception when others then null;--spa_dberror('E38:ไม่พบ sc_com_m_ucf_receipt_item_type('||trim(:new.item_type_id)||')');
  end;

  -- ยอดคงเหลือหลังชำระ
--  if :new.balance is null then
--    if ls_group_item = 'LON'  then
--      if :new.firstint_status = '1' then
--        begin -- ยอดคงเหลือจากสัญญาเงินกู้ Contract
--          ls_loan_contract_no := trim(:new.description);
--          select loan_approve_amount into :new.balance
--          from sc_lon_m_contract where(loan_contract_no = ls_loan_contract_no);
--        exception when others then spa_dberror('E49:ไม่พบข้อมูล sc_lon_m_contract('||trim(:new.description)||')');
--        end ;
--      else
--        begin -- ยอดคงเหลือจากสัญญาเงินกู้ Card
--          ls_loan_contract_no := trim(:new.description);
--          select principal_balance into :new.balance
--          from sc_lon_m_loan_card where(loan_contract_no = ls_loan_contract_no);
--        exception when others then spa_dberror('E56:ไม่พบข้อมูล sc_lon_m_loan_card('||trim(:new.description)||')');
--        end ;
--        :new.balance := :new.balance  - :new.principal_amount ;
--      end if;
--    else
--      :new.balance := 0;
--    end if;
--  end if;
--  if ls_group_item = 'SHR' then
--      -- ทุนเรือนหุ้น(รวมยอดที่ซื้อแล้ว)
--      if :new.item_amount > 0 then 
--        update sc_com_m_receipt 
--        set share_stock = :new.balance
--        where receipt_no = :new.receipt_no ;
--        if sql%rowcount != 1 then 
--          spa_dberror('E76:ไม่พบใบเสร็จชำระพิเศษ('||trim(:new.receipt_no)||' [sql%rowcount='||sql%rowcount||'])');
--        end if;
--      end if;
--  end if;
--  if :new.PENDING_AMOUNT is null then
--    if ls_group_item = 'LON' then
--      if :new.firstint_status = '1' then
--        null; -- ดบ.งวดแรก สัญญาใหม่ยังไม่เกิด
--      else
--        begin -- ยอดรอเรียกเก็บ จากสัญญาเงินกู้
--          ls_loan_contract_no := trim(:new.description);
--          select NVL(pending_amount,0) into :new.pending_amount
--          from sc_lon_m_loan_card where(loan_contract_no = ls_loan_contract_no);
--        exception when others then spa_dberror('E71:ไม่พบข้อมูล sc_lon_m_loan_card('||trim(:new.description)||')');
--        end ;
--      end if;
--    else
--      :new.pending_amount := 0;
--    end if;
--  end if;
--  if :new.PENDING_INTEREST is null then
--    if ls_group_item = 'LON' then
--      if :new.firstint_status = '1' then
--        null; -- ดบ.งวดแรก สัญญาใหม่ยังไม่เกิด
--      else
--        begin -- ยอดรอเรียกเก็บ จากสัญญาเงินกู้
--          ls_loan_contract_no := trim(:new.description);
--          select PENDING_INTEREST into :new.PENDING_INTEREST
--          from sc_lon_m_loan_card where(loan_contract_no = ls_loan_contract_no);
--        exception when others then spa_dberror('E85:ไม่พบข้อมูล sc_lon_m_loan_card('||trim(:new.description)||')');
--        end ;
--      end if;
--    else
--      :new.PENDING_INTEREST := 0;
--    end if;
--  end if;
  -- วันที่ประมวลผล
--  if :new.process_date is null  or pka.to_date(:new.process_date) = pka.to_date('01/01/1900') then
--    if ls_group_item = 'LON' then
--      if :new.firstint_status = '1' then
--        null; -- ดบ.งวดแรก สัญญาใหม่ยังไม่เกิด
--      else
--        begin -- หาวันีที่ประมวลผลจาก loan card
--          ls_loan_contract_no := trim(:new.description);
--          select last_process_date into :new.process_date
--          from sc_lon_m_loan_card where(loan_contract_no = ls_loan_contract_no);
--        exception when others then spa_dberror('E99:ไม่พบข้อมูล sc_lon_m_loan_card('||trim(:new.description)||')');
--        end ;
--      end if;
--    end if ;
--  end if;
if pka.auto_entry then
  -- ประเภทเงินกู้
  if ( coalesce(NEW.loan_type::text, '') = '' or NEW.loan_type = ' ' ) then  -- and len( trim(:new.description) ) <= 15 then
    case ls_group_item
      when 'LON'then
--spa_dberror(':new.loan_type='||:new.loan_type);      
        ls_loan_contract_no := trim(both NEW.description);
        BEGIN  -- หาประเภทเงินกู้จากสัญญาเงินกู้
          select loan_type , loan_code into STRICT NEW.loan_type , NEW.loan_code
          from sc_lon_m_loan_card
          where (loan_contract_no = ls_loan_contract_no);
        exception when others then null;--spa_dberror('E113:ไม่พบสัญญาเงินกู้('||trim(:new.description)||')');
        end;

      when 'SHR'then  NEW.loan_type := 'SH';
      when 'MFE'then  NEW.loan_type := 'FE';
      else NEW.loan_type := '00';
    end case;
  end if;

-- -- loan_code
--Niorn 2023-05-24 TGE ถ้าเป็นเงินกู้ให้หา loan_code ด้วย 
--  if ( :new.loan_code is null or :new.loan_code = ' ' ) then --and len( trim(:new.description) ) <= 15 then
    case trim(both ls_group_item )
      when 'LON'then
        ls_loan_contract_no := trim(both NEW.description);
        BEGIN  -- หา loan_code
          select loan_code into STRICT  NEW.loan_code
          from sc_lon_m_loan_card
          where (loan_contract_no = ls_loan_contract_no);
        exception when others then null;--spa_dberror('E113:ไม่พบสัญญาเงินกู้('||trim(:new.description)||')');
        end;

      when 'SHR'then  NEW.loan_code := '0';
      when 'MFE'then  NEW.loan_code := '0';
      else NEW.loan_code := '0';
    end case;
--  end if;
-- -- contact_status
--TNMA pop ถ้าเป็นเงินกู้ให้หา contact_status ด้วย  
    case trim(both ls_group_item )
      when 'LON'then
        ls_loan_contract_no := trim(both NEW.description);
        BEGIN  -- หา loan_code
          select contact_status into STRICT  NEW.contact_status
          from sc_lon_m_loan_card
          where (loan_contract_no = ls_loan_contract_no);
        exception when others then null;--spa_dberror('E113:ไม่พบสัญญาเงินกู้('||trim(:new.description)||')');
        end;

      when 'SHR'then  NEW.contact_status := '0';
      when 'MFE'then  NEW.contact_status := '0';
      else NEW.contact_status := '0';
    end case;


end if;

   -- Faifa split_loan 
--  if :new.loan_type = '3ส' or :new.loan_type = '3พ' then
--    
--    begin -- หา split_nonvisible
--      select split_nonvisible into :new.split_nonvisible
--      from sc_lon_m_contract
--      where loan_contract_no = trim(:new.description);
--    exception when others then :new.split_nonvisible := '0';
--    end ;    
--  else 
--      :new.split_nonvisible := '0';   
--  end if;
--  
  -- วิธีการคิดดอกเบี้ย interest_calmethod  01 - รายวัน, 02 - รายเดือน
--  if :new.interest_calmethod is null or :new.interest_calmethod = ' ' then
--    if ls_group_item = 'LON' then
--      begin -- ประเภทเงินกู้
--        select interest_cal_method_code into :new.interest_calmethod
--        from sc_lon_m_rule where(loan_type = :new.loan_type);
--      exception when others then spa_dberror('E128:ไม่พบประเภทเงินกู้('||trim(:new.loan_type)||')');
--      end ;
--    else
--      :new.interest_calmethod :='00';
--    end if ;
--  end if;
  -- ยอดรอเรียกเก็บ
--  if ls_group_item = 'LON' then
--    if :new.firstint_status = '1' then
--      null; -- ดบ.งวดแรก สัญญาใหม่ยังไม่เกิด
--    else
--      begin -- ยอดรอเรียกเก็บ จากสัญญาเงินกู้
--        ls_loan_contract_no := trim(:new.description);
--        select NVL(keeping_status,'0') into :new.keeping_status
--        from sc_lon_m_loan_card where(loan_contract_no = ls_loan_contract_no);
--      exception when others then spa_dberror('E170:ไม่พบข้อมูล sc_lon_m_loan_card('||trim(:new.description)||')');
--      end ;
--    end if;
--  end if;
--  begin -- หัวใบเสร็จ > ยอดเงินชำระทั้งหมด
--    select recept_amount into ldc_amount
--    from sc_com_m_receipt where(receipt_no = :new.receipt_no);
--  exception when others then spa_dberror('E184:ไม่พบ sc_com_m_receipt('||trim(:new.receipt_no)||')');
--  end ;
--  ldc_amount := NVL(ldc_amount,0) + :new.item_amount;
--  update sc_com_m_receipt
--  set recept_amount = ldc_amount
--  where(receipt_no = :new.receipt_no);
--  if sql%rowcount <> 1 then spa_dberror('E190:ไม่สามารถอัพเดท หัวใบเสร็จได้(sql%rowcount='||to_char(sql%rowcount)||')');end if;
--
--  if ls_group_item = 'LON' then
--    begin -- หัวใบเสร็จ > ดอกเบี้ยสะสมในใบเสร็จ
--      select total_interest into ldc_amount
--      from sc_com_m_receipt where(receipt_no = :new.receipt_no);
--    exception when others then spa_dberror('E196:ไม่พบ sc_com_m_receipt('||trim(:new.receipt_no)||')');
--    end ;
--    ldc_amount  := NVL(ldc_amount,0) + :new.interest_amount;
--    update sc_com_m_receipt
--    set total_interest = ldc_amount
--    where(receipt_no = :new.receipt_no);
--    if sql%rowcount <> 1 then spa_dberror('E202:ไม่สามารถอัพเดท หัวใบเสร็จได้(sql%rowcount='||to_char(sql%rowcount)||')');end if;
--  end if;
  END;
RETURN NEW;
end
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_tbiu_sc_com_m_receipt_item() FROM PUBLIC;

CREATE TRIGGER tbiu_sc_com_m_receipt_item
	BEFORE INSERT ON sc_com_m_receipt_item FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_tbiu_sc_com_m_receipt_item();

