-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS tbiu_sc_hr_rule_ot ON sc_hr_rule_ot CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_tbiu_sc_hr_rule_ot() RETURNS trigger AS $BODY$
BEGIN
  --กำหนด ให้เป็นวันที่ 1/1/2008 ทั้งหมด
  NEW.time_BEGIN := to_date('01/01/2008 '||to_char(NEW.time_BEGIN,'HH24:MI'),'DD/MM/YYYY HH24:MI');
  NEW.time_end := to_date('01/01/2008 '||to_char(NEW.time_end,'HH24:MI'),'DD/MM/YYYY HH24:MI');
  --ตรวจสอบเวลาเริ่มต้นกันเวลาสิ้นสุด
  if NEW.time_BEGIN < NEW.time_end then null;else
    CALL spa_dberror('กรุณา กำหนดเวลาเริ่มต้น('|| to_char(NEW.time_BEGIN,'HH24:MI')||')และเวลาสิ้นสุด('|| to_char(NEW.time_end,'HH24:MI')||') ซึ่งเวลาสิ้นสุดต้องมากกว่าเวลาเริ่มต้นเสมอ');
  end if;
  --ตรวจสอบการกำหนดอัตรา ot ให้มากกว่า 0
  if coalesce(NEW.ot_rate::text, '') = '' or NEW.ot_rate = 0 then
    CALL spa_dberror('กรุณากำหนดอัตรา ot ให้มากกว่า 0');
  end if;
  --กำหนด seq_no
  if coalesce(NEW.seq_no::text, '') = '' or NEW.seq_no = 0 then
    select max(seq_no) into STRICT NEW.seq_no
    from sc_hr_rule_ot
    where dayofweek = NEW.dayofweek;
    if NEW.seq_no > 0 then
      NEW.seq_no := NEW.seq_no + 1;
    else
      NEW.seq_no := 1;
    end if;
  end if;

RETURN NEW;
end
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_tbiu_sc_hr_rule_ot() FROM PUBLIC;

CREATE TRIGGER tbiu_sc_hr_rule_ot
	BEFORE INSERT OR UPDATE OF time_begin,time_end ON sc_hr_rule_ot FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_tbiu_sc_hr_rule_ot();

