-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS tbiu_si_rep_cats ON si_rep_cats CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_tbiu_si_rep_cats() RETURNS trigger AS $BODY$
BEGIN

  if coalesce(NEW.mis_status::text, '') = '' then NEW.mis_status := '0';end if;

RETURN NEW;
end
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_tbiu_si_rep_cats() FROM PUBLIC;

CREATE TRIGGER tbiu_si_rep_cats
	BEFORE INSERT OR UPDATE ON si_rep_cats FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_tbiu_si_rep_cats();

