-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS tbiu_sc_mem_m_member_address ON sc_mem_m_member_address CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_tbiu_sc_mem_m_member_address() RETURNS trigger AS $BODY$
BEGIN
--return ;
  if coalesce(NEW.membership_no::text, '') = '' then
    CALL spa_dberrcol('sc_mem_m_member_address','membership_no',NEW.membership_no );
  end if;

  if coalesce(NEW.address_type::text, '') = '' then
    CALL spa_dberrcol('sc_mem_m_member_address','address_type',NEW.address_type||'(0=ที่อยู่ปัจจุบัน,1=ที่อยู่ตามทะเบียนบ้าน,2=ที่อยู่ที่ทำงานของสมาชิก');
  else
    if coalesce(OLD.address_type::text, '') = '' or OLD.address_type <> NEW.address_type then
      if NEW.address_type not in ('0','1','2') then
        CALL spa_dberrcol('sc_mem_m_member_address','address_type',NEW.address_type||'(0=ที่อยู่ปัจจุบัน,1=ที่อยู่ตามทะเบียนบ้าน,2=ที่อยู่ที่ทำงานของสมาชิก');
      end if;
    end if;
  end if;

--  if :new.province_code is null then
--    :new.province_code := pka_srv_dbattrib.getdefault('sc_mem_m_member_address','province_code');
--  end if;
--  if :new.district_code is null then
--    :new.district_code := pka_srv_dbattrib.getdefault('sc_mem_m_member_address','district_code');
--  end if;
  --แก้ไข ที่อยู่
  
  if  (OLD.membership_no IS NOT NULL AND OLD.membership_no::text <> '')   then 
    --insert  sc_mem_edit_name
  INSERT INTO sc_mem_edit_address( membership_no,              address_type,       entry_date,              entry_id,   
           	operate_date,   
           	pre_address_no,         pre_moo,                pre_road,   
            pre_soi,               pre_tambol,              pre_district_code,   
           	pre_province_code,      pre_postcode,           pre_telephone,   
           	pre_mooban,              
            address_no,             moo,                    road,             
            soi,                    tambol,                  district_code,              
            province_code,          postcode,               telephone,              
            mooban )  
  VALUES ( NEW.membership_no,        NEW.address_type,    statement_timestamp(),                
            current_setting('app.login_id', true),   TO_DATE( statement_timestamp() ),              
           OLD.address_no,           OLD.moo,             OLD.road, 
           OLD.soi,                  OLD.tambol,           OLD.district_code,
           OLD.province_code,        OLD.postcode,        OLD.telephone,
           OLD.mooban,         

           NEW.address_no,           NEW.moo,             NEW.road, 
           NEW.soi,                  NEW.tambol,           NEW.district_code,
           NEW.province_code,        NEW.postcode,        NEW.telephone,
           NEW.mooban    
           ) 
;
  end if;


RETURN NEW;
end
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_tbiu_sc_mem_m_member_address() FROM PUBLIC;

CREATE TRIGGER tbiu_sc_mem_m_member_address
	BEFORE INSERT OR UPDATE ON sc_mem_m_member_address FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_tbiu_sc_mem_m_member_address();

