-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS tbiu_sc_dep_m_fee ON sc_dep_m_fee CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_tbiu_sc_dep_m_fee() RETURNS trigger AS $BODY$
BEGIN
  if (pka.auto_seqno) then
    if coalesce(NEW.seq_no::text, '') = '' or NEW.seq_no = 0 then
      select max(seq_no) into STRICT NEW.seq_no
      from sc_dep_m_fee
      where deposit_account_no = NEW.deposit_account_no;
      NEW.seq_no := coalesce(NEW.seq_no,0) + 1;
    end if;
  end if;

  if coalesce(NEW.ref_seq_no::text, '') = '' then NEW.ref_seq_no :=0;end if;
  if coalesce(NEW.fee_amount::text, '') = '' then NEW.fee_amount :=0;end if;
  if coalesce(trim(both NEW.officer_id)::text, '') = '' then NEW.officer_id := trim(both pka_com_function.fp_login_id);end if;
  if coalesce(NEW.op_balance::text, '') = '' then NEW.op_balance :=0;end if;
  if coalesce(trim(both NEW.branch_id)::text, '') = '' then NEW.branch_id := trim(both pka_com_function.fp_login_br);end if;
  if coalesce(NEW.working_day::text, '') = '' then NEW.working_day := pka_dep.fp_deposit_date();end if;
  if coalesce(NEW.operate_date::text, '') = '' then NEW.operate_date := statement_timestamp();end if;

RETURN NEW;
end
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_tbiu_sc_dep_m_fee() FROM PUBLIC;

CREATE TRIGGER tbiu_sc_dep_m_fee
	BEFORE INSERT OR UPDATE ON sc_dep_m_fee FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_tbiu_sc_dep_m_fee();

