-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS tbiu_sc_atm_recv_file_scib_003 ON sc_atm_recv_file_scib_003 CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_tbiu_sc_atm_recv_file_scib_003() RETURNS trigger AS $BODY$
BEGIN
  if coalesce(NEW.seq_no::text, '') = '' or NEW.seq_no = 0 then
    select max(seq_no) into STRICT NEW.seq_no
    from sc_atm_recv_file_scib_003
    where (operate_date = NEW.operate_date)
    and (item_no = NEW.item_no);
    NEW.seq_no := coalesce(NEW.seq_no,0) + 1;
  end if;
RETURN NEW;
end
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_tbiu_sc_atm_recv_file_scib_003() FROM PUBLIC;

CREATE TRIGGER tbiu_sc_atm_recv_file_scib_003
	BEFORE INSERT OR UPDATE ON sc_atm_recv_file_scib_003 FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_tbiu_sc_atm_recv_file_scib_003();

