-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS tbiu_sc_mem_m_member_refer ON sc_mem_m_member_member_refer CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_tbiu_sc_mem_m_member_refer() RETURNS trigger AS $BODY$
BEGIN

  if coalesce(NEW.membership_no::text, '') = '' then
    CALL spa_dberrcol('sc_mem_m_member_member_refer','membership_no',NEW.membership_no);
  end if;

  if pka.auto_seqno then
    if coalesce(NEW.seq_no::text, '') = ''  or NEW.seq_no = 0 then
      select max(seq_no) into STRICT NEW.seq_no
      from sc_mem_m_member_member_refer
      where (membership_no = NEW.membership_no );
      NEW.seq_no := coalesce(NEW.seq_no , 0) +  1;
    end if;
  end if;

--NIGHT 2020/07/07 KTM อาจไม่มีสมาชิกอ้างอิง
--  if :new.membership_no_ref is null then
--    spa_dberrcol('sc_mem_m_member_member_refer','membership_no_ref',:new.membership_no_ref);
--  end if;
  if coalesce(NEW.conceern_code::text, '') = '' then
    NEW.conceern_code := pka_srv_dbattrib.getdefault('sc_mem_m_member_member_refer','conceern_code');
  end if;

  if coalesce(OLD.membership_no::text, '') = '' and (NEW.membership_no IS NOT NULL AND NEW.membership_no::text <> '') then
    if pka.auto_entry then 
      NEW.entry_id := current_setting('app.login_id', true);
      NEW.entry_date := statement_timestamp();
      NEW.entry_br := current_setting('app.login_br', true);
      NEW.entry_pc := pka_com_login.login_pc;
    end if;
  end if;

  if coalesce(NEW.refer_status::text, '') = '' then
    NEW.refer_status := pka_srv_dbattrib.getdefault('sc_mem_m_member_member_refer','refer_status');
  end if;


RETURN NEW;
end
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_tbiu_sc_mem_m_member_refer() FROM PUBLIC;

CREATE TRIGGER tbiu_sc_mem_m_member_refer
	BEFORE INSERT OR UPDATE ON sc_mem_m_member_member_refer FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_tbiu_sc_mem_m_member_refer();

