-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS tbiu_sc_mem_m_ucf_appl_type ON sc_mem_m_ucf_application_type CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_tbiu_sc_mem_m_ucf_appl_type() RETURNS trigger AS $BODY$
BEGIN
  if coalesce(NEW.APPLICATION_FEE::text, '') = '' then NEW.APPLICATION_FEE := 0;end if;
RETURN NEW;
end
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_tbiu_sc_mem_m_ucf_appl_type() FROM PUBLIC;

CREATE TRIGGER tbiu_sc_mem_m_ucf_appl_type
	BEFORE INSERT OR UPDATE ON sc_mem_m_ucf_application_type FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_tbiu_sc_mem_m_ucf_appl_type();

