-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS tbiu_sc_lon_m_trans_lon_coll_h ON sc_lon_m_trans_loan_coll_head CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_tbiu_sc_lon_m_trans_lon_coll_h() RETURNS trigger AS $BODY$
BEGIN
  if coalesce(NEW.principal_balance::text, '') = '' then NEW.principal_balance :=0;end if;
  if coalesce(trim(both NEW.transfer_status)::text, '') = '' then NEW.transfer_status :='0';end if;
  if coalesce(NEW.principal_of_loan::text, '') = '' then NEW.principal_of_loan :=0;end if;
  if coalesce(NEW.period_payment::text, '') = '' then NEW.period_payment :=0;end if;
  if coalesce(NEW.last_period::text, '') = '' then NEW.last_period :=0;end if;
  if coalesce(NEW.int_transfer_amount::text, '') = '' then NEW.int_transfer_amount :=0;end if;
  if coalesce(NEW.interest_arrear::text, '') = '' then NEW.interest_arrear :=0;end if;

  if coalesce(NEW.entry_date::text, '') = '' then NEW.entry_date := statement_timestamp();end if;
  if coalesce(trim(both NEW.entry_id)::text, '') = '' then NEW.entry_id := pka_com_function.fp_login_id;end if;
  if coalesce(trim(both NEW.entry_pc)::text, '') = '' then NEW.entry_pc := pka_com_function.fp_login_pc;end if;
  if coalesce(trim(both NEW.entry_br)::text, '') = '' then NEW.entry_br := pka_com_function.fp_login_br;end if;


  if OLD.transfer_status = '0' and NEW.transfer_status = '1' then
    if pka.auto_entry then
      NEW.cancel_date := statement_timestamp();
      NEW.cancel_id := pka_com_function.fp_login_id;
      NEW.cancel_pc := pka_com_function.fp_login_pc;
      NEW.cancel_br := pka_com_function.fp_login_br;
    end if;
  end if;
RETURN NEW;
end
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_tbiu_sc_lon_m_trans_lon_coll_h() FROM PUBLIC;

CREATE TRIGGER tbiu_sc_lon_m_trans_lon_coll_h
	BEFORE INSERT OR UPDATE ON sc_lon_m_trans_loan_coll_head FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_tbiu_sc_lon_m_trans_lon_coll_h();

