-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS tm_eoff_doc_inout ON sc_eoff_doc_inout CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_tm_eoff_doc_inout() RETURNS trigger AS $BODY$
DECLARE v_seq bigint;
BEGIN
    IF (OLD.doc_no IS NOT NULL AND OLD.doc_no::text <> '') THEN
        SELECT coalesce(MAX(SM_SEQ),0)+1 INTO STRICT v_seq FROM SM_DOC_INOUT WHERE io = OLD.inout_status AND tdata = 'DOC' AND requestment_no = OLD.doc_no AND loan_contract_no = trim(both OLD.doc_no);
        INSERT INTO SM_DOC_INOUT(io, tdata, requestment_no, loan_contract_no, SM_SEQ) VALUES (OLD.inout_status, 'DOC', OLD.doc_no, trim(both OLD.doc_no), v_seq);
    END IF;
    IF (NEW.doc_no IS NOT NULL AND NEW.doc_no::text <> '') THEN
        SELECT coalesce(MAX(SM_SEQ),0)+1 INTO STRICT v_seq FROM SM_DOC_INOUT WHERE io = NEW.inout_status AND tdata = 'DOC' AND requestment_no = NEW.doc_no AND loan_contract_no = trim(both NEW.doc_no);
        INSERT INTO SM_DOC_INOUT(io, tdata, requestment_no, loan_contract_no, SM_SEQ) VALUES (NEW.inout_status, 'DOC', NEW.doc_no, trim(both NEW.doc_no), v_seq);
    END IF;
IF TG_OP = 'DELETE' THEN
	RETURN OLD;
ELSE
	RETURN NEW;
END IF;

END
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_tm_eoff_doc_inout() FROM PUBLIC;

CREATE TRIGGER tm_eoff_doc_inout
	AFTER INSERT OR UPDATE OR DELETE ON sc_eoff_doc_inout FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_tm_eoff_doc_inout();

