-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS tm_kep_monthly_giro_file ON sc_kep_monthly_giro_file CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_tm_kep_monthly_giro_file() RETURNS trigger AS $BODY$
DECLARE v_seq bigint;
BEGIN
    IF (OLD.receive_year IS NOT NULL AND OLD.receive_year::text <> '') THEN
        SELECT coalesce(MAX(SM_SEQ),0)+1 INTO STRICT v_seq FROM SM_KEP_MONTHLY_GIRO_FILE WHERE receive_year = OLD.receive_year AND receive_month = OLD.receive_month AND membership_no = OLD.membership_no AND seq_no = OLD.seq_no;
        INSERT INTO SM_KEP_MONTHLY_GIRO_FILE(receive_year, receive_month, membership_no, seq_no, SM_SEQ) VALUES (OLD.receive_year, OLD.receive_month, OLD.membership_no, OLD.seq_no, v_seq);
    END IF;
    IF (NEW.receive_year IS NOT NULL AND NEW.receive_year::text <> '') THEN
        SELECT coalesce(MAX(SM_SEQ),0)+1 INTO STRICT v_seq FROM SM_KEP_MONTHLY_GIRO_FILE WHERE receive_year = NEW.receive_year AND receive_month = NEW.receive_month AND membership_no = NEW.membership_no AND seq_no = NEW.seq_no;
        INSERT INTO SM_KEP_MONTHLY_GIRO_FILE(receive_year, receive_month, membership_no, seq_no, SM_SEQ) VALUES (NEW.receive_year, NEW.receive_month, NEW.membership_no, NEW.seq_no, v_seq);
    END IF;
IF TG_OP = 'DELETE' THEN
	RETURN OLD;
ELSE
	RETURN NEW;
END IF;

END
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_tm_kep_monthly_giro_file() FROM PUBLIC;

CREATE TRIGGER tm_kep_monthly_giro_file
	AFTER INSERT OR UPDATE OR DELETE ON sc_kep_monthly_giro_file FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_tm_kep_monthly_giro_file();

