-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS tm_lon_m_rule ON sc_lon_m_rule CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_tm_lon_m_rule() RETURNS trigger AS $BODY$
DECLARE v_seq bigint;
BEGIN
    IF (OLD.LOAN_TYPE IS NOT NULL AND OLD.LOAN_TYPE::text <> '') THEN
        SELECT coalesce(MAX(SM_SEQ),0)+1 INTO STRICT v_seq FROM SM_LON_M_RULE WHERE LOAN_TYPE = OLD.LOAN_TYPE;
        INSERT INTO SM_LON_M_RULE(LOAN_TYPE, SM_SEQ) VALUES (OLD.LOAN_TYPE, v_seq);
    END IF;
    IF (NEW.LOAN_TYPE IS NOT NULL AND NEW.LOAN_TYPE::text <> '') THEN
        SELECT coalesce(MAX(SM_SEQ),0)+1 INTO STRICT v_seq FROM SM_LON_M_RULE WHERE LOAN_TYPE = NEW.LOAN_TYPE;
        INSERT INTO SM_LON_M_RULE(LOAN_TYPE, SM_SEQ) VALUES (NEW.LOAN_TYPE, v_seq);
    END IF;
IF TG_OP = 'DELETE' THEN
	RETURN OLD;
ELSE
	RETURN NEW;
END IF;

END
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_tm_lon_m_rule() FROM PUBLIC;

CREATE TRIGGER tm_lon_m_rule
	AFTER INSERT OR UPDATE OR DELETE ON sc_lon_m_rule FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_tm_lon_m_rule();

