-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS tm_mem_m_ucf_province ON sc_mem_m_ucf_province CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_tm_mem_m_ucf_province() RETURNS trigger AS $BODY$
DECLARE v_seq bigint;
BEGIN
    IF (OLD.PROVINCE_CODE IS NOT NULL AND OLD.PROVINCE_CODE::text <> '') THEN
        SELECT coalesce(MAX(SM_SEQ),0)+1 INTO STRICT v_seq FROM SM_MEM_M_UCF_PROVINCE WHERE PROVINCE_CODE = OLD.PROVINCE_CODE;
        INSERT INTO SM_MEM_M_UCF_PROVINCE(PROVINCE_CODE, SM_SEQ) VALUES (OLD.PROVINCE_CODE, v_seq);
    END IF;
    IF (NEW.PROVINCE_CODE IS NOT NULL AND NEW.PROVINCE_CODE::text <> '') THEN
        SELECT coalesce(MAX(SM_SEQ),0)+1 INTO STRICT v_seq FROM SM_MEM_M_UCF_PROVINCE WHERE PROVINCE_CODE = NEW.PROVINCE_CODE;
        INSERT INTO SM_MEM_M_UCF_PROVINCE(PROVINCE_CODE, SM_SEQ) VALUES (NEW.PROVINCE_CODE, v_seq);
    END IF;
IF TG_OP = 'DELETE' THEN
	RETURN OLD;
ELSE
	RETURN NEW;
END IF;

END
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_tm_mem_m_ucf_province() FROM PUBLIC;

CREATE TRIGGER tm_mem_m_ucf_province
	AFTER INSERT OR UPDATE OR DELETE ON sc_mem_m_ucf_province FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_tm_mem_m_ucf_province();

