-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS tm_mem_m_ucf_member_group ON sc_mem_m_ucf_member_group CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_tm_mem_m_ucf_member_group() RETURNS trigger AS $BODY$
DECLARE v_seq bigint;
BEGIN
    IF (OLD.member_group_no IS NOT NULL AND OLD.member_group_no::text <> '') THEN
        SELECT coalesce(MAX(SM_SEQ),0)+1 INTO STRICT v_seq FROM SM_MEM_M_UCF_MEMBER_GROUP WHERE member_group_no = OLD.member_group_no;
        INSERT INTO SM_MEM_M_UCF_MEMBER_GROUP(member_group_no, SM_SEQ) VALUES (OLD.member_group_no, v_seq);
    END IF;
    IF (NEW.member_group_no IS NOT NULL AND NEW.member_group_no::text <> '') THEN
        SELECT coalesce(MAX(SM_SEQ),0)+1 INTO STRICT v_seq FROM SM_MEM_M_UCF_MEMBER_GROUP WHERE member_group_no = NEW.member_group_no;
        INSERT INTO SM_MEM_M_UCF_MEMBER_GROUP(member_group_no, SM_SEQ) VALUES (NEW.member_group_no, v_seq);
    END IF;
IF TG_OP = 'DELETE' THEN
	RETURN OLD;
ELSE
	RETURN NEW;
END IF;

END
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_tm_mem_m_ucf_member_group() FROM PUBLIC;

CREATE TRIGGER tm_mem_m_ucf_member_group
	AFTER INSERT OR UPDATE OR DELETE ON sc_mem_m_ucf_member_group FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_tm_mem_m_ucf_member_group();

