-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS tm_mem_m_capital_rate ON sc_mem_m_capital_rate CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_tm_mem_m_capital_rate() RETURNS trigger AS $BODY$
DECLARE v_seq bigint;
BEGIN
    IF (OLD.lon_year IS NOT NULL AND OLD.lon_year::text <> '') THEN
        SELECT coalesce(MAX(SM_SEQ),0)+1 INTO STRICT v_seq FROM SM_MEM_M_CAPITAL_RATE WHERE lon_year = OLD.lon_year;
        INSERT INTO SM_MEM_M_CAPITAL_RATE(lon_year, SM_SEQ) VALUES (OLD.lon_year, v_seq);
    END IF;
    IF (NEW.lon_year IS NOT NULL AND NEW.lon_year::text <> '') THEN
        SELECT coalesce(MAX(SM_SEQ),0)+1 INTO STRICT v_seq FROM SM_MEM_M_CAPITAL_RATE WHERE lon_year = NEW.lon_year;
        INSERT INTO SM_MEM_M_CAPITAL_RATE(lon_year, SM_SEQ) VALUES (NEW.lon_year, v_seq);
    END IF;
IF TG_OP = 'DELETE' THEN
	RETURN OLD;
ELSE
	RETURN NEW;
END IF;

END
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_tm_mem_m_capital_rate() FROM PUBLIC;

CREATE TRIGGER tm_mem_m_capital_rate
	AFTER INSERT OR UPDATE OR DELETE ON sc_mem_m_capital_rate FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_tm_mem_m_capital_rate();

