-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS tm_mem_m_member_crem_rec_det ON sc_mem_m_member_crem_rec_det CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_tm_mem_m_member_crem_rec_det() RETURNS trigger AS $BODY$
DECLARE v_seq bigint;
BEGIN
    IF (OLD.receipt_no IS NOT NULL AND OLD.receipt_no::text <> '') THEN
        SELECT coalesce(MAX(SM_SEQ),0)+1 INTO STRICT v_seq FROM SM_MEM_M_MEMBER_CREM_REC_DET WHERE receipt_no = OLD.receipt_no AND item_type = OLD.item_type AND crem_type = OLD.crem_type;
        INSERT INTO SM_MEM_M_MEMBER_CREM_REC_DET(receipt_no, item_type, crem_type, SM_SEQ) VALUES (OLD.receipt_no, OLD.item_type, OLD.crem_type, v_seq);
    END IF;
    IF (NEW.receipt_no IS NOT NULL AND NEW.receipt_no::text <> '') THEN
        SELECT coalesce(MAX(SM_SEQ),0)+1 INTO STRICT v_seq FROM SM_MEM_M_MEMBER_CREM_REC_DET WHERE receipt_no = NEW.receipt_no AND item_type = NEW.item_type AND crem_type = NEW.crem_type;
        INSERT INTO SM_MEM_M_MEMBER_CREM_REC_DET(receipt_no, item_type, crem_type, SM_SEQ) VALUES (NEW.receipt_no, NEW.item_type, NEW.crem_type, v_seq);
    END IF;
IF TG_OP = 'DELETE' THEN
	RETURN OLD;
ELSE
	RETURN NEW;
END IF;

END
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_tm_mem_m_member_crem_rec_det() FROM PUBLIC;

CREATE TRIGGER tm_mem_m_member_crem_rec_det
	AFTER INSERT OR UPDATE OR DELETE ON sc_mem_m_member_crem_rec_det FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_tm_mem_m_member_crem_rec_det();

