-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS tm_mem_m_ucf_member_type ON sc_mem_m_ucf_member_type CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_tm_mem_m_ucf_member_type() RETURNS trigger AS $BODY$
DECLARE v_seq bigint;
BEGIN
    IF (OLD.mem_type_code IS NOT NULL AND OLD.mem_type_code::text <> '') THEN
        SELECT coalesce(MAX(SM_SEQ),0)+1 INTO STRICT v_seq FROM SM_MEM_M_UCF_MEMBER_TYPE WHERE mem_type_code = OLD.mem_type_code;
        INSERT INTO SM_MEM_M_UCF_MEMBER_TYPE(mem_type_code, SM_SEQ) VALUES (OLD.mem_type_code, v_seq);
    END IF;
    IF (NEW.mem_type_code IS NOT NULL AND NEW.mem_type_code::text <> '') THEN
        SELECT coalesce(MAX(SM_SEQ),0)+1 INTO STRICT v_seq FROM SM_MEM_M_UCF_MEMBER_TYPE WHERE mem_type_code = NEW.mem_type_code;
        INSERT INTO SM_MEM_M_UCF_MEMBER_TYPE(mem_type_code, SM_SEQ) VALUES (NEW.mem_type_code, v_seq);
    END IF;
IF TG_OP = 'DELETE' THEN
	RETURN OLD;
ELSE
	RETURN NEW;
END IF;

END
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_tm_mem_m_ucf_member_type() FROM PUBLIC;

CREATE TRIGGER tm_mem_m_ucf_member_type
	AFTER INSERT OR UPDATE OR DELETE ON sc_mem_m_ucf_member_type FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_tm_mem_m_ucf_member_type();

