-- Generated by Ora2Pg, the Oracle database Schema converter, version 25.0
-- Copyright 2000-2025 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.101.29;sid=pean;port=1521

SET client_encoding TO 'UTF8';

SET check_function_bodies = false;

DROP TRIGGER IF EXISTS tm_mem_m_share_holding_detail ON sc_mem_m_share_holding_detail CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_tm_mem_m_share_holding_detail() RETURNS trigger AS $BODY$
DECLARE v_seq bigint;
BEGIN
    IF (OLD.membership_no IS NOT NULL AND OLD.membership_no::text <> '') THEN
        SELECT coalesce(MAX(SM_SEQ),0)+1 INTO STRICT v_seq FROM SM_MEM_M_SHARE_HOLDING_DETAIL WHERE membership_no = OLD.membership_no AND seq_no = OLD.seq_no;
        INSERT INTO SM_MEM_M_SHARE_HOLDING_DETAIL(membership_no, seq_no, SM_SEQ) VALUES (OLD.membership_no, OLD.seq_no, v_seq);
    END IF;
    IF (NEW.membership_no IS NOT NULL AND NEW.membership_no::text <> '') THEN
        SELECT coalesce(MAX(SM_SEQ),0)+1 INTO STRICT v_seq FROM SM_MEM_M_SHARE_HOLDING_DETAIL WHERE membership_no = NEW.membership_no AND seq_no = NEW.seq_no;
        INSERT INTO SM_MEM_M_SHARE_HOLDING_DETAIL(membership_no, seq_no, SM_SEQ) VALUES (NEW.membership_no, NEW.seq_no, v_seq);
    END IF;
IF TG_OP = 'DELETE' THEN
	RETURN OLD;
ELSE
	RETURN NEW;
END IF;

END
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_tm_mem_m_share_holding_detail() FROM PUBLIC;

CREATE TRIGGER tm_mem_m_share_holding_detail
	AFTER INSERT OR UPDATE OR DELETE ON sc_mem_m_share_holding_detail FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_tm_mem_m_share_holding_detail();

